using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class Application
    {
        public bool? IncomeOfBorrowersSpouseUsedIndicator { get; set; }
        public Borrower Borrower { get; set; }
        public Borrower Coborrower { get; set; }
        public List<Income> Income { get; set; }
        public decimal? RentAmount { get; set; }
        public decimal? FirstMortgagePrincipalAndInterestAmount { get; set; }
        public decimal? OtherMortgagePrincipalAndInterestAmount { get; set; }
        public string HazardInsuranceAmount { get; set; }
        public string RealEstateTaxAmount { get; set; }
        public string MortgageInsuranceAmount { get; set; }
        public string HomeownersAssociationDuesAndCondoFeesAmount { get; set; }
        public decimal? OtherHousingExpenseAmount { get; set; }
        public bool? JointAssetLiabilityReportingIndicator { get; set; }
        public List<Asset> Assets { get; set; }
        public decimal? OtherItemsDeducted { get; set; }
        public string CreditAliasName2 { get; set; }
        public string CreditAliasName1 { get; set; }
        public List<Liability> Liabilities { get; set; }
        public decimal? LiquidAssetsComortSet { get; set; }
        public decimal? PresentHousingExpComortSet { get; set; }
        public decimal? GrossBaseIncomeAmount { get; set; }
        public string CreditReportReferenceIdentifier { get; set; }
        public bool? IncomeOtherThanBorrowerUsedIndicator { get; set; }
        public decimal? TotalMonthlyPaymentAmount { get; set; }
        public decimal? MonthlyInstallmentExpenseAmount { get; set; }
        public decimal? GrossNegativeCashFlow { get; set; }
        public decimal? TotalAssetsAmount { get; set; }
        public decimal? NetWorthAmount { get; set; }
        public decimal? TotalIncomeAmount { get; set; }
        public decimal? McawTotalMortgagePaymentAmount { get; set; }
        public decimal? TopRatioPercent { get; set; }
        public decimal? BottomRatioPercent { get; set; }
        public decimal? TotalBaseIncomeAmount { get; set; }
        public decimal? TotalOvertimeAmount { get; set; }
        public decimal? TotalBonusAmount { get; set; }
        public decimal? TotalCommissionsAmount { get; set; }
        public decimal? TotalDividendsInterestAmount { get; set; }
        public decimal? TotalNetRentalIncomeAmount { get; set; }
        public decimal? TotalOther1Amount { get; set; }
        public decimal? TotalOther2Amount { get; set; }
        public decimal? TotalMortgagesMonthlyPaymentAmount { get; set; }
        public decimal? ReoTotalMarketValueAmount { get; set; }
        public decimal? ReoTotalMortgagesAndLiensAmount { get; set; }
        public decimal? ReoTotalGrossRentalIncomeAmount { get; set; }
        public decimal? ReoTotalMortgagePaymentsAmount { get; set; }
        public decimal? ReoTotalMaintenanceAmount { get; set; }
        public int? ReoTotalNetRentalIncomeAmount { get; set; }
        public decimal? McawBorrowerOtherMonthlyIncomeAmount { get; set; }
        public decimal? McawCoborrowerOtherMonthlyIncomeAmount { get; set; }
        public decimal? TotalMortgagesBalanceAmount { get; set; }
        public decimal? TotalDeposit { get; set; }
        public decimal? VaSummaryTotalMonthlyGrossIncomeAmount { get; set; }
        public bool? SpouseIncomeConsider { get; set; }
        public decimal? VaSummarySpouseIncomeAmount { get; set; }
        public decimal? AssetsAvailableAmount { get; set; }
        public decimal? McawTotalMonthlyPaymentsAmount { get; set; }
        public decimal? McawOtherAmount { get; set; }
        public decimal? McawOtherDebtsAndObligationsAmount { get; set; }
        public decimal? GrossOtherIncomeAmount { get; set; }
        public decimal? GrossPositiveCashFlow { get; set; }
        public decimal? TotalFixedPaymentAmount { get; set; }
        public decimal? BrwCoBrwTotalTaxDeductions { get; set; }
        public decimal? FhaVaTotalNetTakeHomePayAmount { get; set; }
        public decimal? FhaVaTotalOtherNetIncome { get; set; }
        public decimal? FhaVaTotalNetIncomeAmount { get; set; }
        public decimal? FhaVaTotalNetEffectiveIncomeAmount { get; set; }
        public decimal? FhaVaFamilySupportAmount { get; set; }
        public string PastCreditRecord { get; set; }
        public string VACreditStandards { get; set; }
        public decimal? BalanceAvailableFamilySupportGuideline { get; set; }
        public decimal? FhaVaDebtIncomeRatio { get; set; }
        public decimal? FhaVaTotalEstimatedMonthlyShelterExpenseAmount { get; set; }
        public decimal? GrossIncomeForComortSet { get; set; }
        public decimal? PrimaryResidenceComortSet { get; set; }
        public decimal? MonthlyExpenseComortSet { get; set; }
        public decimal? TotalGrossMonthlyIncomeAmount { get; set; }
        public List<Residence> Residences { get; set; }
        public decimal? MonthlySecondHomeAmount { get; set; }
        public decimal? FreDebtToHousingGapRatio { get; set; }
        public decimal? ProposedGroundRentAmount { get; set; }
        public decimal? ProposedFirstMortgageAmount { get; set; }
        public decimal? ProposedOtherMortgagesAmount { get; set; }
        public string ProposedHazardInsuranceAmount { get; set; }
        public string ProposedRealEstateTaxesAmount { get; set; }
        public string ProposedMortgageInsuranceAmount { get; set; }
        public string ProposedDuesAmount { get; set; }
        public decimal? ProposedOtherAmount { get; set; }
        public decimal? TotalPrimaryHousingExpenseAmount { get; set; }
        public decimal? AllOtherPaymentsAmount { get; set; }
        public string CreditorName1 { get; set; }
        public string AccountNumber1 { get; set; }
        public string CreditorName2 { get; set; }
        public string AccountNumber2 { get; set; }
        public decimal? TotalPaymentsAmount { get; set; }
        public decimal? McawGrossMonthlyIncomeAmount { get; set; }
        public decimal? MonthlyHousingExpenseAmount { get; set; }
        public decimal? TotalEmploymentAmount { get; set; }
        public string PropertyUsageType { get; set; }
        public decimal? TotalUserDefinedIncome { get; set; }
        public string UserDefinedIncomeDescription { get; set; }
        public List<Employment> Employment { get; set; }
        public string HudAutoLienHolderName1 { get; set; }
        public string HudAutoYearAndMake1 { get; set; }
        public decimal? HudAutoLoanAmount1 { get; set; }
        public decimal? HudAutoPresentBalance1 { get; set; }
        public decimal? HudAutoMonthlyPayment1 { get; set; }
        public string HudAutoLienHolderName2 { get; set; }
        public string HudAutoYearAndMake2 { get; set; }
        public decimal? HudAutoLoanAmount2 { get; set; }
        public decimal? HudAutoPresentBalance2 { get; set; }
        public decimal? HudAutoMonthlyPayment2 { get; set; }
        public string HudRealEstateLienHolder1 { get; set; }
        public string HudRealEstateLienHolder2 { get; set; }
        public decimal? HudRealEstatePresentBalance1 { get; set; }
        public decimal? HudRealEstateMonthlyPayment1 { get; set; }
        public decimal? HudRealEstatePresentBalance2 { get; set; }
        public decimal? HudRealEstateMonthlyPayment2 { get; set; }
        public decimal? HudLoanAmount1 { get; set; }
        public decimal? HudLoanAmount2 { get; set; }
        public decimal? HudRealEstateLoanAmount1 { get; set; }
        public bool? HudRealEstateFhaInsured1 { get; set; }
        public decimal? HudRealEstateLoanAmount2 { get; set; }
        public bool? HudRealEstateFhaInsured2 { get; set; }
        public decimal? HudLoanAmount3 { get; set; }
        public decimal? HudLoanAmount4 { get; set; }
        public decimal? HudLoanAmount5 { get; set; }
        public decimal? HudLoanAmount6 { get; set; }
        public decimal? HudLoanAmount7 { get; set; }
        public decimal? HudLoanAmount8 { get; set; }
        public decimal? HudLoanAmount9 { get; set; }
        public decimal? HudLoanAmount10 { get; set; }
        public decimal? HudLoanAmount11 { get; set; }
        public string FreddieMacCreditReportReferenceIdentifier { get; set; }
        public decimal? FreddieMacOccupantHousingRatio { get; set; }
        public decimal? FreddieMacOccupantDebtRatio { get; set; }
        public string SofDBorrowerAddressType { get; set; }
        public string SofDBorrowerAddress { get; set; }
        public string SofDBorrowerAddressCity { get; set; }
        public string SofDBorrowerAddressState { get; set; }
        public string SofDBorrowerAddressZipcode { get; set; }
        public string SofDCoBorrowerAddressType { get; set; }
        public string SofDCoBorrowerAddress { get; set; }
        public string SofDCoBorrowerAddressCity { get; set; }
        public string SofDCoBorrowerAddressState { get; set; }
        public string SofDCoBorrowerAddressZipcode { get; set; }
        public string ExperianName { get; set; }
        public string ExperianScoreRangeTo { get; set; }
        public string ExperianAddress { get; set; }
        public string TransUnionName { get; set; }
        public string TransUnionAddress { get; set; }
        public string TransUnionCity { get; set; }
        public string TransUnionState { get; set; }
        public string TransUnionPostalCode { get; set; }
        public string TransUnionPhone { get; set; }
        public string TransUnionFax { get; set; }
        public string TransUnionModel { get; set; }
        public string TransUnionScoreRangeFrom { get; set; }
        public string ExperianCity { get; set; }
        public string TransUnionScoreRangeTo { get; set; }
        public string ExperianState { get; set; }
        public string EquifaxName { get; set; }
        public string EquifaxAddress { get; set; }
        public string EquifaxCity { get; set; }
        public string EquifaxState { get; set; }
        public string EquifaxPostalCode { get; set; }
        public string EquifaxPhone { get; set; }
        public string EquifaxFax { get; set; }
        public string EquifaxModel { get; set; }
        public string EquifaxScoreRangeFrom { get; set; }
        public string ExperianPostalCode { get; set; }
        public string EquifaxScoreRangeTo { get; set; }
        public string ExperianPhone { get; set; }
        public string ExperianFax { get; set; }
        public string ExperianModel { get; set; }
        public string ExperianScoreRangeFrom { get; set; }
        public List<ReoProperty> ReoProperties { get; set; }
        public List<SelfEmployedIncome> SelfEmployedIncomes { get; set; }
        public decimal? McawMortgagePaymentToIncome2Amount { get; set; }
        public decimal? McawTotalFixedPaymentToIncome2Amount { get; set; }
        public decimal? McawTotalFixedPaymentForRefinanceAmount { get; set; }
        public List<Tax4506> Tax4506s { get; set; }
        public decimal? MonthlyNegativeRealEstateAmount { get; set; }
        public decimal? McawMortgagePaymentToIncome1Amount { get; set; }
        public decimal? McawTotalFixedPaymentToIncome1Amount { get; set; }
        public decimal? McawTotalFixedPaymentForPurchaseAmount { get; set; }
        public DateTime? ApplicationSignedDate { get; set; }
        public string ExperianWebsite { get; set; }
        public string TransUnionWebsite { get; set; }
        public string EquifaxWebsite { get; set; }
        public List<ATRQMBorrower> ATRQMBorrowers { get; set; }
        public List<AUSTrackingLog> AUSTrackingLogs { get; set; }
        public List<TQLReportInformation> TQLReports { get; set; }
        public string Id { get; set; }
        public bool? EntityDeleted { get; set; }
        public string ApplicationId { get; set; }
        public int? ApplicationIndex { get; set; }
        public decimal? TotalReoMarketValueAmount { get; set; }
        public decimal? UserDefinedIncome { get; set; }
        public ATRQMBorrower ATRQMBorrower { get; set; }
    }
}