using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class Application
    {
        public string AccountNumber1 { get; set; }
        public string AccountNumber2 { get; set; }
        public JsonNullable<decimal?> AllOtherPaymentsAmount { get; set; }
        public string ApplicationId { get; set; }
        public JsonNullable<int?> ApplicationIndex { get; set; }
        public JsonNullable<DateTime?> ApplicationSignedDate { get; set; }
        public JsonNullable<List<Asset>> Assets { get; set; }
        public JsonNullable<decimal?> AssetsAvailableAmount { get; set; }
        public JsonNullable<ATRQMBorrower> ATRQMBorrower { get; set; }
        public JsonNullable<List<ATRQMBorrower>> ATRQMBorrowers { get; set; }
        public JsonNullable<List<AUSTrackingLog>> AUSTrackingLogs { get; set; }
        public JsonNullable<decimal?> BalanceAvailableFamilySupportGuideline { get; set; }
        public Borrower Borrower { get; set; }
        public JsonNullable<decimal?> BottomRatioPercent { get; set; }
        public JsonNullable<decimal?> BrwCoBrwTotalTaxDeductions { get; set; }
        public Borrower Coborrower { get; set; }
        public string CreditAliasName1 { get; set; }
        public string CreditAliasName2 { get; set; }
        public string CreditorName1 { get; set; }
        public string CreditorName2 { get; set; }
        public string CreditReportReferenceIdentifier { get; set; }
        public JsonNullable<List<Employment>> Employment { get; set; }
        public JsonNullable<bool?> EntityDeleted { get; set; }
        public string EquifaxAddress { get; set; }
        public string EquifaxCity { get; set; }
        public string EquifaxFax { get; set; }
        public string EquifaxModel { get; set; }
        public string EquifaxName { get; set; }
        public string EquifaxPhone { get; set; }
        public string EquifaxPostalCode { get; set; }
        public string EquifaxScoreRangeFrom { get; set; }
        public string EquifaxScoreRangeTo { get; set; }
        public string EquifaxState { get; set; }
        public string EquifaxWebsite { get; set; }
        public string ExperianAddress { get; set; }
        public string ExperianCity { get; set; }
        public string ExperianFax { get; set; }
        public string ExperianModel { get; set; }
        public string ExperianName { get; set; }
        public string ExperianPhone { get; set; }
        public string ExperianPostalCode { get; set; }
        public string ExperianScoreRangeFrom { get; set; }
        public string ExperianScoreRangeTo { get; set; }
        public string ExperianState { get; set; }
        public string ExperianWebsite { get; set; }
        public JsonNullable<decimal?> FhaVaDebtIncomeRatio { get; set; }
        public JsonNullable<decimal?> FhaVaFamilySupportAmount { get; set; }
        public JsonNullable<decimal?> FhaVaTotalEstimatedMonthlyShelterExpenseAmount { get; set; }
        public JsonNullable<decimal?> FhaVaTotalNetEffectiveIncomeAmount { get; set; }
        public JsonNullable<decimal?> FhaVaTotalNetIncomeAmount { get; set; }
        public JsonNullable<decimal?> FhaVaTotalNetTakeHomePayAmount { get; set; }
        public JsonNullable<decimal?> FhaVaTotalOtherNetIncome { get; set; }
        public JsonNullable<decimal?> FirstMortgagePrincipalAndInterestAmount { get; set; }
        public string FreddieMacCreditReportReferenceIdentifier { get; set; }
        public JsonNullable<decimal?> FreddieMacOccupantDebtRatio { get; set; }
        public JsonNullable<decimal?> FreddieMacOccupantHousingRatio { get; set; }
        public JsonNullable<decimal?> FreDebtToHousingGapRatio { get; set; }
        public JsonNullable<decimal?> GrossBaseIncomeAmount { get; set; }
        public JsonNullable<decimal?> GrossIncomeForComortSet { get; set; }
        public JsonNullable<decimal?> GrossNegativeCashFlow { get; set; }
        public JsonNullable<decimal?> GrossOtherIncomeAmount { get; set; }
        public JsonNullable<decimal?> GrossPositiveCashFlow { get; set; }
        public string HazardInsuranceAmount { get; set; }
        public string HomeownersAssociationDuesAndCondoFeesAmount { get; set; }
        public string HudAutoLienHolderName1 { get; set; }
        public string HudAutoLienHolderName2 { get; set; }
        public JsonNullable<decimal?> HudAutoLoanAmount1 { get; set; }
        public JsonNullable<decimal?> HudAutoLoanAmount2 { get; set; }
        public JsonNullable<decimal?> HudAutoMonthlyPayment1 { get; set; }
        public JsonNullable<decimal?> HudAutoMonthlyPayment2 { get; set; }
        public JsonNullable<decimal?> HudAutoPresentBalance1 { get; set; }
        public JsonNullable<decimal?> HudAutoPresentBalance2 { get; set; }
        public string HudAutoYearAndMake1 { get; set; }
        public string HudAutoYearAndMake2 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount1 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount10 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount11 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount2 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount3 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount4 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount5 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount6 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount7 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount8 { get; set; }
        public JsonNullable<decimal?> HudLoanAmount9 { get; set; }
        public JsonNullable<bool?> HudRealEstateFhaInsured1 { get; set; }
        public JsonNullable<bool?> HudRealEstateFhaInsured2 { get; set; }
        public string HudRealEstateLienHolder1 { get; set; }
        public string HudRealEstateLienHolder2 { get; set; }
        public JsonNullable<decimal?> HudRealEstateLoanAmount1 { get; set; }
        public JsonNullable<decimal?> HudRealEstateLoanAmount2 { get; set; }
        public JsonNullable<decimal?> HudRealEstateMonthlyPayment1 { get; set; }
        public JsonNullable<decimal?> HudRealEstateMonthlyPayment2 { get; set; }
        public JsonNullable<decimal?> HudRealEstatePresentBalance1 { get; set; }
        public JsonNullable<decimal?> HudRealEstatePresentBalance2 { get; set; }
        public string Id { get; set; }
        public JsonNullable<List<Income>> Income { get; set; }
        public JsonNullable<bool?> IncomeOfBorrowersSpouseUsedIndicator { get; set; }
        public JsonNullable<bool?> IncomeOtherThanBorrowerUsedIndicator { get; set; }
        public JsonNullable<bool?> JointAssetLiabilityReportingIndicator { get; set; }
        public JsonNullable<List<Liability>> Liabilities { get; set; }
        public JsonNullable<decimal?> LiquidAssetsComortSet { get; set; }
        public JsonNullable<decimal?> McawBorrowerOtherMonthlyIncomeAmount { get; set; }
        public JsonNullable<decimal?> McawCoborrowerOtherMonthlyIncomeAmount { get; set; }
        public JsonNullable<decimal?> McawGrossMonthlyIncomeAmount { get; set; }
        public JsonNullable<decimal?> McawMortgagePaymentToIncome1Amount { get; set; }
        public JsonNullable<decimal?> McawMortgagePaymentToIncome2Amount { get; set; }
        public JsonNullable<decimal?> McawOtherAmount { get; set; }
        public JsonNullable<decimal?> McawOtherDebtsAndObligationsAmount { get; set; }
        public JsonNullable<decimal?> McawTotalFixedPaymentForPurchaseAmount { get; set; }
        public JsonNullable<decimal?> McawTotalFixedPaymentForRefinanceAmount { get; set; }
        public JsonNullable<decimal?> McawTotalFixedPaymentToIncome1Amount { get; set; }
        public JsonNullable<decimal?> McawTotalFixedPaymentToIncome2Amount { get; set; }
        public JsonNullable<decimal?> McawTotalMonthlyPaymentsAmount { get; set; }
        public JsonNullable<decimal?> McawTotalMortgagePaymentAmount { get; set; }
        public JsonNullable<decimal?> MonthlyExpenseComortSet { get; set; }
        public JsonNullable<decimal?> MonthlyHousingExpenseAmount { get; set; }
        public JsonNullable<decimal?> MonthlyInstallmentExpenseAmount { get; set; }
        public JsonNullable<decimal?> MonthlyNegativeRealEstateAmount { get; set; }
        public JsonNullable<decimal?> MonthlySecondHomeAmount { get; set; }
        public string MortgageInsuranceAmount { get; set; }
        public JsonNullable<decimal?> NetWorthAmount { get; set; }
        public JsonNullable<decimal?> OtherHousingExpenseAmount { get; set; }
        public JsonNullable<decimal?> OtherItemsDeducted { get; set; }
        public JsonNullable<decimal?> OtherMortgagePrincipalAndInterestAmount { get; set; }
        public string PastCreditRecord { get; set; }
        public JsonNullable<decimal?> PresentHousingExpComortSet { get; set; }
        public JsonNullable<decimal?> PrimaryResidenceComortSet { get; set; }
        public string PropertyUsageType { get; set; }
        public string ProposedDuesAmount { get; set; }
        public JsonNullable<decimal?> ProposedFirstMortgageAmount { get; set; }
        public JsonNullable<decimal?> ProposedGroundRentAmount { get; set; }
        public string ProposedHazardInsuranceAmount { get; set; }
        public string ProposedMortgageInsuranceAmount { get; set; }
        public JsonNullable<decimal?> ProposedOtherAmount { get; set; }
        public JsonNullable<decimal?> ProposedOtherMortgagesAmount { get; set; }
        public string ProposedRealEstateTaxesAmount { get; set; }
        public string RealEstateTaxAmount { get; set; }
        public JsonNullable<decimal?> RentAmount { get; set; }
        public JsonNullable<List<ReoProperty>> ReoProperties { get; set; }
        public JsonNullable<decimal?> ReoTotalGrossRentalIncomeAmount { get; set; }
        public JsonNullable<decimal?> ReoTotalMaintenanceAmount { get; set; }
        public JsonNullable<decimal?> ReoTotalMarketValueAmount { get; set; }
        public JsonNullable<decimal?> ReoTotalMortgagePaymentsAmount { get; set; }
        public JsonNullable<decimal?> ReoTotalMortgagesAndLiensAmount { get; set; }
        public JsonNullable<int?> ReoTotalNetRentalIncomeAmount { get; set; }
        public JsonNullable<List<Residence>> Residences { get; set; }
        public JsonNullable<List<SelfEmployedIncome>> SelfEmployedIncomes { get; set; }
        public string SofDBorrowerAddress { get; set; }
        public string SofDBorrowerAddressCity { get; set; }
        public string SofDBorrowerAddressState { get; set; }
        public string SofDBorrowerAddressType { get; set; }
        public string SofDBorrowerAddressZipcode { get; set; }
        public string SofDCoBorrowerAddress { get; set; }
        public string SofDCoBorrowerAddressCity { get; set; }
        public string SofDCoBorrowerAddressState { get; set; }
        public string SofDCoBorrowerAddressType { get; set; }
        public string SofDCoBorrowerAddressZipcode { get; set; }
        public JsonNullable<bool?> SpouseIncomeConsider { get; set; }
        public JsonNullable<List<Tax4506>> Tax4506s { get; set; }
        public JsonNullable<decimal?> TopRatioPercent { get; set; }
        public JsonNullable<decimal?> TotalAssetsAmount { get; set; }
        public JsonNullable<decimal?> TotalBaseIncomeAmount { get; set; }
        public JsonNullable<decimal?> TotalBonusAmount { get; set; }
        public JsonNullable<decimal?> TotalCommissionsAmount { get; set; }
        public JsonNullable<decimal?> TotalDeposit { get; set; }
        public JsonNullable<decimal?> TotalDividendsInterestAmount { get; set; }
        public JsonNullable<decimal?> TotalEmploymentAmount { get; set; }
        public JsonNullable<decimal?> TotalFixedPaymentAmount { get; set; }
        public JsonNullable<decimal?> TotalGrossMonthlyIncomeAmount { get; set; }
        public JsonNullable<decimal?> TotalIncomeAmount { get; set; }
        public JsonNullable<decimal?> TotalMonthlyPaymentAmount { get; set; }
        public JsonNullable<decimal?> TotalMortgagesBalanceAmount { get; set; }
        public JsonNullable<decimal?> TotalMortgagesMonthlyPaymentAmount { get; set; }
        public JsonNullable<decimal?> TotalNetRentalIncomeAmount { get; set; }
        public JsonNullable<decimal?> TotalOther1Amount { get; set; }
        public JsonNullable<decimal?> TotalOther2Amount { get; set; }
        public JsonNullable<decimal?> TotalOvertimeAmount { get; set; }
        public JsonNullable<decimal?> TotalPaymentsAmount { get; set; }
        public JsonNullable<decimal?> TotalPrimaryHousingExpenseAmount { get; set; }
        public JsonNullable<decimal?> TotalReoMarketValueAmount { get; set; }
        public JsonNullable<decimal?> TotalUserDefinedIncome { get; set; }
        public JsonNullable<List<TQLReportInformation>> TQLReports { get; set; }
        public string TransUnionAddress { get; set; }
        public string TransUnionCity { get; set; }
        public string TransUnionFax { get; set; }
        public string TransUnionModel { get; set; }
        public string TransUnionName { get; set; }
        public string TransUnionPhone { get; set; }
        public string TransUnionPostalCode { get; set; }
        public string TransUnionScoreRangeFrom { get; set; }
        public string TransUnionScoreRangeTo { get; set; }
        public string TransUnionState { get; set; }
        public string TransUnionWebsite { get; set; }
        public JsonNullable<decimal?> UserDefinedIncome { get; set; }
        public string UserDefinedIncomeDescription { get; set; }
        public string VACreditStandards { get; set; }
        public JsonNullable<decimal?> VaSummarySpouseIncomeAmount { get; set; }
        public JsonNullable<decimal?> VaSummaryTotalMonthlyGrossIncomeAmount { get; set; }
    }
}