using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class ATRQMCommon
    {
        public string EligibleNonStandardToStandard { get; set; }
        public bool? WithOriginalCreditor { get; set; }
        public bool? Has30DayLatePayment { get; set; }
        public DateTime? DateOfLastMonthlyPayment { get; set; }
        public DateTime? WrittenApplicationDate { get; set; }
        public bool? PrincipalBalanceIncreased { get; set; }
        public int? FirstChangeRecase { get; set; }
        public DateTime? ARMRecastDate { get; set; }
        public decimal? ARMRecastMonthlyPayment { get; set; }
        public int? InterestOnlyMonths { get; set; }
        public DateTime? InterestOnlyRecastDate { get; set; }
        public decimal? FullPaymentAfterInterestOnly { get; set; }
        public DateTime? NegAmRecastDate { get; set; }
        public decimal? FullyARMPaymentAfterNegAm { get; set; }
        public DateTime? FirstPmtDateAfterRecast { get; set; }
        public bool? IsConsumerLiklyDefault { get; set; }
        public bool? LoanRateFixedin5Years { get; set; }
        public bool? PaymentDecreasedBy10Percent { get; set; }
        public decimal? RecastDifferencePayment { get; set; }
        public bool? PrincipalHasDeferred { get; set; }
        public bool? PointsFeesThresholdMet { get; set; }
        public bool? PreventConsumersDefault { get; set; }
        public string ATRLoanType { get; set; }
        public string QMLoanType { get; set; }
        public string IsEligibleForSafeHarbor { get; set; }
        public string GeneralATR_Status_Overall { get; set; }
        public string GeneralATR_Status_DTI { get; set; }
        public string GeneralATR_Status_ResidualIncome { get; set; }
        public string GeneralATR_Status_CoveredLoan { get; set; }
        public string GeneralATR_Status_SimultaneousLoan { get; set; }
        public string GeneralATR_Status_MtgRelatedObligations { get; set; }
        public string GeneralATR_Status_Employment { get; set; }
        public string GeneralATR_Status_Income { get; set; }
        public string GeneralATR_Status_Assets { get; set; }
        public string GeneralATR_Status_DebtObligations { get; set; }
        public string GeneralATR_Status_Alimony { get; set; }
        public string GeneralATR_Status_ChildSupport { get; set; }
        public string GeneralATR_Status_CreditHistory { get; set; }
        public string StandardQM_Status_Overall { get; set; }
        public string StandardQM_Status_LoanTerm { get; set; }
        public string StandardQM_Status_InterestOnly { get; set; }
        public string StandardQM_Status_NegativeAmortization { get; set; }
        public string StandardQM_Status_BalloonPayment { get; set; }
        public string StandardQM_Status_PrepaymentPenalty { get; set; }
        public string StandardQM_Status_PointsFeesLimit { get; set; }
        public string StandardQM_Status_DTI { get; set; }
        public string StandardQM_Status_ResidualIncome { get; set; }
        public string StandardQM_Status_CoveredLoan { get; set; }
        public string StandardQM_Status_SimultaneousLoan { get; set; }
        public string StandardQM_Status_MtgRelatedObligations { get; set; }
        public string StandardQM_Status_Employment { get; set; }
        public string StandardQM_Status_Income { get; set; }
        public string StandardQM_Status_Assets { get; set; }
        public string StandardQM_Status_DebtObligations { get; set; }
        public string StandardQM_Status_Alimony { get; set; }
        public string StandardQM_Status_ChildSupport { get; set; }
        public string StandardQM_Status_CreditHistory { get; set; }
        public string StandardQM_Status_SafeHarborEligibility { get; set; }
        public decimal? StandardQM_CalculatedThreshold { get; set; }
        public string GSEAgencyQM_Status_Overall { get; set; }
        public string GSEAgencyQM_Status_LoanTerm { get; set; }
        public string GSEAgencyQM_Status_InterestOnly { get; set; }
        public string GSEAgencyQM_Status_NegativeAmortization { get; set; }
        public string GSEAgencyQM_Status_BalloonPayment { get; set; }
        public string GSEAgencyQM_Status_PrepaymentPenalty { get; set; }
        public string GSEAgencyQM_Status_PointsFeesLimit { get; set; }
        public string GSEAgencyQM_Status_DTI { get; set; }
        public string GSEAgencyQM_Status_ResidualIncome { get; set; }
        public string GSEAgencyQM_Status_CoveredLoan { get; set; }
        public string GSEAgencyQM_Status_SimultaneousLoan { get; set; }
        public string GSEAgencyQM_Status_MtgRelatedObligations { get; set; }
        public string GSEAgencyQM_Status_Employment { get; set; }
        public string GSEAgencyQM_Status_Income { get; set; }
        public string GSEAgencyQM_Status_Assets { get; set; }
        public string GSEAgencyQM_Status_DebtObligations { get; set; }
        public string GSEAgencyQM_Status_Alimony { get; set; }
        public string GSEAgencyQM_Status_ChildSupport { get; set; }
        public string GSEAgencyQM_Status_CreditHistory { get; set; }
        public string GSEAgencyQM_Status_SafeHarborEligibility { get; set; }
        public decimal? GSEAgencyQM_CalculatedThreshold { get; set; }
        public string SmallCreditorQM_Status_Overall { get; set; }
        public string SmallCreditorQM_Status_LoanTerm { get; set; }
        public string SmallCreditorQM_Status_InterestOnly { get; set; }
        public string SmallCreditorQM_Status_NegativeAmortization { get; set; }
        public string SmallCreditorQM_Status_BalloonPayment { get; set; }
        public string SmallCreditorQM_Status_PrepaymentPenalty { get; set; }
        public string SmallCreditorQM_Status_PointsFeesLimit { get; set; }
        public string SmallCreditorQM_Status_DTI { get; set; }
        public string SmallCreditorQM_Status_ResidualIncome { get; set; }
        public string SmallCreditorQM_Status_CoveredLoan { get; set; }
        public string SmallCreditorQM_Status_MtgRelatedObligations { get; set; }
        public string SmallCreditorQM_Status_Income { get; set; }
        public string SmallCreditorQM_Status_Assets { get; set; }
        public string SmallCreditorQM_Status_DebtObligations { get; set; }
        public string SmallCreditorQM_Status_Alimony { get; set; }
        public string SmallCreditorQM_Status_ChildSupport { get; set; }
        public string SmallCreditorQM_Status_SafeHarborEligibility { get; set; }
        public decimal? SmallCreditorQM_CalculatedThreshold { get; set; }
        public bool? TransactionExemptFromRegZ { get; set; }
        public bool? CreditorType { get; set; }
        public string CreditorTypeDescription { get; set; }
        public bool? LoanProgram { get; set; }
        public string LoanProgramDescription { get; set; }
        public bool? UnitCount { get; set; }
        public bool? CreditType { get; set; }
        public decimal? DiscountPointAmount { get; set; }
        public decimal? PrepayPenaltyPercentage { get; set; }
        public decimal? InitialMaxTotalPayment { get; set; }
        public decimal? FullyIndexRateMaxTotalPayment { get; set; }
        public decimal? FullyIndexRateHousingRatio { get; set; }
        public decimal? FullyIndexRateTotalDebtRatio { get; set; }
        public decimal? Max5YrsTotalPayment { get; set; }
        public decimal? Max5YrsHousingRatio { get; set; }
        public decimal? Max5YrsTotalDebtRatio { get; set; }
        public decimal? RegZTotalLoanAmount { get; set; }
        public decimal? CurrentQMFeeThresholdAmt { get; set; }
        public decimal? CurrentQMFeeThresholdPercent { get; set; }
        public decimal? TotalPointsFeesSec32Percent { get; set; }
        public string ThresholdExceedsQM { get; set; }
        public decimal? RequiredServicesLenderSelectedAmt { get; set; }
        public decimal? FinanceChargeFees { get; set; }
        public decimal? RealEstateFees { get; set; }
        public decimal? DiscountPointFees { get; set; }
        public decimal? UpfrontPMIFees { get; set; }
        public decimal? MaxPrepaymentPenaltyFees { get; set; }
        public decimal? PrepaymentPenaltyPayoffFees { get; set; }
        public decimal? CreditInsPremiumFees { get; set; }
        public decimal? CompensationPTBFees { get; set; }
        public decimal? AffiliatesFees { get; set; }
        public string IsHigherPricedLoan { get; set; }
        public decimal? DiscountPointPercentage { get; set; }
        public decimal? TotalCoMortgagorIncome { get; set; }
        public decimal? TotalIncome { get; set; }
        public decimal? Max5YrsPrincipleAndInterest { get; set; }
        public bool? IsEvaluatedMonthlyCoveredLoanPayment { get; set; }
        public bool? IsEvaluatedMonthlySimultaneousLoanPayment { get; set; }
        public bool? IsEvaluatedMonthlyMortgageRelatedObligations { get; set; }
        public bool? IsEvaluatedDebtObligations { get; set; }
        public bool? IsEvaluatedChildSupportObligations { get; set; }
        public bool? IsEvaluatedAlimonyObligations { get; set; }
        public bool? IsEvaluatedCurrentEmploymentStatus { get; set; }
        public bool? IsEvaluatedCurrentExpectedIncome { get; set; }
        public bool? IsEvaluatedCurrentExpectedAssets { get; set; }
        public bool? IsEvaluatedCreditHistory { get; set; }
        public bool? IsEvaluatedDebtToIncomeRatio { get; set; }
        public bool? IsEvaluatedResidualIncome { get; set; }
        public string Status_SimultaneousLoan { get; set; }
        public string Status_CreditHistory { get; set; }
        public decimal? APORMaxBonaFideDiscountPoint { get; set; }
        public decimal? RateReductionBasisPoints { get; set; }
        public decimal? RateReductionDiscountPoints { get; set; }
        public decimal? RateReductionMaxBonaFideDiscountPoint { get; set; }
        public decimal? StartingAdjustedRateMaxBonaFideDiscountPoint { get; set; }
        public decimal? BonaFideDiscountPoint { get; set; }
        public decimal? BonaFideDiscountPointAmount { get; set; }
        public decimal? LOBrokerCompensationAmount { get; set; }
        public bool? BrokerCompensationWhenRateSet { get; set; }
        public decimal? FullyIndexRateMonthlyPayment { get; set; }
        public decimal? InitialRateMonthlyPayment { get; set; }
        public decimal? InitialRateHousingRatio { get; set; }
        public decimal? InitialRateTotalDebtRatio { get; set; }
        public decimal? TitleServicesLenderTitleinsuranceFee { get; set; }
        public DateTime? AUSDataDiscrepencyResolutionDate { get; set; }
        public string AUSDataDiscrepencyResolutionComments { get; set; }
        public string AUSDataDiscrepencyResolvedBy { get; set; }
        public string Id { get; set; }
    }
}