using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class ATRQMCommon
    {
        public JsonNullable<decimal?> AffiliatesFees { get; set; }
        public JsonNullable<decimal?> APORMaxBonaFideDiscountPoint { get; set; }
        public JsonNullable<DateTime?> ARMRecastDate { get; set; }
        public JsonNullable<decimal?> ARMRecastMonthlyPayment { get; set; }
        public string ATRLoanType { get; set; }
        public string AUSDataDiscrepencyResolutionComments { get; set; }
        public JsonNullable<DateTime?> AUSDataDiscrepencyResolutionDate { get; set; }
        public string AUSDataDiscrepencyResolvedBy { get; set; }
        public JsonNullable<decimal?> BonaFideDiscountPoint { get; set; }
        public JsonNullable<decimal?> BonaFideDiscountPointAmount { get; set; }
        public JsonNullable<bool?> BrokerCompensationWhenRateSet { get; set; }
        public JsonNullable<decimal?> CompensationPTBFees { get; set; }
        public JsonNullable<decimal?> CreditInsPremiumFees { get; set; }
        public JsonNullable<bool?> CreditorType { get; set; }
        public string CreditorTypeDescription { get; set; }
        public JsonNullable<bool?> CreditType { get; set; }
        public JsonNullable<decimal?> CurrentQMFeeThresholdAmt { get; set; }
        public JsonNullable<decimal?> CurrentQMFeeThresholdPercent { get; set; }
        public JsonNullable<DateTime?> DateOfLastMonthlyPayment { get; set; }
        public JsonNullable<decimal?> DiscountPointAmount { get; set; }
        public JsonNullable<decimal?> DiscountPointFees { get; set; }
        public JsonNullable<decimal?> DiscountPointPercentage { get; set; }
        public string EligibleNonStandardToStandard { get; set; }
        public JsonNullable<decimal?> FinanceChargeFees { get; set; }
        public JsonNullable<int?> FirstChangeRecase { get; set; }
        public JsonNullable<DateTime?> FirstPmtDateAfterRecast { get; set; }
        public JsonNullable<decimal?> FullPaymentAfterInterestOnly { get; set; }
        public JsonNullable<decimal?> FullyARMPaymentAfterNegAm { get; set; }
        public JsonNullable<decimal?> FullyIndexRateHousingRatio { get; set; }
        public JsonNullable<decimal?> FullyIndexRateMaxTotalPayment { get; set; }
        public JsonNullable<decimal?> FullyIndexRateMonthlyPayment { get; set; }
        public JsonNullable<decimal?> FullyIndexRateTotalDebtRatio { get; set; }
        public string GeneralATR_Status_Alimony { get; set; }
        public string GeneralATR_Status_Assets { get; set; }
        public string GeneralATR_Status_ChildSupport { get; set; }
        public string GeneralATR_Status_CoveredLoan { get; set; }
        public string GeneralATR_Status_CreditHistory { get; set; }
        public string GeneralATR_Status_DebtObligations { get; set; }
        public string GeneralATR_Status_DTI { get; set; }
        public string GeneralATR_Status_Employment { get; set; }
        public string GeneralATR_Status_Income { get; set; }
        public string GeneralATR_Status_MtgRelatedObligations { get; set; }
        public string GeneralATR_Status_Overall { get; set; }
        public string GeneralATR_Status_ResidualIncome { get; set; }
        public string GeneralATR_Status_SimultaneousLoan { get; set; }
        public JsonNullable<decimal?> GSEAgencyQM_CalculatedThreshold { get; set; }
        public string GSEAgencyQM_Status_Alimony { get; set; }
        public string GSEAgencyQM_Status_Assets { get; set; }
        public string GSEAgencyQM_Status_BalloonPayment { get; set; }
        public string GSEAgencyQM_Status_ChildSupport { get; set; }
        public string GSEAgencyQM_Status_CoveredLoan { get; set; }
        public string GSEAgencyQM_Status_CreditHistory { get; set; }
        public string GSEAgencyQM_Status_DebtObligations { get; set; }
        public string GSEAgencyQM_Status_DTI { get; set; }
        public string GSEAgencyQM_Status_Employment { get; set; }
        public string GSEAgencyQM_Status_Income { get; set; }
        public string GSEAgencyQM_Status_InterestOnly { get; set; }
        public string GSEAgencyQM_Status_LoanTerm { get; set; }
        public string GSEAgencyQM_Status_MtgRelatedObligations { get; set; }
        public string GSEAgencyQM_Status_NegativeAmortization { get; set; }
        public string GSEAgencyQM_Status_Overall { get; set; }
        public string GSEAgencyQM_Status_PointsFeesLimit { get; set; }
        public string GSEAgencyQM_Status_PrepaymentPenalty { get; set; }
        public string GSEAgencyQM_Status_ResidualIncome { get; set; }
        public string GSEAgencyQM_Status_SafeHarborEligibility { get; set; }
        public string GSEAgencyQM_Status_SimultaneousLoan { get; set; }
        public JsonNullable<bool?> Has30DayLatePayment { get; set; }
        public string Id { get; set; }
        public JsonNullable<decimal?> InitialMaxTotalPayment { get; set; }
        public JsonNullable<decimal?> InitialRateHousingRatio { get; set; }
        public JsonNullable<decimal?> InitialRateMonthlyPayment { get; set; }
        public JsonNullable<decimal?> InitialRateTotalDebtRatio { get; set; }
        public JsonNullable<int?> InterestOnlyMonths { get; set; }
        public JsonNullable<DateTime?> InterestOnlyRecastDate { get; set; }
        public JsonNullable<bool?> IsConsumerLiklyDefault { get; set; }
        public string IsEligibleForSafeHarbor { get; set; }
        public JsonNullable<bool?> IsEvaluatedAlimonyObligations { get; set; }
        public JsonNullable<bool?> IsEvaluatedChildSupportObligations { get; set; }
        public JsonNullable<bool?> IsEvaluatedCreditHistory { get; set; }
        public JsonNullable<bool?> IsEvaluatedCurrentEmploymentStatus { get; set; }
        public JsonNullable<bool?> IsEvaluatedCurrentExpectedAssets { get; set; }
        public JsonNullable<bool?> IsEvaluatedCurrentExpectedIncome { get; set; }
        public JsonNullable<bool?> IsEvaluatedDebtObligations { get; set; }
        public JsonNullable<bool?> IsEvaluatedDebtToIncomeRatio { get; set; }
        public JsonNullable<bool?> IsEvaluatedMonthlyCoveredLoanPayment { get; set; }
        public JsonNullable<bool?> IsEvaluatedMonthlyMortgageRelatedObligations { get; set; }
        public JsonNullable<bool?> IsEvaluatedMonthlySimultaneousLoanPayment { get; set; }
        public JsonNullable<bool?> IsEvaluatedResidualIncome { get; set; }
        public string IsHigherPricedLoan { get; set; }
        public JsonNullable<bool?> LoanProgram { get; set; }
        public string LoanProgramDescription { get; set; }
        public JsonNullable<bool?> LoanRateFixedin5Years { get; set; }
        public JsonNullable<decimal?> LOBrokerCompensationAmount { get; set; }
        public JsonNullable<decimal?> Max5YrsHousingRatio { get; set; }
        public JsonNullable<decimal?> Max5YrsPrincipleAndInterest { get; set; }
        public JsonNullable<decimal?> Max5YrsTotalDebtRatio { get; set; }
        public JsonNullable<decimal?> Max5YrsTotalPayment { get; set; }
        public JsonNullable<decimal?> MaxPrepaymentPenaltyFees { get; set; }
        public JsonNullable<DateTime?> NegAmRecastDate { get; set; }
        public JsonNullable<bool?> PaymentDecreasedBy10Percent { get; set; }
        public JsonNullable<bool?> PointsFeesThresholdMet { get; set; }
        public JsonNullable<decimal?> PrepaymentPenaltyPayoffFees { get; set; }
        public JsonNullable<decimal?> PrepayPenaltyPercentage { get; set; }
        public JsonNullable<bool?> PreventConsumersDefault { get; set; }
        public JsonNullable<bool?> PrincipalBalanceIncreased { get; set; }
        public JsonNullable<bool?> PrincipalHasDeferred { get; set; }
        public string QMLoanType { get; set; }
        public JsonNullable<decimal?> RateReductionBasisPoints { get; set; }
        public JsonNullable<decimal?> RateReductionDiscountPoints { get; set; }
        public JsonNullable<decimal?> RateReductionMaxBonaFideDiscountPoint { get; set; }
        public JsonNullable<decimal?> RealEstateFees { get; set; }
        public JsonNullable<decimal?> RecastDifferencePayment { get; set; }
        public JsonNullable<decimal?> RegZTotalLoanAmount { get; set; }
        public JsonNullable<decimal?> RequiredServicesLenderSelectedAmt { get; set; }
        public JsonNullable<decimal?> SmallCreditorQM_CalculatedThreshold { get; set; }
        public string SmallCreditorQM_Status_Alimony { get; set; }
        public string SmallCreditorQM_Status_Assets { get; set; }
        public string SmallCreditorQM_Status_BalloonPayment { get; set; }
        public string SmallCreditorQM_Status_ChildSupport { get; set; }
        public string SmallCreditorQM_Status_CoveredLoan { get; set; }
        public string SmallCreditorQM_Status_DebtObligations { get; set; }
        public string SmallCreditorQM_Status_DTI { get; set; }
        public string SmallCreditorQM_Status_Income { get; set; }
        public string SmallCreditorQM_Status_InterestOnly { get; set; }
        public string SmallCreditorQM_Status_LoanTerm { get; set; }
        public string SmallCreditorQM_Status_MtgRelatedObligations { get; set; }
        public string SmallCreditorQM_Status_NegativeAmortization { get; set; }
        public string SmallCreditorQM_Status_Overall { get; set; }
        public string SmallCreditorQM_Status_PointsFeesLimit { get; set; }
        public string SmallCreditorQM_Status_PrepaymentPenalty { get; set; }
        public string SmallCreditorQM_Status_ResidualIncome { get; set; }
        public string SmallCreditorQM_Status_SafeHarborEligibility { get; set; }
        public JsonNullable<decimal?> StandardQM_CalculatedThreshold { get; set; }
        public string StandardQM_Status_Alimony { get; set; }
        public string StandardQM_Status_Assets { get; set; }
        public string StandardQM_Status_BalloonPayment { get; set; }
        public string StandardQM_Status_ChildSupport { get; set; }
        public string StandardQM_Status_CoveredLoan { get; set; }
        public string StandardQM_Status_CreditHistory { get; set; }
        public string StandardQM_Status_DebtObligations { get; set; }
        public string StandardQM_Status_DTI { get; set; }
        public string StandardQM_Status_Employment { get; set; }
        public string StandardQM_Status_Income { get; set; }
        public string StandardQM_Status_InterestOnly { get; set; }
        public string StandardQM_Status_LoanTerm { get; set; }
        public string StandardQM_Status_MtgRelatedObligations { get; set; }
        public string StandardQM_Status_NegativeAmortization { get; set; }
        public string StandardQM_Status_Overall { get; set; }
        public string StandardQM_Status_PointsFeesLimit { get; set; }
        public string StandardQM_Status_PrepaymentPenalty { get; set; }
        public string StandardQM_Status_ResidualIncome { get; set; }
        public string StandardQM_Status_SafeHarborEligibility { get; set; }
        public string StandardQM_Status_SimultaneousLoan { get; set; }
        public JsonNullable<decimal?> StartingAdjustedRateMaxBonaFideDiscountPoint { get; set; }
        public string Status_CreditHistory { get; set; }
        public string Status_SimultaneousLoan { get; set; }
        public string ThresholdExceedsQM { get; set; }
        public JsonNullable<decimal?> TitleServicesLenderTitleinsuranceFee { get; set; }
        public JsonNullable<decimal?> TotalCoMortgagorIncome { get; set; }
        public JsonNullable<decimal?> TotalIncome { get; set; }
        public JsonNullable<decimal?> TotalPointsFeesSec32Percent { get; set; }
        public JsonNullable<bool?> TransactionExemptFromRegZ { get; set; }
        public JsonNullable<bool?> UnitCount { get; set; }
        public JsonNullable<decimal?> UpfrontPMIFees { get; set; }
        public JsonNullable<bool?> WithOriginalCreditor { get; set; }
        public JsonNullable<DateTime?> WrittenApplicationDate { get; set; }
    }
}