using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class ATRQMBorrower
    {
        public int? ATRQMBorrowerIndex { get; set; }
        public string AUSRecommendation { get; set; }
        public string AUSVersion { get; set; }
        public JsonNullable<decimal?> BorBonusAverageOvertime { get; set; }
        public JsonNullable<decimal?> BorBonusMostRecentAmount { get; set; }
        public JsonNullable<int?> BorBonusMostRecentMonths { get; set; }
        public JsonNullable<int?> BorBonusMostRecentYear { get; set; }
        public JsonNullable<decimal?> BorBonusPreviousAmount1 { get; set; }
        public JsonNullable<decimal?> BorBonusPreviousAmount2 { get; set; }
        public JsonNullable<int?> BorBonusPreviousMonths1 { get; set; }
        public JsonNullable<int?> BorBonusPreviousMonths2 { get; set; }
        public JsonNullable<int?> BorBonusPreviousYear1 { get; set; }
        public JsonNullable<int?> BorBonusPreviousYear2 { get; set; }
        public JsonNullable<decimal?> BorCommissionAverageOvertime { get; set; }
        public JsonNullable<decimal?> BorCommissionMostRecentAmount { get; set; }
        public JsonNullable<int?> BorCommissionMostRecentMonths { get; set; }
        public JsonNullable<int?> BorCommissionMostRecentYear { get; set; }
        public JsonNullable<decimal?> BorCommissionPreviousAmount1 { get; set; }
        public JsonNullable<decimal?> BorCommissionPreviousAmount2 { get; set; }
        public JsonNullable<int?> BorCommissionPreviousMonths1 { get; set; }
        public JsonNullable<int?> BorCommissionPreviousMonths2 { get; set; }
        public JsonNullable<int?> BorCommissionPreviousYear1 { get; set; }
        public JsonNullable<int?> BorCommissionPreviousYear2 { get; set; }
        public JsonNullable<decimal?> BorContingentLiabilitiesLiabilityAmount1 { get; set; }
        public JsonNullable<decimal?> BorContingentLiabilitiesLiabilityAmount2 { get; set; }
        public JsonNullable<decimal?> BorContingentLiabilitiesLiabilityAmount3 { get; set; }
        public string BorContingentLiabilitiesLiabilityDescription1 { get; set; }
        public string BorContingentLiabilitiesLiabilityDescription2 { get; set; }
        public string BorContingentLiabilitiesLiabilityDescription3 { get; set; }
        public JsonNullable<decimal?> BorContingentLiabilitiesTotalLiabilityAmount { get; set; }
        public JsonNullable<decimal?> BorCosignedObligationsCarLoanPayment { get; set; }
        public JsonNullable<decimal?> BorCosignedObligationsMortgagePayment { get; set; }
        public JsonNullable<decimal?> BorCosignedObligationsOtherPayment { get; set; }
        public string BorCosignedObligationsOtherPaymentDescription { get; set; }
        public JsonNullable<decimal?> BorCosignedObligationsStudentLoanPayment { get; set; }
        public JsonNullable<decimal?> BorCosignedObligationsTotalCoMortgagorLiabilities { get; set; }
        public JsonNullable<decimal?> BorDividendAverageDividend { get; set; }
        public JsonNullable<decimal?> BorDividendPreviousAmount1 { get; set; }
        public JsonNullable<decimal?> BorDividendPreviousAmount2 { get; set; }
        public JsonNullable<int?> BorDividendPreviousMonths1 { get; set; }
        public JsonNullable<int?> BorDividendPreviousMonths2 { get; set; }
        public JsonNullable<int?> BorDividendPreviousYear1 { get; set; }
        public JsonNullable<int?> BorDividendPreviousYear2 { get; set; }
        public JsonNullable<decimal?> BorDividendRequiredForCashAmount { get; set; }
        public JsonNullable<decimal?> BorInterestAverageDividend { get; set; }
        public JsonNullable<decimal?> BorInterestPreviousAmount1 { get; set; }
        public JsonNullable<decimal?> BorInterestPreviousAmount2 { get; set; }
        public JsonNullable<int?> BorInterestPreviousMonths1 { get; set; }
        public JsonNullable<int?> BorInterestPreviousMonths2 { get; set; }
        public JsonNullable<int?> BorInterestPreviousYear1 { get; set; }
        public JsonNullable<int?> BorInterestPreviousYear2 { get; set; }
        public JsonNullable<decimal?> BorInterestRequiredForCashAmount { get; set; }
        public JsonNullable<decimal?> BorMilitaryAllowanceClothingAllowance { get; set; }
        public JsonNullable<decimal?> BorMilitaryAllowanceOtherAllowance { get; set; }
        public string BorMilitaryAllowanceOtherAllowanceDescription { get; set; }
        public JsonNullable<decimal?> BorMilitaryAllowanceQuartersAllowance { get; set; }
        public JsonNullable<decimal?> BorMilitaryAllowanceRationsAllowance { get; set; }
        public JsonNullable<decimal?> BorMilitaryAllowanceTotalAllowance { get; set; }
        public JsonNullable<decimal?> BorMilitaryAllowanceVariableHousingAllowance { get; set; }
        public JsonNullable<decimal?> BorMilitaryBasePay { get; set; }
        public JsonNullable<decimal?> BorMilitaryCombatPay { get; set; }
        public JsonNullable<decimal?> BorMilitaryFlightPay { get; set; }
        public JsonNullable<decimal?> BorMilitaryHazardPay { get; set; }
        public JsonNullable<decimal?> BorMilitaryOverseasPay { get; set; }
        public JsonNullable<decimal?> BorMilitaryPropPay { get; set; }
        public JsonNullable<decimal?> BorMilitaryTotalPay { get; set; }
        public JsonNullable<decimal?> BorMonthlyEmplymentIncomeBaseIncome { get; set; }
        public JsonNullable<decimal?> BorMonthlyEmplymentIncomeBonuseIncome { get; set; }
        public JsonNullable<decimal?> BorMonthlyEmplymentIncomeCommissionIncome { get; set; }
        public JsonNullable<decimal?> BorMonthlyEmplymentIncomeDividendInterestIncome { get; set; }
        public JsonNullable<decimal?> BorMonthlyEmplymentIncomeOtherIncome1 { get; set; }
        public JsonNullable<decimal?> BorMonthlyEmplymentIncomeOtherIncome2 { get; set; }
        public JsonNullable<decimal?> BorMonthlyEmplymentIncomeOvertimeIncome { get; set; }
        public JsonNullable<decimal?> BorMonthlyEmplymentIncomeTotalEmploymentIncome { get; set; }
        public JsonNullable<decimal?> BorNonEmploymentIncomeGovtAssitProgramIncome { get; set; }
        public JsonNullable<decimal?> BorNonEmploymentIncomeHomeownSubsidyIncome { get; set; }
        public JsonNullable<bool?> BorNonEmploymentIncomeIsOffsetHomeownSubsidyIncome { get; set; }
        public JsonNullable<bool?> BorNonEmploymentIncomeIsOffsetMtgCreditCertificateIncome { get; set; }
        public JsonNullable<decimal?> BorNonEmploymentIncomeMilitaryIncome { get; set; }
        public JsonNullable<decimal?> BorNonEmploymentIncomeMtgCreditCertificateIncome { get; set; }
        public JsonNullable<decimal?> BorNonEmploymentIncomeTotalNonEmploymentIncome { get; set; }
        public JsonNullable<decimal?> BorNonEmploymentIncomeVABenefitIncome { get; set; }
        public JsonNullable<decimal?> BorNonTaxableIncomeChildSupportIncome { get; set; }
        public JsonNullable<decimal?> BorNonTaxableIncomeDisabilityIncome { get; set; }
        public JsonNullable<decimal?> BorNonTaxableIncomeFedGovtEmplRetirementIncome { get; set; }
        public JsonNullable<decimal?> BorNonTaxableIncomeMilitaryAllowances { get; set; }
        public JsonNullable<decimal?> BorNonTaxableIncomeOtherIncome { get; set; }
        public JsonNullable<decimal?> BorNonTaxableIncomePublicAssistPayments { get; set; }
        public JsonNullable<decimal?> BorNonTaxableIncomeRailroadRetirementBenefits { get; set; }
        public JsonNullable<decimal?> BorNonTaxableIncomeSocialSecurityIncome { get; set; }
        public JsonNullable<decimal?> BorNonTaxableIncomeStateGovtEmplRetirementIncome { get; set; }
        public JsonNullable<decimal?> BorNonTaxableIncomeTotalNonTaxableIncome { get; set; }
        public JsonNullable<decimal?> BorOtherNotesReceivableIncome { get; set; }
        public JsonNullable<decimal?> BorOtherOtherIncome { get; set; }
        public JsonNullable<decimal?> BorOtherParttimeIncome { get; set; }
        public JsonNullable<decimal?> BorOtherRetirementIncome { get; set; }
        public JsonNullable<decimal?> BorOtherSeasonalIncome { get; set; }
        public JsonNullable<decimal?> BorOtherSocialSecurityIncome { get; set; }
        public JsonNullable<decimal?> BorOtherTipIncome { get; set; }
        public JsonNullable<decimal?> BorOtherTrustIncome { get; set; }
        public JsonNullable<decimal?> BorOtherUnemploymentIncome { get; set; }
        public JsonNullable<decimal?> BorOvertimeAverageOvertime { get; set; }
        public JsonNullable<decimal?> BorOvertimeMostRecentAmount { get; set; }
        public JsonNullable<int?> BorOvertimeMostRecentMonths { get; set; }
        public JsonNullable<int?> BorOvertimeMostRecentYear { get; set; }
        public JsonNullable<decimal?> BorOvertimePreviousAmount1 { get; set; }
        public JsonNullable<decimal?> BorOvertimePreviousAmount2 { get; set; }
        public JsonNullable<int?> BorOvertimePreviousMonths1 { get; set; }
        public JsonNullable<int?> BorOvertimePreviousMonths2 { get; set; }
        public JsonNullable<int?> BorOvertimePreviousYear1 { get; set; }
        public JsonNullable<int?> BorOvertimePreviousYear2 { get; set; }
        public JsonNullable<decimal?> BorProjectedIncomeProjectedBonuses { get; set; }
        public JsonNullable<decimal?> BorProjectedIncomeProjectedCostLivingAdjustment { get; set; }
        public JsonNullable<decimal?> BorProjectedIncomeProjectedNewJobIncome { get; set; }
        public JsonNullable<decimal?> BorProjectedIncomeProjectedPerformanceRaises { get; set; }
        public JsonNullable<decimal?> BorProjectedIncomeTotalProjectedIncome { get; set; }
        public JsonNullable<decimal?> CobBonusAverageOvertime { get; set; }
        public JsonNullable<decimal?> CobBonusMostRecentAmount { get; set; }
        public JsonNullable<int?> CobBonusMostRecentMonths { get; set; }
        public JsonNullable<int?> CobBonusMostRecentYear { get; set; }
        public JsonNullable<decimal?> CobBonusPreviousAmount1 { get; set; }
        public JsonNullable<decimal?> CobBonusPreviousAmount2 { get; set; }
        public JsonNullable<int?> CobBonusPreviousMonths1 { get; set; }
        public JsonNullable<int?> CobBonusPreviousMonths2 { get; set; }
        public JsonNullable<int?> CobBonusPreviousYear1 { get; set; }
        public JsonNullable<int?> CobBonusPreviousYear2 { get; set; }
        public JsonNullable<decimal?> CobCommissionAverageOvertime { get; set; }
        public JsonNullable<decimal?> CobCommissionMostRecentAmount { get; set; }
        public JsonNullable<int?> CobCommissionMostRecentMonths { get; set; }
        public JsonNullable<int?> CobCommissionMostRecentYear { get; set; }
        public JsonNullable<decimal?> CobCommissionPreviousAmount1 { get; set; }
        public JsonNullable<decimal?> CobCommissionPreviousAmount2 { get; set; }
        public JsonNullable<int?> CobCommissionPreviousMonths1 { get; set; }
        public JsonNullable<int?> CobCommissionPreviousMonths2 { get; set; }
        public JsonNullable<int?> CobCommissionPreviousYear1 { get; set; }
        public JsonNullable<int?> CobCommissionPreviousYear2 { get; set; }
        public JsonNullable<decimal?> CobDividendAverageDividend { get; set; }
        public JsonNullable<decimal?> CobDividendPreviousAmount1 { get; set; }
        public JsonNullable<decimal?> CobDividendPreviousAmount2 { get; set; }
        public JsonNullable<int?> CobDividendPreviousMonths1 { get; set; }
        public JsonNullable<int?> CobDividendPreviousMonths2 { get; set; }
        public JsonNullable<int?> CobDividendPreviousYear1 { get; set; }
        public JsonNullable<int?> CobDividendPreviousYear2 { get; set; }
        public JsonNullable<decimal?> CobDividendRequiredForCashAmount { get; set; }
        public JsonNullable<decimal?> CobInterestAverageDividend { get; set; }
        public JsonNullable<decimal?> CobInterestPreviousAmount1 { get; set; }
        public JsonNullable<decimal?> CobInterestPreviousAmount2 { get; set; }
        public JsonNullable<int?> CobInterestPreviousMonths1 { get; set; }
        public JsonNullable<int?> CobInterestPreviousMonths2 { get; set; }
        public JsonNullable<int?> CobInterestPreviousYear1 { get; set; }
        public JsonNullable<int?> CobInterestPreviousYear2 { get; set; }
        public JsonNullable<decimal?> CobInterestRequiredForCashAmount { get; set; }
        public JsonNullable<decimal?> CobMilitaryAllowanceClothingAllowance { get; set; }
        public JsonNullable<decimal?> CobMilitaryAllowanceOtherAllowance { get; set; }
        public JsonNullable<decimal?> CobMilitaryAllowanceQuartersAllowance { get; set; }
        public JsonNullable<decimal?> CobMilitaryAllowanceRationsAllowance { get; set; }
        public JsonNullable<decimal?> CobMilitaryAllowanceTotalAllowance { get; set; }
        public JsonNullable<decimal?> CobMilitaryAllowanceVariableHousingAllowance { get; set; }
        public JsonNullable<decimal?> CobMilitaryBasePay { get; set; }
        public JsonNullable<decimal?> CobMilitaryCombatPay { get; set; }
        public JsonNullable<decimal?> CobMilitaryFlightPay { get; set; }
        public JsonNullable<decimal?> CobMilitaryHazardPay { get; set; }
        public JsonNullable<decimal?> CobMilitaryOverseasPay { get; set; }
        public JsonNullable<decimal?> CobMilitaryPropPay { get; set; }
        public JsonNullable<decimal?> CobMilitaryTotalPay { get; set; }
        public JsonNullable<decimal?> CobMonthlyEmplymentIncomeBaseIncome { get; set; }
        public JsonNullable<decimal?> CobMonthlyEmplymentIncomeBonuseIncome { get; set; }
        public JsonNullable<decimal?> CobMonthlyEmplymentIncomeCommissionIncome { get; set; }
        public JsonNullable<decimal?> CobMonthlyEmplymentIncomeDividendInterestIncome { get; set; }
        public JsonNullable<decimal?> CobMonthlyEmplymentIncomeOtherIncome1 { get; set; }
        public JsonNullable<decimal?> CobMonthlyEmplymentIncomeOtherIncome2 { get; set; }
        public JsonNullable<decimal?> CobMonthlyEmplymentIncomeOvertimeIncome { get; set; }
        public JsonNullable<decimal?> CobMonthlyEmplymentIncomeTotalEmploymentIncome { get; set; }
        public JsonNullable<decimal?> CobNonEmploymentIncomeGovtAssitProgramIncome { get; set; }
        public JsonNullable<decimal?> CobNonEmploymentIncomeHomeownSubsidyIncome { get; set; }
        public JsonNullable<decimal?> CobNonEmploymentIncomeMilitaryIncome { get; set; }
        public JsonNullable<decimal?> CobNonEmploymentIncomeMtgCreditCertificateIncome { get; set; }
        public JsonNullable<decimal?> CobNonEmploymentIncomeTotalNonEmploymentIncome { get; set; }
        public JsonNullable<decimal?> CobNonEmploymentIncomeVABenefitIncome { get; set; }
        public JsonNullable<decimal?> CobNonTaxableIncomeChildSupportIncome { get; set; }
        public JsonNullable<decimal?> CobNonTaxableIncomeDisabilityIncome { get; set; }
        public JsonNullable<decimal?> CobNonTaxableIncomeFedGovtEmplRetirementIncome { get; set; }
        public JsonNullable<decimal?> CobNonTaxableIncomeMilitaryAllowances { get; set; }
        public JsonNullable<decimal?> CobNonTaxableIncomeOtherIncome { get; set; }
        public JsonNullable<decimal?> CobNonTaxableIncomePublicAssistPayments { get; set; }
        public JsonNullable<decimal?> CobNonTaxableIncomeRailroadRetirementBenefits { get; set; }
        public JsonNullable<decimal?> CobNonTaxableIncomeSocialSecurityIncome { get; set; }
        public JsonNullable<decimal?> CobNonTaxableIncomeStateGovtEmplRetirementIncome { get; set; }
        public JsonNullable<decimal?> CobNonTaxableIncomeTotalNonTaxableIncome { get; set; }
        public JsonNullable<decimal?> CobOtherNotesReceivableIncome { get; set; }
        public JsonNullable<decimal?> CobOtherOtherIncome { get; set; }
        public JsonNullable<decimal?> CobOtherParttimeIncome { get; set; }
        public JsonNullable<decimal?> CobOtherRetirementIncome { get; set; }
        public JsonNullable<decimal?> CobOtherSeasonalIncome { get; set; }
        public JsonNullable<decimal?> CobOtherSocialSecurityIncome { get; set; }
        public JsonNullable<decimal?> CobOtherTipIncome { get; set; }
        public JsonNullable<decimal?> CobOtherTrustIncome { get; set; }
        public JsonNullable<decimal?> CobOtherUnemploymentIncome { get; set; }
        public JsonNullable<decimal?> CobOvertimeAverageOvertime { get; set; }
        public JsonNullable<decimal?> CobOvertimeMostRecentAmount { get; set; }
        public JsonNullable<int?> CobOvertimeMostRecentMonths { get; set; }
        public JsonNullable<int?> CobOvertimeMostRecentYear { get; set; }
        public JsonNullable<decimal?> CobOvertimePreviousAmount1 { get; set; }
        public JsonNullable<decimal?> CobOvertimePreviousAmount2 { get; set; }
        public JsonNullable<int?> CobOvertimePreviousMonths1 { get; set; }
        public JsonNullable<int?> CobOvertimePreviousMonths2 { get; set; }
        public JsonNullable<int?> CobOvertimePreviousYear1 { get; set; }
        public JsonNullable<int?> CobOvertimePreviousYear2 { get; set; }
        public JsonNullable<decimal?> CobProjectedIncomeProjectedBonuses { get; set; }
        public JsonNullable<decimal?> CobProjectedIncomeProjectedCostLivingAdjustment { get; set; }
        public JsonNullable<decimal?> CobProjectedIncomeProjectedNewJobIncome { get; set; }
        public JsonNullable<decimal?> CobProjectedIncomeProjectedPerformanceRaises { get; set; }
        public JsonNullable<decimal?> CobProjectedIncomeTotalProjectedIncome { get; set; }
        public string DUCaseIDorLPAUSKey { get; set; }
        public JsonNullable<DateTime?> FirstSubmissionDate { get; set; }
        public string FirstSubmissionTime { get; set; }
        public string FreddieDocClass { get; set; }
        public JsonNullable<decimal?> HousingRatio { get; set; }
        public string Id { get; set; }
        public bool? IsEmpty { get; set; }
        public JsonNullable<DateTime?> SubmissionDate { get; set; }
        public string SubmissionNumber { get; set; }
        public string SubmissionTime { get; set; }
        public string SubmittedBy { get; set; }
        public JsonNullable<decimal?> TotalExpenseRatio { get; set; }
        public JsonNullable<decimal?> TotalHousingPayment { get; set; }
        public JsonNullable<decimal?> TotalMonthlyAssets { get; set; }
        public JsonNullable<decimal?> TotalMonthlyDebt { get; set; }
        public JsonNullable<decimal?> TotalMonthlyIncome { get; set; }
        public string UnderwritingRiskAssessOther { get; set; }
        public string UnderwritingRiskAssessType { get; set; }
    }
}