using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class Borrower
    {
        public string AcountChekAssetId { get; set; }
        public JsonNullable<int?> AgeAtApplicationYearsCount { get; set; }
        public string AliasName { get; set; }
        public JsonNullable<bool?> AlimonyChildSupportObligationIndicator { get; set; }
        public string AltId { get; set; }
        public string ApplicantType { get; set; }
        public Application Application { get; set; }
        public string ApplicationTakenMethodType { get; set; }
        public JsonNullable<bool?> AuthorizedCreditReportIndicator { get; set; }
        public JsonNullable<bool?> AuthorizedToSignIndicator { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountType { get; set; }
        public string BankContactAddress { get; set; }
        public string BankContactCity { get; set; }
        public string BankContactName { get; set; }
        public string BankContactPostalCode { get; set; }
        public string BankContactState { get; set; }
        public JsonNullable<bool?> BankruptcyIndicator { get; set; }
        public string BankruptcyStatus { get; set; }
        public JsonNullable<decimal?> BaseMonthlyIncomeAmount { get; set; }
        public JsonNullable<DateTime?> BirthDate { get; set; }
        public JsonNullable<bool?> BorrowedDownPaymentIndicator { get; set; }
        public JsonNullable<DateTime?> BorrowerConsentRequestDate { get; set; }
        public int? BorrowerIndex { get; set; }
        public string BorrowerType { get; set; }
        public string BorrowerTypeInSummary { get; set; }
        public string CaivrsIdentifier { get; set; }
        public string CitizenshipResidencyType { get; set; }
        public JsonNullable<bool?> CoMakerEndorserOfNoteIndicator { get; set; }
        public string CommentOfCreditReport { get; set; }
        public JsonNullable<bool?> ConfirmedCRDIL { get; set; }
        public JsonNullable<bool?> ConfirmedCRFCEC { get; set; }
        public JsonNullable<bool?> ConfirmedCRFCIncorrect { get; set; }
        public JsonNullable<bool?> ConfirmedCRPFS { get; set; }
        public JsonNullable<bool?> ConfirmedOther { get; set; }
        public string ConfirmedOtherDescription { get; set; }
        public JsonNullable<bool?> CreditCounseling { get; set; }
        public JsonNullable<DateTime?> CreditReceivedDate { get; set; }
        public string CreditReportAuthorizationMethod { get; set; }
        public JsonNullable<bool?> CreditScoreIndicator { get; set; }
        public JsonNullable<DateTime?> DateAuthorizedCreditReport { get; set; }
        public JsonNullable<DateTime?> DateOfBankruptcy { get; set; }
        public JsonNullable<DateTime?> DateOfForeclosure { get; set; }
        public JsonNullable<bool?> DeclarationsJIndicator { get; set; }
        public JsonNullable<bool?> DeclarationsKIndicator { get; set; }
        public JsonNullable<int?> DependentCount { get; set; }
        public string DependentsAgesDescription { get; set; }
        public JsonNullable<bool?> DisabledIndicator { get; set; }
        public string EmailAddressText { get; set; }
        public JsonNullable<int?> Equifax120Days { get; set; }
        public JsonNullable<int?> Equifax150Days { get; set; }
        public JsonNullable<int?> Equifax30Days { get; set; }
        public JsonNullable<int?> Equifax60Days { get; set; }
        public JsonNullable<int?> Equifax90Days { get; set; }
        public JsonNullable<bool?> EquifaxCreditScoreForDisclosure { get; set; }
        public JsonNullable<int?> EquifaxCreditScoreRanksPercent { get; set; }
        public JsonNullable<DateTime?> EquifaxDatePulled { get; set; }
        public string EquifaxFactorCode1 { get; set; }
        public string EquifaxFactorCode2 { get; set; }
        public string EquifaxFactorCode3 { get; set; }
        public string EquifaxFactorCode4 { get; set; }
        public string EquifaxFactorCode5 { get; set; }
        public string EquifaxKeyFactor1 { get; set; }
        public string EquifaxKeyFactor2 { get; set; }
        public string EquifaxKeyFactor3 { get; set; }
        public string EquifaxKeyFactor4 { get; set; }
        public string EquifaxKeyFactor5 { get; set; }
        public JsonNullable<bool?> EquifaxMaterialTermsCreditByScore { get; set; }
        public string EquifaxScore { get; set; }
        public JsonNullable<int?> Experian120Days { get; set; }
        public JsonNullable<int?> Experian150Days { get; set; }
        public JsonNullable<int?> Experian30Days { get; set; }
        public JsonNullable<int?> Experian60Days { get; set; }
        public JsonNullable<int?> Experian90Days { get; set; }
        public string ExperianCreditScore { get; set; }
        public JsonNullable<bool?> ExperianCreditScoreForDisclosure { get; set; }
        public JsonNullable<int?> ExperianCreditScoreRanksPercent { get; set; }
        public JsonNullable<DateTime?> ExperianDatePulled { get; set; }
        public string ExperianFactorCode1 { get; set; }
        public string ExperianFactorCode2 { get; set; }
        public string ExperianFactorCode3 { get; set; }
        public string ExperianFactorCode4 { get; set; }
        public string ExperianFactorCode5 { get; set; }
        public string ExperianKeyFactor1 { get; set; }
        public string ExperianKeyFactor2 { get; set; }
        public string ExperianKeyFactor3 { get; set; }
        public string ExperianKeyFactor4 { get; set; }
        public string ExperianKeyFactor5 { get; set; }
        public JsonNullable<bool?> ExperianMaterialTermsCreditByScore { get; set; }
        public string FirstName { get; set; }
        public string FirstNameWithMiddleName { get; set; }
        public JsonNullable<bool?> FirstTimeHomeBuyer { get; set; }
        public JsonNullable<DateTime?> ForeclosureSatisfied { get; set; }
        public string ForeclosureStatus { get; set; }
        public string FreddieMacPerson1 { get; set; }
        public string FreddieMacPerson2 { get; set; }
        public string FullName { get; set; }
        public string FullNameWithSuffix { get; set; }
        public JsonNullable<decimal?> HighestCreditLimit { get; set; }
        public string Hmda2003OtherRaceNationalOriginDescription { get; set; }
        public string Hmda2003RaceNationalOriginType { get; set; }
        public JsonNullable<bool?> HmdaAfricanAmericanIndicator { get; set; }
        public string HmdaAge { get; set; }
        public JsonNullable<bool?> HmdaAmericanIndianIndicator { get; set; }
        public string HmdaAmericanIndianTribe { get; set; }
        public JsonNullable<bool?> HmdaAsianIndianIndicator { get; set; }
        public JsonNullable<bool?> HmdaAsianIndicator { get; set; }
        public JsonNullable<bool?> HmdaAsianOtherRaceIndicator { get; set; }
        public JsonNullable<bool?> HmdaChineseIndicator { get; set; }
        public string HmdaCreditScoreForDecisionMaking { get; set; }
        public string HmdaCreditScoringModel { get; set; }
        public JsonNullable<bool?> HmdaCubanIndicator { get; set; }
        public string HmdaEthnicityType { get; set; }
        public JsonNullable<bool?> HmdaFilipinoIndicator { get; set; }
        public string HmdaGenderType { get; set; }
        public JsonNullable<bool?> HmdaGuamanianOrChamorroIndicator { get; set; }
        public JsonNullable<bool?> HmdaHispanicLatinoOtherOriginIndicator { get; set; }
        public JsonNullable<bool?> HmdaJapaneseIndicator { get; set; }
        public JsonNullable<bool?> HmdaKoreanIndicator { get; set; }
        public JsonNullable<bool?> HmdaMexicanIndicator { get; set; }
        public JsonNullable<bool?> HmdaNativeHawaiianIndicator { get; set; }
        public JsonNullable<bool?> HmdaNoCoApplicantIndicator { get; set; }
        public JsonNullable<bool?> HmdaNotApplicableIndicator { get; set; }
        public JsonNullable<bool?> HmdaNotProvidedIndicator { get; set; }
        public string HmdaOtherAsianRace { get; set; }
        public string HmdaOtherHispanicLatinoOrigin { get; set; }
        public string HmdaOtherPacificIslanderRace { get; set; }
        public string HmdaOtherScoringModel { get; set; }
        public JsonNullable<bool?> HmdaPacificIslanderIndicator { get; set; }
        public JsonNullable<bool?> HmdaPacificIslanderOtherIndicator { get; set; }
        public JsonNullable<bool?> HmdaPuertoRicanIndicator { get; set; }
        public JsonNullable<bool?> HmdaRefusalIndicator { get; set; }
        public JsonNullable<bool?> HmdaSamoanIndicator { get; set; }
        public JsonNullable<bool?> HmdaVietnameseIndicator { get; set; }
        public JsonNullable<bool?> HmdaWhiteIndicator { get; set; }
        public JsonNullable<bool?> HomeownerPastThreeYearsIndicator { get; set; }
        public string HomePhoneNumber { get; set; }
        public string Id { get; set; }
        public JsonNullable<bool?> IntentToOccupyIndicator { get; set; }
        public string IntuitReportId { get; set; }
        public bool? IsBorrower { get; set; }
        public string IsEthnicityBasedOnVisual { get; set; }
        public string IsRaceBasedOnVisual { get; set; }
        public string IsSexBasedOnVisual { get; set; }
        public string LastName { get; set; }
        public string LastNameWithSuffix { get; set; }
        public JsonNullable<bool?> LoanForeclosureOrJudgementIndicator { get; set; }
        public string LpdGsa { get; set; }
        public JsonNullable<bool?> MailingAddressSameAsPresentIndicator { get; set; }
        public string MaritalStatusType { get; set; }
        public JsonNullable<int?> MiddleCreditScore { get; set; }
        public string MiddleFicoScore { get; set; }
        public string MiddleName { get; set; }
        public string MinFicoScore { get; set; }
        public string MobilePhone { get; set; }
        public JsonNullable<bool?> MortgageOnCredit { get; set; }
        public string NameToObtainLoanFromRHS { get; set; }
        public string NearestRelativeAddress { get; set; }
        public string NearestRelativeCity { get; set; }
        public string NearestRelativeName { get; set; }
        public string NearestRelativePhone { get; set; }
        public string NearestRelativePostalCode { get; set; }
        public string NearestRelativeRelationship { get; set; }
        public string NearestRelativeState { get; set; }
        public JsonNullable<bool?> No3rdPartyEmailIndicator { get; set; }
        public JsonNullable<bool?> NoCoApplicantIndicator { get; set; }
        public JsonNullable<int?> NumberofTradelines { get; set; }
        public JsonNullable<bool?> ObtainLoanFromRHSIndicator { get; set; }
        public string OpenBankruptcy2 { get; set; }
        public JsonNullable<decimal?> OtherMonthlyIncomeAmount { get; set; }
        public JsonNullable<decimal?> OtherSumAmount { get; set; }
        public JsonNullable<bool?> OutstandingJudgementsIndicator { get; set; }
        public JsonNullable<bool?> PartyToLawsuitIndicator { get; set; }
        public JsonNullable<int?> Pass120Days { get; set; }
        public JsonNullable<int?> Pass150Days { get; set; }
        public JsonNullable<int?> Pass30Days { get; set; }
        public JsonNullable<int?> Pass60Days { get; set; }
        public JsonNullable<int?> Pass90Days { get; set; }
        public string PersonFaxNumber { get; set; }
        public JsonNullable<decimal?> PersonHoursPerWeek { get; set; }
        public JsonNullable<decimal?> PersonIncomeAmount { get; set; }
        public string PersonIncomeFrequencyType { get; set; }
        public JsonNullable<decimal?> PersonMonthlyIncome { get; set; }
        public string PoaOccupancyIntent { get; set; }
        public string PoaSignatureText { get; set; }
        public JsonNullable<decimal?> PositiveCashFlow { get; set; }
        public string PowerOfAttorneyName { get; set; }
        public string PowerOfAttorneyTitleDescription { get; set; }
        public JsonNullable<bool?> PresentlyDelinquentIndicator { get; set; }
        public JsonNullable<DateTime?> PriorBankruptcy2 { get; set; }
        public JsonNullable<bool?> PriorForeclosure { get; set; }
        public string PriorPropertyTitleType { get; set; }
        public string PriorPropertyUsageType { get; set; }
        public JsonNullable<bool?> PropertyForeclosedPastSevenYearsIndicator { get; set; }
        public string RelationshipDescription { get; set; }
        public JsonNullable<bool?> RelationshipWithRDEmployeeIndicator { get; set; }
        public JsonNullable<int?> SchoolingTermYears { get; set; }
        public JsonNullable<bool?> SSA89BackgroundCheckIndicator { get; set; }
        public JsonNullable<bool?> SSA89BankingServiceIndicator { get; set; }
        public JsonNullable<bool?> SSA89CreditCheckIndicator { get; set; }
        public JsonNullable<bool?> SSA89LicenseRequirementIndicator { get; set; }
        public JsonNullable<bool?> SSA89MortgageServiceIndicator { get; set; }
        public JsonNullable<bool?> SSA89OtherIndicator { get; set; }
        public JsonNullable<decimal?> SubtotalLiquidAssetsMinusGiftAmount { get; set; }
        public string SuffixToName { get; set; }
        public string Tax4506LastInvestor { get; set; }
        public string Tax4506LastOrderNumber { get; set; }
        public JsonNullable<int?> Tax4506LastOrderYear1 { get; set; }
        public JsonNullable<int?> Tax4506LastOrderYear2 { get; set; }
        public JsonNullable<int?> Tax4506LastOrderYear3 { get; set; }
        public JsonNullable<int?> Tax4506LastOrderYear4 { get; set; }
        public string Tax4506LastProductsOrdered { get; set; }
        public string Tax4506LastStatus { get; set; }
        public string Tax4506LastTranscriptType { get; set; }
        public string Tax4506LastUserIDWhoOrdered { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyIncome1 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyIncome2 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyIncome3 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyIncome4 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyJointIncome1 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyJointIncome2 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyJointIncome3 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyJointIncome4 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyVarianceIncome1 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyVarianceIncome2 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyVarianceIncome3 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyVarianceIncome4 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyVarianceJointIncome1 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyVarianceJointIncome2 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyVarianceJointIncome3 { get; set; }
        public JsonNullable<decimal?> Tax4506TotalYearlyVarianceJointIncome4 { get; set; }
        public string TaxIdentificationIdentifier { get; set; }
        public JsonNullable<decimal?> TotalLiabilitiesBalanceAmount { get; set; }
        public JsonNullable<decimal?> TotalMonthlyIncomeAmount { get; set; }
        public JsonNullable<decimal?> TotalMonthlyIncomeMinusNetRentalAmount { get; set; }
        public JsonNullable<decimal?> TotalPresentHousingExpenseAmount { get; set; }
        public string TransactionPurposeDescription { get; set; }
        public JsonNullable<int?> TransUnion120Days { get; set; }
        public JsonNullable<int?> TransUnion150Days { get; set; }
        public JsonNullable<int?> TransUnion30Days { get; set; }
        public JsonNullable<int?> TransUnion60Days { get; set; }
        public JsonNullable<int?> TransUnion90Days { get; set; }
        public JsonNullable<bool?> TransUnionCreditScoreForDisclosure { get; set; }
        public JsonNullable<int?> TransUnionCreditScoreRanksPercent { get; set; }
        public JsonNullable<DateTime?> TransUnionDatePulled { get; set; }
        public string TransUnionFactorCode1 { get; set; }
        public string TransUnionFactorCode2 { get; set; }
        public string TransUnionFactorCode3 { get; set; }
        public string TransUnionFactorCode4 { get; set; }
        public string TransUnionFactorCode5 { get; set; }
        public string TransUnionKeyFactor1 { get; set; }
        public string TransUnionKeyFactor2 { get; set; }
        public string TransUnionKeyFactor3 { get; set; }
        public string TransUnionKeyFactor4 { get; set; }
        public string TransUnionKeyFactor5 { get; set; }
        public JsonNullable<bool?> TransUnionMaterialTermsCreditByScore { get; set; }
        public string TransUnionScore { get; set; }
        public JsonNullable<decimal?> UserDefinedIncome { get; set; }
        public JsonNullable<decimal?> VaFederalTaxAmount { get; set; }
        public JsonNullable<int?> ValidDaysForConsentCount { get; set; }
        public JsonNullable<decimal?> VaNetTakeHomePayAmount { get; set; }
        public JsonNullable<decimal?> VaOtherAmount { get; set; }
        public JsonNullable<decimal?> VaOtherNetIncomeAmount { get; set; }
        public JsonNullable<decimal?> VaRetirementAmount { get; set; }
        public JsonNullable<decimal?> VaStateTaxAmount { get; set; }
        public JsonNullable<decimal?> VaTotalIncomeDeductionsAmount { get; set; }
        public JsonNullable<decimal?> VaTotalNetIncomeAmount { get; set; }
        public string Vendor1 { get; set; }
        public string Vendor10 { get; set; }
        public string Vendor11 { get; set; }
        public string Vendor12 { get; set; }
        public string Vendor2 { get; set; }
        public string Vendor3 { get; set; }
        public string Vendor4 { get; set; }
        public string Vendor5 { get; set; }
        public string Vendor6 { get; set; }
        public string Vendor7 { get; set; }
        public string Vendor8 { get; set; }
        public string Vendor9 { get; set; }
        public string VestingTrusteeOfType { get; set; }
        public JsonNullable<bool?> VeteranIndicator { get; set; }
        public string WorkEmailAddress { get; set; }
        public JsonNullable<int?> YearsofCreditOnFile { get; set; }
    }
}