using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class Borrower
    {
        public string FirstNameWithMiddleName { get; set; }
        public string LastNameWithSuffix { get; set; }
        public int? AgeAtApplicationYearsCount { get; set; }
        public int? SchoolingTermYears { get; set; }
        public string MaritalStatusType { get; set; }
        public int? DependentCount { get; set; }
        public string DependentsAgesDescription { get; set; }
        public string ExperianCreditScore { get; set; }
        public string TaxIdentificationIdentifier { get; set; }
        public string HomePhoneNumber { get; set; }
        public decimal? OtherSumAmount { get; set; }
        public bool? OutstandingJudgementsIndicator { get; set; }
        public bool? PropertyForeclosedPastSevenYearsIndicator { get; set; }
        public bool? CoMakerEndorserOfNoteIndicator { get; set; }
        public bool? PartyToLawsuitIndicator { get; set; }
        public bool? AlimonyChildSupportObligationIndicator { get; set; }
        public bool? BorrowedDownPaymentIndicator { get; set; }
        public Application Application { get; set; }
        public bool? HmdaRefusalIndicator { get; set; }
        public bool? BankruptcyIndicator { get; set; }
        public bool? HomeownerPastThreeYearsIndicator { get; set; }
        public bool? IntentToOccupyIndicator { get; set; }
        public bool? PresentlyDelinquentIndicator { get; set; }
        public bool? DeclarationsKIndicator { get; set; }
        public string Hmda2003RaceNationalOriginType { get; set; }
        public string HmdaGenderType { get; set; }
        public decimal? TotalLiabilitiesBalanceAmount { get; set; }
        public decimal? TotalPresentHousingExpenseAmount { get; set; }
        public decimal? TotalMonthlyIncomeMinusNetRentalAmount { get; set; }
        public decimal? SubtotalLiquidAssetsMinusGiftAmount { get; set; }
        public string LpdGsa { get; set; }
        public bool? DeclarationsJIndicator { get; set; }
        public string PriorPropertyUsageType { get; set; }
        public string CaivrsIdentifier { get; set; }
        public bool? LoanForeclosureOrJudgementIndicator { get; set; }
        public string PriorPropertyTitleType { get; set; }
        public decimal? BaseMonthlyIncomeAmount { get; set; }
        public string Hmda2003OtherRaceNationalOriginDescription { get; set; }
        public decimal? OtherMonthlyIncomeAmount { get; set; }
        public decimal? VaFederalTaxAmount { get; set; }
        public decimal? VaStateTaxAmount { get; set; }
        public decimal? VaRetirementAmount { get; set; }
        public decimal? PositiveCashFlow { get; set; }
        public string WorkEmailAddress { get; set; }
        public string PersonFaxNumber { get; set; }
        public string EmailAddressText { get; set; }
        public decimal? VaOtherAmount { get; set; }
        public decimal? VaTotalIncomeDeductionsAmount { get; set; }
        public decimal? VaNetTakeHomePayAmount { get; set; }
        public decimal? VaOtherNetIncomeAmount { get; set; }
        public decimal? VaTotalNetIncomeAmount { get; set; }
        public DateTime? BirthDate { get; set; }
        public string EquifaxScore { get; set; }
        public string TransUnionScore { get; set; }
        public string MobilePhone { get; set; }
        public string MinFicoScore { get; set; }
        public string HmdaEthnicityType { get; set; }
        public bool? HmdaAmericanIndianIndicator { get; set; }
        public bool? HmdaAsianIndicator { get; set; }
        public bool? HmdaAfricanAmericanIndicator { get; set; }
        public bool? HmdaPacificIslanderIndicator { get; set; }
        public bool? HmdaWhiteIndicator { get; set; }
        public bool? HmdaNotProvidedIndicator { get; set; }
        public bool? HmdaNotApplicableIndicator { get; set; }
        public decimal? TotalMonthlyIncomeAmount { get; set; }
        public decimal? UserDefinedIncome { get; set; }
        public bool? MailingAddressSameAsPresentIndicator { get; set; }
        public string FullNameWithSuffix { get; set; }
        public string AliasName { get; set; }
        public string PowerOfAttorneyName { get; set; }
        public string BorrowerType { get; set; }
        public string PowerOfAttorneyTitleDescription { get; set; }
        public int? Experian30Days { get; set; }
        public int? Experian60Days { get; set; }
        public int? Experian90Days { get; set; }
        public int? Experian120Days { get; set; }
        public int? TransUnion30Days { get; set; }
        public int? TransUnion60Days { get; set; }
        public int? TransUnion90Days { get; set; }
        public int? TransUnion120Days { get; set; }
        public int? Equifax30Days { get; set; }
        public int? Equifax60Days { get; set; }
        public int? Equifax90Days { get; set; }
        public int? Equifax120Days { get; set; }
        public DateTime? CreditReceivedDate { get; set; }
        public bool? PriorForeclosure { get; set; }
        public DateTime? DateOfBankruptcy { get; set; }
        public DateTime? DateOfForeclosure { get; set; }
        public string ApplicationTakenMethodType { get; set; }
        public string IsEthnicityBasedOnVisual { get; set; }
        public string IsRaceBasedOnVisual { get; set; }
        public string IsSexBasedOnVisual { get; set; }
        public string HmdaOtherHispanicLatinoOrigin { get; set; }
        public string HmdaAmericanIndianTribe { get; set; }
        public string HmdaOtherAsianRace { get; set; }
        public string HmdaOtherPacificIslanderRace { get; set; }
        public bool? HmdaMexicanIndicator { get; set; }
        public bool? HmdaPuertoRicanIndicator { get; set; }
        public bool? HmdaCubanIndicator { get; set; }
        public bool? HmdaHispanicLatinoOtherOriginIndicator { get; set; }
        public bool? HmdaAsianIndianIndicator { get; set; }
        public bool? HmdaChineseIndicator { get; set; }
        public bool? HmdaFilipinoIndicator { get; set; }
        public bool? HmdaJapaneseIndicator { get; set; }
        public bool? HmdaKoreanIndicator { get; set; }
        public bool? HmdaVietnameseIndicator { get; set; }
        public bool? HmdaAsianOtherRaceIndicator { get; set; }
        public bool? HmdaNativeHawaiianIndicator { get; set; }
        public bool? HmdaGuamanianOrChamorroIndicator { get; set; }
        public bool? HmdaSamoanIndicator { get; set; }
        public bool? HmdaPacificIslanderOtherIndicator { get; set; }
        public string CitizenshipResidencyType { get; set; }
        public string NearestRelativeAddress { get; set; }
        public string NearestRelativeCity { get; set; }
        public string NearestRelativeState { get; set; }
        public string BankAccountType { get; set; }
        public string BankContactName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankContactAddress { get; set; }
        public string BankContactCity { get; set; }
        public string BankContactState { get; set; }
        public string BankContactPostalCode { get; set; }
        public string NearestRelativePostalCode { get; set; }
        public string NearestRelativeRelationship { get; set; }
        public string NearestRelativePhone { get; set; }
        public string NearestRelativeName { get; set; }
        public string FreddieMacPerson1 { get; set; }
        public string FreddieMacPerson2 { get; set; }
        public DateTime? ExperianDatePulled { get; set; }
        public string ExperianKeyFactor1 { get; set; }
        public string ExperianKeyFactor2 { get; set; }
        public string ExperianKeyFactor3 { get; set; }
        public string ExperianKeyFactor4 { get; set; }
        public string ExperianKeyFactor5 { get; set; }
        public string TransUnionKeyFactor5 { get; set; }
        public string EquifaxKeyFactor5 { get; set; }
        public DateTime? TransUnionDatePulled { get; set; }
        public string TransUnionKeyFactor1 { get; set; }
        public string TransUnionKeyFactor2 { get; set; }
        public string TransUnionKeyFactor3 { get; set; }
        public string TransUnionKeyFactor4 { get; set; }
        public DateTime? EquifaxDatePulled { get; set; }
        public string EquifaxKeyFactor1 { get; set; }
        public string EquifaxKeyFactor2 { get; set; }
        public string EquifaxKeyFactor3 { get; set; }
        public string EquifaxKeyFactor4 { get; set; }
        public string ExperianFactorCode1 { get; set; }
        public string ExperianFactorCode2 { get; set; }
        public string ExperianFactorCode3 { get; set; }
        public string ExperianFactorCode4 { get; set; }
        public string ExperianFactorCode5 { get; set; }
        public string TransUnionFactorCode1 { get; set; }
        public string TransUnionFactorCode2 { get; set; }
        public string TransUnionFactorCode3 { get; set; }
        public string TransUnionFactorCode4 { get; set; }
        public string TransUnionFactorCode5 { get; set; }
        public string EquifaxFactorCode1 { get; set; }
        public string EquifaxFactorCode2 { get; set; }
        public string EquifaxFactorCode3 { get; set; }
        public string EquifaxFactorCode4 { get; set; }
        public string EquifaxFactorCode5 { get; set; }
        public string HmdaCreditScoreForDecisionMaking { get; set; }
        public string HmdaCreditScoringModel { get; set; }
        public string HmdaOtherScoringModel { get; set; }
        public string HmdaAge { get; set; }
        public decimal? PersonHoursPerWeek { get; set; }
        public decimal? PersonIncomeAmount { get; set; }
        public string PersonIncomeFrequencyType { get; set; }
        public decimal? PersonMonthlyIncome { get; set; }
        public bool? ConfirmedCRFCIncorrect { get; set; }
        public bool? ConfirmedCRFCEC { get; set; }
        public bool? ConfirmedCRDIL { get; set; }
        public bool? ConfirmedCRPFS { get; set; }
        public bool? ConfirmedOther { get; set; }
        public string ConfirmedOtherDescription { get; set; }
        public int? Experian150Days { get; set; }
        public int? TransUnion150Days { get; set; }
        public int? Equifax150Days { get; set; }
        public int? Pass30Days { get; set; }
        public int? Pass60Days { get; set; }
        public int? Pass90Days { get; set; }
        public int? Pass120Days { get; set; }
        public int? Pass150Days { get; set; }
        public bool? MortgageOnCredit { get; set; }
        public int? NumberofTradelines { get; set; }
        public int? YearsofCreditOnFile { get; set; }
        public bool? CreditCounseling { get; set; }
        public decimal? HighestCreditLimit { get; set; }
        public string OpenBankruptcy2 { get; set; }
        public DateTime? PriorBankruptcy2 { get; set; }
        public string BankruptcyStatus { get; set; }
        public DateTime? ForeclosureSatisfied { get; set; }
        public string ForeclosureStatus { get; set; }
        public string MiddleFicoScore { get; set; }
        public bool? No3rdPartyEmailIndicator { get; set; }
        public bool? AuthorizedToSignIndicator { get; set; }
        public bool? ExperianCreditScoreForDisclosure { get; set; }
        public bool? TransUnionCreditScoreForDisclosure { get; set; }
        public bool? EquifaxCreditScoreForDisclosure { get; set; }
        public int? ExperianCreditScoreRanksPercent { get; set; }
        public int? TransUnionCreditScoreRanksPercent { get; set; }
        public int? EquifaxCreditScoreRanksPercent { get; set; }
        public bool? ExperianMaterialTermsCreditByScore { get; set; }
        public bool? TransUnionMaterialTermsCreditByScore { get; set; }
        public bool? EquifaxMaterialTermsCreditByScore { get; set; }
        public bool? NoCoApplicantIndicator { get; set; }
        public bool? VeteranIndicator { get; set; }
        public bool? DisabledIndicator { get; set; }
        public bool? FirstTimeHomeBuyer { get; set; }
        public bool? RelationshipWithRDEmployeeIndicator { get; set; }
        public string RelationshipDescription { get; set; }
        public bool? CreditScoreIndicator { get; set; }
        public bool? ObtainLoanFromRHSIndicator { get; set; }
        public string NameToObtainLoanFromRHS { get; set; }
        public int? MiddleCreditScore { get; set; }
        public string Tax4506LastStatus { get; set; }
        public string Tax4506LastOrderNumber { get; set; }
        public string Tax4506LastInvestor { get; set; }
        public int? Tax4506LastOrderYear1 { get; set; }
        public int? Tax4506LastOrderYear2 { get; set; }
        public int? Tax4506LastOrderYear3 { get; set; }
        public int? Tax4506LastOrderYear4 { get; set; }
        public string Tax4506LastProductsOrdered { get; set; }
        public string Tax4506LastTranscriptType { get; set; }
        public decimal? Tax4506TotalYearlyIncome3 { get; set; }
        public decimal? Tax4506TotalYearlyIncome4 { get; set; }
        public decimal? Tax4506TotalYearlyJointIncome3 { get; set; }
        public decimal? Tax4506TotalYearlyJointIncome4 { get; set; }
        public decimal? Tax4506TotalYearlyVarianceIncome3 { get; set; }
        public decimal? Tax4506TotalYearlyVarianceIncome4 { get; set; }
        public decimal? Tax4506TotalYearlyVarianceJointIncome3 { get; set; }
        public decimal? Tax4506TotalYearlyVarianceJointIncome4 { get; set; }
        public string Tax4506LastUserIDWhoOrdered { get; set; }
        public string AcountChekAssetId { get; set; }
        public string IntuitReportId { get; set; }
        public string Vendor1 { get; set; }
        public string Vendor2 { get; set; }
        public string Vendor3 { get; set; }
        public string Vendor4 { get; set; }
        public string Vendor5 { get; set; }
        public string Vendor6 { get; set; }
        public string Vendor7 { get; set; }
        public string Vendor8 { get; set; }
        public string Vendor9 { get; set; }
        public string Vendor10 { get; set; }
        public string Vendor11 { get; set; }
        public string Vendor12 { get; set; }
        public string TransactionPurposeDescription { get; set; }
        public int? ValidDaysForConsentCount { get; set; }
        public bool? AuthorizedCreditReportIndicator { get; set; }
        public DateTime? DateAuthorizedCreditReport { get; set; }
        public string CreditReportAuthorizationMethod { get; set; }
        public string CommentOfCreditReport { get; set; }
        public decimal? Tax4506TotalYearlyIncome1 { get; set; }
        public decimal? Tax4506TotalYearlyIncome2 { get; set; }
        public decimal? Tax4506TotalYearlyVarianceIncome1 { get; set; }
        public decimal? Tax4506TotalYearlyVarianceIncome2 { get; set; }
        public decimal? Tax4506TotalYearlyJointIncome1 { get; set; }
        public decimal? Tax4506TotalYearlyJointIncome2 { get; set; }
        public decimal? Tax4506TotalYearlyVarianceJointIncome1 { get; set; }
        public decimal? Tax4506TotalYearlyVarianceJointIncome2 { get; set; }
        public bool? HmdaNoCoApplicantIndicator { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string SuffixToName { get; set; }
        public string BorrowerTypeInSummary { get; set; }
        public bool? SSA89MortgageServiceIndicator { get; set; }
        public bool? SSA89BankingServiceIndicator { get; set; }
        public bool? SSA89BackgroundCheckIndicator { get; set; }
        public bool? SSA89LicenseRequirementIndicator { get; set; }
        public bool? SSA89CreditCheckIndicator { get; set; }
        public bool? SSA89OtherIndicator { get; set; }
        public string VestingTrusteeOfType { get; set; }
        public string PoaSignatureText { get; set; }
        public string PoaOccupancyIntent { get; set; }
        public DateTime? BorrowerConsentRequestDate { get; set; }
        public string Id { get; set; }
        public string AltId { get; set; }
        public string ApplicantType { get; set; }
        public int? BorrowerIndex { get; set; }
        public string FullName { get; set; }
        public bool? IsBorrower { get; set; }
    }
}