using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class ClosingDisclosure3
    {
        public decimal? ClosingCostsPaidAtClosing { get; set; }
        public string Adjustments06_1 { get; set; }
        public decimal? Adjustments06_2 { get; set; }
        public string Adjustments07_1 { get; set; }
        public decimal? Adjustments07_2 { get; set; }
        public string Adjustments15_1 { get; set; }
        public decimal? Adjustments15_2 { get; set; }
        public string OtherCredits6_1 { get; set; }
        public decimal? OtherCredits6_2 { get; set; }
        public string OtherCredits7_1 { get; set; }
        public decimal? OtherCredits7_2 { get; set; }
        public string Adjustments8_1 { get; set; }
        public decimal? Adjustments8_2 { get; set; }
        public string Adjustments9_1 { get; set; }
        public decimal? Adjustments9_2 { get; set; }
        public string Adjustments10_1 { get; set; }
        public decimal? Adjustments10_2 { get; set; }
        public string Adjustments11_1 { get; set; }
        public decimal? Adjustments11_2 { get; set; }
        public decimal? TotalDuefromBorrowerAtClosing { get; set; }
        public decimal? TotalPaidAlreadybyoronBehalfofBoroweratClosing { get; set; }
        public decimal? CashToClose { get; set; }
        public string DueToSellerAtClosing6_1 { get; set; }
        public decimal? DueToSellerAtClosing6_2 { get; set; }
        public string DueToSellerAtClosing7_1 { get; set; }
        public decimal? DueToSellerAtClosing7_2 { get; set; }
        public string DueToSellerAtClosing8_1 { get; set; }
        public decimal? DueToSellerAtClosing8_2 { get; set; }
        public string AdjustmentsforItemsPaidbySellerinAdvance16_1 { get; set; }
        public decimal? AdjustmentsforItemsPaidbySellerinAdvance16_2 { get; set; }
        public string DuefromSelleratClosing11_1 { get; set; }
        public decimal? DuefromSelleratClosing11_2 { get; set; }
        public string DuefromSelleratClosing12_1 { get; set; }
        public decimal? DuefromSelleratClosing12_2 { get; set; }
        public string DuefromSelleratClosing13_1 { get; set; }
        public decimal? DuefromSelleratClosing13_2 { get; set; }
        public decimal? TotalDuetoSelleratClosing_M { get; set; }
        public decimal? TotalDuefromSelleratClosing_N { get; set; }
        public decimal? Cash { get; set; }
        public decimal? TotalFromK { get; set; }
        public decimal? TotalFromL { get; set; }
        public decimal? TotalFromM { get; set; }
        public decimal? TotalFromN { get; set; }
        public decimal? FinalCashToClose { get; set; }
        public decimal? ClosingCostsPaidatClosing_J { get; set; }
        public string FromToBorrower { get; set; }
        public string FromToSeller { get; set; }
        public string LiabilityTo1 { get; set; }
        public string LiabilityTo2 { get; set; }
        public string LiabilityTo3 { get; set; }
        public string LiabilityTo4 { get; set; }
        public string LiabilityTo5 { get; set; }
        public string LiabilityTo6 { get; set; }
        public string LiabilityTo7 { get; set; }
        public string LiabilityTo8 { get; set; }
        public string LiabilityTo9 { get; set; }
        public string LiabilityTo10 { get; set; }
        public string LiabilityTo11 { get; set; }
        public string LiabilityTo12 { get; set; }
        public string LiabilityTo13 { get; set; }
        public string LiabilityTo14 { get; set; }
        public string LiabilityTo15 { get; set; }
        public decimal? LiabilityAmount1 { get; set; }
        public decimal? LiabilityAmount2 { get; set; }
        public decimal? LiabilityAmount3 { get; set; }
        public decimal? LiabilityAmount4 { get; set; }
        public decimal? LiabilityAmount5 { get; set; }
        public decimal? LiabilityAmount6 { get; set; }
        public decimal? LiabilityAmount7 { get; set; }
        public decimal? LiabilityAmount8 { get; set; }
        public decimal? LiabilityAmount9 { get; set; }
        public decimal? LiabilityAmount10 { get; set; }
        public decimal? LiabilityAmount11 { get; set; }
        public decimal? LiabilityAmount12 { get; set; }
        public decimal? LiabilityAmount13 { get; set; }
        public decimal? LiabilityAmount14 { get; set; }
        public decimal? LiabilityAmount15 { get; set; }
        public decimal? LiabilityTotal { get; set; }
        public decimal? LoanAmount { get; set; }
        public decimal? CD3TotalClosingCost_J { get; set; }
        public decimal? CD3ClosingCostsPaidBeforeClosing { get; set; }
        public decimal? CD3TotalPayoffsAndPayments_K { get; set; }
        public decimal? CD3CashToClose { get; set; }
        public string CD3CashToCloseFromToBorrower { get; set; }
        public decimal? LELoanAmount { get; set; }
        public decimal? LECD3TotalClosingCost_J { get; set; }
        public decimal? LECD3ClosingCostsPaidBeforeClosing { get; set; }
        public decimal? LECD3TotalPayoffsAndPayments_K { get; set; }
        public decimal? LECD3CashToClose { get; set; }
        public string LECD3CashToCloseFromToBorrower { get; set; }
        public decimal? STDLETotalClosingCostJ { get; set; }
        public decimal? STDLECD3ClosingCostsPaidBeforeClosing { get; set; }
        public decimal? STDLEClosingCostFinanced { get; set; }
        public decimal? STDLEDownPayment { get; set; }
        public decimal? STDLEDeposit { get; set; }
        public decimal? STDLEFundForBorrower { get; set; }
        public decimal? STDLESellerCredits { get; set; }
        public decimal? STDLEAdjustmentAndOtherCredits { get; set; }
        public decimal? STDLECashToClose { get; set; }
        public decimal? STDFinalTotalClosingCostJ { get; set; }
        public decimal? STDFinalCD3ClosingCostsPaidBeforeClosing { get; set; }
        public decimal? STDFinalClosingCostFinanced { get; set; }
        public decimal? STDFinalDownPayment { get; set; }
        public decimal? STDFinalDeposit { get; set; }
        public decimal? STDFinalFundForBorrower { get; set; }
        public decimal? STDFinalSellerCredits { get; set; }
        public decimal? STDFinalAdjustmentAndOtherCredits { get; set; }
        public decimal? STDFinalCashToClose { get; set; }
        public string STDTotalClosingCostDidChangeCol { get; set; }
        public string STDTotalClosingCostBeforeClosingDidChangeCol { get; set; }
        public string STDDownPaymentDidChangeCol { get; set; }
        public string STDDepositDidChangeCol { get; set; }
        public string STDFundsForBorrowerDidChangeCol { get; set; }
        public string STDSellerCreditsDidChangeCol { get; set; }
        public string STDAdjustmentsDidChangeCol { get; set; }
        public string ALTLoanAmountDidChangeCol { get; set; }
        public string ALTTotalClosingCostDidChangeCol { get; set; }
        public string ALTClosingCostBeforeClosingDidChangeCol { get; set; }
        public string ALTTotalPayoffsDidChangeCol { get; set; }
        public string ALTCashToCloseDidChangeCol { get; set; }
        public string STDTotalClosingCostRemark { get; set; }
        public string STDDownPaymentIncDecRemark { get; set; }
        public string STDClosingCostFinancedDidChangeCol { get; set; }
        public string STDDownPaymentSectionRemark { get; set; }
        public string STDDepositIncDecRemark { get; set; }
        public string STDFundsForBorrowerIncDecRemark { get; set; }
        public string STDSellerCreditsIncDecRemark { get; set; }
        public decimal? STDLegalLimit { get; set; }
        public string ALTLoanAmountIncDecRemark { get; set; }
        public string ALTTotalClosingCostRemark { get; set; }
        public decimal? ALTLegalLimit { get; set; }
        public decimal? ALTCashToCloseRemark { get; set; }
        public decimal? PriorToleranceCureAmount { get; set; }
        public string STDAdjustmentAndOtherCreditsRemark { get; set; }
        public bool? ExcludeBorrowerClosingCosts { get; set; }
        public bool? OmitFromPrintSellersTransaction { get; set; }
        public List<UCDDetail> UCDDetails { get; set; }
        public decimal? UCDKSubTotal { get; set; }
        public decimal? UCDLSubTotal { get; set; }
        public decimal? UCDTotalAdjustmentsAndOtherCredits { get; set; }
        public decimal? NonUCDTotalAdjustmentsAndOtherCredits { get; set; }
        public decimal? TotalAdjustmentsAndOtherCredits { get; set; }
        public decimal? ActualLELoanAmountFromLatestRec { get; set; }
        public decimal? ActualLECD3TotalClosingCostJFromLatestRec { get; set; }
        public decimal? ActualLECD3TotalPayoffsAndPaymentsKFromLatestRec { get; set; }
        public decimal? ActualSTDLETotalClosingCostJFromLatestRec { get; set; }
        public decimal? ActualSTDLEClosingCostFinancedFromLatestRec { get; set; }
        public decimal? ActualSTDLEDownPaymentFromLatestRec { get; set; }
        public decimal? ActualSTDLEDepositFromLatestRec { get; set; }
        public decimal? ActualSTDLEFundForBorrowerFromLatestRec { get; set; }
        public decimal? ActualSTDLESellerCreditsFromLatestRec { get; set; }
        public decimal? ActualSTDLEAdjustmentAndOtherCreditsFromLatestRec { get; set; }
        public string Id { get; set; }
        public decimal? ActualLenderCredits { get; set; }
        public decimal? ActualSTDLETotalClosingCostJ { get; set; }
        public decimal? ActualSTDLESellerCredits { get; set; }
    }
}