using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class ClosingDisclosure3
    {
        public JsonNullable<decimal?> ActualLECD3TotalClosingCostJFromLatestRec { get; set; }
        public JsonNullable<decimal?> ActualLECD3TotalPayoffsAndPaymentsKFromLatestRec { get; set; }
        public JsonNullable<decimal?> ActualLELoanAmountFromLatestRec { get; set; }
        public JsonNullable<decimal?> ActualLenderCredits { get; set; }
        public JsonNullable<decimal?> ActualSTDLEAdjustmentAndOtherCreditsFromLatestRec { get; set; }
        public JsonNullable<decimal?> ActualSTDLEClosingCostFinancedFromLatestRec { get; set; }
        public JsonNullable<decimal?> ActualSTDLEDepositFromLatestRec { get; set; }
        public JsonNullable<decimal?> ActualSTDLEDownPaymentFromLatestRec { get; set; }
        public JsonNullable<decimal?> ActualSTDLEFundForBorrowerFromLatestRec { get; set; }
        public JsonNullable<decimal?> ActualSTDLESellerCredits { get; set; }
        public JsonNullable<decimal?> ActualSTDLESellerCreditsFromLatestRec { get; set; }
        public JsonNullable<decimal?> ActualSTDLETotalClosingCostJ { get; set; }
        public JsonNullable<decimal?> ActualSTDLETotalClosingCostJFromLatestRec { get; set; }
        public string Adjustments06_1 { get; set; }
        public JsonNullable<decimal?> Adjustments06_2 { get; set; }
        public string Adjustments07_1 { get; set; }
        public JsonNullable<decimal?> Adjustments07_2 { get; set; }
        public string Adjustments10_1 { get; set; }
        public JsonNullable<decimal?> Adjustments10_2 { get; set; }
        public string Adjustments11_1 { get; set; }
        public JsonNullable<decimal?> Adjustments11_2 { get; set; }
        public string Adjustments15_1 { get; set; }
        public JsonNullable<decimal?> Adjustments15_2 { get; set; }
        public string Adjustments8_1 { get; set; }
        public JsonNullable<decimal?> Adjustments8_2 { get; set; }
        public string Adjustments9_1 { get; set; }
        public JsonNullable<decimal?> Adjustments9_2 { get; set; }
        public string AdjustmentsforItemsPaidbySellerinAdvance16_1 { get; set; }
        public JsonNullable<decimal?> AdjustmentsforItemsPaidbySellerinAdvance16_2 { get; set; }
        public string ALTCashToCloseDidChangeCol { get; set; }
        public JsonNullable<decimal?> ALTCashToCloseRemark { get; set; }
        public string ALTClosingCostBeforeClosingDidChangeCol { get; set; }
        public JsonNullable<decimal?> ALTLegalLimit { get; set; }
        public string ALTLoanAmountDidChangeCol { get; set; }
        public string ALTLoanAmountIncDecRemark { get; set; }
        public string ALTTotalClosingCostDidChangeCol { get; set; }
        public string ALTTotalClosingCostRemark { get; set; }
        public string ALTTotalPayoffsDidChangeCol { get; set; }
        public JsonNullable<decimal?> Cash { get; set; }
        public JsonNullable<decimal?> CashToClose { get; set; }
        public JsonNullable<decimal?> CD3CashToClose { get; set; }
        public string CD3CashToCloseFromToBorrower { get; set; }
        public JsonNullable<decimal?> CD3ClosingCostsPaidBeforeClosing { get; set; }
        public JsonNullable<decimal?> CD3TotalClosingCost_J { get; set; }
        public JsonNullable<decimal?> CD3TotalPayoffsAndPayments_K { get; set; }
        public JsonNullable<decimal?> ClosingCostsPaidAtClosing { get; set; }
        public JsonNullable<decimal?> ClosingCostsPaidatClosing_J { get; set; }
        public string DuefromSelleratClosing11_1 { get; set; }
        public JsonNullable<decimal?> DuefromSelleratClosing11_2 { get; set; }
        public string DuefromSelleratClosing12_1 { get; set; }
        public JsonNullable<decimal?> DuefromSelleratClosing12_2 { get; set; }
        public string DuefromSelleratClosing13_1 { get; set; }
        public JsonNullable<decimal?> DuefromSelleratClosing13_2 { get; set; }
        public string DueToSellerAtClosing6_1 { get; set; }
        public JsonNullable<decimal?> DueToSellerAtClosing6_2 { get; set; }
        public string DueToSellerAtClosing7_1 { get; set; }
        public JsonNullable<decimal?> DueToSellerAtClosing7_2 { get; set; }
        public string DueToSellerAtClosing8_1 { get; set; }
        public JsonNullable<decimal?> DueToSellerAtClosing8_2 { get; set; }
        public JsonNullable<bool?> ExcludeBorrowerClosingCosts { get; set; }
        public JsonNullable<decimal?> FinalCashToClose { get; set; }
        public string FromToBorrower { get; set; }
        public string FromToSeller { get; set; }
        public string Id { get; set; }
        public JsonNullable<decimal?> LECD3CashToClose { get; set; }
        public string LECD3CashToCloseFromToBorrower { get; set; }
        public JsonNullable<decimal?> LECD3ClosingCostsPaidBeforeClosing { get; set; }
        public JsonNullable<decimal?> LECD3TotalClosingCost_J { get; set; }
        public JsonNullable<decimal?> LECD3TotalPayoffsAndPayments_K { get; set; }
        public JsonNullable<decimal?> LELoanAmount { get; set; }
        public JsonNullable<decimal?> LiabilityAmount1 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount10 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount11 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount12 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount13 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount14 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount15 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount2 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount3 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount4 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount5 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount6 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount7 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount8 { get; set; }
        public JsonNullable<decimal?> LiabilityAmount9 { get; set; }
        public string LiabilityTo1 { get; set; }
        public string LiabilityTo10 { get; set; }
        public string LiabilityTo11 { get; set; }
        public string LiabilityTo12 { get; set; }
        public string LiabilityTo13 { get; set; }
        public string LiabilityTo14 { get; set; }
        public string LiabilityTo15 { get; set; }
        public string LiabilityTo2 { get; set; }
        public string LiabilityTo3 { get; set; }
        public string LiabilityTo4 { get; set; }
        public string LiabilityTo5 { get; set; }
        public string LiabilityTo6 { get; set; }
        public string LiabilityTo7 { get; set; }
        public string LiabilityTo8 { get; set; }
        public string LiabilityTo9 { get; set; }
        public JsonNullable<decimal?> LiabilityTotal { get; set; }
        public JsonNullable<decimal?> LoanAmount { get; set; }
        public JsonNullable<decimal?> NonUCDTotalAdjustmentsAndOtherCredits { get; set; }
        public JsonNullable<bool?> OmitFromPrintSellersTransaction { get; set; }
        public string OtherCredits6_1 { get; set; }
        public JsonNullable<decimal?> OtherCredits6_2 { get; set; }
        public string OtherCredits7_1 { get; set; }
        public JsonNullable<decimal?> OtherCredits7_2 { get; set; }
        public JsonNullable<decimal?> PriorToleranceCureAmount { get; set; }
        public string STDAdjustmentAndOtherCreditsRemark { get; set; }
        public string STDAdjustmentsDidChangeCol { get; set; }
        public string STDClosingCostFinancedDidChangeCol { get; set; }
        public string STDDepositDidChangeCol { get; set; }
        public string STDDepositIncDecRemark { get; set; }
        public string STDDownPaymentDidChangeCol { get; set; }
        public string STDDownPaymentIncDecRemark { get; set; }
        public string STDDownPaymentSectionRemark { get; set; }
        public JsonNullable<decimal?> STDFinalAdjustmentAndOtherCredits { get; set; }
        public JsonNullable<decimal?> STDFinalCashToClose { get; set; }
        public JsonNullable<decimal?> STDFinalCD3ClosingCostsPaidBeforeClosing { get; set; }
        public JsonNullable<decimal?> STDFinalClosingCostFinanced { get; set; }
        public JsonNullable<decimal?> STDFinalDeposit { get; set; }
        public JsonNullable<decimal?> STDFinalDownPayment { get; set; }
        public JsonNullable<decimal?> STDFinalFundForBorrower { get; set; }
        public JsonNullable<decimal?> STDFinalSellerCredits { get; set; }
        public JsonNullable<decimal?> STDFinalTotalClosingCostJ { get; set; }
        public string STDFundsForBorrowerDidChangeCol { get; set; }
        public string STDFundsForBorrowerIncDecRemark { get; set; }
        public JsonNullable<decimal?> STDLEAdjustmentAndOtherCredits { get; set; }
        public JsonNullable<decimal?> STDLECashToClose { get; set; }
        public JsonNullable<decimal?> STDLECD3ClosingCostsPaidBeforeClosing { get; set; }
        public JsonNullable<decimal?> STDLEClosingCostFinanced { get; set; }
        public JsonNullable<decimal?> STDLEDeposit { get; set; }
        public JsonNullable<decimal?> STDLEDownPayment { get; set; }
        public JsonNullable<decimal?> STDLEFundForBorrower { get; set; }
        public JsonNullable<decimal?> STDLegalLimit { get; set; }
        public JsonNullable<decimal?> STDLESellerCredits { get; set; }
        public JsonNullable<decimal?> STDLETotalClosingCostJ { get; set; }
        public string STDSellerCreditsDidChangeCol { get; set; }
        public string STDSellerCreditsIncDecRemark { get; set; }
        public string STDTotalClosingCostBeforeClosingDidChangeCol { get; set; }
        public string STDTotalClosingCostDidChangeCol { get; set; }
        public string STDTotalClosingCostRemark { get; set; }
        public JsonNullable<decimal?> TotalAdjustmentsAndOtherCredits { get; set; }
        public JsonNullable<decimal?> TotalDuefromBorrowerAtClosing { get; set; }
        public JsonNullable<decimal?> TotalDuefromSelleratClosing_N { get; set; }
        public JsonNullable<decimal?> TotalDuetoSelleratClosing_M { get; set; }
        public JsonNullable<decimal?> TotalFromK { get; set; }
        public JsonNullable<decimal?> TotalFromL { get; set; }
        public JsonNullable<decimal?> TotalFromM { get; set; }
        public JsonNullable<decimal?> TotalFromN { get; set; }
        public JsonNullable<decimal?> TotalPaidAlreadybyoronBehalfofBoroweratClosing { get; set; }
        public JsonNullable<List<UCDDetail>> UCDDetails { get; set; }
        public JsonNullable<decimal?> UCDKSubTotal { get; set; }
        public JsonNullable<decimal?> UCDLSubTotal { get; set; }
        public JsonNullable<decimal?> UCDTotalAdjustmentsAndOtherCredits { get; set; }
    }
}