using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class ClosingDocument
    {
        public string AdditionalLienHolderAddress { get; set; }
        public string AdditionalLienHolderAddressCity { get; set; }
        public string AdditionalLienHolderAddressPostalCode { get; set; }
        public string AdditionalLienHolderAddressState { get; set; }
        public string AdditionalLienHolderName { get; set; }
        public JsonNullable<decimal?> AdditionalOriginalPincipalAmountSecured { get; set; }
        public string AdditionalSigVerbiageType { get; set; }
        public JsonNullable<List<AdditionalStateDisclosure>> AdditionalStateDisclosures { get; set; }
        public JsonNullable<bool?> AffectedByInterest { get; set; }
        public string AlternateLender { get; set; }
        public string AltLenderId { get; set; }
        public JsonNullable<List<AntiSteeringLoanOption>> AntiSteeringLoanOptions { get; set; }
        public string AreAbleToServiceIndicator { get; set; }
        public string AssociatedDocumentNumber { get; set; }
        public string Beneficiaries { get; set; }
        public JsonNullable<bool?> BorrowerConsentType1 { get; set; }
        public JsonNullable<bool?> BorrowerConsentType2 { get; set; }
        public string BorrowerOrganizationType1 { get; set; }
        public string BorrowerOrganizationType2 { get; set; }
        public string BorrowerOrganizedUnderTheLawsOfJurisdictionName1 { get; set; }
        public string BorrowerOrganizedUnderTheLawsOfJurisdictionName2 { get; set; }
        public string BorrowerTaxIdentificationNumberIdentifier1 { get; set; }
        public string BorrowerTaxIdentificationNumberIdentifier2 { get; set; }
        public string BorrowerTrustAmendedDateOrYear1 { get; set; }
        public string BorrowerTrustAmendedDateOrYear2 { get; set; }
        public string BorrowerTrustDateOrYear1 { get; set; }
        public string BorrowerTrustDateOrYear2 { get; set; }
        public string BorrowerUnparsedName1 { get; set; }
        public string BorrowerUnparsedName2 { get; set; }
        public string BrokerAuthorizedRepresentativeTitle { get; set; }
        public string BrokerCompensationMethod { get; set; }
        public string BrokerFeeRefundConditions1 { get; set; }
        public string BrokerFeeRefundConditions2 { get; set; }
        public string BrokerFeeRefundConditions3 { get; set; }
        public string BrokerForPlacingLoan { get; set; }
        public string BrokerInterestRateEffect { get; set; }
        public string BrokerLenderRelationship { get; set; }
        public string BrokerLicenseNumberIdentifier { get; set; }
        public string BrokerNameAsLicensed { get; set; }
        public string BrokerTaxIdentificationNumberIdentifier { get; set; }
        public string BrokerWithLenders { get; set; }
        public JsonNullable<decimal?> CashCheckFromBorrower { get; set; }
        public string ClosingDocsLoanProgramType { get; set; }
        public JsonNullable<List<ClosingEntity>> ClosingEntities { get; set; }
        public string ClosingProvider { get; set; }
        public string ClosingState { get; set; }
        public string ComplianceJurisdictionCounty { get; set; }
        public JsonNullable<DateTime?> CompliancePropertyIdentifiedDate { get; set; }
        public string ConditionDescription { get; set; }
        public JsonNullable<bool?> ConflictofInterestCheck1 { get; set; }
        public JsonNullable<bool?> ConflictofInterestCheck2 { get; set; }
        public JsonNullable<bool?> ConflictofInterestCheck3 { get; set; }
        public JsonNullable<bool?> ConflictofInterestCheck4 { get; set; }
        public JsonNullable<bool?> ConflictofInterestCheck5 { get; set; }
        public JsonNullable<bool?> ConflictofInterestCheck6 { get; set; }
        public string CoopApartmentNumber { get; set; }
        public JsonNullable<DateTime?> CoopAssignmentLeaseDate { get; set; }
        public string CoopAttorneyInFact { get; set; }
        public string CoopBuildingName { get; set; }
        public string CoopCompanyExistsUnderTHeLawsOf { get; set; }
        public string CoopCompanyName { get; set; }
        public JsonNullable<DateTime?> CoopProprietaryLeaseDate { get; set; }
        public JsonNullable<decimal?> CoopSharesOwned { get; set; }
        public string CoopStockCertificationNumber { get; set; }
        public JsonNullable<decimal?> CoopVacancyPercentNotification { get; set; }
        public string CustomOtherRiderDescription { get; set; }
        public JsonNullable<DateTime?> DisbursementDate { get; set; }
        public JsonNullable<decimal?> DisbursementsToBorrower { get; set; }
        public string DisclosureAlternateLender { get; set; }
        public string DisclosureCompanyFunction { get; set; }
        public string DisclosurePlanCode { get; set; }
        public string DocReportGUID { get; set; }
        public JsonNullable<DateTime?> DocumentPreparationDate { get; set; }
        public JsonNullable<DateTime?> DocumentSigningDate { get; set; }
        public string DrawCity { get; set; }
        public string DrawCounty { get; set; }
        public string DrawState { get; set; }
        public string EmployeeofMortgageLender { get; set; }
        public string ExpectToAssignSellOrTransferPercent { get; set; }
        public string FinalVestingDescription { get; set; }
        public string FirstTransferYear { get; set; }
        public JsonNullable<decimal?> FirstTransferYearValue { get; set; }
        public string HoursDocumentsNeededPriorToDisbursementCount { get; set; }
        public JsonNullable<bool?> HousingIndicator { get; set; }
        public string HousingProgramName { get; set; }
        public string HUD1FileNumberIdentifier { get; set; }
        public string HUD1SettlementAgentUnparsedAddress { get; set; }
        public string HUD1SettlementAgentUnparsedName { get; set; }
        public JsonNullable<DateTime?> HUD1SettlementDate { get; set; }
        public string Id { get; set; }
        public JsonNullable<decimal?> IncludeSafeHaborDisclosure { get; set; }
        public string InvestorCode { get; set; }
        public string LastAuditDate { get; set; }
        public string LastDocumentOrdered { get; set; }
        public JsonNullable<bool?> LegalAttached { get; set; }
        public string LenderAuthorizedRepresentativeTitle { get; set; }
        public string LenderBrokerRepresents { get; set; }
        public string LienHolderAddress { get; set; }
        public string LienHolderAddressCity { get; set; }
        public string LienHolderAddressPostalCode { get; set; }
        public string LienHolderAddressState { get; set; }
        public string LienHolderName { get; set; }
        public JsonNullable<bool?> LoanIsLocked { get; set; }
        public string LoanOption { get; set; }
        public string LockInFeeType { get; set; }
        public string MfgHomeAnchored { get; set; }
        public string MfgHomeCertificateOfTitleIdentifier { get; set; }
        public string MfgHomeCertificateOfTitleType { get; set; }
        public string MfgHomeDescription { get; set; }
        public string MfgHomeHUDCertificationLabelIdentifier { get; set; }
        public JsonNullable<int?> MfgHomeLengthFeetCount { get; set; }
        public string MfgHomeMakeIdentifier { get; set; }
        public string MfgHomeManufacturer { get; set; }
        public string MfgHomeManufacturerAddress { get; set; }
        public string MfgHomeManufacturerCity { get; set; }
        public string MfgHomeManufacturerPhoneNumber { get; set; }
        public string MfgHomeManufacturerPostalCode { get; set; }
        public string MfgHomeManufacturerState { get; set; }
        public JsonNullable<int?> MfgHomeManufactureYear { get; set; }
        public string MfgHomeModelIdentifier { get; set; }
        public string MfgHomeNewOrUsed { get; set; }
        public string MfgHomeSerialNumberIdentifier { get; set; }
        public JsonNullable<int?> MfgHomeWidthFeetCount { get; set; }
        public string MineralRightsDescription { get; set; }
        public string MortgageType { get; set; }
        public JsonNullable<int?> NumberBrokerAgreements { get; set; }
        public JsonNullable<int?> NumberSuccessfulBrokerAgreements { get; set; }
        public string OfficeOfRecordationName { get; set; }
        public JsonNullable<bool?> OnlyOneEntity { get; set; }
        public string OptionSelectedReason { get; set; }
        public JsonNullable<decimal?> OriginalPincipalAmountSecured { get; set; }
        public string OtherOptionDescription { get; set; }
        public string ParentAffiliatedCoName { get; set; }
        public string PayToTheOrderOfDescription { get; set; }
        public string PerDiemCalculationMethodType { get; set; }
        public string PlanCode { get; set; }
        public string PlanCodeDescription { get; set; }
        public string PlanCodeId { get; set; }
        public JsonNullable<DateTime?> PreliminaryTitleReportDate { get; set; }
        public string PrepaymentPenaltyDescriptions1 { get; set; }
        public string PrepaymentPenaltyDescriptions2 { get; set; }
        public string PrepaymentPenaltyDescriptions3 { get; set; }
        public JsonNullable<int?> ProcessingNumberDays { get; set; }
        public string ProgramCode { get; set; }
        public string ProgramSponsor { get; set; }
        public JsonNullable<bool?> PropertyIsLandTrust { get; set; }
        public string PropertyTaxMessageDescription { get; set; }
        public string RateLockRefundConditions1 { get; set; }
        public string RateLockRefundConditions2 { get; set; }
        public string RateLockRefundConditions3 { get; set; }
        public string RecordingJurisdictionName { get; set; }
        public JsonNullable<bool?> RefinanceBalloonMortgageGuarantee { get; set; }
        public JsonNullable<bool?> RefinanceRightOfRescissionExemptFlag { get; set; }
        public string RenewalExtensionDescription { get; set; }
        public JsonNullable<DateTime?> RescissionDate { get; set; }
        public JsonNullable<List<RespaHudDetail>> RespaHudDetails { get; set; }
        public string RMLANamePreceding10Years { get; set; }
        public string RmlLenderBrokerRepresents { get; set; }
        public string SecondTransferYear { get; set; }
        public JsonNullable<decimal?> SecondTransferYearValue { get; set; }
        public JsonNullable<DateTime?> SignatureDateFor1003 { get; set; }
        public string SpecialFloodHazardAreaIndictor { get; set; }
        public JsonNullable<List<StateLicense>> StateLicenses { get; set; }
        public string SuretyCompanyName { get; set; }
        public JsonNullable<bool?> SyncInterestDateDisbursementDate { get; set; }
        public string TermiteReportRequiredIndicator { get; set; }
        public string TextDescription { get; set; }
        public string ThirdTransferYear { get; set; }
        public JsonNullable<decimal?> ThirdTransferYearValue { get; set; }
        public string TitleReportItemsDescription { get; set; }
        public string TitleReportRequiredEndorsementsDescription { get; set; }
        public JsonNullable<decimal?> TotalDisbursed { get; set; }
        public string Trust2Beneficiaries { get; set; }
        public string WeConductBusiness { get; set; }
    }
}