using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class ClosingDisclosure1
    {
        public JsonNullable<DateTime?> CDDateIssued { get; set; }
        public string ChangedCircumstance { get; set; }
        public JsonNullable<bool?> ChangedCircumstanceFlag { get; set; }
        public JsonNullable<DateTime?> ChangesReceivedDate { get; set; }
        public string Comments { get; set; }
        public string DisclosureBy { get; set; }
        public string DisclosureComments { get; set; }
        public JsonNullable<DateTime?> DisclosureLastSentDate { get; set; }
        public JsonNullable<DateTime?> DisclosureReceivedDate { get; set; }
        public string DisclosureSentMethod { get; set; }
        public string DocumentGUIDFinalExecutedCopyofAlternateCD { get; set; }
        public string DocumentGUIDFinalExecutedCopyofSellerCD { get; set; }
        public string DocumentGUIDFinalExecutedCopyofStandardCD { get; set; }
        public JsonNullable<decimal?> EstimatedTaxesInsuranceAssessments { get; set; }
        public string Id { get; set; }
        public string InEscrowHomeownerInsurance { get; set; }
        public string InEscrowOther { get; set; }
        public string InEscrowPropertyTaxes { get; set; }
        public JsonNullable<DateTime?> InitialCDReceivedDate { get; set; }
        public string MICReference { get; set; }
        public JsonNullable<bool?> NotNaturalPersonFlag { get; set; }
        public JsonNullable<decimal?> PPC1EstimatedEscrowAmount { get; set; }
        public string PPC1EstimatedEscrowAmountUI { get; set; }
        public JsonNullable<bool?> PPC1InterestOnly { get; set; }
        public JsonNullable<decimal?> PPC1MaximumMonthlyPayment { get; set; }
        public string PPC1MaximumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC1MaximumPIPayment { get; set; }
        public string PPC1MaximumPIPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC1MIAmount { get; set; }
        public string PPC1MIAmountUI { get; set; }
        public JsonNullable<decimal?> PPC1MinimumMonthlyPayment { get; set; }
        public string PPC1MinimumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC1MinimumPIPayment { get; set; }
        public string PPC1MinimumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC1Year { get; set; }
        public JsonNullable<decimal?> PPC2EstimatedEscrowAmount { get; set; }
        public string PPC2EstimatedEscrowAmountUI { get; set; }
        public JsonNullable<bool?> PPC2InterestOnly { get; set; }
        public JsonNullable<decimal?> PPC2MaximumMonthlyPayment { get; set; }
        public string PPC2MaximumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC2MaximumPIPayment { get; set; }
        public string PPC2MaximumPIPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC2MIAmount { get; set; }
        public string PPC2MIAmountUI { get; set; }
        public JsonNullable<decimal?> PPC2MinimumMonthlyPayment { get; set; }
        public string PPC2MinimumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC2MinimumPIPayment { get; set; }
        public string PPC2MinimumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC2YearFrom { get; set; }
        public JsonNullable<int?> PPC2YearTo { get; set; }
        public JsonNullable<decimal?> PPC3EstimatedEscrowAmount { get; set; }
        public string PPC3EstimatedEscrowAmountUI { get; set; }
        public JsonNullable<bool?> PPC3InterestOnly { get; set; }
        public JsonNullable<decimal?> PPC3MaximumMonthlyPayment { get; set; }
        public string PPC3MaximumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC3MaximumPIPayment { get; set; }
        public string PPC3MaximumPIPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC3MIAmount { get; set; }
        public string PPC3MIAmountUI { get; set; }
        public JsonNullable<decimal?> PPC3MinimumMonthlyPayment { get; set; }
        public string PPC3MinimumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC3MinimumPIPayment { get; set; }
        public string PPC3MinimumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC3YearFrom { get; set; }
        public JsonNullable<int?> PPC3YearTo { get; set; }
        public JsonNullable<decimal?> PPC4EstimatedEscrowAmount { get; set; }
        public string PPC4EstimatedEscrowAmountUI { get; set; }
        public JsonNullable<bool?> PPC4InterestOnly { get; set; }
        public JsonNullable<decimal?> PPC4MaximumMonthlyPayment { get; set; }
        public string PPC4MaximumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC4MaximumPIPayment { get; set; }
        public string PPC4MaximumPIPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC4MIAmount { get; set; }
        public string PPC4MIAmountUI { get; set; }
        public JsonNullable<decimal?> PPC4MinimumMonthlyPayment { get; set; }
        public string PPC4MinimumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC4MinimumPIPayment { get; set; }
        public string PPC4MinimumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC4YearFrom { get; set; }
        public JsonNullable<int?> PPC4YearTo { get; set; }
        public JsonNullable<bool?> PPCEstimatedEscrowIndicator { get; set; }
        public JsonNullable<bool?> PPCMortgageInsuranceIndicator { get; set; }
        public JsonNullable<bool?> RangePaymentIndicatorC1 { get; set; }
        public JsonNullable<bool?> RangePaymentIndicatorC2 { get; set; }
        public JsonNullable<bool?> RangePaymentIndicatorC3 { get; set; }
        public JsonNullable<bool?> RangePaymentIndicatorC4 { get; set; }
        public JsonNullable<bool?> ReasonAdvancedReview { get; set; }
        public JsonNullable<bool?> ReasonChangedCircumstanceElg { get; set; }
        public string ReasonChangedCircumstanceFlags { get; set; }
        public JsonNullable<bool?> ReasonChangeInAPR { get; set; }
        public JsonNullable<bool?> ReasonChangeInLoanProduct { get; set; }
        public JsonNullable<bool?> ReasonChangeSettlementCharges { get; set; }
        public JsonNullable<bool?> ReasonClericalErrorCorrection { get; set; }
        public JsonNullable<bool?> ReasonInterestRatecharges { get; set; }
        public JsonNullable<bool?> ReasonOther { get; set; }
        public string ReasonOtherDescription { get; set; }
        public JsonNullable<bool?> ReasonPrepaymentPenalty { get; set; }
        public JsonNullable<bool?> ReasonRevisionsReqConsumer { get; set; }
        public JsonNullable<bool?> ReasonToleranceCure { get; set; }
        public JsonNullable<DateTime?> RevisedCDDueDate { get; set; }
        public JsonNullable<DateTime?> RevisedCDReceivedDate { get; set; }
        public string SellerNames { get; set; }
        public string SignatureTypeFinalExecutedCopyofAlternateCD { get; set; }
        public string SignatureTypeFinalExecutedCopyofSellerCD { get; set; }
        public string SignatureTypeFinalExecutedCopyofStandardCD { get; set; }
        public JsonNullable<decimal?> TotalCashToClose { get; set; }
    }
}