using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class DisclosureTracking2015Log
    {
        public JsonNullable<List<LogAlert>> Alerts { get; set; }
        public string AlertsXml { get; set; }
        public JsonNullable<DateTime?> ApplicationDate { get; set; }
        public string AppliedCureAmount { get; set; }
        public JsonNullable<DateTime?> BorrowerActualReceivedDate { get; set; }
        public string BorrowerDisclosedMethod { get; set; }
        public string BorrowerDisclosedMethodOther { get; set; }
        public string BorrowerName { get; set; }
        public string BorrowerPairId { get; set; }
        public JsonNullable<DateTime?> BorrowerPresumedReceivedDate { get; set; }
        public string BorrowerType { get; set; }
        public JsonNullable<bool?> CDReasonIs24HourAdvancePreview { get; set; }
        public JsonNullable<bool?> CDReasonIsChangeInAPR { get; set; }
        public JsonNullable<bool?> CDReasonIsChangeInLoanProduct { get; set; }
        public JsonNullable<bool?> CDReasonIsChangeInSettlementCharges { get; set; }
        public JsonNullable<bool?> CDReasonIsClericalErrorCorrection { get; set; }
        public JsonNullable<bool?> CDReasonIsOther { get; set; }
        public JsonNullable<bool?> CDReasonIsPrepaymentPenaltyAdded { get; set; }
        public JsonNullable<bool?> CDReasonIsToleranceCure { get; set; }
        public string CDReasonOther { get; set; }
        public string ChangeInCircumstance { get; set; }
        public string ChangeInCircumstanceComments { get; set; }
        public string ChargesCannotIncrease10Itemization34 { get; set; }
        public string ChargesCannotIncrease10LE32 { get; set; }
        public string ChargesThatCannotDecreaseItemization9 { get; set; }
        public string ChargesThatCannotDecreaseLE7 { get; set; }
        public string ChargesThatCannotIncreaseItemization13 { get; set; }
        public string ChargesThatCannotIncreaseLE11 { get; set; }
        public JsonNullable<DateTime?> CoBorrowerActualReceivedDate { get; set; }
        public string CoBorrowerDisclosedMethod { get; set; }
        public string CoBorrowerDisclosedMethodOther { get; set; }
        public string CoBorrowerName { get; set; }
        public JsonNullable<DateTime?> CoBorrowerPresumedReceivedDate { get; set; }
        public string CoBorrowerType { get; set; }
        public JsonNullable<List<LogComment>> CommentList { get; set; }
        public string CommentListXml { get; set; }
        public string Comments { get; set; }
        public JsonNullable<bool?> ContainCD { get; set; }
        public JsonNullable<bool?> ContainLE { get; set; }
        public JsonNullable<bool?> ContainSafeHarbor { get; set; }
        public JsonNullable<DateTime?> DateAdded { get; set; }
        public JsonNullable<DateTime?> DateUtc { get; set; }
        public string DisclosedAPR { get; set; }
        public string DisclosedBy { get; set; }
        public string DisclosedByFullName { get; set; }
        public string DisclosedDailyInterest { get; set; }
        public JsonNullable<DateTime?> DisclosedDate { get; set; }
        public JsonNullable<bool?> DisclosedForCD { get; set; }
        public string DisclosedMethod { get; set; }
        public string DisclosedMethodName { get; set; }
        public string DisclosedMethodOther { get; set; }
        public JsonNullable<DateTime?> DisclosureCreatedDttmUtc { get; set; }
        public string DisclosureMethod { get; set; }
        public string DisclosureType { get; set; }
        public JsonNullable<bool?> EDisclosureApplicationPackageIndicator { get; set; }
        public JsonNullable<bool?> EDisclosureApprovalPackageIndicator { get; set; }
        public JsonNullable<DateTime?> EDisclosureBorrowerAcceptConsentDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureBorrowereSignedDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureBorrowerRejectConsentDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureBorrowerViewConsentDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureBorrowerViewMessageDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureBorrowerWetSignedDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureCoBorrowerAcceptConsentDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureCoBorrowereSignedDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureCoBorrowerRejectConsentDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureCoBorrowerViewConsentDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureCoBorrowerViewMessageDate { get; set; }
        public JsonNullable<DateTime?> EDisclosureCoBorrowerWebSignedDate { get; set; }
        public string EDisclosureConsentPdf { get; set; }
        public string EDisclosureDisclosedMessage { get; set; }
        public JsonNullable<bool?> EDisclosureLockPackageIndicator { get; set; }
        public string EDisclosureManualFulfillmentComment { get; set; }
        public JsonNullable<DateTime?> EDisclosureManualFulfillmentDate { get; set; }
        public string EDisclosureManualFulfillmentMethod { get; set; }
        public string EDisclosureManuallyFulfilledBy { get; set; }
        public JsonNullable<DateTime?> EDisclosurePackageCreatedDate { get; set; }
        public string EDisclosurePackageId { get; set; }
        public string EDisclosurePackageViewableFile { get; set; }
        public JsonNullable<bool?> EDisclosureThreeDayPackageIndicator { get; set; }
        public string EstimatedTotalPayoffsAndPaymentsAmount { get; set; }
        public JsonNullable<bool?> FileAttachmentsMigrated { get; set; }
        public string FinanceCharge { get; set; }
        public JsonNullable<List<DisclosureForm>> Forms { get; set; }
        public string FormsXml { get; set; }
        public string FulfillmentOrderedBy { get; set; }
        public string FullfillmentProcessedDate { get; set; }
        public string Guid { get; set; }
        public string Id { get; set; }
        public JsonNullable<bool?> IntentToProceed { get; set; }
        public string IntentToProceedComments { get; set; }
        public JsonNullable<DateTime?> IntentToProceedDate { get; set; }
        public string IntentToProceedReceivedBy { get; set; }
        public string IntentToProceedReceivedMethod { get; set; }
        public string IntentToProceedReceivedMethodOther { get; set; }
        public JsonNullable<bool?> IsBorrowerPresumedDateLocked { get; set; }
        public JsonNullable<bool?> IsCoBorrowerPresumedDateLocked { get; set; }
        public string IsDisclosed { get; set; }
        public string IsDisclosedAprLocked { get; set; }
        public string IsDisclosedByLocked { get; set; }
        public string IsDisclosedFinanceChargeLocked { get; set; }
        public string IsDisclosedReceivedDateLocked { get; set; }
        public string IsLocked { get; set; }
        public bool? IsSystemSpecificIndicator { get; set; }
        public JsonNullable<bool?> IsWetSignedIndicator { get; set; }
        public string LenderCompensationCreditAmount2 { get; set; }
        public string LenderTotalPaidOriginatorAmount { get; set; }
        public JsonNullable<bool?> LEReasonIsChangedCircumstanceEligibility { get; set; }
        public JsonNullable<bool?> LEReasonIsChangedCircumstanceSettlementCharges { get; set; }
        public JsonNullable<bool?> LEReasonIsDelayedSettlementOnConstructionLoans { get; set; }
        public JsonNullable<bool?> LEReasonIsExpiration { get; set; }
        public JsonNullable<bool?> LEReasonIsInterestRateDependentCharges { get; set; }
        public JsonNullable<bool?> LEReasonIsOther { get; set; }
        public JsonNullable<bool?> LEReasonIsRevisionsRequestedByConsumer { get; set; }
        public string LEReasonOther { get; set; }
        public string Line802LOCompAdditionalAmount1 { get; set; }
        public string Line802LOCompAdditionalAmount2 { get; set; }
        public string Line907InsuranceIndicator2015 { get; set; }
        public string Line907PropertyIndicator2015 { get; set; }
        public string Line907TaxesIndicator2015 { get; set; }
        public string Line908InsuranceIndicator2015 { get; set; }
        public string Line908PropertyIndicator2015 { get; set; }
        public string Line908TaxesIndicator2015 { get; set; }
        public string Line909InsuranceIndicator2015 { get; set; }
        public string Line909PropertyIndicator2015 { get; set; }
        public string Line909TaxesIndicator2015 { get; set; }
        public string Line910InsuranceIndicator2015 { get; set; }
        public string Line910PropertyIndicator2015 { get; set; }
        public string Line910TaxesIndicator2015 { get; set; }
        public string Line911InsuranceIndicator2015 { get; set; }
        public string Line911PropertyIndicator2015 { get; set; }
        public string Line911TaxesIndicator2015 { get; set; }
        public string Line912InsuranceIndicator2015 { get; set; }
        public string Line912PropertyIndicator2015 { get; set; }
        public string Line912TaxesIndicator2015 { get; set; }
        public string LoanAdjustmentsOtherCredits { get; set; }
        public string LoanAmount { get; set; }
        public string LoanClosingCost2BorrowerClosingCostAtClosing { get; set; }
        public string LoanClosingCost2LenderCredits { get; set; }
        public string LoanClosingCost2TotalLoanCost { get; set; }
        public string LoanClosingCost2TotalOtherCost { get; set; }
        public string LoanClosingCost3StdLegalLimit { get; set; }
        public string LoanClosingCostGfe1200BorPaidAmount { get; set; }
        public string LoanClosingCostGfe800BorPaidAmount { get; set; }
        public string LoanClosingCostLenderCredits { get; set; }
        public string LoanClosingCostSection1000BorrowerTotalPaidAmount { get; set; }
        public string LoanClosingCostsFinanced { get; set; }
        public string LoanClosingCostTotalFeeAmount2015 { get; set; }
        public string LoanDownPayment { get; set; }
        public string LoanEstimate2TotalLoanAndOtherCosts { get; set; }
        public string LoanEstimate2TotalLoanCosts { get; set; }
        public string LoanEstimate2TotalOtherCosts { get; set; }
        public string LoanEstimate2UnroundedTotalLoanCosts { get; set; }
        public string LoanEstimate2UnroundedTotalOtherCosts { get; set; }
        public string LoanEstimateLoanProduct { get; set; }
        public string LoanFeesCityTaxBorPaidAmount { get; set; }
        public string LoanFeesStateTaxBorPaidAmount { get; set; }
        public string LoanFundsForBorrower { get; set; }
        public string LoanGfeAgregateAdjustment { get; set; }
        public string LoanGfeGovermentRecordingCharges { get; set; }
        public string LoanLineItemAmount { get; set; }
        public string LoanProgram { get; set; }
        public string LoanPurchaseCreditAmount1 { get; set; }
        public string LoanPurchaseCreditAmount2 { get; set; }
        public string LoanPurchaseCreditAmount3 { get; set; }
        public string LoanPurchaseCreditAmount4 { get; set; }
        public string LoanPurchaseCreditType1 { get; set; }
        public string LoanPurchaseCreditType2 { get; set; }
        public string LoanPurchaseCreditType3 { get; set; }
        public string LoanPurchaseCreditType4 { get; set; }
        public string LoanRefinanceIncludingDebtsToBePaidOffAmount { get; set; }
        public string LoanSection1000SellerPaidTotalAmount { get; set; }
        public string LoanSellerCreditAmount { get; set; }
        public string LoanTotalClosingCosts { get; set; }
        public JsonNullable<DateTime?> LockedBorrowerPresumedReceivedDate { get; set; }
        public JsonNullable<DateTime?> LockedCoBorrowerPresumedReceivedDate { get; set; }
        public string LockedDisclosedAprField { get; set; }
        public string LockedDisclosedByField { get; set; }
        public string LockedDisclosedFinanceChargeField { get; set; }
        public JsonNullable<DateTime?> LockedDisclosedReceivedDate { get; set; }
        public int? LogRecordIndex { get; set; }
        public string ManuallyCreated { get; set; }
        public string PrepaymentPenaltyIndicator { get; set; }
        public string PropertyAddress { get; set; }
        public string PropertyCity { get; set; }
        public string PropertyState { get; set; }
        public string PropertyZip { get; set; }
        public JsonNullable<bool?> ProviderListSent { get; set; }
        public string PurchasePriceAmount { get; set; }
        public JsonNullable<DateTime?> ReceivedDate { get; set; }
        public JsonNullable<List<LogSnapshotField>> SnapshotFields { get; set; }
        public string SnapshotXml { get; set; }
        public JsonNullable<string> SystemId { get; set; }
    }
}