using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class EmDocument
    {
        public string AllngToNtPayToJrsdctn { get; set; }
        public string AllngToNtPayToOrdNm { get; set; }
        public string AllngToNtPayToOrgTyp { get; set; }
        public string AllngToNtPayToScsrsClaus { get; set; }
        public string AllngToNtSignedByNm { get; set; }
        public string AllngToNtSignedByNm2 { get; set; }
        public string AllngToNtSignedByNm3 { get; set; }
        public string AllngToNtSignedByTtl { get; set; }
        public string AllngToNtSignedByTtl2 { get; set; }
        public string AllngToNtSignedByTtl3 { get; set; }
        public string AllngToNtSignedByTyp { get; set; }
        public string AllngToNtWithoutRcrse { get; set; }
        public string ApnLbl { get; set; }
        public JsonNullable<bool?> AsgnPrepByLblTxtDesc { get; set; }
        public JsonNullable<bool?> AsgnRecRtrnLblTxtDesc { get; set; }
        public string BenCty { get; set; }
        public string BenJrsdctn { get; set; }
        public string BenNm { get; set; }
        public string BenOrgTyp { get; set; }
        public string BenStCd { get; set; }
        public string BenStreetAddr1 { get; set; }
        public string BenStreetAddr2 { get; set; }
        public string BenZip { get; set; }
        public string ClosInstrLndCntcInfoCity { get; set; }
        public string ClosInstrLndCntcInfoCoNm { get; set; }
        public string ClosInstrLndCntcInfoSamePtyTypDesc { get; set; }
        public string ClosInstrLndCntcInfoStCd { get; set; }
        public string ClosInstrLndCntcInfoStreetAddr1 { get; set; }
        public string ClosInstrLndCntcInfoStreetAddr2 { get; set; }
        public string ClosInstrLndCntcInfoZip { get; set; }
        public JsonNullable<bool?> ClosInstrPrtInvLossPayee { get; set; }
        public JsonNullable<bool?> ClosInstrStlmtAgtUseLndHud1 { get; set; }
        public string ClosInstrTtlPlcyTyp { get; set; }
        public string EmxmlVersionId { get; set; }
        public string ExeClosDocDlvrdToCty { get; set; }
        public string ExeClosDocDlvrdToMiscTxtDesc { get; set; }
        public string ExeClosDocDlvrdToNm { get; set; }
        public string ExeClosDocDlvrdToSamePtyTypDesc { get; set; }
        public string ExeClosDocDlvrdToStCd { get; set; }
        public string ExeClosDocDlvrdToStreetAddr1 { get; set; }
        public string ExeClosDocDlvrdToStreetAddr2 { get; set; }
        public string ExeClosDocDlvrdToZip { get; set; }
        public string ExeClosDocExprDt { get; set; }
        public string ExeClosDocToBeRtrnd { get; set; }
        public string ExeClosDocToBeRtrndHrs { get; set; }
        public string FnlTtlePcyRecDocsSentToAddlLine1 { get; set; }
        public string FnlTtlePcyRecDocsSentToAddlLine2 { get; set; }
        public string FnlTtlePcyRecDocsSentToCty { get; set; }
        public string FnlTtlePcyRecDocsSentToNm { get; set; }
        public string FnlTtlePcyRecDocsSentToSamePtyTypDesc { get; set; }
        public string FnlTtlePcyRecDocsSentToStcd { get; set; }
        public string FnlTtlePcyRecDocsSentToStreetAddr1 { get; set; }
        public string FnlTtlePcyRecDocsSentToStreetAddr2 { get; set; }
        public string FnlTtlePcyRecDocsSentToZip { get; set; }
        public string HazInsurEndsmtMailToAdtlTxt { get; set; }
        public string HazInsurEndsmtMailToCty { get; set; }
        public string HazInsurEndsmtMailToNm { get; set; }
        public string HazInsurEndsmtMailToStCd { get; set; }
        public string HazInsurEndsmtMailToStreetAddr1 { get; set; }
        public string HazInsurEndsmtMailToStreetAddr2 { get; set; }
        public string HazInsurEndsmtMailToZip { get; set; }
        public string Id { get; set; }
        public string MersAdtlCity { get; set; }
        public string MersAdtlStCd { get; set; }
        public string MersAdtlStreetAddr1 { get; set; }
        public string MersAdtlStreetAddr2 { get; set; }
        public string MersAdtlZip { get; set; }
        public string MersCty { get; set; }
        public string MersJrsdctn { get; set; }
        public string MersName { get; set; }
        public string MersOrgTyp { get; set; }
        public string MersPhoneNum { get; set; }
        public string MersStCd { get; set; }
        public string MersStreetAddr1 { get; set; }
        public string MersStreetAddr2 { get; set; }
        public string MersZip { get; set; }
        public string NtEndrsmtPayToJrsdctn { get; set; }
        public string NtEndrsmtPayToOrdNm { get; set; }
        public string NtEndrsmtPayToOrgTyp { get; set; }
        public string NtEndrsmtPayToScsrsClaus { get; set; }
        public string NtEndrsmtSgndBy1MiscTxt { get; set; }
        public string NtEndrsmtSgndBy2MiscTxt { get; set; }
        public string NtEndrsmtSignedByNm { get; set; }
        public string NtEndrsmtSignedByNm2 { get; set; }
        public string NtEndrsmtSignedByNm3 { get; set; }
        public string NtEndrsmtSignedByTtl { get; set; }
        public string NtEndrsmtSignedByTtl2 { get; set; }
        public string NtEndrsmtSignedByTtl3 { get; set; }
        public string NtEndrsmtSignedByTyp { get; set; }
        public string NtEndrsmtWithoutRcrse { get; set; }
        public string NtEndsmtThrdPtyAddr1 { get; set; }
        public string NtEndsmtThrdPtyAddr2 { get; set; }
        public string NtEndsmtThrdPtyCty { get; set; }
        public string NtEndsmtThrdPtyJrsdctn { get; set; }
        public string NtEndsmtThrdPtyName { get; set; }
        public string NtEndsmtThrdPtyOrgTyp { get; set; }
        public string NtEndsmtThrdPtyPhone { get; set; }
        public string NtEndsmtThrdPtyScsrClaus { get; set; }
        public string NtEndsmtThrdPtyStCd { get; set; }
        public string NtEndsmtThrdPtyZip { get; set; }
        public string NtPayToAdtlTxt { get; set; }
        public string NtPayToCty { get; set; }
        public string NtPayToJrsdctn { get; set; }
        public string NtPayToNm { get; set; }
        public string NtPayToOrgTyp { get; set; }
        public string NtPayToStCd { get; set; }
        public string NtPayToStreetAddr1 { get; set; }
        public string NtPayToStreetAddr2 { get; set; }
        public string NtPayToZip { get; set; }
        public string PmtCpn2PayToAdtlTxt { get; set; }
        public string PmtCpn2PayToAdtlTxt2 { get; set; }
        public string PmtCpn2PayToCty { get; set; }
        public string PmtCpn2PayToNm { get; set; }
        public string PmtCpn2PayToStCd { get; set; }
        public string PmtCpn2PayToStreetAddr1 { get; set; }
        public string PmtCpn2PayToStreetAddr2 { get; set; }
        public string PmtCpn2PayToZip { get; set; }
        public string PmtCpnPayToAdtlTxt { get; set; }
        public string PmtCpnPayToAdtlTxt2 { get; set; }
        public string PmtCpnPayToCty { get; set; }
        public string PmtCpnPayToNm { get; set; }
        public string PmtCpnPayToStCd { get; set; }
        public string PmtCpnPayToStreetAddr1 { get; set; }
        public string PmtCpnPayToStreetAddr2 { get; set; }
        public string PmtCpnPayToZip { get; set; }
        public string PrtAdtlDateHud1 { get; set; }
        public JsonNullable<bool?> PrtAllngToNtBool { get; set; }
        public JsonNullable<bool?> PrtCorpMsgAsgnBool { get; set; }
        public string PrtDocDtSctyIstrmtNtryAprncDt { get; set; }
        public JsonNullable<bool?> PrtIndxTilBool { get; set; }
        public JsonNullable<bool?> PrtInitBlckNtBool { get; set; }
        public JsonNullable<bool?> PrtInitBlckSctyIstrmtBool { get; set; }
        public JsonNullable<bool?> PrtInvLoanNumBool { get; set; }
        public JsonNullable<bool?> PrtInvLoanNumPmtCpn2Ind { get; set; }
        public JsonNullable<bool?> PrtInvLoanNumPmtCpnInd { get; set; }
        public JsonNullable<bool?> PrtInvLossPayeeHazInsurDisBool { get; set; }
        public JsonNullable<bool?> PrtLoanNumDeedBool { get; set; }
        public JsonNullable<bool?> PrtNtEndsmtBool { get; set; }
        public JsonNullable<bool?> PrtNtPayToCorpMsgBool { get; set; }
        public JsonNullable<bool?> PrtScsrsClausClosInstBool { get; set; }
        public JsonNullable<bool?> PrtScsrsClausHazInsurDisBool { get; set; }
        public JsonNullable<bool?> PrtScsrsClausHazInsurLtrBool { get; set; }
        public JsonNullable<bool?> PrtScsrsClausPmtCpnBool { get; set; }
        public JsonNullable<bool?> PrtSctyIstrmtCorpMsgBool { get; set; }
        public string RecRtrnAttnLnNmTxtDesc { get; set; }
        public string RecRtrnCty { get; set; }
        public string RecRtrnLblTxtDesc { get; set; }
        public string RecRtrnNm { get; set; }
        public string RecRtrnNmSamePtyTypDesc { get; set; }
        public string RecRtrnPhoneNum { get; set; }
        public string RecRtrnStCd { get; set; }
        public string RecRtrnStreetAddr1 { get; set; }
        public string RecRtrnStreetAddr2 { get; set; }
        public string RecRtrnTollFreePhoneNum { get; set; }
        public string RecRtrnZip { get; set; }
        public JsonNullable<bool?> RtrnExeClosPkgToLndBrchBool { get; set; }
        public string RtToCancelNtfcAdtlTxt { get; set; }
        public string RtToCancelNtfcCty { get; set; }
        public string RtToCancelNtfcEmail { get; set; }
        public string RtToCancelNtfcFax { get; set; }
        public string RtToCancelNtfcNm { get; set; }
        public string RtToCancelNtfcStCd { get; set; }
        public string RtToCancelNtfcStreetAddr1 { get; set; }
        public string RtToCancelNtfcStreetAddr2 { get; set; }
        public string RtToCancelNtfcZip { get; set; }
        public string RtToCancelTransDtTyp { get; set; }
        public string SctyIstrmtDCTrstFeePct { get; set; }
        public string SctyIstrmtDEAttyFeePct { get; set; }
        public JsonNullable<decimal?> SctyIstrmtLAAttyFeePct { get; set; }
        public JsonNullable<decimal?> SctyIstrmtLAMinAttyFeeAmt { get; set; }
        public string SctyIstrmtMDTrstFeePct { get; set; }
        public string SctyIstrmtMSTrstFeePct { get; set; }
        public string SctyIstrmtNCAttyFeePct { get; set; }
        public string SctyIstrmtNETrstFeePct { get; set; }
        public string SctyIstrmtNVAssmFeeAmt { get; set; }
        public string SctyIstrmtNVTrstFeePct { get; set; }
        public string SctyIstrmtOKAssmFeeAmt { get; set; }
        public string SctyIstrmtPOBoxAddr1 { get; set; }
        public string SctyIstrmtPOBoxAddr2 { get; set; }
        public string SctyIstrmtPrepByAdtlTxt { get; set; }
        public string SctyIstrmtPrepByCoNm { get; set; }
        public string SctyIstrmtPrepByCty { get; set; }
        public string SctyIstrmtPrepByIndvNm { get; set; }
        public string SctyIstrmtPrepByIndvTtl { get; set; }
        public string SctyIstrmtPrepByPhone { get; set; }
        public string SctyIstrmtPrepBySamePtyTypDesc { get; set; }
        public string SctyIstrmtPrepByStCd { get; set; }
        public string SctyIstrmtPrepByStreetAddr1 { get; set; }
        public string SctyIstrmtPrepByStreetAddr2 { get; set; }
        public string SctyIstrmtPrepByTxt { get; set; }
        public string SctyIstrmtPrepByZip { get; set; }
        public string SctyIstrmtTtlAdtlTxt { get; set; }
        public JsonNullable<bool?> SctyIstrmtTtlAdtlTxtAbvTtl { get; set; }
        public string SctyIstrmtVATrstFeePct { get; set; }
        public string Trst1Cnty { get; set; }
        public string Trst1Cty { get; set; }
        public JsonNullable<bool?> Trst1IndvBool { get; set; }
        public string Trst1Jrsdctn { get; set; }
        public string Trst1Nm { get; set; }
        public string Trst1OrgTyp { get; set; }
        public string Trst1Phone { get; set; }
        public string Trst1RsdtTxtDesc { get; set; }
        public string Trst1SamePtyTypDesc { get; set; }
        public string Trst1StCd { get; set; }
        public string Trst1StreetAddr1 { get; set; }
        public string Trst1StreetAddr2 { get; set; }
        public string Trst1Zip { get; set; }
        public string Trst2Cnty { get; set; }
        public string Trst2Cty { get; set; }
        public JsonNullable<bool?> Trst2IndvBool { get; set; }
        public string Trst2Jrsdctn { get; set; }
        public string Trst2Nm { get; set; }
        public string Trst2OrgTyp { get; set; }
        public string Trst2Phone { get; set; }
        public string Trst2RsdtTxtDesc { get; set; }
        public string Trst2SamePtyTypDesc { get; set; }
        public string Trst2StCd { get; set; }
        public string Trst2StreetAddr1 { get; set; }
        public string Trst2StreetAddr2 { get; set; }
        public string Trst2Zip { get; set; }
    }
}