using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class FhaVaLoan
    {
        public string AddendumType { get; set; }
        public JsonNullable<bool?> AdditionalCondition1 { get; set; }
        public JsonNullable<bool?> AdditionalCondition2 { get; set; }
        public JsonNullable<bool?> AdditionalCondition3 { get; set; }
        public JsonNullable<bool?> AdditionalCondition4 { get; set; }
        public JsonNullable<bool?> AdditionalCondition5 { get; set; }
        public JsonNullable<bool?> AdditionalCondition6 { get; set; }
        public JsonNullable<bool?> AdditionalCondition7 { get; set; }
        public JsonNullable<bool?> AdditionalCondition8 { get; set; }
        public JsonNullable<bool?> AdditionalCondition9 { get; set; }
        public string AddressValidatedBy { get; set; }
        public string AddressValidationMessage { get; set; }
        public JsonNullable<bool?> AllConditionsSatisfied { get; set; }
        public JsonNullable<DateTime?> AppraisalLoggedDate { get; set; }
        public string AppraisalLookupBy { get; set; }
        public string BeenInformed { get; set; }
        public string BorrowerCertificationAddress { get; set; }
        public string BorrowerCertificationCity { get; set; }
        public string BorrowerCertificationPostalCode { get; set; }
        public string BorrowerCertificationState { get; set; }
        public string CAIVRSObtainedBy { get; set; }
        public string CaseBinderShippedBy { get; set; }
        public JsonNullable<DateTime?> CaseBinderShippedDate { get; set; }
        public JsonNullable<DateTime?> ClosingDate { get; set; }
        public string CondoPudID { get; set; }
        public string CondoPudLookupBy { get; set; }
        public JsonNullable<DateTime?> CondoPudLookupDate { get; set; }
        public JsonNullable<DateTime?> DateApprovalExpires { get; set; }
        public JsonNullable<DateTime?> DateMortgageApproved { get; set; }
        public string DetailForOther { get; set; }
        public JsonNullable<decimal?> DiscountPoints { get; set; }
        public string DulyAgentAddress { get; set; }
        public string DulyAgentCity { get; set; }
        public string DulyAgentFunction1 { get; set; }
        public string DulyAgentFunction2 { get; set; }
        public string DulyAgentName { get; set; }
        public string DulyAgentState { get; set; }
        public JsonNullable<bool?> DwellingCoveredBy { get; set; }
        public EnergyEfficientMortgage Eem { get; set; }
        public string EligibilityAssessment { get; set; }
        public JsonNullable<decimal?> EnergyEfficientMortgageAmount { get; set; }
        public JsonNullable<List<EnergyEfficientMortgageItem>> EnergyEfficientMortgageItems { get; set; }
        public JsonNullable<bool?> EverHadVAHomeLoan { get; set; }
        public JsonNullable<decimal?> ExcessContributionAmount { get; set; }
        public JsonNullable<decimal?> ExistingDebtAmount { get; set; }
        public string FHACaseOrderedBy { get; set; }
        public string FHAManagementCounselType { get; set; }
        public JsonNullable<decimal?> FHAMaxLoanAmount { get; set; }
        public JsonNullable<bool?> ForeclosedProperty { get; set; }
        public string FreddieMacCounselType { get; set; }
        public JsonNullable<decimal?> FundingFeePaidInCash { get; set; }
        public JsonNullable<decimal?> GiftFundsAmount { get; set; }
        public JsonNullable<bool?> HaveReceivedLeadPaintPoisoningInfo { get; set; }
        public string HUD1003AddendumApproved { get; set; }
        public string Id { get; set; }
        public JsonNullable<DateTime?> LastRefiDate { get; set; }
        public JsonNullable<DateTime?> LDPGSASearchDate { get; set; }
        public string LDPGSASearchedBy { get; set; }
        public string LenderAddress { get; set; }
        public string LenderCity { get; set; }
        public string LenderName { get; set; }
        public string LenderNMLS { get; set; }
        public string LenderPostalCode { get; set; }
        public string LenderRepresentativeName { get; set; }
        public string LenderRepresentativePhone { get; set; }
        public string LenderRepresentativeTitle { get; set; }
        public string LenderState { get; set; }
        public string LenderTaxID { get; set; }
        public string LoanScoreID { get; set; }
        public string MIAppliedBy { get; set; }
        public JsonNullable<DateTime?> MIAppliedDate { get; set; }
        public JsonNullable<DateTime?> MICRetrivedDate { get; set; }
        public JsonNullable<decimal?> MinimumDownPayment { get; set; }
        public JsonNullable<DateTime?> MIP1stDueDate { get; set; }
        public JsonNullable<DateTime?> MIP1stToInvestor { get; set; }
        public JsonNullable<DateTime?> MIPRemittedDate { get; set; }
        public JsonNullable<DateTime?> MIRejectedDate { get; set; }
        public JsonNullable<decimal?> ModifiedInterestRate { get; set; }
        public JsonNullable<decimal?> ModifiedLoanAmount { get; set; }
        public JsonNullable<decimal?> ModifiedMonthlyPayment { get; set; }
        public JsonNullable<decimal?> ModifiedMonthlyPremium { get; set; }
        public JsonNullable<int?> ModifiedProposedMaturityMonth { get; set; }
        public JsonNullable<int?> ModifiedProposedMaturityYear { get; set; }
        public JsonNullable<int?> ModifiedTermAnnualPremium { get; set; }
        public JsonNullable<decimal?> ModifiedUpfrontPremium { get; set; }
        public string MortgageeRepresentative { get; set; }
        public string MortgageFinancialInterest { get; set; }
        public JsonNullable<decimal?> NonRealtyAndOtherItems { get; set; }
        public JsonNullable<DateTime?> ObtainCAIVRSDate { get; set; }
        public string Occupancy { get; set; }
        public string OldAgencyCaseIdentifier { get; set; }
        public JsonNullable<decimal?> OriginalMortgageAmount { get; set; }
        public JsonNullable<decimal?> OtherLiabilitiesMonthlyPayment { get; set; }
        public JsonNullable<decimal?> OtherLiabilitiesUnpaidBalance { get; set; }
        public JsonNullable<decimal?> OtherMonthlyShelterExpense { get; set; }
        public string OtherTitleDescription { get; set; }
        public JsonNullable<bool?> OwnMoreThanFourDwellings { get; set; }
        public JsonNullable<bool?> OwnOrSoldOtherRealEstate { get; set; }
        public JsonNullable<decimal?> PaidAmount { get; set; }
        public JsonNullable<int?> PremiumMonths { get; set; }
        public JsonNullable<decimal?> PrepaidExpenses { get; set; }
        public JsonNullable<DateTime?> PreviousPurchaseDate { get; set; }
        public JsonNullable<DateTime?> PriorEndorsementDate { get; set; }
        public JsonNullable<int?> ProposedMaturityMonths { get; set; }
        public JsonNullable<int?> ProposedMaturityYears { get; set; }
        public string PurposeOfLoan { get; set; }
        public string RefiAuthorizationBy { get; set; }
        public JsonNullable<DateTime?> RefiAuthorizationDate { get; set; }
        public JsonNullable<decimal?> SalesPrice { get; set; }
        public JsonNullable<decimal?> SecondMortgageAmount { get; set; }
        public JsonNullable<decimal?> SellerPaidClosingCost { get; set; }
        public JsonNullable<DateTime?> ServingTransferedDate { get; set; }
        public JsonNullable<decimal?> SpecialAssessments { get; set; }
        public string SponsorAgentAddress { get; set; }
        public string SponsorAgentCity { get; set; }
        public string SponsorAgentName { get; set; }
        public string SponsorAgentNMLS { get; set; }
        public string SponsorAgentPostalCode { get; set; }
        public string SponsorAgentState { get; set; }
        public string SponsorAgentTaxID { get; set; }
        public string SponsoredOriginationsName { get; set; }
        public string SponsoredOriginationsNMLS { get; set; }
        public string SponsoredOriginationsTaxID { get; set; }
        public string SponsorID { get; set; }
        public string TitleVestedIn { get; set; }
        public JsonNullable<bool?> ToBeSold { get; set; }
        public JsonNullable<decimal?> TotalClosingCost { get; set; }
        public string TotalScorecardBy { get; set; }
        public JsonNullable<DateTime?> TotalScorecardDate { get; set; }
        public JsonNullable<DateTime?> UFMIPRemittanceDueDate { get; set; }
        public JsonNullable<decimal?> UFMIPRemittedAmount { get; set; }
        public string UFMIPRemittedBy { get; set; }
        public JsonNullable<DateTime?> UFMIPRemittedDate { get; set; }
        public string UFMIPVerificationCode { get; set; }
        public JsonNullable<bool?> UseDefaultLenderInfo { get; set; }
        public JsonNullable<bool?> UtilityIncluded { get; set; }
        public JsonNullable<DateTime?> ValidateAddressDate { get; set; }
        public string Valuation { get; set; }
    }
}