using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class Gfe2010Section
    {
        public decimal? Section800ChargeAmount { get; set; }
        public string Line808 { get; set; }
        public string Line809 { get; set; }
        public string Line810 { get; set; }
        public string Line811 { get; set; }
        public string Line812 { get; set; }
        public string Line1101 { get; set; }
        public string Line1102 { get; set; }
        public string Line1103 { get; set; }
        public string Line1104 { get; set; }
        public string Line1107 { get; set; }
        public string Line1108 { get; set; }
        public string Line1109 { get; set; }
        public string Line1110 { get; set; }
        public string Line1302 { get; set; }
        public string Line1310 { get; set; }
        public string Line1311 { get; set; }
        public string Line807Company { get; set; }
        public decimal? HudGfeLine1109 { get; set; }
        public decimal? HudGfeLine1110 { get; set; }
        public decimal? HudGfeLine1111 { get; set; }
        public decimal? HudGfeLine1112 { get; set; }
        public decimal? HudGfeLine1113 { get; set; }
        public decimal? HudGfeLine1114 { get; set; }
        public bool? Section1100BorrowerSelectIndicator1 { get; set; }
        public bool? Section1100BorrowerSelectIndicator2 { get; set; }
        public bool? Section1100BorrowerSelectIndicator3 { get; set; }
        public bool? Section1100BorrowerSelectIndicator4 { get; set; }
        public bool? Section1100BorrowerSelectIndicator5 { get; set; }
        public bool? Section1100BorrowerSelectIndicator6 { get; set; }
        public bool? Section1100BorrowerSelectIndicator7 { get; set; }
        public bool? Section1100BorrowerSelectIndicator8 { get; set; }
        public bool? Section1100BorrowerSelectIndicator9 { get; set; }
        public string Line904 { get; set; }
        public string Line909 { get; set; }
        public string Line910 { get; set; }
        public bool? BorrowerSelectIndicator904 { get; set; }
        public bool? BorrowerSelectIndicator906 { get; set; }
        public bool? BorrowerSelectIndicator907 { get; set; }
        public bool? BorrowerSelectIndicator908 { get; set; }
        public bool? BorrowerSelectIndicator909 { get; set; }
        public bool? BorrowerSelectIndicator910 { get; set; }
        public bool? Section1100BorrowerSelectIndicator10 { get; set; }
        public bool? BorrowerSelectIndicator903 { get; set; }
        public string Line819 { get; set; }
        public decimal? Section900HudGfeVaFundingFee { get; set; }
        public decimal? Section800TotalTransferTaxes { get; set; }
        public decimal? Line1101SellerPaidAtoF { get; set; }
        public string Section800CreditChargeType { get; set; }
        public string Section800IncludeOriginationPointsCreditType { get; set; }
        public decimal? Section900HomeownerInsurance { get; set; }
        public bool? Section800ItemizeFeesIndicator { get; set; }
        public decimal? Line1101BorPaidTotal { get; set; }
        public decimal? Line1201BorPaidTotal { get; set; }
        public decimal? Line1301BorPaidTotal { get; set; }
        public decimal? Section1200TotalTransferTaxes { get; set; }
        public decimal? Section800SelChargeAmount { get; set; }
        public decimal? Section1000AggregateAdjust { get; set; }
        public bool? Section1100ItemizeFeesIndicator { get; set; }
        public bool? Section800BonaFideIndicator { get; set; }
        public bool? LoCompensationUseLoCompensationToolIndicator { get; set; }
        public bool? LoCompensationItemizeFeesIndicator { get; set; }
        public decimal? LoCompensationLenderTotalPaidOriginatorAmount { get; set; }
        public decimal? LoCompensationTotalBorrowerPaidDiscountPointAmount4 { get; set; }
        public decimal? LoCompensationTotalSellerPaidDiscountPointAmount4 { get; set; }
        public decimal? LoCompensationTotalLoCompensationAmount { get; set; }
        public decimal? LoCompensationNewHudLenderTotalPaidOriginatorAmount { get; set; }
        public decimal? LoCompensationNewHudTotalBorrowerPaidDiscountPointAmount { get; set; }
        public decimal? LoCompensationNewHudTotalLoCompensationAmount { get; set; }
        public string Line820 { get; set; }
        public string Line821 { get; set; }
        public string Line822 { get; set; }
        public string Line823 { get; set; }
        public string Line824 { get; set; }
        public string Line825 { get; set; }
        public string Line826 { get; set; }
        public string Line827 { get; set; }
        public string Line828 { get; set; }
        public string Line829 { get; set; }
        public string Line830 { get; set; }
        public string Line831 { get; set; }
        public string Line832 { get; set; }
        public string Line833 { get; set; }
        public string Line834 { get; set; }
        public string Line835 { get; set; }
        public string Line911 { get; set; }
        public string Line912 { get; set; }
        public string Line1115 { get; set; }
        public string Line1116 { get; set; }
        public string Line1209 { get; set; }
        public string Line1210 { get; set; }
        public string Line1312 { get; set; }
        public string Line1313 { get; set; }
        public string Line1314 { get; set; }
        public string Line1315 { get; set; }
        public bool? Section1000HudGuaranteeFeeAprIndicator { get; set; }
        public decimal? Line1001BorPaidTotal { get; set; }
        public decimal? Section800InitialDiscountRate { get; set; }
        public decimal? Section800InitialDiscountPoint { get; set; }
        public decimal? Section800InitialDiscountPointAdditionalAmount { get; set; }
        public decimal? Section800BorrowerPaidInitialDiscountPointAmount { get; set; }
        public decimal? Line1103PTAAmount { get; set; }
        public decimal? Line1104PTAAmount { get; set; }
        public string Line803x { get; set; }
        public string Line1316 { get; set; }
        public string Line1317 { get; set; }
        public string Line1318 { get; set; }
        public string Line1319 { get; set; }
        public string Line1320 { get; set; }
        public string ProjectedPaymentTableType { get; set; }
        public string ProjectedPaymentTableColumns { get; set; }
        public bool? ProjectedPaymentTableCustomized { get; set; }
        public bool? LoanTermTableCustomized { get; set; }
        public bool? UseActualPaymentChange { get; set; }
        public string Id { get; set; }
        public decimal? LoCompensationLenderTotalPaidOriginatorAmountForGFE { get; set; }
        public decimal? LoCompensationLenderTotalPaidOriginatorAmountForLOTool { get; set; }
        public string Line701 { get; set; }
        public string Line702 { get; set; }
        public string Line703 { get; set; }
        public string Line704 { get; set; }
        public string Line1001 { get; set; }
        public string Line1002 { get; set; }
        public string Line1003 { get; set; }
        public string Line1004 { get; set; }
        public string Line1005 { get; set; }
        public string Line1006 { get; set; }
        public string Line1007 { get; set; }
        public string Line1008 { get; set; }
        public string Line1009 { get; set; }
        public string Line1010 { get; set; }
        public string Line1011 { get; set; }
    }
}