using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class Gfe2010
    {
        public string DateForRate { get; set; }
        public DateTime? DateForCharges { get; set; }
        public string MustLockRateDays { get; set; }
        public decimal? InitialLoanAmount { get; set; }
        public bool? InterestRateRiseIndicator { get; set; }
        public bool? LoanBalanceRiseIndicator { get; set; }
        public decimal? MaximumLoanBalance { get; set; }
        public bool? MonthlyPaymentRiseIndicator { get; set; }
        public int? MonthlyPaymentFirstIncreaseDate { get; set; }
        public decimal? MaximumOwedMonthlyPayment { get; set; }
        public decimal? OriginationCharges { get; set; }
        public decimal? CuredOriginationCharges { get; set; }
        public decimal? CreditOrChange { get; set; }
        public decimal? CuredCreditOrChange { get; set; }
        public string CreditChargeType { get; set; }
        public decimal? AdjustedOriginationCharges { get; set; }
        public decimal? CuredAdjustedOriginationCharges { get; set; }
        public decimal? RequiredServicesAmount { get; set; }
        public List<Gfe2010Fee> Gfe2010Fees { get; set; }
        public decimal? TitleServiceAmount { get; set; }
        public decimal? OwnerTitleInsuranceAmount { get; set; }
        public decimal? ShopRequiredServicesAmount { get; set; }
        public decimal? TotalBelow10 { get; set; }
        public decimal? TotalTransferTaxes { get; set; }
        public decimal? CuredTotalTransferTaxes { get; set; }
        public string EscrowOtherDescription { get; set; }
        public decimal? HomeownerInsurance { get; set; }
        public decimal? AllOtherServiceAmount { get; set; }
        public decimal? TotalSettlementCharges { get; set; }
        public decimal? LowerSettlementInitialInterestRate { get; set; }
        public decimal? LowerSettlementInitialMonthlyAmountOwed { get; set; }
        public decimal? LowerSettlementMonthlyPaymentIncreased { get; set; }
        public decimal? LowerSettlementServiceChargeReducedAmount { get; set; }
        public decimal? LowerSettlementTotalSettlementCharges { get; set; }
        public decimal? LowerInterestInitialInterestRate { get; set; }
        public decimal? LowerInterestInitialMonthlyAmountOwed { get; set; }
        public decimal? LowerInterestMonthlyPaymentReduced { get; set; }
        public decimal? LowerInterestServiceChargeIncreasedAmount { get; set; }
        public decimal? LowerInterestTotalSettlementCharges { get; set; }
        public bool? BorrowerSelectIndicator2 { get; set; }
        public bool? BorrowerSelectIndicator3 { get; set; }
        public bool? BorrowerSelectIndicator4 { get; set; }
        public bool? BorrowerSelectIndicator5 { get; set; }
        public bool? BorrowerSelectIndicator6 { get; set; }
        public bool? BorrowerSelectIndicator7 { get; set; }
        public bool? BorrowerSelectIndicator8 { get; set; }
        public bool? BorrowerSelectIndicator9 { get; set; }
        public bool? BorrowerSelectIndicator10 { get; set; }
        public bool? BorrowerSelectIndicator11 { get; set; }
        public bool? BorrowerSelectIndicator12 { get; set; }
        public bool? BorrowerSelectIndicator14 { get; set; }
        public bool? BorrowerSelectIndicator15 { get; set; }
        public bool? BorrowerSelectIndicator16 { get; set; }
        public bool? BorrowerSelectIndicator17 { get; set; }
        public bool? BorrowerSelectIndicator18 { get; set; }
        public bool? BorrowerSelectIndicator19 { get; set; }
        public decimal? GfeGovernmentRecordingCharges { get; set; }
        public decimal? InitialMonthlyAmount { get; set; }
        public bool? UseLOCompTool { get; set; }
        public decimal? Line801BrokerCompensationRate { get; set; }
        public decimal? Line801BrokerCompensationAdditionalAmount { get; set; }
        public decimal? Line801BrokerCompensationFees { get; set; }
        public bool? EscrowChargeAllPropertyTaxesIndicator { get; set; }
        public bool? EscrowChargeAllInsuranceIndicator { get; set; }
        public bool? EscrowChargeOtherIndicator { get; set; }
        public bool? CopyFromGfeIndicator1 { get; set; }
        public bool? CopyFromGfeIndicator2 { get; set; }
        public bool? CopyFromGfeIndicator3 { get; set; }
        public bool? CopyFromGfeIndicator4 { get; set; }
        public bool? CopyFromGfeIndicator5 { get; set; }
        public bool? CopyFromGfeIndicator6 { get; set; }
        public bool? CopyFromGfeIndicator7 { get; set; }
        public bool? CopyFromGfeIndicator8 { get; set; }
        public bool? CopyFromGfeIndicator9 { get; set; }
        public bool? CopyFromGfeIndicator10 { get; set; }
        public bool? CopyFromGfeIndicator11 { get; set; }
        public bool? CopyFromGfeIndicator12 { get; set; }
        public bool? CopyFromGfeIndicator13 { get; set; }
        public bool? CopyFromGfeIndicator14 { get; set; }
        public bool? CopyFromGfeIndicator15 { get; set; }
        public bool? CopyFromGfeIndicator16 { get; set; }
        public bool? CopyFromGfeIndicator17 { get; set; }
        public bool? CopyFromGfeIndicator18 { get; set; }
        public bool? CopyFromGfeIndicator19 { get; set; }
        public bool? CopyFromGfeIndicator20 { get; set; }
        public bool? CopyFromGfeIndicator21 { get; set; }
        public bool? CopyFromGfeIndicator22 { get; set; }
        public bool? CopyFromGfeIndicator23 { get; set; }
        public bool? CopyFromGfeIndicator24 { get; set; }
        public bool? CopyFromGfeIndicator25 { get; set; }
        public bool? CopyFromGfeIndicator26 { get; set; }
        public bool? CopyFromGfeIndicator27 { get; set; }
        public bool? CopyFromGfeIndicator28 { get; set; }
        public bool? CopyFromGfeIndicator29 { get; set; }
        public bool? CopyFromGfeIndicator30 { get; set; }
        public bool? CopyFromGfeIndicator31 { get; set; }
        public bool? CopyFromGfeIndicator32 { get; set; }
        public bool? CopyFromGfeIndicator33 { get; set; }
        public decimal? MaxLifeInterestCapPercent { get; set; }
        public int? SubsequentRateAdjustmentMonths { get; set; }
        public int? DurationMonths { get; set; }
        public decimal? SubsequentCapPercent { get; set; }
        public decimal? RequiredAppraisalFee { get; set; }
        public decimal? RequiredCreditReportFee { get; set; }
        public decimal? RequiredTaxServiceFee { get; set; }
        public decimal? RequiredFloodCertificationFee { get; set; }
        public bool? CopyFromGfeIndicator34 { get; set; }
        public bool? CopyFromGfeIndicator35 { get; set; }
        public decimal? MortgageInsurancePremium { get; set; }
        public decimal? HazardInsurance { get; set; }
        public bool? BorrowerSelectIndicator20 { get; set; }
        public decimal? Line808Fee { get; set; }
        public decimal? Line809Fee { get; set; }
        public decimal? Line810Fee { get; set; }
        public decimal? Line811Fee { get; set; }
        public decimal? Line812Fee { get; set; }
        public decimal? Line813Fee { get; set; }
        public decimal? Line814Fee { get; set; }
        public decimal? Line815Fee { get; set; }
        public decimal? Line816Fee { get; set; }
        public decimal? Line817Fee { get; set; }
        public decimal? Line1001Fee { get; set; }
        public decimal? Line1002Fee { get; set; }
        public decimal? Line1003Fee { get; set; }
        public decimal? Line1004Fee { get; set; }
        public decimal? Line1005Fee { get; set; }
        public decimal? Line1006Fee { get; set; }
        public decimal? Line1007Fee { get; set; }
        public decimal? Line1008Fee { get; set; }
        public decimal? Line1009Fee { get; set; }
        public decimal? DailyInterestCharges { get; set; }
        public decimal? ApplicationFees { get; set; }
        public decimal? ProcessingFees { get; set; }
        public decimal? UnderwritingFees { get; set; }
        public decimal? BrokerFeesPercentage { get; set; }
        public decimal? BrokerAdditionalFees { get; set; }
        public decimal? BrokerFees { get; set; }
        public decimal? OriginationPointsPercentage { get; set; }
        public decimal? OriginationPointsAdditional { get; set; }
        public decimal? OriginationPoints { get; set; }
        public decimal? OriginationCreditYsp { get; set; }
        public string IncludeOriginationPointsCreditType { get; set; }
        public decimal? CreditAmount { get; set; }
        public string DaysToSettlement { get; set; }
        public decimal? ChargeAmount { get; set; }
        public decimal? CreditAmountForPrint { get; set; }
        public decimal? ChargeAmountForPrint { get; set; }
        public string TimeForRate { get; set; }
        public decimal? TransferTaxes { get; set; }
        public decimal? OriginationCreditYspAdditional { get; set; }
        public decimal? LoanOriginationPercentage { get; set; }
        public decimal? LoanOriginationFees { get; set; }
        public string LoanOriginatorName { get; set; }
        public bool? PrintShoppingChartIndicator { get; set; }
        public List<Gfe2010WholePoc> Gfe2010WholePocs { get; set; }
        public bool? TableFundedIndicator { get; set; }
        public decimal? Line818Fee { get; set; }
        public decimal? Line819Fee { get; set; }
        public decimal? Line820Fee { get; set; }
        public decimal? Line821Fee { get; set; }
        public decimal? Line822Fee { get; set; }
        public decimal? Line823Fee { get; set; }
        public decimal? Line824Fee { get; set; }
        public decimal? Line825Fee { get; set; }
        public decimal? Line826Fee { get; set; }
        public decimal? Line827Fee { get; set; }
        public decimal? Line828Fee { get; set; }
        public decimal? Line829Fee { get; set; }
        public decimal? Line830Fee { get; set; }
        public decimal? Line831Fee { get; set; }
        public decimal? Line832Fee { get; set; }
        public decimal? Line833Fee { get; set; }
        public decimal? TotalOfFinancedFees { get; set; }
        public decimal? FinancedFeesFromPrepaid { get; set; }
        public decimal? HudGuaranteeFee { get; set; }
        public bool? PrintNAInLockRateDays { get; set; }
        public decimal? Section700TotalBorrowerPaidAmount { get; set; }
        public decimal? Section700TotalSellerPaidAmount { get; set; }
        public decimal? Section700TotalOtherPaidAmount { get; set; }
        public decimal? Section700TotalPaidAmount { get; set; }
        public decimal? Section800TotalBorrowerPaidAmount { get; set; }
        public decimal? Section800TotalSellerPaidAmount { get; set; }
        public decimal? Section800TotalOtherPaidAmount { get; set; }
        public decimal? Section800TotalPaidAmount { get; set; }
        public decimal? Section900TotalBorrowerPaidAmount { get; set; }
        public decimal? Section900TotalSellerPaidAmount { get; set; }
        public decimal? Section900TotalOtherPaidAmount { get; set; }
        public decimal? Section900TotalPaidAmount { get; set; }
        public decimal? Section1000TotalBorrowerPaidAmount { get; set; }
        public decimal? Section1000TotalSellerPaidAmount { get; set; }
        public decimal? Section1000TotalOtherPaidAmount { get; set; }
        public decimal? Section1000TotalPaidAmount { get; set; }
        public decimal? Section1100TotalBorrowerPaidAmount { get; set; }
        public decimal? Section1100TotalSellerPaidAmount { get; set; }
        public decimal? Section1100TotalOtherPaidAmount { get; set; }
        public decimal? Section1100TotalPaidAmount { get; set; }
        public decimal? Section1200TotalBorrowerPaidAmount { get; set; }
        public decimal? Section1200TotalSellerPaidAmount { get; set; }
        public decimal? Section1200TotalOtherPaidAmount { get; set; }
        public decimal? Section1200TotalPaidAmount { get; set; }
        public decimal? Section1300TotalBorrowerPaidAmount { get; set; }
        public decimal? Section1300TotalSellerPaidAmount { get; set; }
        public decimal? Section1300TotalOtherPaidAmount { get; set; }
        public decimal? Section1300TotalPaidAmount { get; set; }
        public decimal? Section1400TotalOtherPaidAmount { get; set; }
        public decimal? Section1400TotalPaidAmount { get; set; }
        public decimal? Section1400TotalBorrowerPaidAmount { get; set; }
        public decimal? Section1400TotalSellerPaidAmount { get; set; }
        public bool? IsCDValidForEarliestClosingDate { get; set; }
        public string Id { get; set; }
        public bool? BorrowerSelectIndicator13 { get; set; }
        public decimal? NewHudSection1100Line1104BorPaidAmount { get; set; }
        public decimal? NewHudSection1100Line1104SelPaidAmount { get; set; }
        public decimal? NewHudSection1100Line1107BorPaidAmount { get; set; }
        public decimal? NewHudSection1100Line1108BorPaidAmount { get; set; }
    }
}