using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class Gfe2010
    {
        public JsonNullable<decimal?> AdjustedOriginationCharges { get; set; }
        public JsonNullable<decimal?> AllOtherServiceAmount { get; set; }
        public JsonNullable<decimal?> ApplicationFees { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator10 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator11 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator12 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator13 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator14 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator15 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator16 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator17 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator18 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator19 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator2 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator20 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator3 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator4 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator5 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator6 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator7 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator8 { get; set; }
        public JsonNullable<bool?> BorrowerSelectIndicator9 { get; set; }
        public JsonNullable<decimal?> BrokerAdditionalFees { get; set; }
        public JsonNullable<decimal?> BrokerFees { get; set; }
        public JsonNullable<decimal?> BrokerFeesPercentage { get; set; }
        public JsonNullable<decimal?> ChargeAmount { get; set; }
        public JsonNullable<decimal?> ChargeAmountForPrint { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator1 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator10 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator11 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator12 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator13 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator14 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator15 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator16 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator17 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator18 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator19 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator2 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator20 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator21 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator22 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator23 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator24 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator25 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator26 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator27 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator28 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator29 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator3 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator30 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator31 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator32 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator33 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator34 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator35 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator4 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator5 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator6 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator7 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator8 { get; set; }
        public JsonNullable<bool?> CopyFromGfeIndicator9 { get; set; }
        public JsonNullable<decimal?> CreditAmount { get; set; }
        public JsonNullable<decimal?> CreditAmountForPrint { get; set; }
        public string CreditChargeType { get; set; }
        public JsonNullable<decimal?> CreditOrChange { get; set; }
        public JsonNullable<decimal?> CuredAdjustedOriginationCharges { get; set; }
        public JsonNullable<decimal?> CuredCreditOrChange { get; set; }
        public JsonNullable<decimal?> CuredOriginationCharges { get; set; }
        public JsonNullable<decimal?> CuredTotalTransferTaxes { get; set; }
        public JsonNullable<decimal?> DailyInterestCharges { get; set; }
        public JsonNullable<DateTime?> DateForCharges { get; set; }
        public string DateForRate { get; set; }
        public string DaysToSettlement { get; set; }
        public JsonNullable<int?> DurationMonths { get; set; }
        public JsonNullable<bool?> EscrowChargeAllInsuranceIndicator { get; set; }
        public JsonNullable<bool?> EscrowChargeAllPropertyTaxesIndicator { get; set; }
        public JsonNullable<bool?> EscrowChargeOtherIndicator { get; set; }
        public string EscrowOtherDescription { get; set; }
        public JsonNullable<decimal?> FinancedFeesFromPrepaid { get; set; }
        public JsonNullable<List<Gfe2010Fee>> Gfe2010Fees { get; set; }
        public JsonNullable<List<Gfe2010WholePoc>> Gfe2010WholePocs { get; set; }
        public JsonNullable<decimal?> GfeGovernmentRecordingCharges { get; set; }
        public JsonNullable<decimal?> HazardInsurance { get; set; }
        public JsonNullable<decimal?> HomeownerInsurance { get; set; }
        public JsonNullable<decimal?> HudGuaranteeFee { get; set; }
        public string Id { get; set; }
        public string IncludeOriginationPointsCreditType { get; set; }
        public JsonNullable<decimal?> InitialLoanAmount { get; set; }
        public JsonNullable<decimal?> InitialMonthlyAmount { get; set; }
        public JsonNullable<bool?> InterestRateRiseIndicator { get; set; }
        public JsonNullable<bool?> IsCDValidForEarliestClosingDate { get; set; }
        public JsonNullable<decimal?> Line1001Fee { get; set; }
        public JsonNullable<decimal?> Line1002Fee { get; set; }
        public JsonNullable<decimal?> Line1003Fee { get; set; }
        public JsonNullable<decimal?> Line1004Fee { get; set; }
        public JsonNullable<decimal?> Line1005Fee { get; set; }
        public JsonNullable<decimal?> Line1006Fee { get; set; }
        public JsonNullable<decimal?> Line1007Fee { get; set; }
        public JsonNullable<decimal?> Line1008Fee { get; set; }
        public JsonNullable<decimal?> Line1009Fee { get; set; }
        public JsonNullable<decimal?> Line801BrokerCompensationAdditionalAmount { get; set; }
        public JsonNullable<decimal?> Line801BrokerCompensationFees { get; set; }
        public JsonNullable<decimal?> Line801BrokerCompensationRate { get; set; }
        public JsonNullable<decimal?> Line808Fee { get; set; }
        public JsonNullable<decimal?> Line809Fee { get; set; }
        public JsonNullable<decimal?> Line810Fee { get; set; }
        public JsonNullable<decimal?> Line811Fee { get; set; }
        public JsonNullable<decimal?> Line812Fee { get; set; }
        public JsonNullable<decimal?> Line813Fee { get; set; }
        public JsonNullable<decimal?> Line814Fee { get; set; }
        public JsonNullable<decimal?> Line815Fee { get; set; }
        public JsonNullable<decimal?> Line816Fee { get; set; }
        public JsonNullable<decimal?> Line817Fee { get; set; }
        public JsonNullable<decimal?> Line818Fee { get; set; }
        public JsonNullable<decimal?> Line819Fee { get; set; }
        public JsonNullable<decimal?> Line820Fee { get; set; }
        public JsonNullable<decimal?> Line821Fee { get; set; }
        public JsonNullable<decimal?> Line822Fee { get; set; }
        public JsonNullable<decimal?> Line823Fee { get; set; }
        public JsonNullable<decimal?> Line824Fee { get; set; }
        public JsonNullable<decimal?> Line825Fee { get; set; }
        public JsonNullable<decimal?> Line826Fee { get; set; }
        public JsonNullable<decimal?> Line827Fee { get; set; }
        public JsonNullable<decimal?> Line828Fee { get; set; }
        public JsonNullable<decimal?> Line829Fee { get; set; }
        public JsonNullable<decimal?> Line830Fee { get; set; }
        public JsonNullable<decimal?> Line831Fee { get; set; }
        public JsonNullable<decimal?> Line832Fee { get; set; }
        public JsonNullable<decimal?> Line833Fee { get; set; }
        public JsonNullable<bool?> LoanBalanceRiseIndicator { get; set; }
        public JsonNullable<decimal?> LoanOriginationFees { get; set; }
        public JsonNullable<decimal?> LoanOriginationPercentage { get; set; }
        public string LoanOriginatorName { get; set; }
        public JsonNullable<decimal?> LowerInterestInitialInterestRate { get; set; }
        public JsonNullable<decimal?> LowerInterestInitialMonthlyAmountOwed { get; set; }
        public JsonNullable<decimal?> LowerInterestMonthlyPaymentReduced { get; set; }
        public JsonNullable<decimal?> LowerInterestServiceChargeIncreasedAmount { get; set; }
        public JsonNullable<decimal?> LowerInterestTotalSettlementCharges { get; set; }
        public JsonNullable<decimal?> LowerSettlementInitialInterestRate { get; set; }
        public JsonNullable<decimal?> LowerSettlementInitialMonthlyAmountOwed { get; set; }
        public JsonNullable<decimal?> LowerSettlementMonthlyPaymentIncreased { get; set; }
        public JsonNullable<decimal?> LowerSettlementServiceChargeReducedAmount { get; set; }
        public JsonNullable<decimal?> LowerSettlementTotalSettlementCharges { get; set; }
        public JsonNullable<decimal?> MaximumLoanBalance { get; set; }
        public JsonNullable<decimal?> MaximumOwedMonthlyPayment { get; set; }
        public JsonNullable<decimal?> MaxLifeInterestCapPercent { get; set; }
        public JsonNullable<int?> MonthlyPaymentFirstIncreaseDate { get; set; }
        public JsonNullable<bool?> MonthlyPaymentRiseIndicator { get; set; }
        public JsonNullable<decimal?> MortgageInsurancePremium { get; set; }
        public string MustLockRateDays { get; set; }
        public JsonNullable<decimal?> NewHudSection1100Line1104BorPaidAmount { get; set; }
        public JsonNullable<decimal?> NewHudSection1100Line1104SelPaidAmount { get; set; }
        public JsonNullable<decimal?> NewHudSection1100Line1107BorPaidAmount { get; set; }
        public JsonNullable<decimal?> NewHudSection1100Line1108BorPaidAmount { get; set; }
        public JsonNullable<decimal?> OriginationCharges { get; set; }
        public JsonNullable<decimal?> OriginationCreditYsp { get; set; }
        public JsonNullable<decimal?> OriginationCreditYspAdditional { get; set; }
        public JsonNullable<decimal?> OriginationPoints { get; set; }
        public JsonNullable<decimal?> OriginationPointsAdditional { get; set; }
        public JsonNullable<decimal?> OriginationPointsPercentage { get; set; }
        public decimal? OwnerTitleInsuranceAmount { get; set; }
        public JsonNullable<bool?> PrintNAInLockRateDays { get; set; }
        public JsonNullable<bool?> PrintShoppingChartIndicator { get; set; }
        public JsonNullable<decimal?> ProcessingFees { get; set; }
        public JsonNullable<decimal?> RequiredAppraisalFee { get; set; }
        public JsonNullable<decimal?> RequiredCreditReportFee { get; set; }
        public JsonNullable<decimal?> RequiredFloodCertificationFee { get; set; }
        public JsonNullable<decimal?> RequiredServicesAmount { get; set; }
        public JsonNullable<decimal?> RequiredTaxServiceFee { get; set; }
        public JsonNullable<decimal?> Section1000TotalBorrowerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1000TotalOtherPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1000TotalPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1000TotalSellerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1100TotalBorrowerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1100TotalOtherPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1100TotalPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1100TotalSellerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1200TotalBorrowerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1200TotalOtherPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1200TotalPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1200TotalSellerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1300TotalBorrowerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1300TotalOtherPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1300TotalPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1300TotalSellerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1400TotalBorrowerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1400TotalOtherPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1400TotalPaidAmount { get; set; }
        public JsonNullable<decimal?> Section1400TotalSellerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section700TotalBorrowerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section700TotalOtherPaidAmount { get; set; }
        public JsonNullable<decimal?> Section700TotalPaidAmount { get; set; }
        public JsonNullable<decimal?> Section700TotalSellerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section800TotalBorrowerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section800TotalOtherPaidAmount { get; set; }
        public JsonNullable<decimal?> Section800TotalPaidAmount { get; set; }
        public JsonNullable<decimal?> Section800TotalSellerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section900TotalBorrowerPaidAmount { get; set; }
        public JsonNullable<decimal?> Section900TotalOtherPaidAmount { get; set; }
        public JsonNullable<decimal?> Section900TotalPaidAmount { get; set; }
        public JsonNullable<decimal?> Section900TotalSellerPaidAmount { get; set; }
        public JsonNullable<decimal?> ShopRequiredServicesAmount { get; set; }
        public JsonNullable<decimal?> SubsequentCapPercent { get; set; }
        public JsonNullable<int?> SubsequentRateAdjustmentMonths { get; set; }
        public JsonNullable<bool?> TableFundedIndicator { get; set; }
        public string TimeForRate { get; set; }
        public JsonNullable<decimal?> TitleServiceAmount { get; set; }
        public JsonNullable<decimal?> TotalBelow10 { get; set; }
        public JsonNullable<decimal?> TotalOfFinancedFees { get; set; }
        public JsonNullable<decimal?> TotalSettlementCharges { get; set; }
        public JsonNullable<decimal?> TotalTransferTaxes { get; set; }
        public JsonNullable<decimal?> TransferTaxes { get; set; }
        public JsonNullable<decimal?> UnderwritingFees { get; set; }
        public JsonNullable<bool?> UseLOCompTool { get; set; }
    }
}