using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class HudLoanData
    {
        public JsonNullable<decimal?> ActualCashInvRequired { get; set; }
        public JsonNullable<decimal?> AdjustedMaxMtgAmount { get; set; }
        public JsonNullable<decimal?> AfterImprovedValue { get; set; }
        public JsonNullable<decimal?> AfterImprovedValueAfter20Percent { get; set; }
        public JsonNullable<decimal?> AllowableEnergyImprovements { get; set; }
        public JsonNullable<decimal?> AppropriateLTVFactor { get; set; }
        public JsonNullable<decimal?> ArchitecturalEngineeringFee { get; set; }
        public JsonNullable<decimal?> AsIsValue { get; set; }
        public JsonNullable<decimal?> BaseMortgageAmountFrom3COr3D { get; set; }
        public string BorrowerAcknowledgement { get; set; }
        public JsonNullable<decimal?> BorrowerEstimatedProfit1 { get; set; }
        public JsonNullable<decimal?> BorrowerEstimatedProfit2 { get; set; }
        public JsonNullable<decimal?> BorrowerPaidClosingCosts { get; set; }
        public JsonNullable<decimal?> BorrowerRequiredInvestment { get; set; }
        public JsonNullable<decimal?> BorrowersOwnFundsforContingencyReserves { get; set; }
        public JsonNullable<bool?> BuildingOnOwnLand { get; set; }
        public JsonNullable<DateTime?> CaseAssignedDate { get; set; }
        public JsonNullable<decimal?> ChildSupportBalance { get; set; }
        public string CHUMSForAppraisal { get; set; }
        public JsonNullable<decimal?> CommitmentMaximumMortgageAmount { get; set; }
        public string CommitmentStage { get; set; }
        public JsonNullable<decimal?> ConstructionRepairsRehabilitationCosts { get; set; }
        public JsonNullable<decimal?> ContingencyReserveCostsAmount { get; set; }
        public JsonNullable<decimal?> ContingencyReserveCostsPercent { get; set; }
        public JsonNullable<decimal?> ContractSalesPrice { get; set; }
        public string CriteriaForAppropriateLTVFactor { get; set; }
        public string DealerContractorAddress { get; set; }
        public string DealerContractorCity { get; set; }
        public string DealerContractorName { get; set; }
        public string DealerContractorPostalCode { get; set; }
        public string DealerContractorState { get; set; }
        public JsonNullable<decimal?> DiscountPointsAmount { get; set; }
        public JsonNullable<decimal?> DiscountPointsPercent { get; set; }
        public JsonNullable<bool?> EEMIndicator { get; set; }
        public JsonNullable<decimal?> EnergyEfficientMortgageAmount { get; set; }
        public string EscrowCommitment { get; set; }
        public JsonNullable<bool?> ExistingDebt { get; set; }
        public JsonNullable<decimal?> ExistingDebtPlusRehabCosts { get; set; }
        public JsonNullable<decimal?> ExistingDebtPlusRehabCostsPlusNewLoanFees { get; set; }
        public JsonNullable<decimal?> FeasibilityStudyWhenNecessary { get; set; }
        public JsonNullable<decimal?> FeesAssociatedWithNewLoan { get; set; }
        public JsonNullable<decimal?> FHA203kB10SubTotal { get; set; }
        public string FHA203kRemarks { get; set; }
        public string FHAStreamlineType { get; set; }
        public JsonNullable<decimal?> FinalBaseMortgageAmount { get; set; }
        public JsonNullable<decimal?> FinanceableMortgageFeesIfCharged { get; set; }
        public JsonNullable<bool?> HaveOtherPendingApplicationForFHA { get; set; }
        public JsonNullable<bool?> HUDOwned { get; set; }
        public JsonNullable<bool?> HUDREOIndicator { get; set; }
        public string Id { get; set; }
        public JsonNullable<decimal?> IndependentConsultantFee { get; set; }
        public JsonNullable<decimal?> InitialBaseMortgageAmountPlusEEMImprovementAmount { get; set; }
        public JsonNullable<decimal?> InitialDrawAtClosingTotal { get; set; }
        public JsonNullable<decimal?> InspectionFeeAmount { get; set; }
        public JsonNullable<decimal?> InspectionFeesDuringRehabilitation { get; set; }
        public JsonNullable<int?> InspectionFeeTimes { get; set; }
        public JsonNullable<bool?> LDPGSAForBorrower { get; set; }
        public JsonNullable<bool?> LDPGSAForCoBorrower { get; set; }
        public JsonNullable<bool?> LeasedFromSomeoneElse { get; set; }
        public JsonNullable<DateTime?> LeaseExpiradionDate { get; set; }
        public JsonNullable<decimal?> LeaseMonthlyPayment { get; set; }
        public JsonNullable<decimal?> LessAllowableDownpayment { get; set; }
        public JsonNullable<decimal?> LesserOf3AOr3B { get; set; }
        public JsonNullable<decimal?> LesserOf3AOr3BMultiply3F { get; set; }
        public JsonNullable<decimal?> LesserOfMaximumFinanceableSolarOrWindEnergyAmount { get; set; }
        public JsonNullable<decimal?> LesserOfSalesPrice { get; set; }
        public JsonNullable<decimal?> LesserOfSumAmount { get; set; }
        public JsonNullable<decimal?> LesserOfSumAsIs { get; set; }
        public JsonNullable<decimal?> LesserOfSumPercent { get; set; }
        public JsonNullable<bool?> LimitedProgram { get; set; }
        public JsonNullable<bool?> LoanFor203KIndicator { get; set; }
        public string LoanPurpose { get; set; }
        public JsonNullable<decimal?> MaterialCostsOrderedPrepaidByBorrowerContractor { get; set; }
        public JsonNullable<decimal?> MaterialCostsOrderedPrepaidByBorrowerContractorAfter50Percent { get; set; }
        public JsonNullable<decimal?> MaximumMortgageWithUFMIP { get; set; }
        public JsonNullable<decimal?> MIPLTV { get; set; }
        public JsonNullable<bool?> MtgOrDeedOfTrusOnProperty { get; set; }
        public JsonNullable<decimal?> MtgPaymentEscrowedAmount { get; set; }
        public JsonNullable<int?> MtgPaymentEscrowedTimes { get; set; }
        public JsonNullable<decimal?> NationwideMortgageLimit { get; set; }
        public JsonNullable<decimal?> NationwideMortgageLimitAfter120Percent { get; set; }
        public JsonNullable<bool?> NewResidential { get; set; }
        public string NonresidentialTypeOfUse { get; set; }
        public JsonNullable<int?> NumberOfHistoricUnits { get; set; }
        public JsonNullable<int?> NumberOfMultifamilyUnits { get; set; }
        public string OtherDescription { get; set; }
        public JsonNullable<bool?> OwnedByBorrower { get; set; }
        public JsonNullable<decimal?> PercentAfterImprovedValue { get; set; }
        public JsonNullable<decimal?> PermitsAndOtherFee { get; set; }
        public JsonNullable<decimal?> PlanReviewerFeeAddition { get; set; }
        public JsonNullable<decimal?> PlanReviewerFeeAmount { get; set; }
        public JsonNullable<int?> PlanReviewerFeeMiles { get; set; }
        public string PropertyOwnerAddress { get; set; }
        public string PropertyOwnerCity { get; set; }
        public string PropertyOwnerName { get; set; }
        public string PropertyOwnerPostalCode { get; set; }
        public string PropertyOwnerState { get; set; }
        public string PropertyToBeImproved { get; set; }
        public string PropertyType { get; set; }
        public JsonNullable<DateTime?> PurchaseDate { get; set; }
        public JsonNullable<bool?> PurchasedOnContract { get; set; }
        public JsonNullable<decimal?> PurchaseMaximumMortgageAmount { get; set; }
        public JsonNullable<decimal?> PurchaseMaximumMortgagePercent { get; set; }
        public JsonNullable<decimal?> PurchasePriceLessInducementToPurchase { get; set; }
        public JsonNullable<decimal?> RefinanceMaximumMortgageAmount { get; set; }
        public JsonNullable<bool?> RefinancingATitleILoan { get; set; }
        public JsonNullable<decimal?> RehabilitationEscrowAccount { get; set; }
        public JsonNullable<decimal?> RehabilitationEscrowAmountBalanceForFutureDraws { get; set; }
        public JsonNullable<decimal?> RentalCashFlowBalance { get; set; }
        public string ResidencyType { get; set; }
        public string RiskClass { get; set; }
        public JsonNullable<bool?> ScoredByTotal { get; set; }
        public JsonNullable<List<SecondaryFinancingProvider>> SecondaryFinancingProviders { get; set; }
        public JsonNullable<decimal?> SellerContributionRate { get; set; }
        public JsonNullable<bool?> SimpleRefinance { get; set; }
        public JsonNullable<decimal?> StatutoryInvestment { get; set; }
        public JsonNullable<decimal?> Step2EPlusStep1E { get; set; }
        public JsonNullable<bool?> Streamlined { get; set; }
        public JsonNullable<decimal?> SubTotalForEscrowAccount { get; set; }
        public JsonNullable<decimal?> SubTotalForReleaseAtClosing { get; set; }
        public JsonNullable<decimal?> SumForInvestor { get; set; }
        public JsonNullable<decimal?> SumForOwnerOccupied { get; set; }
        public JsonNullable<decimal?> SumOfExistingDebt { get; set; }
        public JsonNullable<decimal?> SuplementalOriginationFee { get; set; }
        public JsonNullable<decimal?> Title1LoanBalance { get; set; }
        public string Title1LoanNumber { get; set; }
        public string Title1LoanWithWhom { get; set; }
        public JsonNullable<decimal?> TitleUpdateFeeAmount { get; set; }
        public JsonNullable<decimal?> TitleUpdateFees { get; set; }
        public JsonNullable<int?> TitleUpdateFeeTimes { get; set; }
        public JsonNullable<decimal?> TotalCostsOfRepairsInA6 { get; set; }
        public JsonNullable<decimal?> TotalEscrowCommitment { get; set; }
        public JsonNullable<decimal?> TotalEscrowedFunds { get; set; }
        public JsonNullable<decimal?> TotalFixedUnpaidBalance { get; set; }
        public JsonNullable<decimal?> TotalForBorrowerEstimatedProfit { get; set; }
        public JsonNullable<decimal?> TotalForInspectionAndTitleFee { get; set; }
        public JsonNullable<decimal?> TotalForLesserOfSumAsIs { get; set; }
        public JsonNullable<decimal?> TotalForMtgPaymentEscrowed { get; set; }
        public JsonNullable<decimal?> TotalForPlanReviewerFee { get; set; }
        public JsonNullable<decimal?> TotalForRehabilitationCost { get; set; }
        public JsonNullable<decimal?> TotalRehabilitationCosts { get; set; }
        public JsonNullable<decimal?> TotalRehabilitationCostsFeesReserves { get; set; }
        public JsonNullable<decimal?> ValueEstablished { get; set; }
        public JsonNullable<decimal?> WindEnergySystemActualCost { get; set; }
    }
}