using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class HudLoanData
    {
        public string DealerContractorName { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public bool? HaveOtherPendingApplicationForFHA { get; set; }
        public string DealerContractorAddress { get; set; }
        public string DealerContractorCity { get; set; }
        public string DealerContractorState { get; set; }
        public string DealerContractorPostalCode { get; set; }
        public bool? RefinancingATitleILoan { get; set; }
        public string Title1LoanNumber { get; set; }
        public decimal? Title1LoanBalance { get; set; }
        public string NonresidentialTypeOfUse { get; set; }
        public int? NumberOfHistoricUnits { get; set; }
        public bool? OwnedByBorrower { get; set; }
        public bool? LeasedFromSomeoneElse { get; set; }
        public bool? PurchasedOnContract { get; set; }
        public bool? MtgOrDeedOfTrusOnProperty { get; set; }
        public string PropertyOwnerName { get; set; }
        public string PropertyOwnerAddress { get; set; }
        public string PropertyOwnerCity { get; set; }
        public string PropertyOwnerState { get; set; }
        public string PropertyOwnerPostalCode { get; set; }
        public decimal? LeaseMonthlyPayment { get; set; }
        public DateTime? LeaseExpiradionDate { get; set; }
        public bool? NewResidential { get; set; }
        public string Title1LoanWithWhom { get; set; }
        public string PropertyToBeImproved { get; set; }
        public int? NumberOfMultifamilyUnits { get; set; }
        public bool? HUDOwned { get; set; }
        public decimal? ContingencyReserveCostsAmount { get; set; }
        public int? InspectionFeeTimes { get; set; }
        public decimal? InspectionFeeAmount { get; set; }
        public int? TitleUpdateFeeTimes { get; set; }
        public decimal? TitleUpdateFeeAmount { get; set; }
        public decimal? TotalForInspectionAndTitleFee { get; set; }
        public int? MtgPaymentEscrowedTimes { get; set; }
        public decimal? TotalForMtgPaymentEscrowed { get; set; }
        public decimal? SubTotalForEscrowAccount { get; set; }
        public decimal? ArchitecturalEngineeringFee { get; set; }
        public string CommitmentStage { get; set; }
        public decimal? IndependentConsultantFee { get; set; }
        public decimal? PermitsAndOtherFee { get; set; }
        public int? PlanReviewerFeeMiles { get; set; }
        public decimal? PlanReviewerFeeAmount { get; set; }
        public decimal? TotalForPlanReviewerFee { get; set; }
        public decimal? FHA203kB10SubTotal { get; set; }
        public decimal? DiscountPointsPercent { get; set; }
        public decimal? DiscountPointsAmount { get; set; }
        public decimal? SubTotalForReleaseAtClosing { get; set; }
        public decimal? TotalForRehabilitationCost { get; set; }
        public string EscrowCommitment { get; set; }
        public decimal? LesserOfSalesPrice { get; set; }
        public decimal? BorrowerEstimatedProfit2 { get; set; }
        public decimal? LesserOfSumPercent { get; set; }
        public decimal? LesserOfSumAmount { get; set; }
        public decimal? StatutoryInvestment { get; set; }
        public decimal? PurchaseMaximumMortgagePercent { get; set; }
        public decimal? LessAllowableDownpayment { get; set; }
        public decimal? PurchaseMaximumMortgageAmount { get; set; }
        public decimal? ActualCashInvRequired { get; set; }
        public decimal? AdjustedMaxMtgAmount { get; set; }
        public decimal? ContractSalesPrice { get; set; }
        public decimal? SumOfExistingDebt { get; set; }
        public decimal? LesserOfSumAsIs { get; set; }
        public decimal? TotalForLesserOfSumAsIs { get; set; }
        public decimal? SuplementalOriginationFee { get; set; }
        public decimal? SumForInvestor { get; set; }
        public decimal? SumForOwnerOccupied { get; set; }
        public decimal? RefinanceMaximumMortgageAmount { get; set; }
        public decimal? BorrowerRequiredInvestment { get; set; }
        public decimal? CommitmentMaximumMortgageAmount { get; set; }
        public decimal? AsIsValue { get; set; }
        public decimal? ValueEstablished { get; set; }
        public decimal? TotalEscrowCommitment { get; set; }
        public decimal? TotalForBorrowerEstimatedProfit { get; set; }
        public string FHA203kRemarks { get; set; }
        public decimal? BorrowerPaidClosingCosts { get; set; }
        public decimal? AfterImprovedValue { get; set; }
        public decimal? TotalRehabilitationCosts { get; set; }
        public decimal? MtgPaymentEscrowedAmount { get; set; }
        public decimal? EnergyEfficientMortgageAmount { get; set; }
        public decimal? TotalEscrowedFunds { get; set; }
        public string ResidencyType { get; set; }
        public decimal? PercentAfterImprovedValue { get; set; }
        public decimal? TotalCostsOfRepairsInA6 { get; set; }
        public string BorrowerAcknowledgement { get; set; }
        public string OtherDescription { get; set; }
        public bool? ExistingDebt { get; set; }
        public decimal? BorrowerEstimatedProfit1 { get; set; }
        public decimal? PlanReviewerFeeAddition { get; set; }
        public bool? Streamlined { get; set; }
        public decimal? MaximumMortgageWithUFMIP { get; set; }
        public decimal? AllowableEnergyImprovements { get; set; }
        public decimal? ContingencyReserveCostsPercent { get; set; }
        public decimal? ConstructionRepairsRehabilitationCosts { get; set; }
        public decimal? FeasibilityStudyWhenNecessary { get; set; }
        public decimal? FinanceableMortgageFeesIfCharged { get; set; }
        public decimal? TotalRehabilitationCostsFeesReserves { get; set; }
        public decimal? PurchasePriceLessInducementToPurchase { get; set; }
        public decimal? Step2EPlusStep1E { get; set; }
        public decimal? LesserOf3AOr3B { get; set; }
        public decimal? AppropriateLTVFactor { get; set; }
        public decimal? LesserOf3AOr3BMultiply3F { get; set; }
        public decimal? NationwideMortgageLimit { get; set; }
        public decimal? BaseMortgageAmountFrom3COr3D { get; set; }
        public decimal? MaterialCostsOrderedPrepaidByBorrowerContractor { get; set; }
        public decimal? MaterialCostsOrderedPrepaidByBorrowerContractorAfter50Percent { get; set; }
        public decimal? InitialDrawAtClosingTotal { get; set; }
        public decimal? BorrowersOwnFundsforContingencyReserves { get; set; }
        public decimal? InitialBaseMortgageAmountPlusEEMImprovementAmount { get; set; }
        public decimal? WindEnergySystemActualCost { get; set; }
        public decimal? AfterImprovedValueAfter20Percent { get; set; }
        public decimal? LesserOfMaximumFinanceableSolarOrWindEnergyAmount { get; set; }
        public decimal? NationwideMortgageLimitAfter120Percent { get; set; }
        public decimal? FinalBaseMortgageAmount { get; set; }
        public decimal? RehabilitationEscrowAccount { get; set; }
        public decimal? MIPLTV { get; set; }
        public decimal? FeesAssociatedWithNewLoan { get; set; }
        public decimal? ExistingDebtPlusRehabCosts { get; set; }
        public decimal? ExistingDebtPlusRehabCostsPlusNewLoanFees { get; set; }
        public decimal? InspectionFeesDuringRehabilitation { get; set; }
        public decimal? TitleUpdateFees { get; set; }
        public decimal? RehabilitationEscrowAmountBalanceForFutureDraws { get; set; }
        public bool? LimitedProgram { get; set; }
        public string CriteriaForAppropriateLTVFactor { get; set; }
        public string PropertyType { get; set; }
        public bool? EEMIndicator { get; set; }
        public bool? BuildingOnOwnLand { get; set; }
        public bool? HUDREOIndicator { get; set; }
        public bool? LoanFor203KIndicator { get; set; }
        public string FHAStreamlineType { get; set; }
        public List<SecondaryFinancingProvider> SecondaryFinancingProviders { get; set; }
        public decimal? ChildSupportBalance { get; set; }
        public decimal? RentalCashFlowBalance { get; set; }
        public decimal? TotalFixedUnpaidBalance { get; set; }
        public bool? LDPGSAForBorrower { get; set; }
        public bool? LDPGSAForCoBorrower { get; set; }
        public bool? ScoredByTotal { get; set; }
        public string RiskClass { get; set; }
        public string CHUMSForAppraisal { get; set; }
        public string LoanPurpose { get; set; }
        public DateTime? CaseAssignedDate { get; set; }
        public decimal? SellerContributionRate { get; set; }
        public bool? SimpleRefinance { get; set; }
        public string Id { get; set; }
    }
}