using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class InterimServicing
    {
        public string BorrCellPhoneNumber { get; set; }
        public string BorrHomeEmail { get; set; }
        public string BorrHomePhoneNumber { get; set; }
        public string BorrowerFirstName { get; set; }
        public string BorrowerLastName { get; set; }
        public string BorrWorkPhoneNumber { get; set; }
        public string CalcTriggered { get; set; }
        public JsonNullable<decimal?> CityInsurance { get; set; }
        public string Comments { get; set; }
        public JsonNullable<decimal?> CurrentPrincipalBalance { get; set; }
        public JsonNullable<decimal?> EscrowBalance { get; set; }
        public JsonNullable<List<EscrowDisbursementTransaction>> EscrowDisbursementTransactions { get; set; }
        public JsonNullable<List<EscrowInterestTransaction>> EscrowInterestTransactions { get; set; }
        public JsonNullable<decimal?> FloodInsurance { get; set; }
        public string Id { get; set; }
        public JsonNullable<List<InterimServicingTransaction>> InterimServicingTransactions { get; set; }
        public JsonNullable<decimal?> LastPaymentAdditionalEscrow { get; set; }
        public JsonNullable<decimal?> LastPaymentAdditionalPrincipal { get; set; }
        public JsonNullable<decimal?> LastPaymentBuydownSubsidyAmount { get; set; }
        public JsonNullable<decimal?> LastPaymentEscrowAmount { get; set; }
        public JsonNullable<decimal?> LastPaymentEscrowCityPropertyTax { get; set; }
        public JsonNullable<decimal?> LastPaymentEscrowFloodInsurance { get; set; }
        public JsonNullable<decimal?> LastPaymentEscrowHazardInsurance { get; set; }
        public JsonNullable<decimal?> LastPaymentEscrowMortgageInsurance { get; set; }
        public JsonNullable<decimal?> LastPaymentEscrowOther1 { get; set; }
        public JsonNullable<decimal?> LastPaymentEscrowOther2 { get; set; }
        public JsonNullable<decimal?> LastPaymentEscrowOther3 { get; set; }
        public JsonNullable<decimal?> LastPaymentEscrowTax { get; set; }
        public JsonNullable<decimal?> LastPaymentEscrowUSDAMonthlyPremium { get; set; }
        public string LastPaymentGuid { get; set; }
        public JsonNullable<decimal?> LastPaymentInterest { get; set; }
        public JsonNullable<decimal?> LastPaymentLateFee { get; set; }
        public JsonNullable<decimal?> LastPaymentMiscFee { get; set; }
        public JsonNullable<int?> LastPaymentNumber { get; set; }
        public JsonNullable<decimal?> LastPaymentPrincipal { get; set; }
        public JsonNullable<decimal?> LastPaymentPrincipalAndInterest { get; set; }
        public JsonNullable<DateTime?> LastPaymentReceivedDate { get; set; }
        public JsonNullable<DateTime?> LastPaymentStatementDate { get; set; }
        public JsonNullable<decimal?> LastPaymentTotalAmountReceived { get; set; }
        public JsonNullable<SchedulePaymentTransaction> LastScheduledPayment { get; set; }
        public JsonNullable<DateTime?> LastStatementPrintedDate { get; set; }
        public string LoanSnapshotXml { get; set; }
        public string MailingCity { get; set; }
        public string MailingPostalCode { get; set; }
        public string MailingState { get; set; }
        public string MailingStreetAddress { get; set; }
        public string MortgageAccount { get; set; }
        public JsonNullable<decimal?> NextEscrowTotalFloodInsurance { get; set; }
        public JsonNullable<DateTime?> NextEscrowTotalFloodInsuranceDueDate { get; set; }
        public JsonNullable<decimal?> NextEscrowTotalHazardInsurance { get; set; }
        public JsonNullable<DateTime?> NextEscrowTotalHazardInsuranceDueDate { get; set; }
        public JsonNullable<decimal?> NextEscrowTotalMortgageInsurance { get; set; }
        public JsonNullable<DateTime?> NextEscrowTotalMortgageInsuranceDueDate { get; set; }
        public JsonNullable<decimal?> NextEscrowTotalOtherTax1 { get; set; }
        public JsonNullable<DateTime?> NextEscrowTotalOtherTax1DueDate { get; set; }
        public JsonNullable<decimal?> NextEscrowTotalOtherTax2 { get; set; }
        public JsonNullable<DateTime?> NextEscrowTotalOtherTax2DueDate { get; set; }
        public JsonNullable<decimal?> NextEscrowTotalOtherTax3 { get; set; }
        public JsonNullable<DateTime?> NextEscrowTotalOtherTax3DueDate { get; set; }
        public JsonNullable<decimal?> NextEscrowTotalPropertyTax { get; set; }
        public JsonNullable<DateTime?> NextEscrowTotalPropertyTaxDueDate { get; set; }
        public JsonNullable<decimal?> NextEscrowTotalTax { get; set; }
        public JsonNullable<DateTime?> NextEscrowTotalTaxDueDate { get; set; }
        public JsonNullable<decimal?> NextEscrowTotalUsdaMonthlyPremium { get; set; }
        public JsonNullable<DateTime?> NextEscrowTotalUsdaMonthlyPremiumDueDate { get; set; }
        public JsonNullable<decimal?> NextPaymentBuydownSubsidyAmount { get; set; }
        public JsonNullable<decimal?> NextPaymentEscrowAmount { get; set; }
        public JsonNullable<decimal?> NextPaymentEscrowCityPropertyTax { get; set; }
        public JsonNullable<decimal?> NextPaymentEscrowFloodInsurance { get; set; }
        public JsonNullable<decimal?> NextPaymentEscrowHazardInsurance { get; set; }
        public JsonNullable<decimal?> NextPaymentEscrowMortgageInsurance { get; set; }
        public JsonNullable<decimal?> NextPaymentEscrowOther1 { get; set; }
        public JsonNullable<decimal?> NextPaymentEscrowOther2 { get; set; }
        public JsonNullable<decimal?> NextPaymentEscrowOther3 { get; set; }
        public JsonNullable<decimal?> NextPaymentEscrowTax { get; set; }
        public JsonNullable<decimal?> NextPaymentEscrowUSDAMonthlyPremium { get; set; }
        public JsonNullable<decimal?> NextPaymentIndexCurrentValuePercent { get; set; }
        public JsonNullable<decimal?> NextPaymentInterest { get; set; }
        public JsonNullable<decimal?> NextPaymentLateFee { get; set; }
        public JsonNullable<DateTime?> NextPaymentLatePaymentDate { get; set; }
        public JsonNullable<decimal?> NextPaymentMiscFee { get; set; }
        public JsonNullable<decimal?> NextPaymentPastDueAmount { get; set; }
        public JsonNullable<DateTime?> NextPaymentPaymentDueDate { get; set; }
        public JsonNullable<DateTime?> NextPaymentPaymentIndexDate { get; set; }
        public JsonNullable<decimal?> NextPaymentPrincipal { get; set; }
        public JsonNullable<decimal?> NextPaymentPrincipalAndInterest { get; set; }
        public JsonNullable<decimal?> NextPaymentRequestedInterestRatePercent { get; set; }
        public JsonNullable<DateTime?> NextPaymentStatementDueDate { get; set; }
        public JsonNullable<decimal?> NextPaymentTotalAmountDue { get; set; }
        public JsonNullable<decimal?> NextPaymentTotalAmountWithLateFee { get; set; }
        public JsonNullable<decimal?> NextPaymentUnpaidLateFee { get; set; }
        public JsonNullable<SchedulePaymentTransaction> NextScheduledPayment { get; set; }
        public JsonNullable<int?> NumberOfDisbursement { get; set; }
        public JsonNullable<List<OtherTransaction>> OtherTransactions { get; set; }
        public JsonNullable<DateTime?> PaymentDueDatePrinted { get; set; }
        public JsonNullable<List<PaymentReversalTransaction>> PaymentReversalTransactions { get; set; }
        public JsonNullable<List<PaymentTransaction>> PaymentTransactions { get; set; }
        public string PrintedByUserId { get; set; }
        public string PrintedByUserName { get; set; }
        public JsonNullable<decimal?> PurchasedPrincipal { get; set; }
        public JsonNullable<List<SchedulePaymentTransaction>> ScheduledPayments { get; set; }
        public JsonNullable<List<SchedulePaymentTransaction>> SchedulePaymentTransactions { get; set; }
        public string ServicerLoanNumber { get; set; }
        public string ServicingStatus { get; set; }
        public JsonNullable<DateTime?> ServicingTransferDate { get; set; }
        public string SubServicer { get; set; }
        public string SubServicerLoanNumber { get; set; }
        public JsonNullable<decimal?> TotalAdditionalEscrow { get; set; }
        public JsonNullable<decimal?> TotalAdditionalEscrowYearToDate { get; set; }
        public JsonNullable<decimal?> TotalAdditionalPrincipal { get; set; }
        public JsonNullable<decimal?> TotalAdditionalPrincipalYearToDate { get; set; }
        public JsonNullable<decimal?> TotalAmountDisbursed { get; set; }
        public JsonNullable<decimal?> TotalBuydownSubsidyAmount { get; set; }
        public JsonNullable<decimal?> TotalBuydownSubsidyAmountYearToDate { get; set; }
        public JsonNullable<decimal?> TotalEscrow { get; set; }
        public JsonNullable<decimal?> TotalEscrowYearToDate { get; set; }
        public JsonNullable<decimal?> TotalHazardInsurance { get; set; }
        public JsonNullable<decimal?> TotalInterest { get; set; }
        public JsonNullable<decimal?> TotalInterestYearToDate { get; set; }
        public JsonNullable<decimal?> TotalLateFee { get; set; }
        public JsonNullable<decimal?> TotalLateFeeYearToDate { get; set; }
        public JsonNullable<decimal?> TotalMiscFee { get; set; }
        public JsonNullable<decimal?> TotalMiscFeeYearToDate { get; set; }
        public JsonNullable<decimal?> TotalMortgageInsurance { get; set; }
        public JsonNullable<int?> TotalNumberOfLatePayment { get; set; }
        public JsonNullable<int?> TotalNumberOfPayment { get; set; }
        public JsonNullable<decimal?> TotalOtherTaxes { get; set; }
        public JsonNullable<decimal?> TotalPAndI { get; set; }
        public JsonNullable<decimal?> TotalPAndIYearToDate { get; set; }
        public JsonNullable<decimal?> TotalPaymentCollected { get; set; }
        public JsonNullable<decimal?> TotalPaymentCollectedYearToDate { get; set; }
        public JsonNullable<decimal?> TotalPrincipal { get; set; }
        public JsonNullable<decimal?> TotalPrincipalYearToDate { get; set; }
        public JsonNullable<decimal?> TotalTaxes { get; set; }
        public JsonNullable<decimal?> TotalUsdaMonthlyPremium { get; set; }
        public JsonNullable<decimal?> UnpaidBuydownSubsidyAmount { get; set; }
        public JsonNullable<decimal?> UnpaidEscrow { get; set; }
        public JsonNullable<decimal?> UnpaidEscrowCityPropertyTax { get; set; }
        public JsonNullable<decimal?> UnpaidEscrowFloodInsurance { get; set; }
        public JsonNullable<decimal?> UnpaidEscrowHazardInsurance { get; set; }
        public JsonNullable<decimal?> UnpaidEscrowMortgageInsurance { get; set; }
        public JsonNullable<decimal?> UnpaidEscrowOther1 { get; set; }
        public JsonNullable<decimal?> UnpaidEscrowOther2 { get; set; }
        public JsonNullable<decimal?> UnpaidEscrowOther3 { get; set; }
        public JsonNullable<decimal?> UnpaidEscrowTax { get; set; }
        public JsonNullable<decimal?> UnpaidEscrowUSDAMonthlyPremium { get; set; }
        public JsonNullable<decimal?> UnpaidInterest { get; set; }
        public JsonNullable<decimal?> UnpaidLateFee { get; set; }
        public JsonNullable<decimal?> UnpaidMiscrFee { get; set; }
        public JsonNullable<decimal?> UnpaidPrincipal { get; set; }
    }
}