using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class LoanProductData
    {
        public JsonNullable<decimal?> AnnualFeeNeededAmount { get; set; }
        public JsonNullable<bool?> ApplyLifeCapLowIndicator { get; set; }
        public string ArmDisclosureType { get; set; }
        public string ArmIndexType { get; set; }
        public JsonNullable<bool?> BalloonIndicator { get; set; }
        public JsonNullable<int?> BalloonLoanMaturityTermMonthsCount { get; set; }
        public JsonNullable<DateTime?> BorrowerEstimatedClosingDate { get; set; }
        public string BranchLocationNmlsId { get; set; }
        public string BranchManagerNmlsId { get; set; }
        public JsonNullable<List<Buydown>> Buydowns { get; set; }
        public JsonNullable<bool?> ConvertibleIndicator { get; set; }
        public string Discounted { get; set; }
        public JsonNullable<decimal?> DiscountedRate { get; set; }
        public JsonNullable<int?> DrawPeriodMonthsCount { get; set; }
        public JsonNullable<bool?> EscrowWaiverIndicator { get; set; }
        public JsonNullable<bool?> ExcludeLoanFromNMLSReportIndicator { get; set; }
        public string FloorBasis { get; set; }
        public JsonNullable<decimal?> FloorPercent { get; set; }
        public string FloorVerbiage { get; set; }
        public string FnmProductPlanIdentifier { get; set; }
        public string FreddieMacArmIndexType { get; set; }
        public string FreOfferingIdentifier { get; set; }
        public string FullPrepaymentPenaltyOptionType { get; set; }
        public string GseProjectClassificationType { get; set; }
        public string GsePropertyType { get; set; }
        public JsonNullable<int?> HardPrepaymentPenaltyMonths { get; set; }
        public string HelocPeriodTemplateName { get; set; }
        public JsonNullable<List<HelocRepaymentDrawPeriod>> HelocRepaymentDrawPeriods { get; set; }
        public string Id { get; set; }
        public JsonNullable<decimal?> IndexCurrentValuePercent { get; set; }
        public string IndexLookbackPeriod { get; set; }
        public JsonNullable<decimal?> IndexMarginPercent { get; set; }
        public JsonNullable<decimal?> InitialAdvanceAmount { get; set; }
        public JsonNullable<decimal?> InitialApplicationAmount { get; set; }
        public JsonNullable<bool?> InquiryOrPreQualificationIndicator { get; set; }
        public string LienPriorityType { get; set; }
        public string LoanDocumentationType { get; set; }
        public string LoanRepaymentType { get; set; }
        public JsonNullable<DateTime?> LoanScheduledClosingDate { get; set; }
        public JsonNullable<decimal?> MaximumMonthlyPayment { get; set; }
        public JsonNullable<decimal?> MaxLifeInterestCapPercent { get; set; }
        public JsonNullable<decimal?> MiCoveragePercent { get; set; }
        public JsonNullable<decimal?> MinimumAdvanceAmount { get; set; }
        public JsonNullable<decimal?> MinimumAllowableApr { get; set; }
        public JsonNullable<decimal?> MinimumDrawPeroidPaymentPercent { get; set; }
        public JsonNullable<decimal?> MinimumPaymentAmount { get; set; }
        public JsonNullable<decimal?> MinimumPaymentLessThanAmount { get; set; }
        public JsonNullable<decimal?> MinimumPaymentPercent { get; set; }
        public JsonNullable<decimal?> MinimumPaymentUpbAmount { get; set; }
        public JsonNullable<decimal?> MinimumPaymentUpbPercent { get; set; }
        public JsonNullable<decimal?> MinimumRepayPeriodPaymentPercent { get; set; }
        public JsonNullable<int?> MonthsAppliedToPrepaymentPenaltyFeeCount { get; set; }
        public JsonNullable<decimal?> NegativeAmortizationLimitPercent { get; set; }
        public JsonNullable<decimal?> NetInitialAndFinal { get; set; }
        public string NmlsDocumentationType { get; set; }
        public string NmlsFirstMortgageType { get; set; }
        public string NmlsLoanType { get; set; }
        public JsonNullable<bool?> NmlsOptionARMIndicator { get; set; }
        public JsonNullable<bool?> NmlsPiggyBackOrFundedHELOCIndicator { get; set; }
        public string NmlsProductionSoldToType { get; set; }
        public string NmlsRefinancePurposeType { get; set; }
        public string NmlsReverseMortgageType { get; set; }
        public JsonNullable<bool?> OralRequestForExtensionOfCreditIndicator { get; set; }
        public JsonNullable<decimal?> OverLimitCharge { get; set; }
        public JsonNullable<decimal?> OverLimitReturnCharge { get; set; }
        public JsonNullable<decimal?> ParticipationFees { get; set; }
        public JsonNullable<int?> PaymentAdjustmentDurationMonthsCount { get; set; }
        public JsonNullable<decimal?> PaymentAdjustmentPeriodicCapPercent { get; set; }
        public string PaymentFrequencyType { get; set; }
        public JsonNullable<List<PrepaymentPenalty>> PrepaymentPenalties { get; set; }
        public string PrepaymentPenaltyBasedOn { get; set; }
        public JsonNullable<bool?> PrepaymentPenaltyIndicator { get; set; }
        public JsonNullable<decimal?> PrepaymentPenaltyPercent { get; set; }
        public JsonNullable<int?> PrepaymentPenaltyTermMonthsCount { get; set; }
        public string PrepaymentPenaltyVerbiage { get; set; }
        public string ProductName { get; set; }
        public JsonNullable<decimal?> QualifyingRatePercent { get; set; }
        public JsonNullable<int?> RateAdjustmentDurationMonthsCount { get; set; }
        public JsonNullable<decimal?> RateAdjustmentLifetimeCapPercent { get; set; }
        public JsonNullable<decimal?> RateAdjustmentPercent { get; set; }
        public JsonNullable<decimal?> RateAdjustmentSubsequentCapPercent { get; set; }
        public JsonNullable<decimal?> ReleaseRecoringCharge { get; set; }
        public JsonNullable<decimal?> RemainingBuydownAmount { get; set; }
        public JsonNullable<int?> RepayPeriodMonthsCount { get; set; }
        public JsonNullable<decimal?> ReturnedCheckCharge { get; set; }
        public JsonNullable<decimal?> ReturnedCheckChargeRatePercent { get; set; }
        public JsonNullable<decimal?> ReturnedCheckMaxCharge { get; set; }
        public JsonNullable<decimal?> ReturnedCheckMinCharge { get; set; }
        public JsonNullable<decimal?> RoundPercent { get; set; }
        public string RoundType { get; set; }
        public JsonNullable<DateTime?> ScheduledFirstPaymentAdjustmentDate { get; set; }
        public JsonNullable<DateTime?> ScheduledFirstPaymentDate { get; set; }
        public JsonNullable<decimal?> StopPaymentCharge { get; set; }
        public JsonNullable<int?> SubsequentRateAdjustmentMonthsCount { get; set; }
        public JsonNullable<decimal?> TerminationFeeAmount { get; set; }
        public JsonNullable<int?> TerminationPeriodMonthsCount { get; set; }
        public JsonNullable<decimal?> ThirdPartyFeeFromAmount { get; set; }
        public JsonNullable<decimal?> ThirdPartyFeeToAmount { get; set; }
        public JsonNullable<decimal?> TimelyPaymentRateReductionPercent { get; set; }
        public string TimelyPaymentRewards { get; set; }
        public JsonNullable<decimal?> TotalSubsidyAmount { get; set; }
        public JsonNullable<decimal?> TransactionFees { get; set; }
        public JsonNullable<decimal?> WireFee { get; set; }
    }
}