using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class Loan
    {
        public AdditionalRequests AdditionalRequests { get; set; }
        public JsonNullable<DateTime?> AdverseActionDate { get; set; }
        public JsonNullable<List<AffiliatedBusinessArrangement>> AffiliatedBusinessArrangements { get; set; }
        public string AgencyCaseIdentifier { get; set; }
        public JsonNullable<decimal?> AlterationsImprovementsOrRepairsAmount { get; set; }
        public JsonNullable<List<Application>> Applications { get; set; }
        public string ApplicationTakenMethodType { get; set; }
        public JsonNullable<DateTime?> AprDisclosureDate { get; set; }
        public string ArmTypeDescription { get; set; }
        public ATRQMCommon ATRQMCommon { get; set; }
        public JsonNullable<decimal?> BaseLoanAmount { get; set; }
        public JsonNullable<bool?> BelowMarketSubordinateFinancingIndicator { get; set; }
        public string BillingCategory { get; set; }
        public JsonNullable<decimal?> BiweeklyPaymentAmount { get; set; }
        public JsonNullable<int?> BLTV { get; set; }
        public JsonNullable<bool?> BorrowerCoBorrowerMarriedIndicator { get; set; }
        public JsonNullable<decimal?> BorrowerPaidClosingCostsAmount { get; set; }
        public JsonNullable<decimal?> BorrowerPaidDiscountPointsAmount { get; set; }
        public JsonNullable<decimal?> BorrowerPaidFHAVAClosingCostsAmount { get; set; }
        public JsonNullable<decimal?> BorrowerRequestedLoanAmount { get; set; }
        public JsonNullable<decimal?> BrokerPaidClosingCostsAmount { get; set; }
        public JsonNullable<bool?> BuydownIndicator { get; set; }
        public JsonNullable<decimal?> BuydownMonthlyPaymentAmount { get; set; }
        public JsonNullable<decimal?> BuydownRatePercent { get; set; }
        public JsonNullable<decimal?> CashFromToBorrowerAmount { get; set; }
        public string Channel { get; set; }
        public JsonNullable<DateTime?> ClosingBillingDate { get; set; }
        public ClosingCost ClosingCost { get; set; }
        public string ClosingCostProgram { get; set; }
        public JsonNullable<decimal?> ClosingCostsAndPrepaidsFromOtherLienAmount { get; set; }
        public JsonNullable<decimal?> ClosingCostsPaidByOthersAmount { get; set; }
        public string ClosingDocsStackingOrder { get; set; }
        public ClosingDocument ClosingDocument { get; set; }
        public JsonNullable<int?> CollateralManagerScore { get; set; }
        public JsonNullable<decimal?> CombinedLtv { get; set; }
        public string CommitmentNumber { get; set; }
        public CommitmentTerms CommitmentTerms { get; set; }
        public JsonNullable<List<ComplianceTestLog>> ComplianceTestLogs { get; set; }
        public string ConformingJumbo { get; set; }
        public ConstructionManagement ConstructionManagement { get; set; }
        public string ConsumerConnectSiteID { get; set; }
        public JsonNullable<List<Contact>> Contacts { get; set; }
        public JsonNullable<bool?> ContactUpdatedIndicator { get; set; }
        public JsonNullable<decimal?> ContractSellerCreditAmount { get; set; }
        public JsonNullable<List<ConversationLog>> ConversationLogs { get; set; }
        public JsonNullable<bool?> CopyBrokerToLenderIndicator { get; set; }
        public string CopyLoanNumLenderCaseNum { get; set; }
        public Correspondent Correspondent { get; set; }
        public string CreditScoreToUse { get; set; }
        public JsonNullable<List<CrmLog>> CrmLogs { get; set; }
        public Application CurrentApplication { get; set; }
        public int? CurrentApplicationIndex { get; set; }
        public bool? CurrentApplicationIsPrimary { get; set; }
        public string CurrentFirstMortgageHolderType { get; set; }
        public JsonNullable<List<CustomField>> CustomFields { get; set; }
        public JsonNullable<CustomModelFields> CustomModelFields { get; set; }
        public JsonNullable<List<DataTracLog>> DataTracLogs { get; set; }
        public bool? DBIndicator { get; set; }
        public JsonNullable<bool?> DeductOverwireAmountIndicator { get; set; }
        public JsonNullable<bool?> DisableESignConsentAlert { get; set; }
        public JsonNullable<bool?> DisableKeyPricingAlert { get; set; }
        public DisclosureNotices DisclosureNotices { get; set; }
        public JsonNullable<List<DisclosureTracking2015Log>> DisclosureTracking2015Logs { get; set; }
        public JsonNullable<List<DisclosureTrackingLog>> DisclosureTrackingLogs { get; set; }
        public JsonNullable<decimal?> DiscountPoint { get; set; }
        public string DocEngine { get; set; }
        public JsonNullable<List<DocumentLog>> DocumentLogs { get; set; }
        public string DoNotCheckEmail { get; set; }
        public JsonNullable<bool?> DoNotPrintCompensationFees { get; set; }
        public JsonNullable<List<DownloadLog>> DownloadLogs { get; set; }
        public DownPayment DownPayment { get; set; }
        public JsonNullable<decimal?> DownPaymentPercent { get; set; }
        public JsonNullable<List<EdmLog>> EdmLogs { get; set; }
        public JsonNullable<List<EmailTriggerLog>> EmailTriggerLogs { get; set; }
        public EmDocument EmDocument { get; set; }
        public EmDocumentInvestor EmDocumentInvestor { get; set; }
        public EmDocumentLender EmDocumentLender { get; set; }
        public string EmXmlVersionId { get; set; }
        public string EncompassId { get; set; }
        public JsonNullable<bool?> EnforceCountyLoanLimit { get; set; }
        public JsonNullable<decimal?> EstimatedClosingCostsAmount { get; set; }
        public JsonNullable<decimal?> EstimatedConstructionInterest { get; set; }
        public JsonNullable<decimal?> EstimatedPrepaidItemsAmount { get; set; }
        public string ExportLoanNumber { get; set; }
        public FannieMae FannieMae { get; set; }
        public JsonNullable<List<Fee>> Fees { get; set; }
        public JsonNullable<decimal?> FhaMiPremiumRefundAmount { get; set; }
        public FhaVaLoan FhaVaLoan { get; set; }
        public string FHAVALoanOriginatorIdentifier { get; set; }
        public JsonNullable<List<FieldLockData>> FieldLockData { get; set; }
        public JsonNullable<decimal?> FirstAdjustmentMinimum { get; set; }
        public JsonNullable<decimal?> FirstSubordinateLienAmount { get; set; }
        public JsonNullable<bool?> FirstTimeHomebuyersIndicator { get; set; }
        public string FnmCommunityLendingProductName { get; set; }
        public JsonNullable<bool?> FnmCommunitySecondsIndicator { get; set; }
        public JsonNullable<bool?> FnmNeighborsMortgageEligibilityIndicator { get; set; }
        public JsonNullable<List<Form>> Forms { get; set; }
        public JsonNullable<int?> FraudScore { get; set; }
        public FreddieMac FreddieMac { get; set; }
        public Funding Funding { get; set; }
        public string FundingDeductionList { get; set; }
        public string FundingFeeList { get; set; }
        public JsonNullable<List<FundingFee>> FundingFees { get; set; }
        public Gfe Gfe { get; set; }
        public string GovernmentLoanLenderIdentifier { get; set; }
        public string GovernmentLoanSponsorIdentifier { get; set; }
        public JsonNullable<decimal?> GovernmentMortgageCreditCertificateAmount { get; set; }
        public string HasAbusinessRelationshipWith { get; set; }
        public JsonNullable<decimal?> HcltvHtltv { get; set; }
        public JsonNullable<decimal?> HelocTeaserRate { get; set; }
        public Hmda Hmda { get; set; }
        public JsonNullable<List<HomeCounselingProvider>> HomeCounselingProviders { get; set; }
        public string HomeCounselingProvidersDistance { get; set; }
        public string HomeCounselingProvidersLanguageNames { get; set; }
        public string HomeCounselingProvidersServiceNames { get; set; }
        public JsonNullable<int?> HouseholdSizeCount { get; set; }
        public JsonNullable<List<HtmlEmailLog>> HtmlEmailLogs { get; set; }
        public Hud1Es Hud1Es { get; set; }
        public JsonNullable<decimal?> HudIncomeLimitAdjustmentFactor { get; set; }
        public JsonNullable<decimal?> HudLendingIncomeLimitAmount { get; set; }
        public HudLoanData HudLoanData { get; set; }
        public JsonNullable<decimal?> HudMedianIncomeAmount { get; set; }
        public string Id { get; set; }
        public JsonNullable<bool?> IncludeUSDAFeeInClosing { get; set; }
        public JsonNullable<decimal?> InitialInterestRate { get; set; }
        public string InsuranceAuthorizationIndicator { get; set; }
        public InterimServicing InterimServicing { get; set; }
        public JsonNullable<DateTime?> InterviewerApplicationSignedDate { get; set; }
        public string InterviewerEmail { get; set; }
        public string InterviewerLicenseIdentifier { get; set; }
        public string InterviewerPhoneNumber { get; set; }
        public string InterviewersCompanyStateLicense { get; set; }
        public string InterviewersId { get; set; }
        public string InverviewerName { get; set; }
        public JsonNullable<bool?> IsCreditorProhibitsBorrower { get; set; }
        public JsonNullable<bool?> IsEmployeeLoan { get; set; }
        public JsonNullable<bool?> IsLSSecondaryFile { get; set; }
        public JsonNullable<bool?> IsRequiredInterestReserveCompoundInterest { get; set; }
        public JsonNullable<decimal?> LandIfAcquiredSeperatelyAmount { get; set; }
        public string LeadSource { get; set; }
        public string LenderCaseIdentifier { get; set; }
        public string LenderChannel { get; set; }
        public JsonNullable<decimal?> LenderCreditsInFunding { get; set; }
        public string LenderInvestorCode { get; set; }
        public JsonNullable<decimal?> LenderPaidClosignCostsDotAmount { get; set; }
        public JsonNullable<decimal?> LenderPaidClosingCostsAmount { get; set; }
        public JsonNullable<decimal?> LesserAppraisedValueOrSalesPrice { get; set; }
        public JsonNullable<decimal?> LifeInsuranceCoverageAmount { get; set; }
        public JsonNullable<decimal?> LifeInsuranceEstimatedMonthlyAmount { get; set; }
        public JsonNullable<decimal?> LifeInsuranceTotalProtectedMonthlyAmount { get; set; }
        public string LinkId { get; set; }
        public JsonNullable<List<LoanActionLog>> LoanActionLogs { get; set; }
        public JsonNullable<int?> LoanAmortizationTermMonths { get; set; }
        public string LoanAmortizationType { get; set; }
        public string LoanCreatedDate { get; set; }
        public JsonNullable<DateTime?> LoanCreatedDateUtc { get; set; }
        public string LoanIdNumber { get; set; }
        public JsonNullable<bool?> LoanImportStatusIndicator { get; set; }
        public string LoanLinkSyncType { get; set; }
        public string LoanNumber { get; set; }
        public LoanProductData LoanProductData { get; set; }
        public string LoanProgramName { get; set; }
        public JsonNullable<List<LoanProgram>> LoanPrograms { get; set; }
        public string LoanPurposeOfRefinanceType { get; set; }
        public string LoanSource { get; set; }
        public LoanSubmission LoanSubmission { get; set; }
        public JsonNullable<decimal?> LoanTotalProposedMonthlyMaintenanceAmount { get; set; }
        public JsonNullable<decimal?> LoanTotalProposedMonthlyUtilitiesAmount { get; set; }
        public string LoanUnderwriterCHUMSIdentifier { get; set; }
        public string LoanVALoanProcedureType { get; set; }
        public JsonNullable<decimal?> LoanVARateReductionInitialComputationTotalAmount { get; set; }
        public JsonNullable<decimal?> LoanVAResidualIncomeAmount { get; set; }
        public int? LoanVersionId { get; set; }
        public JsonNullable<List<LockConfirmLog>> LockConfirmLogs { get; set; }
        public JsonNullable<List<LockDenialLog>> LockDenialLogs { get; set; }
        public JsonNullable<List<LockRequestLog>> LockRequestLogs { get; set; }
        public ElliLOCompensation LOCompensation { get; set; }
        public JsonNullable<List<LogEntryLog>> LogEntryLogs { get; set; }
        public JsonNullable<decimal?> Ltv { get; set; }
        public JsonNullable<decimal?> LtvPropertyValue { get; set; }
        public string MasterCommitmentNumber { get; set; }
        public JsonNullable<DateTime?> MaturityDate { get; set; }
        public JsonNullable<decimal?> MaxBackRatio { get; set; }
        public JsonNullable<decimal?> MaxFrontRatio { get; set; }
        public Mcaw Mcaw { get; set; }
        public string MersNumber { get; set; }
        public JsonNullable<DateTime?> MersNumberRegistrationDate { get; set; }
        public JsonNullable<decimal?> MiAndFundingFeeFinancedAmount { get; set; }
        public JsonNullable<decimal?> MiAndFundingFeeTotalAmount { get; set; }
        public JsonNullable<DateTime?> MilestoneApprovedDate { get; set; }
        public JsonNullable<DateTime?> MilestoneApprovedDueDate { get; set; }
        public JsonNullable<DateTime?> MilestoneCompletedDate { get; set; }
        public JsonNullable<DateTime?> MilestoneCompletedDueDate { get; set; }
        public JsonNullable<DateTime?> MilestoneCurrentDateUtc { get; set; }
        public string MilestoneCurrentName { get; set; }
        public JsonNullable<DateTime?> MilestoneDocSignedDate { get; set; }
        public JsonNullable<DateTime?> MilestoneDocSignedDueDate { get; set; }
        public JsonNullable<int?> MilestoneDuration { get; set; }
        public JsonNullable<DateTime?> MilestoneFileStartedDate { get; set; }
        public JsonNullable<List<MilestoneFreeRoleLog>> MilestoneFreeRoleLogs { get; set; }
        public JsonNullable<DateTime?> MilestoneFundedDate { get; set; }
        public JsonNullable<DateTime?> MilestoneFundedDueDate { get; set; }
        public JsonNullable<List<MilestoneLog>> MilestoneLogs { get; set; }
        public JsonNullable<DateTime?> MilestoneProcessedDate { get; set; }
        public string MilestoneStage { get; set; }
        public JsonNullable<DateTime?> MilestoneSubmittedDate { get; set; }
        public JsonNullable<DateTime?> MilestoneSubmittedDueDate { get; set; }
        public JsonNullable<List<MilestoneTaskLog>> MilestoneTaskLogs { get; set; }
        public JsonNullable<List<MilestoneTemplateLog>> MilestoneTemplateLogs { get; set; }
        public JsonNullable<decimal?> MipBorrowerPaidInCashAmount { get; set; }
        public JsonNullable<decimal?> MipPaidInCashAmount { get; set; }
        public Miscellaneous Miscellaneous { get; set; }
        public JsonNullable<decimal?> MonthlyPIPaymentAmountForLE1andCD1 { get; set; }
        public JsonNullable<decimal?> MortgageInsurancePremiumFHARefundAmount { get; set; }
        public JsonNullable<decimal?> MortgageInsurancePremiumUpfrontFactorPercent { get; set; }
        public string MortgageType { get; set; }
        public string MsaIdentifier { get; set; }
        public NetTangibleBenefit NetTangibleBenefit { get; set; }
        public JsonNullable<decimal?> NewFirstMortgageAmount { get; set; }
        public string NmlsLoanOriginatorId { get; set; }
        public JsonNullable<bool?> NoClosingCostOption { get; set; }
        public JsonNullable<bool?> NotRequiredForPurchaseSaleOrRefinance { get; set; }
        public JsonNullable<bool?> NotRequiredForSettlementOfYourLoan { get; set; }
        public string OccupancyType { get; set; }
        public string OpeningDocsInvestorCode { get; set; }
        public string OpeningDocsLoanProgramType { get; set; }
        public string OpeningDocsPlanDescription { get; set; }
        public string OpeningDocsPlanId { get; set; }
        public string OpeningDocsProgramCode { get; set; }
        public string OpeningDocsStackingOrder { get; set; }
        public string OrganizationCode { get; set; }
        public JsonNullable<DateTime?> OriginationDate { get; set; }
        public string OtherAmortizationTypeDescription { get; set; }
        public string OtherMortgageTypeDescription { get; set; }
        public JsonNullable<decimal?> OtherPaidClosingCostsAmount { get; set; }
        public JsonNullable<decimal?> OverwireAmount { get; set; }
        public JsonNullable<bool?> PaymentScheduleCalcRequiredIndicator { get; set; }
        public string PercentageOfOwnership { get; set; }
        public JsonNullable<decimal?> PercentageOwnershipInterest { get; set; }
        public JsonNullable<bool?> PmiIndicator { get; set; }
        public JsonNullable<List<PostClosingConditionLog>> PostClosingConditionLogs { get; set; }
        public JsonNullable<List<PreliminaryConditionLog>> PreliminaryConditionLogs { get; set; }
        public Prequalification Prequalification { get; set; }
        public JsonNullable<decimal?> PrincipalAndInterestMonthlyPaymentAmount { get; set; }
        public string Print2003Application { get; set; }
        public JsonNullable<List<PrintLog>> PrintLogs { get; set; }
        public PrivacyPolicy PrivacyPolicy { get; set; }
        public ProfitManagement ProfitManagement { get; set; }
        public Property Property { get; set; }
        public JsonNullable<int?> PropertyAppraisedValueAmount { get; set; }
        public JsonNullable<bool?> PropertyEnergyEfficientHomeIndicator { get; set; }
        public JsonNullable<int?> PropertyEstimatedValueAmount { get; set; }
        public string ProposedDuesAmount { get; set; }
        public JsonNullable<decimal?> ProposedFirstMortgageAmount { get; set; }
        public JsonNullable<decimal?> ProposedGroundRentAmount { get; set; }
        public string ProposedHazardInsuranceAmount { get; set; }
        public JsonNullable<decimal?> ProposedHousingExpenseTotal { get; set; }
        public string ProposedMortgageInsuranceAmount { get; set; }
        public JsonNullable<decimal?> ProposedOtherAmount { get; set; }
        public JsonNullable<decimal?> ProposedOtherMortgagesAmount { get; set; }
        public string ProposedRealEstateTaxesAmount { get; set; }
        public JsonNullable<List<PurchaseCredit>> PurchaseCredits { get; set; }
        public JsonNullable<decimal?> PurchasePriceAmount { get; set; }
        public RateLock RateLock { get; set; }
        public string ReferralAddress { get; set; }
        public string ReferralCity { get; set; }
        public JsonNullable<decimal?> ReferralFeeAmount { get; set; }
        public string ReferralPostalCode { get; set; }
        public string ReferralSource { get; set; }
        public string ReferralState { get; set; }
        public JsonNullable<decimal?> RefinanceIncludingDebtsToBePaidOffAmount { get; set; }
        public JsonNullable<List<RegistrationLog>> RegistrationLogs { get; set; }
        public RegulationZ RegulationZ { get; set; }
        public JsonNullable<List<RemovedLogRecord>> RemovedLogRecords { get; set; }
        public JsonNullable<decimal?> RepurchaseCostAmount { get; set; }
        public JsonNullable<DateTime?> RepurchaseDate { get; set; }
        public JsonNullable<decimal?> RequestedInterestRatePercent { get; set; }
        public JsonNullable<decimal?> SalesConcessionAmount { get; set; }
        public JsonNullable<decimal?> SecondSubordinateAmount { get; set; }
        public Section32 Section32 { get; set; }
        public string SectionOfActType { get; set; }
        public SelectedHomeCounselingProvider SelectedHomeCounselingProvider { get; set; }
        public JsonNullable<decimal?> SellerPaidClosingCostsAmount { get; set; }
        public string ServiceProviderAdditionalInfo { get; set; }
        public JsonNullable<List<ServiceProviderContact>> ServiceProviderContacts { get; set; }
        public JsonNullable<DateTime?> ServiceProviderDateIssued { get; set; }
        public ServicingDisclosure ServicingDisclosure { get; set; }
        public JsonNullable<bool?> SetForSettlementServicesOfAnAttorney { get; set; }
        public JsonNullable<bool?> SetForTheSettlementServicesListed { get; set; }
        public JsonNullable<List<SettlementServiceCharge>> SettlementServiceCharges { get; set; }
        public Shipping Shipping { get; set; }
        public JsonNullable<bool?> SimpleRefinanceType { get; set; }
        public JsonNullable<decimal?> StartingAdjPrice { get; set; }
        public JsonNullable<decimal?> StartingAdjRate { get; set; }
        public StateDisclosure StateDisclosure { get; set; }
        public StatementCreditDenial StatementCreditDenial { get; set; }
        public JsonNullable<List<StatusOnlineLog>> StatusOnlineLogs { get; set; }
        public JsonNullable<decimal?> SubjectPropertyGrossRentalIncomeAmount { get; set; }
        public JsonNullable<decimal?> SubjectPropertyOccupancyPercent { get; set; }
        public JsonNullable<decimal?> SubordinateLienAmount { get; set; }
        public string SystemIdGuid { get; set; }
        public JsonNullable<DateTime?> TilApplicationDate { get; set; }
        public string TitleHolderName1 { get; set; }
        public string TitleHolderName2 { get; set; }
        public JsonNullable<decimal?> Tltv { get; set; }
        public JsonNullable<decimal?> TotalClosingCostsAmount { get; set; }
        public JsonNullable<decimal?> TotalDeductionsAmount { get; set; }
        public JsonNullable<decimal?> TotalFeesCostAmount { get; set; }
        public JsonNullable<decimal?> TotalFeesCreditAmount { get; set; }
        public JsonNullable<decimal?> TotalNonborrowerPaidClosingCostsAmount { get; set; }
        public JsonNullable<decimal?> TotalPaidOutsideClosingAmount { get; set; }
        public JsonNullable<decimal?> TotalPaidToBrokerAmount { get; set; }
        public JsonNullable<decimal?> TotalWireTransferAmount { get; set; }
        public TPO TPO { get; set; }
        public TQL TQL { get; set; }
        public TrustAccount TrustAccount { get; set; }
        public Tsum Tsum { get; set; }
        public JsonNullable<bool?> TwelveMonthMortgageRentalHistoryIndicator { get; set; }
        public Uldd Uldd { get; set; }
        public UnderwriterSummary UnderwriterSummary { get; set; }
        public JsonNullable<List<UnderwritingConditionLog>> UnderwritingConditionLogs { get; set; }
        public JsonNullable<bool?> UnderwritingEscrowIndicator { get; set; }
        public JsonNullable<decimal?> UndiscountedRate { get; set; }
        public JsonNullable<int?> UnimprovedAppraisedValue { get; set; }
        public JsonNullable<int?> UnimprovedEstimatedValue { get; set; }
        public string UrlPage4Comments { get; set; }
        public Usda Usda { get; set; }
        public string UsdaGovernmentLoanType { get; set; }
        public JsonNullable<bool?> Use2018DiIndicator { get; set; }
        public string UseNew2015FormsIndicator { get; set; }
        public JsonNullable<bool?> UseNewHudIndicator { get; set; }
        public JsonNullable<decimal?> VAEntitlementAmount { get; set; }
        public VaLoanData VaLoanData { get; set; }
        public JsonNullable<List<VerificationLog>> VerificationLogs { get; set; }
        public string VirtualFields { get; set; }
        public string WebsiteId { get; set; }
    }
}