using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class LoanProductData
    {
        public decimal? RateAdjustmentLifetimeCapPercent { get; set; }
        public int? BalloonLoanMaturityTermMonthsCount { get; set; }
        public string LienPriorityType { get; set; }
        public string PaymentFrequencyType { get; set; }
        public string LoanRepaymentType { get; set; }
        public decimal? MiCoveragePercent { get; set; }
        public bool? PrepaymentPenaltyIndicator { get; set; }
        public DateTime? ScheduledFirstPaymentDate { get; set; }
        public decimal? IndexCurrentValuePercent { get; set; }
        public decimal? IndexMarginPercent { get; set; }
        public int? PaymentAdjustmentDurationMonthsCount { get; set; }
        public decimal? PaymentAdjustmentPeriodicCapPercent { get; set; }
        public int? RateAdjustmentDurationMonthsCount { get; set; }
        public decimal? RateAdjustmentSubsequentCapPercent { get; set; }
        public int? SubsequentRateAdjustmentMonthsCount { get; set; }
        public decimal? RateAdjustmentPercent { get; set; }
        public decimal? NegativeAmortizationLimitPercent { get; set; }
        public DateTime? LoanScheduledClosingDate { get; set; }
        public string FnmProductPlanIdentifier { get; set; }
        public string GseProjectClassificationType { get; set; }
        public decimal? QualifyingRatePercent { get; set; }
        public string GsePropertyType { get; set; }
        public List<Buydown> Buydowns { get; set; }
        public bool? ConvertibleIndicator { get; set; }
        public decimal? MinimumPaymentPercent { get; set; }
        public decimal? MinimumPaymentAmount { get; set; }
        public bool? BalloonIndicator { get; set; }
        public decimal? FloorPercent { get; set; }
        public decimal? RoundPercent { get; set; }
        public decimal? InitialAdvanceAmount { get; set; }
        public int? DrawPeriodMonthsCount { get; set; }
        public int? RepayPeriodMonthsCount { get; set; }
        public decimal? AnnualFeeNeededAmount { get; set; }
        public decimal? MinimumAdvanceAmount { get; set; }
        public decimal? MinimumAllowableApr { get; set; }
        public string FullPrepaymentPenaltyOptionType { get; set; }
        public int? PrepaymentPenaltyTermMonthsCount { get; set; }
        public decimal? PrepaymentPenaltyPercent { get; set; }
        public string ArmDisclosureType { get; set; }
        public decimal? ThirdPartyFeeFromAmount { get; set; }
        public decimal? ThirdPartyFeeToAmount { get; set; }
        public string Discounted { get; set; }
        public decimal? DiscountedRate { get; set; }
        public List<PrepaymentPenalty> PrepaymentPenalties { get; set; }
        public string HelocPeriodTemplateName { get; set; }
        public decimal? TerminationFeeAmount { get; set; }
        public int? TerminationPeriodMonthsCount { get; set; }
        public string FreddieMacArmIndexType { get; set; }
        public string FreOfferingIdentifier { get; set; }
        public List<HelocRepaymentDrawPeriod> HelocRepaymentDrawPeriods { get; set; }
        public bool? EscrowWaiverIndicator { get; set; }
        public string ProductName { get; set; }
        public string LoanDocumentationType { get; set; }
        public string ArmIndexType { get; set; }
        public string RoundType { get; set; }
        public decimal? MaxLifeInterestCapPercent { get; set; }
        public string TimelyPaymentRewards { get; set; }
        public decimal? TimelyPaymentRateReductionPercent { get; set; }
        public int? MonthsAppliedToPrepaymentPenaltyFeeCount { get; set; }
        public string PrepaymentPenaltyBasedOn { get; set; }
        public int? HardPrepaymentPenaltyMonths { get; set; }
        public DateTime? ScheduledFirstPaymentAdjustmentDate { get; set; }
        public decimal? TotalSubsidyAmount { get; set; }
        public decimal? RemainingBuydownAmount { get; set; }
        public decimal? MaximumMonthlyPayment { get; set; }
        public string NmlsLoanType { get; set; }
        public string NmlsFirstMortgageType { get; set; }
        public string NmlsDocumentationType { get; set; }
        public bool? NmlsOptionARMIndicator { get; set; }
        public bool? NmlsPiggyBackOrFundedHELOCIndicator { get; set; }
        public string NmlsRefinancePurposeType { get; set; }
        public string NmlsProductionSoldToType { get; set; }
        public string BranchManagerNmlsId { get; set; }
        public string BranchLocationNmlsId { get; set; }
        public string NmlsReverseMortgageType { get; set; }
        public decimal? InitialApplicationAmount { get; set; }
        public decimal? NetInitialAndFinal { get; set; }
        public bool? InquiryOrPreQualificationIndicator { get; set; }
        public bool? OralRequestForExtensionOfCreditIndicator { get; set; }
        public bool? ExcludeLoanFromNMLSReportIndicator { get; set; }
        public bool? ApplyLifeCapLowIndicator { get; set; }
        public string FloorBasis { get; set; }
        public string FloorVerbiage { get; set; }
        public string IndexLookbackPeriod { get; set; }
        public string PrepaymentPenaltyVerbiage { get; set; }
        public decimal? ParticipationFees { get; set; }
        public decimal? TransactionFees { get; set; }
        public decimal? MinimumPaymentUpbPercent { get; set; }
        public decimal? OverLimitCharge { get; set; }
        public decimal? OverLimitReturnCharge { get; set; }
        public decimal? ReleaseRecoringCharge { get; set; }
        public decimal? ReturnedCheckCharge { get; set; }
        public decimal? ReturnedCheckMaxCharge { get; set; }
        public decimal? ReturnedCheckMinCharge { get; set; }
        public decimal? ReturnedCheckChargeRatePercent { get; set; }
        public decimal? StopPaymentCharge { get; set; }
        public decimal? WireFee { get; set; }
        public decimal? MinimumPaymentUpbAmount { get; set; }
        public decimal? MinimumPaymentLessThanAmount { get; set; }
        public decimal? MinimumRepayPeriodPaymentPercent { get; set; }
        public decimal? MinimumDrawPeroidPaymentPercent { get; set; }
        public DateTime? BorrowerEstimatedClosingDate { get; set; }
        public string Id { get; set; }
    }
}