using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class LoanEstimate1
    {
        public string AdjustsTermType { get; set; }
        public string ChangedCircumstanceComments { get; set; }
        public JsonNullable<DateTime?> ClosingCostEstimateExpirationDate { get; set; }
        public string ClosingCostEstimateExpirationTime { get; set; }
        public string ClosingCostEstimateExpirationTimeZone { get; set; }
        public string DisclosureBy { get; set; }
        public JsonNullable<DateTime?> DisclosureClosingCostExpDate { get; set; }
        public string DisclosureClosingCostExpTime { get; set; }
        public string DisclosureClosingCostExpTimeZone { get; set; }
        public string DisclosureComments { get; set; }
        public JsonNullable<DateTime?> DisclosureLastSentDate { get; set; }
        public JsonNullable<DateTime?> DisclosureReceivedDate { get; set; }
        public string DisclosureSentMethod { get; set; }
        public JsonNullable<decimal?> EstimatedTaxesInsuranceAssessments { get; set; }
        public string EstimatedTaxesInsuranceAssessmentsUI { get; set; }
        public JsonNullable<decimal?> HighestMonthlyPI { get; set; }
        public string Id { get; set; }
        public string InEscrowHomeownerInsurance { get; set; }
        public string InEscrowOther { get; set; }
        public string InEscrowPropertyTaxes { get; set; }
        public string InterestRateAdjustsEveryYears { get; set; }
        public JsonNullable<int?> InterestRateAdjustsInYear { get; set; }
        public string InterestRateAdjustsStartingInType { get; set; }
        public JsonNullable<int?> InterestRateAfterAdjustment { get; set; }
        public string InterestRateCanGoGoes { get; set; }
        public JsonNullable<DateTime?> LEDateIssued { get; set; }
        public string LoanAmountCanGoGoes { get; set; }
        public string LoanAmountCanIncreaseOrIncreases { get; set; }
        public string LoanProduct { get; set; }
        public string LoanPurpose { get; set; }
        public JsonNullable<int?> LoanTermMonths { get; set; }
        public JsonNullable<int?> LoanTermYears { get; set; }
        public string MonthlyPIAdjustedInDateType { get; set; }
        public string MonthlyPIAdjustsEveryYears { get; set; }
        public JsonNullable<int?> MonthlyPIAdjustsInYear { get; set; }
        public string MonthlyPIAdjustsStartingInType { get; set; }
        public string MonthlyPIAdjustsTermType { get; set; }
        public JsonNullable<int?> MonthlyPIAfterAdjustment { get; set; }
        public string MonthlyPICanGoGoes { get; set; }
        public string MonthlyPIInterestOnlyDateType { get; set; }
        public JsonNullable<int?> MonthlyPIInterestOnlyUntilYear { get; set; }
        public JsonNullable<int?> PPC1EstimatedEscrowAmount { get; set; }
        public string PPC1EstimatedEscrowAmountUI { get; set; }
        public JsonNullable<bool?> PPC1InterestOnly { get; set; }
        public JsonNullable<decimal?> PPC1MaximumMonthlyPayment { get; set; }
        public string PPC1MaximumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC1MaximumPIPayment { get; set; }
        public string PPC1MaximumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC1MIAmount { get; set; }
        public string PPC1MIAmountUI { get; set; }
        public JsonNullable<int?> PPC1MinimumMonthlyPayment { get; set; }
        public string PPC1MinimumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC1MinimumPIPayment { get; set; }
        public string PPC1MinimumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC1Year { get; set; }
        public JsonNullable<int?> PPC2EstimatedEscrowAmount { get; set; }
        public string PPC2EstimatedEscrowAmountUI { get; set; }
        public JsonNullable<bool?> PPC2InterestOnly { get; set; }
        public JsonNullable<decimal?> PPC2MaximumMonthlyPayment { get; set; }
        public string PPC2MaximumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC2MaximumPIPayment { get; set; }
        public string PPC2MaximumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC2MIAmount { get; set; }
        public string PPC2MIAmountUI { get; set; }
        public JsonNullable<int?> PPC2MinimumMonthlyPayment { get; set; }
        public string PPC2MinimumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC2MinimumPIPayment { get; set; }
        public string PPC2MinimumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC2YearFrom { get; set; }
        public JsonNullable<int?> PPC2YearTo { get; set; }
        public JsonNullable<int?> PPC3EstimatedEscrowAmount { get; set; }
        public string PPC3EstimatedEscrowAmountUI { get; set; }
        public JsonNullable<bool?> PPC3InterestOnly { get; set; }
        public JsonNullable<decimal?> PPC3MaximumMonthlyPayment { get; set; }
        public string PPC3MaximumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC3MaximumPIPayment { get; set; }
        public string PPC3MaximumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC3MIAmount { get; set; }
        public string PPC3MIAmountUI { get; set; }
        public JsonNullable<int?> PPC3MinimumMonthlyPayment { get; set; }
        public string PPC3MinimumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC3MinimumPIPayment { get; set; }
        public string PPC3MinimumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC3YearFrom { get; set; }
        public JsonNullable<int?> PPC3YearTo { get; set; }
        public JsonNullable<int?> PPC4EstimatedEscrowAmount { get; set; }
        public string PPC4EstimatedEscrowAmountUI { get; set; }
        public JsonNullable<bool?> PPC4InterestOnly { get; set; }
        public JsonNullable<decimal?> PPC4MaximumMonthlyPayment { get; set; }
        public string PPC4MaximumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC4MaximumPIPayment { get; set; }
        public string PPC4MaximumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC4MIAmount { get; set; }
        public string PPC4MIAmountUI { get; set; }
        public JsonNullable<int?> PPC4MinimumMonthlyPayment { get; set; }
        public string PPC4MinimumMonthlyPaymentUI { get; set; }
        public JsonNullable<decimal?> PPC4MinimumPIPayment { get; set; }
        public string PPC4MinimumPIPaymentUI { get; set; }
        public JsonNullable<int?> PPC4YearFrom { get; set; }
        public JsonNullable<int?> PPC4YearTo { get; set; }
        public JsonNullable<bool?> PPEstimatedEscrowIndicator { get; set; }
        public JsonNullable<int?> PrepaymentPenaltyPayOffDuringYear { get; set; }
        public string PrepaymentPenaltyPayOffInDateType { get; set; }
        public string PrepaymentPenaltyPayOffInFirstYear { get; set; }
        public JsonNullable<bool?> RangePaymentIndicatorC1 { get; set; }
        public JsonNullable<bool?> RangePaymentIndicatorC2 { get; set; }
        public JsonNullable<bool?> RangePaymentIndicatorC3 { get; set; }
        public JsonNullable<bool?> RangePaymentIndicatorC4 { get; set; }
        public string RateLockExpirationTime { get; set; }
        public string RateLockExpirationTimeZone { get; set; }
        public string ReasonChangedCircumstanceFlags { get; set; }
        public JsonNullable<bool?> ReasonDelayedSettlement { get; set; }
        public JsonNullable<bool?> ReasonEligibility { get; set; }
        public JsonNullable<bool?> ReasonExpiration { get; set; }
        public JsonNullable<bool?> ReasonInterestRate { get; set; }
        public JsonNullable<bool?> ReasonOther { get; set; }
        public string ReasonOtherDescription { get; set; }
        public JsonNullable<bool?> ReasonRevisions { get; set; }
        public JsonNullable<bool?> ReasonSettlementCharges { get; set; }
        public JsonNullable<decimal?> TotalEstimatedCashClose { get; set; }
        public JsonNullable<int?> YearsToRecast { get; set; }
    }
}