using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class LoanProgram
    {
        public string Acquisition { get; set; }
        public string AdditionalArmInformation { get; set; }
        public string AllDateAndNumericalDisclosures { get; set; }
        public JsonNullable<decimal?> AnnualFeeNeeded { get; set; }
        public string ArmTypeDescription { get; set; }
        public string AssumptionOnYourProperty { get; set; }
        public JsonNullable<int?> BalloonLoanMaturityTermMonths { get; set; }
        public JsonNullable<int?> BuydownChangeFrequencyMonths1 { get; set; }
        public JsonNullable<int?> BuydownChangeFrequencyMonths2 { get; set; }
        public JsonNullable<int?> BuydownChangeFrequencyMonths3 { get; set; }
        public JsonNullable<int?> BuydownChangeFrequencyMonths4 { get; set; }
        public JsonNullable<int?> BuydownChangeFrequencyMonths5 { get; set; }
        public JsonNullable<int?> BuydownChangeFrequencyMonths6 { get; set; }
        public JsonNullable<decimal?> BuydownIncreaseRatePercent1 { get; set; }
        public JsonNullable<decimal?> BuydownIncreaseRatePercent2 { get; set; }
        public JsonNullable<decimal?> BuydownIncreaseRatePercent3 { get; set; }
        public JsonNullable<decimal?> BuydownIncreaseRatePercent4 { get; set; }
        public JsonNullable<decimal?> BuydownIncreaseRatePercent5 { get; set; }
        public JsonNullable<decimal?> BuydownIncreaseRatePercent6 { get; set; }
        public string CalculateBasedOnRemainingBalance { get; set; }
        public string ClosingCostProgram { get; set; }
        public string ConstructionDescription { get; set; }
        public JsonNullable<decimal?> ConstructionInterestReserveAmount { get; set; }
        public string ConstructionLoanMethod { get; set; }
        public JsonNullable<int?> ConstructionPeriodMonths { get; set; }
        public JsonNullable<decimal?> ConstructionRate { get; set; }
        public string Convertible { get; set; }
        public string CreditDisability { get; set; }
        public string CreditLifeInsurance { get; set; }
        public string DemandFeature { get; set; }
        public string Description { get; set; }
        public string DisclosureType { get; set; }
        public string Discounted { get; set; }
        public JsonNullable<decimal?> DiscountedRate { get; set; }
        public string DrawRepayPeriodTableName { get; set; }
        public JsonNullable<decimal?> FhaUpfrontMiPremiumPercent { get; set; }
        public string FloodInsurance { get; set; }
        public JsonNullable<decimal?> FloorPercent { get; set; }
        public JsonNullable<decimal?> FundingFeePaidInCash { get; set; }
        public JsonNullable<decimal?> GpmExtraPaymentForEarlyPayOff { get; set; }
        public JsonNullable<decimal?> GpmRate { get; set; }
        public JsonNullable<int?> GpmYears { get; set; }
        public string Id { get; set; }
        public string IfYouPurchase { get; set; }
        public string IfYouPurchaseType { get; set; }
        public JsonNullable<decimal?> IndexCurrentValuePercent { get; set; }
        public JsonNullable<decimal?> IndexMarginPercent { get; set; }
        public JsonNullable<decimal?> InitialAdvanceAmount { get; set; }
        public JsonNullable<int?> InterestOnlyMonths { get; set; }
        public JsonNullable<int?> LateChargeDays { get; set; }
        public JsonNullable<decimal?> LateChargePercent { get; set; }
        public string LateChargeType { get; set; }
        public string LenderInvestorCode { get; set; }
        public string LienPriorityType { get; set; }
        public JsonNullable<int?> LoanAmortizationTermMonths { get; set; }
        public string LoanAmortizationType { get; set; }
        public string LoanDocumentationType { get; set; }
        public string LoanFeaturesPaymentFrequencyType { get; set; }
        public string LoanProgramName { get; set; }
        public string LockField { get; set; }
        public JsonNullable<decimal?> MaxBackRatio { get; set; }
        public JsonNullable<decimal?> MaxCltv { get; set; }
        public JsonNullable<decimal?> MaxFrontRatio { get; set; }
        public JsonNullable<decimal?> MaximumBalance { get; set; }
        public JsonNullable<decimal?> MaxLoanAmount { get; set; }
        public JsonNullable<decimal?> MaxLtv { get; set; }
        public string MeansAnEstimate { get; set; }
        public string MiCalculationType { get; set; }
        public string MidpointCancellation { get; set; }
        public string MinCreditScore { get; set; }
        public JsonNullable<decimal?> MinimumAdvanceAmount { get; set; }
        public JsonNullable<decimal?> MinimumAllowableApr { get; set; }
        public JsonNullable<decimal?> MinimumPaymentAmount { get; set; }
        public JsonNullable<decimal?> MinimumPaymentPercent { get; set; }
        public JsonNullable<decimal?> MipPaidInCash { get; set; }
        public string Mmi { get; set; }
        public JsonNullable<decimal?> MortgageInsuranceAdjustmentFactor1 { get; set; }
        public JsonNullable<decimal?> MortgageInsuranceAdjustmentFactor2 { get; set; }
        public JsonNullable<decimal?> MortgageInsuranceCancelPercent { get; set; }
        public JsonNullable<decimal?> MortgageInsuranceMonthlyPayment1 { get; set; }
        public JsonNullable<decimal?> MortgageInsuranceMonthlyPayment2 { get; set; }
        public JsonNullable<int?> MortgageInsuranceMonthsOfAdjustment1 { get; set; }
        public JsonNullable<int?> MortgageInsuranceMonthsOfAdjustment2 { get; set; }
        public string MortgageType { get; set; }
        public string OtherAmortizationTypeDescription { get; set; }
        public string OtherLoanPurposeDescription { get; set; }
        public string OtherMortgageTypeDescription { get; set; }
        public JsonNullable<int?> PaymentAdjustmentDurationMonths { get; set; }
        public JsonNullable<decimal?> PaymentAdjustmentPeriodicCapPercent { get; set; }
        public JsonNullable<decimal?> PaymentFactor { get; set; }
        public JsonNullable<decimal?> PercentageOfRental { get; set; }
        public string PerDiemCalculationMethodType { get; set; }
        public string Pmi { get; set; }
        public string PrepaymentPenaltyIndicator { get; set; }
        public string ProgramCode { get; set; }
        public string PropertyInsurance { get; set; }
        public string PropertyUsageType { get; set; }
        public JsonNullable<decimal?> QualifyingRatePercent { get; set; }
        public JsonNullable<int?> RateAdjustmentDurationMonths { get; set; }
        public JsonNullable<decimal?> RateAdjustmentLifetimeCapPercent { get; set; }
        public JsonNullable<decimal?> RateAdjustmentPercent { get; set; }
        public JsonNullable<decimal?> RateAdjustmentSubsequentCapPercent { get; set; }
        public JsonNullable<int?> RateAdjustmentSubsequentRateAdjustmentMonths { get; set; }
        public JsonNullable<int?> RecastPaidMonths { get; set; }
        public JsonNullable<int?> RecastStopMonths { get; set; }
        public string RefundPaymentIndicator { get; set; }
        public JsonNullable<decimal?> RequestedInterestRatePercent { get; set; }
        public string RequiredDeposit { get; set; }
        public JsonNullable<decimal?> RoundPercent { get; set; }
        public string RoundType { get; set; }
        public string SecurityInterestInNameOf { get; set; }
        public string SecurityType { get; set; }
        public JsonNullable<decimal?> SubjectPropertyGrossRentalIncome { get; set; }
        public JsonNullable<decimal?> TeaserRate { get; set; }
        public JsonNullable<decimal?> TerminationFeeAmount { get; set; }
        public JsonNullable<int?> TerminationPeriodMonthsCount { get; set; }
        public JsonNullable<decimal?> ThirdPartyFeeFrom { get; set; }
        public JsonNullable<decimal?> ThirdPartyFeeTo { get; set; }
        public string Type { get; set; }
        public string UseDaysInYears { get; set; }
        public string UsePitiForRatio { get; set; }
        public string VariableRateFeature { get; set; }
        public JsonNullable<decimal?> YearlyTerm { get; set; }
    }
}