using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class Miscellaneous
    {
        public string Address { get; set; }
        public string BorrowerDescription1 { get; set; }
        public string BorrowerDescription2 { get; set; }
        public string BorrowerDescription3 { get; set; }
        public string BorrowerDescription4 { get; set; }
        public string BorrowerDescription5 { get; set; }
        public string BorrowerDescription6 { get; set; }
        public string BorrowerDescription7 { get; set; }
        public string City { get; set; }
        public string ClosingCostProgramFile { get; set; }
        public string ClosingTaxYear { get; set; }
        public JsonNullable<decimal?> ClosingTaxYearInterestReceived { get; set; }
        public JsonNullable<bool?> CopyFromSubjectProperty { get; set; }
        public string DataTracLoanId { get; set; }
        public string DocSetFile { get; set; }
        public JsonNullable<int?> FactorForRevolvingDebt { get; set; }
        public JsonNullable<bool?> FannieDuAutoOrderIndicator { get; set; }
        public JsonNullable<bool?> FannieEcAutoOrderIndicator { get; set; }
        public string FloodInsuranceExcluded { get; set; }
        public string FormListFile { get; set; }
        public JsonNullable<bool?> FreddieLPAAutoOrderIndicator { get; set; }
        public JsonNullable<bool?> FreddieLQAAutoOrderIndicator { get; set; }
        public JsonNullable<decimal?> HousingExpenseIntRate1 { get; set; }
        public JsonNullable<decimal?> HousingExpenseIntRate2 { get; set; }
        public JsonNullable<decimal?> HousingExpenseLoanAmt1 { get; set; }
        public JsonNullable<decimal?> HousingExpenseLoanAmt2 { get; set; }
        public JsonNullable<decimal?> HousingExpensePayment1 { get; set; }
        public JsonNullable<decimal?> HousingExpensePayment2 { get; set; }
        public JsonNullable<int?> HousingExpenseTerm1 { get; set; }
        public JsonNullable<int?> HousingExpenseTerm2 { get; set; }
        public string Id { get; set; }
        public JsonNullable<bool?> IsSameAddresswithPayer { get; set; }
        public string Line1006Excluded { get; set; }
        public string Line1007Excluded { get; set; }
        public string Line1008Excluded { get; set; }
        public string Line1010Excluded { get; set; }
        public string LoanProgramFile { get; set; }
        public string LoanTemplateFile { get; set; }
        public string MaventATRQMResult { get; set; }
        public JsonNullable<bool?> MaventAutoOrderIndicator { get; set; }
        public string MaventCraxResult { get; set; }
        public string MaventEnterpriseResult { get; set; }
        public string MaventGseResult { get; set; }
        public string MaventHighCostResult { get; set; }
        public string MaventHmdaResult { get; set; }
        public string MaventHpmlResult { get; set; }
        public string MaventLicenseResult { get; set; }
        public string MaventNmlsResult { get; set; }
        public string MaventOfacResult { get; set; }
        public string MaventOrderedBy { get; set; }
        public JsonNullable<DateTime?> MaventOrderedDate { get; set; }
        public string MaventOtherResult { get; set; }
        public string MaventReviewResult { get; set; }
        public string MaventStateResult { get; set; }
        public string MaventTilaRorResult { get; set; }
        public string MaventTilaToleranceResult { get; set; }
        public JsonNullable<decimal?> MIPremiums { get; set; }
        public string MiscDataFile { get; set; }
        public JsonNullable<int?> MonthsToExclude { get; set; }
        public string OptimalBlueHistoryData { get; set; }
        public string OptimalBlueRequest { get; set; }
        public string OptimalBlueResponse { get; set; }
        public JsonNullable<decimal?> OtherPresentHousingExpense { get; set; }
        public JsonNullable<decimal?> OutstandingMtgPrincipal { get; set; }
        public JsonNullable<DateTime?> OutstandingMtgPrincipalDate { get; set; }
        public JsonNullable<bool?> ParticipateHomePoints { get; set; }
        public string PartnerEmail { get; set; }
        public string PartnerName { get; set; }
        public string PartnerPhone { get; set; }
        public JsonNullable<decimal?> PointsPaid { get; set; }
        public JsonNullable<DateTime?> RateRegistrationExpirationDate { get; set; }
        public string RateRegistrationInvestorName { get; set; }
        public JsonNullable<bool?> RateRegistrationLoanIsRegistered { get; set; }
        public string RateRegistrationReference { get; set; }
        public string RateRegistrationRegisteredBy { get; set; }
        public string RateRegistrationRegisteredUserId { get; set; }
        public JsonNullable<DateTime?> RateRegistrationRegistrationDate { get; set; }
        public JsonNullable<decimal?> RefundOrOverpaidInterest { get; set; }
        public string SchoolTaxExcluded { get; set; }
        public string State { get; set; }
        public string StatusUrl { get; set; }
        public JsonNullable<DateTime?> SubmitDate { get; set; }
        public string SubTaxYear { get; set; }
        public JsonNullable<decimal?> SubTaxYearInterestReceived { get; set; }
        public JsonNullable<decimal?> SubTaxYearMIPremiums { get; set; }
        public JsonNullable<decimal?> SubTaxYearPointsPaid { get; set; }
        public JsonNullable<decimal?> SubTaxYearRefundOrOverpaidInterest { get; set; }
        public string TaxId { get; set; }
        public JsonNullable<decimal?> TotalBox4 { get; set; }
        public JsonNullable<decimal?> TotalYearlyMi { get; set; }
        public string UseGfeTax { get; set; }
        public string UseRegZMi { get; set; }
        public string Zip { get; set; }
    }
}