using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class RateLock
    {
        public JsonNullable<decimal?> ActualSellAmount { get; set; }
        public JsonNullable<decimal?> ActualSellPrice { get; set; }
        public JsonNullable<decimal?> ActualSellSideSRP { get; set; }
        public JsonNullable<decimal?> ActualSRPAmount { get; set; }
        public JsonNullable<decimal?> AmountDue { get; set; }
        public string AmountDueTo { get; set; }
        public JsonNullable<decimal?> AmountPaid { get; set; }
        public string AmountPaidTo { get; set; }
        public JsonNullable<decimal?> AmountReceived { get; set; }
        public JsonNullable<int?> BalloonLoanMaturityTermMonths { get; set; }
        public JsonNullable<decimal?> BaseLoanAmount { get; set; }
        public JsonNullable<decimal?> BorrowerRequestedLoanAmount { get; set; }
        public JsonNullable<DateTime?> BranchApprovalDate { get; set; }
        public string BranchApprovedby { get; set; }
        public JsonNullable<decimal?> BranchPrice { get; set; }
        public JsonNullable<List<PriceAdjustment>> BuySideAdjustments { get; set; }
        public string BuySideComments { get; set; }
        public JsonNullable<DateTime?> BuySideCommitmentDate { get; set; }
        public string BuySideCommitmentNumber { get; set; }
        public string BuySideCommitmentType { get; set; }
        public JsonNullable<DateTime?> BuySideCurrentRateSetDate { get; set; }
        public JsonNullable<int?> BuySideDaystoExtend { get; set; }
        public JsonNullable<DateTime?> BuySideDeliveryExpirationDate { get; set; }
        public string BuySideDeliveryType { get; set; }
        public JsonNullable<DateTime?> BuySideExpirationDate { get; set; }
        public JsonNullable<DateTime?> BuySideExtendedLockExpires { get; set; }
        public JsonNullable<DateTime?> BuySideLockDate { get; set; }
        public JsonNullable<DateTime?> BuySideLockExpires { get; set; }
        public JsonNullable<decimal?> BuySideLockExtendPriceAdjustment { get; set; }
        public JsonNullable<decimal?> BuySideMarginNetBuyRate { get; set; }
        public JsonNullable<decimal?> BuySideMarginRate { get; set; }
        public JsonNullable<decimal?> BuySideMarginTotalAdjustment { get; set; }
        public string BuySideMasterCommitmentNumber { get; set; }
        public JsonNullable<int?> BuySideNumberOfDays { get; set; }
        public JsonNullable<bool?> BuySideOnrpEligible { get; set; }
        public JsonNullable<DateTime?> BuySideOnrpLockDate { get; set; }
        public string BuySideOnrpLockTime { get; set; }
        public string BuySideOrgID { get; set; }
        public JsonNullable<DateTime?> BuySideOriginalLockExpires { get; set; }
        public JsonNullable<decimal?> BuySidePriceNetBuyPrice { get; set; }
        public JsonNullable<decimal?> BuySidePriceRate { get; set; }
        public JsonNullable<decimal?> BuySidePriceTotalAdjustment { get; set; }
        public JsonNullable<decimal?> BuySideRate { get; set; }
        public JsonNullable<decimal?> BuySideRateNetBuyRate { get; set; }
        public string BuySideRateSheetID { get; set; }
        public JsonNullable<decimal?> BuySideRateTotalAdjustment { get; set; }
        public string BuySideRequestedBy { get; set; }
        public JsonNullable<decimal?> BuySideSRPPaidOut { get; set; }
        public JsonNullable<decimal?> BuySideStartingAdjPoint { get; set; }
        public JsonNullable<decimal?> BuySideStartingAdjPrice { get; set; }
        public JsonNullable<decimal?> BuySideStartingAdjRate { get; set; }
        public string BuySideTPOID { get; set; }
        public string BuySideTPOName { get; set; }
        public string BuySideTradeGuid { get; set; }
        public string BuySideTradeNumber { get; set; }
        public JsonNullable<decimal?> BuySideUnDiscountedRate { get; set; }
        public string CancellationRequestPending { get; set; }
        public JsonNullable<decimal?> CombinedLTV { get; set; }
        public string Comments { get; set; }
        public string Commitment { get; set; }
        public JsonNullable<decimal?> CompGainLossPercentage { get; set; }
        public JsonNullable<decimal?> CompGainLossPrice { get; set; }
        public JsonNullable<decimal?> CompGainLossTotalBuyPrice { get; set; }
        public JsonNullable<decimal?> CompGainLossTotalCompPrice { get; set; }
        public string CompInvestorAddress { get; set; }
        public string CompInvestorCity { get; set; }
        public string CompInvestorCommitment { get; set; }
        public string CompInvestorContact { get; set; }
        public string CompInvestorEmail { get; set; }
        public string CompInvestorLockType { get; set; }
        public string CompInvestorName { get; set; }
        public string CompInvestorPhone { get; set; }
        public string CompInvestorPostalCode { get; set; }
        public string CompInvestorProgramCode { get; set; }
        public string CompInvestorState { get; set; }
        public string CompInvestorTemplateName { get; set; }
        public string CompInvestorWebsite { get; set; }
        public JsonNullable<List<PriceAdjustment>> CompSideAdjustments { get; set; }
        public string CompSideComments { get; set; }
        public string CompSideComparisonedBy { get; set; }
        public JsonNullable<DateTime?> CompSideCurrentRateSetDate { get; set; }
        public JsonNullable<int?> CompSideDaystoExtend { get; set; }
        public JsonNullable<decimal?> CompSideDiscountYSP { get; set; }
        public JsonNullable<DateTime?> CompSideExtendedLockExpires { get; set; }
        public string CompSideInvestorStatus { get; set; }
        public JsonNullable<DateTime?> CompSideInvestorStatusDate { get; set; }
        public string CompSideInvestorTradeNumber { get; set; }
        public string CompSideLoanProgram { get; set; }
        public JsonNullable<DateTime?> CompSideLockDate { get; set; }
        public JsonNullable<DateTime?> CompSideLockExpires { get; set; }
        public JsonNullable<decimal?> CompSideLockExtendPriceAdjustment { get; set; }
        public JsonNullable<decimal?> CompSideMarginNetCompRate { get; set; }
        public JsonNullable<decimal?> CompSideMarginRate { get; set; }
        public JsonNullable<decimal?> CompSideMarginTotalAdjustment { get; set; }
        public string CompSideMasterContractNumber { get; set; }
        public JsonNullable<decimal?> CompSideNetCompPrice { get; set; }
        public JsonNullable<decimal?> CompSideNetCompRate { get; set; }
        public JsonNullable<int?> CompSideNumberOfDays { get; set; }
        public JsonNullable<DateTime?> CompSideOriginalLockExpires { get; set; }
        public JsonNullable<decimal?> CompSidePriceRate { get; set; }
        public JsonNullable<decimal?> CompSidePriceTotalAdjustment { get; set; }
        public JsonNullable<decimal?> CompSideRate { get; set; }
        public string CompSideRateSheetID { get; set; }
        public JsonNullable<decimal?> CompSideRateTotalAdjustment { get; set; }
        public string CompSideRequestedBy { get; set; }
        public string CompSideServicingType { get; set; }
        public JsonNullable<decimal?> CompSideSRPPaidOut { get; set; }
        public string CompSideTradeGuid { get; set; }
        public string CompSideTradeNumber { get; set; }
        public string ConfirmedBy { get; set; }
        public JsonNullable<DateTime?> ConfirmedDate { get; set; }
        public JsonNullable<DateTime?> CorporateApprovalDate { get; set; }
        public string CorporateApprovedby { get; set; }
        public JsonNullable<decimal?> CorporatePrice { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount1 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount10 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount11 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount12 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount13 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount2 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount3 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount4 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount5 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount6 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount7 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount8 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineAmount9 { get; set; }
        public string CorrespondentAdditionalLineDescription1 { get; set; }
        public string CorrespondentAdditionalLineDescription10 { get; set; }
        public string CorrespondentAdditionalLineDescription11 { get; set; }
        public string CorrespondentAdditionalLineDescription12 { get; set; }
        public string CorrespondentAdditionalLineDescription2 { get; set; }
        public string CorrespondentAdditionalLineDescription3 { get; set; }
        public string CorrespondentAdditionalLineDescription4 { get; set; }
        public string CorrespondentAdditionalLineDescription5 { get; set; }
        public string CorrespondentAdditionalLineDescription6 { get; set; }
        public string CorrespondentAdditionalLineDescription7 { get; set; }
        public string CorrespondentAdditionalLineDescription8 { get; set; }
        public string CorrespondentAdditionalLineDescription9 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdditionalLineTotalAmount { get; set; }
        public JsonNullable<decimal?> CorrespondentAdjusterAmount1 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdjusterAmount2 { get; set; }
        public JsonNullable<decimal?> CorrespondentAdjusterAmount3 { get; set; }
        public string CorrespondentAdjusterDescription1 { get; set; }
        public string CorrespondentAdjusterDescription2 { get; set; }
        public string CorrespondentAdjusterDescription3 { get; set; }
        public string CorrespondentConfirmedBy { get; set; }
        public JsonNullable<DateTime?> CorrespondentConfirmedDate { get; set; }
        public JsonNullable<decimal?> CorrespondentCurrentImpounds { get; set; }
        public JsonNullable<decimal?> CorrespondentCurrentPrincipal { get; set; }
        public JsonNullable<DateTime?> CorrespondentDate { get; set; }
        public JsonNullable<decimal?> CorrespondentFinalBuyAmount { get; set; }
        public JsonNullable<decimal?> CorrespondentFinalBuyPrice { get; set; }
        public JsonNullable<DateTime?> CorrespondentFirstPaymentDate { get; set; }
        public JsonNullable<decimal?> CorrespondentImpounds { get; set; }
        public JsonNullable<decimal?> CorrespondentInterest { get; set; }
        public JsonNullable<int?> CorrespondentInterestDays { get; set; }
        public JsonNullable<decimal?> CorrespondentLateFeeAmount { get; set; }
        public JsonNullable<decimal?> CorrespondentLateFeePriceAdjustment { get; set; }
        public JsonNullable<DateTime?> CorrespondentPaidToDate { get; set; }
        public JsonNullable<decimal?> CorrespondentPurchasedPrincipal { get; set; }
        public string CorrespondentReconcilationComments { get; set; }
        public JsonNullable<decimal?> CorrespondentRemainingBuydownAmount { get; set; }
        public JsonNullable<decimal?> CorrespondentSRPAmount { get; set; }
        public string CorrespondentWarehouseBankABANum { get; set; }
        public string CorrespondentWarehouseBankAcctNum { get; set; }
        public string CorrespondentWarehouseBankAddress { get; set; }
        public string CorrespondentWarehouseBankAddress1 { get; set; }
        public JsonNullable<DateTime?> CorrespondentWarehouseBankBaileeExpirationDate { get; set; }
        public JsonNullable<bool?> CorrespondentWarehouseBankBaileeLetterReceivedIndicator { get; set; }
        public JsonNullable<bool?> CorrespondentWarehouseBankBaileeLetterReqIndicator { get; set; }
        public string CorrespondentWarehouseBankCity { get; set; }
        public string CorrespondentWarehouseBankContactEmail { get; set; }
        public string CorrespondentWarehouseBankContactFax { get; set; }
        public string CorrespondentWarehouseBankContactName { get; set; }
        public string CorrespondentWarehouseBankContactPhone { get; set; }
        public string CorrespondentWarehouseBankDescription { get; set; }
        public int? CorrespondentWarehouseBankId { get; set; }
        public string CorrespondentWarehouseBankName { get; set; }
        public string CorrespondentWarehouseBankNotes { get; set; }
        public JsonNullable<bool?> CorrespondentWarehouseBankSelfFunderIndicator { get; set; }
        public string CorrespondentWarehouseBankState { get; set; }
        public JsonNullable<bool?> CorrespondentWarehouseBankTriPartyContractIndicator { get; set; }
        public JsonNullable<bool?> CorrespondentWarehouseBankUseDefaultContactIndicator { get; set; }
        public JsonNullable<bool?> CorrespondentWarehouseBankWireInstructionsReceivedIndicator { get; set; }
        public string CorrespondentWarehouseBankZip { get; set; }
        public string CreditScoreToUse { get; set; }
        public JsonNullable<int?> CumulatedDaystoExtend { get; set; }
        public JsonNullable<List<PriceAdjustment>> CurrentAdjustments { get; set; }
        public string CurrentComments { get; set; }
        public JsonNullable<DateTime?> CurrentLockDate { get; set; }
        public JsonNullable<DateTime?> CurrentLockExpires { get; set; }
        public JsonNullable<decimal?> CurrentMarginRate { get; set; }
        public JsonNullable<decimal?> CurrentMarginRateRequested { get; set; }
        public JsonNullable<decimal?> CurrentMarginTotalAdjustment { get; set; }
        public JsonNullable<int?> CurrentNumberOfDays { get; set; }
        public JsonNullable<decimal?> CurrentPriceRate { get; set; }
        public JsonNullable<decimal?> CurrentPriceRateRequested { get; set; }
        public JsonNullable<decimal?> CurrentPriceTotalAdjustment { get; set; }
        public JsonNullable<decimal?> CurrentRate { get; set; }
        public JsonNullable<decimal?> CurrentRateRequested { get; set; }
        public JsonNullable<DateTime?> CurrentRateSetDate { get; set; }
        public string CurrentRateSheetID { get; set; }
        public JsonNullable<decimal?> CurrentRateTotalAdjustment { get; set; }
        public JsonNullable<DateTime?> Date { get; set; }
        public JsonNullable<DateTime?> DateFirstPaymentToInvestor { get; set; }
        public JsonNullable<DateTime?> DateLockedWithInvestor { get; set; }
        public JsonNullable<DateTime?> DateSold { get; set; }
        public JsonNullable<DateTime?> DateWarehoused { get; set; }
        public int? DaysToExtend { get; set; }
        public string DeliveryType { get; set; }
        public JsonNullable<decimal?> DiffAmountReceived { get; set; }
        public JsonNullable<decimal?> DiffImpounds { get; set; }
        public JsonNullable<decimal?> DiffInterest { get; set; }
        public JsonNullable<decimal?> DiffPremium { get; set; }
        public JsonNullable<decimal?> DiffPrinciple { get; set; }
        public JsonNullable<decimal?> DiffRemainingBuydownFunds { get; set; }
        public JsonNullable<decimal?> DiffSellAmount { get; set; }
        public JsonNullable<decimal?> DiffSellPrice { get; set; }
        public JsonNullable<decimal?> DiffSellSideSRP { get; set; }
        public JsonNullable<decimal?> DiffSRP { get; set; }
        public JsonNullable<decimal?> DiffSRPAmount { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator1 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator10 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator11 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator12 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator2 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator3 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator4 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator5 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator6 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator7 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator8 { get; set; }
        public JsonNullable<bool?> EmploymentBorrowerSelfEmployedIndicator9 { get; set; }
        public JsonNullable<decimal?> ExpectedAmountReceived { get; set; }
        public JsonNullable<decimal?> ExpectedImpounds { get; set; }
        public JsonNullable<decimal?> ExpectedInterest { get; set; }
        public JsonNullable<decimal?> ExpectedPremium { get; set; }
        public JsonNullable<decimal?> ExpectedPrinciple { get; set; }
        public JsonNullable<decimal?> ExpectedRemainingBuydownFunds { get; set; }
        public JsonNullable<decimal?> ExpectedSRP { get; set; }
        public string ExtensionRequestPending { get; set; }
        public JsonNullable<int?> ExtensionSequenceNumber { get; set; }
        public JsonNullable<decimal?> FHAUpfrontMIPremiumPercent { get; set; }
        public JsonNullable<int?> FinancedNumberOfUnits { get; set; }
        public string FirstPaymenTo { get; set; }
        public JsonNullable<decimal?> FirstSubordinateAmount { get; set; }
        public JsonNullable<bool?> FirstTimeHomebuyersIndicator { get; set; }
        public string FNMProductPlanIdentifier { get; set; }
        public JsonNullable<decimal?> FundingAmount { get; set; }
        public JsonNullable<decimal?> GainLossPercentage { get; set; }
        public JsonNullable<decimal?> GainLossPrice { get; set; }
        public JsonNullable<decimal?> GainLossTotalBuyPrice { get; set; }
        public JsonNullable<decimal?> GPMRate { get; set; }
        public JsonNullable<int?> GPMYears { get; set; }
        public string GSEPropertyType { get; set; }
        public string Hedging { get; set; }
        public string HELOCActualBalance { get; set; }
        public string Id { get; set; }
        public JsonNullable<decimal?> Impounds { get; set; }
        public string ImpoundType { get; set; }
        public string ImpoundWavied { get; set; }
        public JsonNullable<decimal?> Interest { get; set; }
        public string InvestorAddress { get; set; }
        public string InvestorCity { get; set; }
        public string InvestorCommitment { get; set; }
        public string InvestorContact { get; set; }
        public JsonNullable<DateTime?> InvestorDeliveryDate { get; set; }
        public string InvestorEmail { get; set; }
        public string InvestorLoanNumber { get; set; }
        public string InvestorLockType { get; set; }
        public string InvestorMERSNumber { get; set; }
        public string InvestorName { get; set; }
        public string InvestorPhone { get; set; }
        public string InvestorPostalCode { get; set; }
        public string InvestorProgramCode { get; set; }
        public string InvestorState { get; set; }
        public JsonNullable<DateTime?> InvestorTargetDeliveryDate { get; set; }
        public string InvestorTemplateName { get; set; }
        public string InvestorWebsite { get; set; }
        public string IsCancelled { get; set; }
        public JsonNullable<bool?> IsDeliveryType { get; set; }
        public JsonNullable<bool?> LenderPaidMortgageInsuranceIndicator { get; set; }
        public string LienPriorityType { get; set; }
        public JsonNullable<int?> LoanAmortizationTermMonths { get; set; }
        public string LoanAmortizationType { get; set; }
        public string LoanDocumentationType { get; set; }
        public JsonNullable<bool?> LoanFor203K { get; set; }
        public string LoanProgram { get; set; }
        public string LoanProgramFile { get; set; }
        public JsonNullable<DateTime?> LoanScheduledClosingDate { get; set; }
        public JsonNullable<bool?> LockField { get; set; }
        public JsonNullable<List<PriceAdjustment>> LockRequestAdjustments { get; set; }
        public JsonNullable<List<LockRequestBorrower>> LockRequestBorrowers { get; set; }
        public string LockRequestLoanPurposeType { get; set; }
        public JsonNullable<decimal?> LTV { get; set; }
        public string MinFICO { get; set; }
        public string MinFICO2 { get; set; }
        public JsonNullable<decimal?> MIPPaidInCash { get; set; }
        public string MortgageType { get; set; }
        public JsonNullable<decimal?> NetSellAmount { get; set; }
        public JsonNullable<decimal?> NetSellPrice { get; set; }
        public JsonNullable<DateTime?> NextPaymentDate { get; set; }
        public JsonNullable<bool?> NoClosingCostOption { get; set; }
        public string ONRPLock { get; set; }
        public string OtherAmortizationTypeDescription { get; set; }
        public JsonNullable<decimal?> OtherSubordinateAmount { get; set; }
        public string PenaltyTerm { get; set; }
        public string PerDiemInterestRoundingType { get; set; }
        public string PlanCode { get; set; }
        public JsonNullable<decimal?> Premium { get; set; }
        public string PrepayPenalty { get; set; }
        public decimal? PriceAdjustment { get; set; }
        public JsonNullable<List<PriceAdjustment>> PriceAdjustments { get; set; }
        public string PricingHistoryData { get; set; }
        public string PricingUpdated { get; set; }
        public JsonNullable<decimal?> Principle { get; set; }
        public JsonNullable<decimal?> ProfitMarginAdjustedBuyPrice { get; set; }
        public JsonNullable<int?> PropertyAppraisedValueAmount { get; set; }
        public JsonNullable<int?> PropertyEstimatedValueAmount { get; set; }
        public string PropertyUsageType { get; set; }
        public JsonNullable<int?> PurchaseAdviceNumberOfDays { get; set; }
        public JsonNullable<List<PurchaseAdvicePayout>> PurchaseAdvicePayouts { get; set; }
        public JsonNullable<decimal?> PurchasePriceAmount { get; set; }
        public string RateRequestStatus { get; set; }
        public string RateStatus { get; set; }
        public string ReasonforBranchApproval { get; set; }
        public string ReasonforCorporateApproval { get; set; }
        public JsonNullable<decimal?> ReconciledDiff { get; set; }
        public string ReLockRequestPending { get; set; }
        public JsonNullable<decimal?> RemainingBuydownFunds { get; set; }
        public string RequestComments { get; set; }
        public JsonNullable<DateTime?> RequestCurrentRateSetDate { get; set; }
        public JsonNullable<int?> RequestDaystoExtend { get; set; }
        public JsonNullable<DateTime?> RequestExtendedLockExpires { get; set; }
        public string RequestFullfilledDateTime { get; set; }
        public string RequestImpoundType { get; set; }
        public string RequestImpoundWavied { get; set; }
        public string RequestLockCancellationComment { get; set; }
        public JsonNullable<DateTime?> RequestLockCancellationDate { get; set; }
        public JsonNullable<DateTime?> RequestLockDate { get; set; }
        public JsonNullable<DateTime?> RequestLockExpires { get; set; }
        public string RequestLockExtendComment { get; set; }
        public JsonNullable<decimal?> RequestLockExtendPriceAdjustment { get; set; }
        public string RequestLockType { get; set; }
        public JsonNullable<decimal?> RequestMarginRate { get; set; }
        public JsonNullable<decimal?> RequestMarginRateRequested { get; set; }
        public JsonNullable<decimal?> RequestMarginSRPPaidOut { get; set; }
        public JsonNullable<decimal?> RequestMarginTotalAdjustment { get; set; }
        public JsonNullable<int?> RequestNumberOfDays { get; set; }
        public JsonNullable<bool?> RequestOnrpEligible { get; set; }
        public JsonNullable<DateTime?> RequestOnrpLockDate { get; set; }
        public string RequestOnrpLockTime { get; set; }
        public JsonNullable<DateTime?> RequestOriginalLockExpires { get; set; }
        public string RequestPenaltyTerm { get; set; }
        public string RequestPending { get; set; }
        public string RequestPrepayPenalty { get; set; }
        public JsonNullable<decimal?> RequestPriceRate { get; set; }
        public JsonNullable<decimal?> RequestPriceRateRequested { get; set; }
        public JsonNullable<decimal?> RequestPriceTotalAdjustment { get; set; }
        public JsonNullable<decimal?> RequestRate { get; set; }
        public JsonNullable<decimal?> RequestRateRequested { get; set; }
        public string RequestRateSheetID { get; set; }
        public JsonNullable<decimal?> RequestRateTotalAdjustment { get; set; }
        public JsonNullable<decimal?> RequestStartingAdjPoint { get; set; }
        public JsonNullable<decimal?> RequestStartingAdjRate { get; set; }
        public string RequestType { get; set; }
        public JsonNullable<decimal?> RequestUnDiscountedRate { get; set; }
        public JsonNullable<bool?> RoundToNearest50 { get; set; }
        public JsonNullable<decimal?> SecondSubordinateAmount { get; set; }
        public JsonNullable<decimal?> SellerPaidMIPremium { get; set; }
        public JsonNullable<List<PriceAdjustment>> SellSideAdjustments { get; set; }
        public string SellSideComments { get; set; }
        public string SellSideCommitmentContractNumber { get; set; }
        public JsonNullable<DateTime?> SellSideCommitmentDate { get; set; }
        public JsonNullable<DateTime?> SellSideCurrentRateSetDate { get; set; }
        public JsonNullable<int?> SellSideDaystoExtend { get; set; }
        public JsonNullable<decimal?> SellSideDiscountYSP { get; set; }
        public JsonNullable<DateTime?> SellSideExtendedLockExpires { get; set; }
        public JsonNullable<decimal?> SellSideGuaranteeFee { get; set; }
        public JsonNullable<decimal?> SellSideGuarantyBaseFee { get; set; }
        public string SellSideInvestorStatus { get; set; }
        public JsonNullable<DateTime?> SellSideInvestorStatusDate { get; set; }
        public string SellSideInvestorTradeNumber { get; set; }
        public string SellSideLoanProgram { get; set; }
        public JsonNullable<DateTime?> SellSideLockDate { get; set; }
        public JsonNullable<DateTime?> SellSideLockExpires { get; set; }
        public JsonNullable<decimal?> SellSideLockExtendPriceAdjustment { get; set; }
        public JsonNullable<decimal?> SellSideMarginNetSellRate { get; set; }
        public JsonNullable<decimal?> SellSideMarginRate { get; set; }
        public JsonNullable<decimal?> SellSideMarginTotalAdjustment { get; set; }
        public string SellSideMasterContractNumber { get; set; }
        public JsonNullable<decimal?> SellSideMSRValue { get; set; }
        public JsonNullable<decimal?> SellSideNetSellPrice { get; set; }
        public JsonNullable<decimal?> SellSideNetSellRate { get; set; }
        public JsonNullable<int?> SellSideNumberOfDays { get; set; }
        public JsonNullable<DateTime?> SellSideOriginalLockExpires { get; set; }
        public string SellSidePoolID { get; set; }
        public string SellSidePoolNumber { get; set; }
        public JsonNullable<decimal?> SellSidePriceRate { get; set; }
        public JsonNullable<decimal?> SellSidePriceTotalAdjustment { get; set; }
        public string SellSideProductName { get; set; }
        public JsonNullable<decimal?> SellSideRate { get; set; }
        public string SellSideRateSheetID { get; set; }
        public JsonNullable<decimal?> SellSideRateTotalAdjustment { get; set; }
        public string SellSideRequestedBy { get; set; }
        public string SellSideServicer { get; set; }
        public JsonNullable<decimal?> SellSideServicingFee { get; set; }
        public string SellSideServicingType { get; set; }
        public JsonNullable<decimal?> SellSideSRP { get; set; }
        public JsonNullable<decimal?> SellSideSRPPaidOut { get; set; }
        public string SellSideTradeGuid { get; set; }
        public string SellSideTradeMgmtPrevConfirmedLockGuid { get; set; }
        public string SellSideTradeNumber { get; set; }
        public JsonNullable<bool?> ServicingReleaseIndicator { get; set; }
        public JsonNullable<decimal?> SRP { get; set; }
        public JsonNullable<decimal?> SRPAmount { get; set; }
        public string SubjectPropertyCity { get; set; }
        public JsonNullable<bool?> SubjectPropertyCondotelIndicator { get; set; }
        public string SubjectPropertyCounty { get; set; }
        public JsonNullable<bool?> SubjectPropertyNonWarrantableProjectIndicator { get; set; }
        public string SubjectPropertyPostalCode { get; set; }
        public string SubjectPropertyState { get; set; }
        public string SubjectPropertyStreetAddress { get; set; }
        public string TimeLockedWithInvestor { get; set; }
        public JsonNullable<decimal?> TotalBuyPrice { get; set; }
        public JsonNullable<decimal?> TotalForLesserOfSumAsIs { get; set; }
        public JsonNullable<decimal?> TotalPrice { get; set; }
        public JsonNullable<decimal?> TotalSubordinateFinancing { get; set; }
        public JsonNullable<bool?> TwelveMonthMortgageRentalHistoryIndicator { get; set; }
        public string Type { get; set; }
        public JsonNullable<bool?> UsePoint { get; set; }
    }
}