using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class RegulationZ
    {
        public string AcknowledgedDay { get; set; }
        public string AcknowledgedMonth { get; set; }
        public string AcknowledgedYear { get; set; }
        public JsonNullable<bool?> Acquisition { get; set; }
        public string AdditionalArmInformation { get; set; }
        public JsonNullable<bool?> AllDateAndNumericalDisclosuresIndicator { get; set; }
        public JsonNullable<decimal?> AmountFinanced { get; set; }
        public JsonNullable<decimal?> AprPercent { get; set; }
        public string ArmDisclosureDescription { get; set; }
        public string AssumptionOnYourProperty { get; set; }
        public JsonNullable<DateTime?> BorrowerIntendToContinueDate { get; set; }
        public JsonNullable<bool?> BorrowerIntendToContinueIndicator { get; set; }
        public string BorrowerMiTerminationDate { get; set; }
        public string CalculateBasedOnRemainingBalance { get; set; }
        public JsonNullable<bool?> ChargesAddedToPaymentsIndicator { get; set; }
        public JsonNullable<bool?> ChargesAtLoanClosingIndicator { get; set; }
        public string CircumstanceChangeReason { get; set; }
        public JsonNullable<DateTime?> CircumstanceChangeReceivedDate { get; set; }
        public JsonNullable<DateTime?> ClosingDisclosureReceivedDate { get; set; }
        public JsonNullable<DateTime?> ClosingDisclosureSentDate { get; set; }
        public string ConstructionFirstIntChangeAdjType { get; set; }
        public string ConstructionLoanDescription { get; set; }
        public string ConstructionLoanMethod { get; set; }
        public JsonNullable<int?> ConstructionPeriodMonths { get; set; }
        public JsonNullable<decimal?> ConstructionRatePercent { get; set; }
        public JsonNullable<bool?> ConstructionRefinanceIndicator { get; set; }
        public JsonNullable<decimal?> CreditDisability { get; set; }
        public JsonNullable<bool?> CreditDisabilityIndicator { get; set; }
        public JsonNullable<decimal?> CreditLife { get; set; }
        public JsonNullable<decimal?> CreditLifeAndCreditDisability { get; set; }
        public JsonNullable<bool?> CreditLifeInsuranceIndicator { get; set; }
        public JsonNullable<bool?> CustomizePaymentScheduleIndicator { get; set; }
        public JsonNullable<bool?> DemandFeatureIndicator { get; set; }
        public JsonNullable<decimal?> DisclosedAprPercent { get; set; }
        public JsonNullable<bool?> DisclosedByBrokerIndicator { get; set; }
        public string DisclosedComments { get; set; }
        public JsonNullable<decimal?> DisclosedDailyInterestCharge { get; set; }
        public JsonNullable<decimal?> DisclosedFinanceCharge { get; set; }
        public JsonNullable<bool?> DisclosedPrepayment { get; set; }
        public string DisclosedProduct { get; set; }
        public string DisclosureMethod { get; set; }
        public string DisclosureType { get; set; }
        public JsonNullable<int?> DiscountPeriod { get; set; }
        public JsonNullable<decimal?> DiscountRatePercent { get; set; }
        public string DiscountType { get; set; }
        public JsonNullable<DateTime?> DueDate { get; set; }
        public JsonNullable<DateTime?> EarliestClosingDate { get; set; }
        public JsonNullable<DateTime?> EarliestFeeCollectionDate { get; set; }
        public JsonNullable<DateTime?> eSignConsentBorrowerDateAccepted1 { get; set; }
        public JsonNullable<DateTime?> eSignConsentBorrowerDateAccepted2 { get; set; }
        public JsonNullable<DateTime?> eSignConsentBorrowerDateAccepted3 { get; set; }
        public JsonNullable<DateTime?> eSignConsentBorrowerDateAccepted4 { get; set; }
        public JsonNullable<DateTime?> eSignConsentBorrowerDateAccepted5 { get; set; }
        public JsonNullable<DateTime?> eSignConsentBorrowerDateAccepted6 { get; set; }
        public string eSignConsentBorrowerIPAddress1 { get; set; }
        public string eSignConsentBorrowerIPAddress2 { get; set; }
        public string eSignConsentBorrowerIPAddress3 { get; set; }
        public string eSignConsentBorrowerIPAddress4 { get; set; }
        public string eSignConsentBorrowerIPAddress5 { get; set; }
        public string eSignConsentBorrowerIPAddress6 { get; set; }
        public string eSignConsentBorrowerSource1 { get; set; }
        public string eSignConsentBorrowerSource2 { get; set; }
        public string eSignConsentBorrowerSource3 { get; set; }
        public string eSignConsentBorrowerSource4 { get; set; }
        public string eSignConsentBorrowerSource5 { get; set; }
        public string eSignConsentBorrowerSource6 { get; set; }
        public string eSignConsentBorrowerStatus1 { get; set; }
        public string eSignConsentBorrowerStatus2 { get; set; }
        public string eSignConsentBorrowerStatus3 { get; set; }
        public string eSignConsentBorrowerStatus4 { get; set; }
        public string eSignConsentBorrowerStatus5 { get; set; }
        public string eSignConsentBorrowerStatus6 { get; set; }
        public JsonNullable<DateTime?> eSignConsentCoBorrowerDateAccepted1 { get; set; }
        public JsonNullable<DateTime?> eSignConsentCoBorrowerDateAccepted2 { get; set; }
        public JsonNullable<DateTime?> eSignConsentCoBorrowerDateAccepted3 { get; set; }
        public JsonNullable<DateTime?> eSignConsentCoBorrowerDateAccepted4 { get; set; }
        public JsonNullable<DateTime?> eSignConsentCoBorrowerDateAccepted5 { get; set; }
        public JsonNullable<DateTime?> eSignConsentCoBorrowerDateAccepted6 { get; set; }
        public string eSignConsentCoBorrowerIPAddress1 { get; set; }
        public string eSignConsentCoBorrowerIPAddress2 { get; set; }
        public string eSignConsentCoBorrowerIPAddress3 { get; set; }
        public string eSignConsentCoBorrowerIPAddress4 { get; set; }
        public string eSignConsentCoBorrowerIPAddress5 { get; set; }
        public string eSignConsentCoBorrowerIPAddress6 { get; set; }
        public string eSignConsentCoBorrowerSource1 { get; set; }
        public string eSignConsentCoBorrowerSource2 { get; set; }
        public string eSignConsentCoBorrowerSource3 { get; set; }
        public string eSignConsentCoBorrowerSource4 { get; set; }
        public string eSignConsentCoBorrowerSource5 { get; set; }
        public string eSignConsentCoBorrowerSource6 { get; set; }
        public string eSignConsentCoBorrowerStatus1 { get; set; }
        public string eSignConsentCoBorrowerStatus2 { get; set; }
        public string eSignConsentCoBorrowerStatus3 { get; set; }
        public string eSignConsentCoBorrowerStatus4 { get; set; }
        public string eSignConsentCoBorrowerStatus5 { get; set; }
        public string eSignConsentCoBorrowerStatus6 { get; set; }
        public JsonNullable<DateTime?> eSignConsentDate { get; set; }
        public JsonNullable<decimal?> ExtraPaymentForEarlyPayOff { get; set; }
        public JsonNullable<DateTime?> FeeCollectedDate { get; set; }
        public JsonNullable<decimal?> FilingFees { get; set; }
        public JsonNullable<DateTime?> FinalPaymentDate { get; set; }
        public JsonNullable<decimal?> FinanceCharge { get; set; }
        public JsonNullable<decimal?> FinancedAllGuaranteeFeeAmount { get; set; }
        public JsonNullable<decimal?> FinancedAllGuaranteeFeePercent { get; set; }
        public JsonNullable<decimal?> FinancedAllTotalLoanAmount { get; set; }
        public JsonNullable<decimal?> FinancedPortionGuaranteeFeeAmount { get; set; }
        public JsonNullable<decimal?> FinancedPortionGuaranteeFeePercent { get; set; }
        public JsonNullable<decimal?> FinancedPortionTotalLoanAmount { get; set; }
        public string FinancingType { get; set; }
        public JsonNullable<DateTime?> FirstAmortizationPaymentDate { get; set; }
        public JsonNullable<bool?> FloodInsuranceIndicator { get; set; }
        public JsonNullable<DateTime?> GfeApplicationDate { get; set; }
        public JsonNullable<bool?> GfeChangedCircumstanceIndicator { get; set; }
        public string GfeChangedCircumstanceItem { get; set; }
        public string GFEChangedCirsumstanceItemCode { get; set; }
        public JsonNullable<DateTime?> GfeDate { get; set; }
        public JsonNullable<DateTime?> GfeExpirationDate { get; set; }
        public string GfeExpirationPeriod { get; set; }
        public JsonNullable<bool?> GfeRateLockRedisclosureRequiredIndicator { get; set; }
        public JsonNullable<DateTime?> GfeRedisclosureProvidedDate { get; set; }
        public JsonNullable<DateTime?> GfeRedisclosureReceivedDate { get; set; }
        public JsonNullable<DateTime?> HighCostDisclosure { get; set; }
        public JsonNullable<DateTime?> HomeCounselingProvidedDate { get; set; }
        public JsonNullable<bool?> Hud1ToleranceViolatedIndicator { get; set; }
        public string HudToleranceResolutionComments { get; set; }
        public JsonNullable<DateTime?> HudToleranceResolutionDate { get; set; }
        public string HudToleranceResolvedBy { get; set; }
        public string Id { get; set; }
        public JsonNullable<bool?> IfYouPurchaseIndicator { get; set; }
        public string IfYouPurchaseType { get; set; }
        public JsonNullable<bool?> IncludeMiIndicator { get; set; }
        public JsonNullable<bool?> IncludePmiIndicator { get; set; }
        public JsonNullable<bool?> IncludeTaxesInsuranceIndicator { get; set; }
        public JsonNullable<DateTime?> InitialAVMProvidedDate { get; set; }
        public JsonNullable<DateTime?> InitialDisclosureDueDate { get; set; }
        public JsonNullable<DateTime?> InitialDisclosureProvidedDate { get; set; }
        public JsonNullable<DateTime?> InitialGfeAffiliatedBusinessProvidedDate { get; set; }
        public JsonNullable<DateTime?> InitialGFEAppraisalProvidedDate { get; set; }
        public JsonNullable<DateTime?> InitialGfeCharmBookletProvidedDate { get; set; }
        public JsonNullable<DateTime?> InitialGfeDisclosureProvidedDate { get; set; }
        public JsonNullable<DateTime?> InitialGfeDisclosureReceivedDate { get; set; }
        public JsonNullable<DateTime?> InitialGfeHelocBrochureProvidedDate { get; set; }
        public JsonNullable<DateTime?> InitialGfeHudSpecialBookletProvidedDate { get; set; }
        public JsonNullable<DateTime?> InitialSubsequentAppraisalProvidedDate { get; set; }
        public JsonNullable<DateTime?> InitialTilDisclosureProvidedDate { get; set; }
        public JsonNullable<DateTime?> InitialTilDisclosureReceivedDate { get; set; }
        public string InsuranceRequiredDescription { get; set; }
        public string InterestInNameOf { get; set; }
        public JsonNullable<bool?> InterestOnly { get; set; }
        public JsonNullable<bool?> InterestOnlyIndicator { get; set; }
        public JsonNullable<int?> InterestOnlyMonths { get; set; }
        public string InterestRateType { get; set; }
        public JsonNullable<decimal?> InterestReserveAmount { get; set; }
        public string LastDisclosedBy { get; set; }
        public JsonNullable<DateTime?> LastDisclosedDate { get; set; }
        public JsonNullable<DateTime?> LastDisclosedGfeReceivedDate { get; set; }
        public string LateChargeComments { get; set; }
        public JsonNullable<int?> LateChargeDays { get; set; }
        public JsonNullable<decimal?> LateChargePercent { get; set; }
        public string LateChargeType { get; set; }
        public JsonNullable<decimal?> LateFee { get; set; }
        public string LEIntentToProceedComment { get; set; }
        public JsonNullable<bool?> LenderPaidMortgageInsuranceIndicator { get; set; }
        public JsonNullable<decimal?> LendersInspectionFee { get; set; }
        public string LEReceivedBy { get; set; }
        public string LEReceivedMethod { get; set; }
        public string LEReceivedMethodOther { get; set; }
        public JsonNullable<DateTime?> LESentOnDate { get; set; }
        public JsonNullable<decimal?> MarginPlusIndexPercent { get; set; }
        public JsonNullable<decimal?> MaximumLateCharge { get; set; }
        public JsonNullable<decimal?> MaximumPayment { get; set; }
        public JsonNullable<bool?> MeansAnEstimateIndicator { get; set; }
        public JsonNullable<decimal?> MiAdjustmentFactorLevel2 { get; set; }
        public JsonNullable<bool?> MiDecliningRenewalsIndicator { get; set; }
        public string MidpointCancellation { get; set; }
        public JsonNullable<decimal?> MiMonthlyPaymentLevel1 { get; set; }
        public JsonNullable<decimal?> MiMonthlyPaymentLevel2 { get; set; }
        public JsonNullable<int?> MiMonthsOfAdjustmentLevel1 { get; set; }
        public JsonNullable<int?> MiMonthsOfAdjustmentLevel2 { get; set; }
        public JsonNullable<decimal?> MinimumLateCharge { get; set; }
        public JsonNullable<decimal?> MinimumPayment { get; set; }
        public JsonNullable<bool?> MIPFactorLocked { get; set; }
        public JsonNullable<decimal?> MIPrepaidAmount { get; set; }
        public JsonNullable<bool?> MiPrepaidIndicator { get; set; }
        public string MiScheduledTerminationDate { get; set; }
        public JsonNullable<bool?> MmiIndicator { get; set; }
        public JsonNullable<decimal?> MonthlyTerm { get; set; }
        public JsonNullable<int?> MonthsOfMiPrepaid { get; set; }
        public JsonNullable<decimal?> MortgageInsuranceCancelPercent { get; set; }
        public string NamePreparedBy { get; set; }
        public string NewConstructionIndicator { get; set; }
        public JsonNullable<int?> NumberOfPayments { get; set; }
        public JsonNullable<DateTime?> OccupancyCertDate { get; set; }
        public JsonNullable<DateTime?> OriginalContractDate { get; set; }
        public JsonNullable<decimal?> OutstandingBalance { get; set; }
        public string PaymentFrequencyType { get; set; }
        public JsonNullable<decimal?> PaymentIncreasePercent { get; set; }
        public string PhonePreparedBy { get; set; }
        public JsonNullable<bool?> PmiIndicator { get; set; }
        public JsonNullable<DateTime?> PmiMidpointCancelationDate { get; set; }
        public JsonNullable<DateTime?> PostConsummationDisclosureReceivedDate { get; set; }
        public JsonNullable<DateTime?> PostConsummationDisclosureSentDate { get; set; }
        public JsonNullable<decimal?> PrepaidFinanceCharge { get; set; }
        public JsonNullable<bool?> PropertyInsuranceIndicator { get; set; }
        public JsonNullable<DateTime?> RateLockGfeDueDate { get; set; }
        public JsonNullable<decimal?> RatePercent { get; set; }
        public JsonNullable<int?> RecastPaidMonths { get; set; }
        public JsonNullable<int?> RecastStopMonths { get; set; }
        public JsonNullable<bool?> RefundPaymentIndicator { get; set; }
        public JsonNullable<bool?> RefundUnearnedMipIndicator { get; set; }
        public JsonNullable<List<RegulationZInterestRatePeriod>> RegulationZInterestRatePeriods { get; set; }
        public JsonNullable<List<RegulationZPayment>> RegulationZPayments { get; set; }
        public string RegzTableType { get; set; }
        public JsonNullable<bool?> RequiredDepositIndicator { get; set; }
        public JsonNullable<DateTime?> RevisedClosingDisclosureReceivedDate { get; set; }
        public JsonNullable<DateTime?> RevisedClosingDisclosureSentDate { get; set; }
        public JsonNullable<DateTime?> RevisedGfeDueDate { get; set; }
        public JsonNullable<decimal?> RoundedMarginPlusIndexPercent { get; set; }
        public JsonNullable<DateTime?> SafeHarborSentDate { get; set; }
        public JsonNullable<decimal?> SamplePayments { get; set; }
        public string SecurityType { get; set; }
        public JsonNullable<DateTime?> SSPLSentDate { get; set; }
        public JsonNullable<DateTime?> TilDate { get; set; }
        public string TilDisclosedComments { get; set; }
        public string TilDisclosureMethod { get; set; }
        public JsonNullable<DateTime?> TilLastDisclosedBorrowerReceivedDate { get; set; }
        public string TilLastDisclosedBy { get; set; }
        public JsonNullable<DateTime?> TilLastDisclosedDate { get; set; }
        public JsonNullable<DateTime?> TilRedisclosureProvidedDate { get; set; }
        public JsonNullable<DateTime?> TilRedisclosureReceivedDate { get; set; }
        public JsonNullable<decimal?> TotalBrokerFees { get; set; }
        public JsonNullable<decimal?> TotalLatePayment { get; set; }
        public JsonNullable<decimal?> TotalLenderFees { get; set; }
        public JsonNullable<decimal?> TotalOfPayments { get; set; }
        public JsonNullable<decimal?> TotalOfPrincipalAndInterest { get; set; }
        public JsonNullable<bool?> UseCustomLenderProfile { get; set; }
        public string UseDaysInYears { get; set; }
        public JsonNullable<bool?> UsePitiForRatioIndicator { get; set; }
        public JsonNullable<bool?> VariableRateFeatureIndicator { get; set; }
        public JsonNullable<decimal?> YearlyTerm { get; set; }
        public string YearOfMaximumPayment { get; set; }
        public JsonNullable<int?> Years { get; set; }
    }
}