using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class Section32
    {
        public JsonNullable<bool?> AppraisalFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> AppraisalPortionOfFeeIndicator { get; set; }
        public JsonNullable<decimal?> AprExceedsTsyForFirstMortgage { get; set; }
        public JsonNullable<decimal?> AprExceedsTsyForSubordinateMortgage { get; set; }
        public JsonNullable<bool?> AssumptionFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> AssumptionPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> AttorneyFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> AttorneyPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> CityCountyTaxStampsFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> CityCountyTaxStampsPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> ClosingFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> ClosingPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> CreditReportFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> CreditReportPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> DocPrepFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> DocPrepPortionOfFeeIndicator { get; set; }
        public string Exceed2PercentPrepayPenalty { get; set; }
        public JsonNullable<decimal?> HoepaAPR { get; set; }
        public JsonNullable<decimal?> HoepaFee { get; set; }
        public string Id { get; set; }
        public string Jurisdications { get; set; }
        public JsonNullable<bool?> LendersInspectionFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> LendersInspectionPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> LoanDiscountFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> LoanDiscountPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> LoanOriginationFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> LoanOriginationPortionOfFeeIndicator { get; set; }
        public string LoanQualifyAsHighCostMortgage { get; set; }
        public JsonNullable<decimal?> MaximumPercentageOfLoan { get; set; }
        public JsonNullable<decimal?> MaximumPointsAndFees { get; set; }
        public JsonNullable<bool?> MortgageBrokerFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> MortgageBrokerPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> MortgageInspectionFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> MortgageInspectionPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> MortgageInsuranceFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> MortgageInsurancePortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> MortgageInsurancePremiumFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> MortgageInsurancePremiumPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> NotaryFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> NotaryPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> OtherHighCostIndicator { get; set; }
        public string PenaltyChargeMoreThan36Months { get; set; }
        public JsonNullable<bool?> PestInspectionFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> PestInspectionPortionOfFeeIndicator { get; set; }
        public JsonNullable<decimal?> PrepayPenaltyPercentofAmtPrepaid { get; set; }
        public JsonNullable<bool?> ProcessingFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> ProcessingPortionOfFeeIndicator { get; set; }
        public JsonNullable<decimal?> RateSetIndex { get; set; }
        public JsonNullable<bool?> RecordingFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> RecordingPortionOfFeeIndicator { get; set; }
        public string ResultOfPointAndFees { get; set; }
        public string ResultOfSecurityYieldTest { get; set; }
        public JsonNullable<bool?> Section32Indicator { get; set; }
        public JsonNullable<decimal?> Section35AveragePrimeRate { get; set; }
        public string Section35IsSecondAppraisalRequired { get; set; }
        public JsonNullable<DateTime?> Section35PriorAcquisitionDate { get; set; }
        public JsonNullable<decimal?> Section35PriorAcquisitionPrice { get; set; }
        public string Section35PriorAcquisitionSource { get; set; }
        public string Section35ResultOfSecurityYieldTest { get; set; }
        public JsonNullable<DateTime?> Section35SalesContractDate { get; set; }
        public JsonNullable<bool?> StateTaxStampsFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> StateTaxStampsPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> SurveyFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> SurveyPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> TaxServiceFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> TaxServicePortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> TitleBinderFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> TitleBinderPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> TitleExaminationFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> TitleExaminationPortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> TitleInsuranceFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> TitleInsurancePortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> TitleSearchFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> TitleSearchPortionOfFeeIndicator { get; set; }
        public JsonNullable<decimal?> TotalPointsAndFees { get; set; }
        public JsonNullable<decimal?> TreasurySecurityYield { get; set; }
        public JsonNullable<bool?> UnderwritingFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UnderwritingPortionOfFeeIndicator { get; set; }
        public JsonNullable<decimal?> UserDefined1109BorPaidAmount { get; set; }
        public JsonNullable<bool?> UserDefined1109FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1109PortionOfFeeIndicator { get; set; }
        public JsonNullable<decimal?> UserDefined1110BorPaidAmount { get; set; }
        public JsonNullable<bool?> UserDefined1110FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1110PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1111FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1111PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1112FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1112PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1113FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1113PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1114FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1114PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1204FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1204PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1205FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1205PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1206FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1206PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1303FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1303PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1304FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1304PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1305FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1305PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1306FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1306PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1307FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1307PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1308FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1308PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1309FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined1309PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined813FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined813PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined814FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined814PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined815FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined815PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined816FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined816PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined817FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined817PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined818FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined818PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined819FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined819PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined820FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined820PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined821FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined821PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined822FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined822PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> UserDefined823FeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> UserDefined823PortionOfFeeIndicator { get; set; }
        public JsonNullable<bool?> WireTransferFeeToBeFinancedIndicator { get; set; }
        public JsonNullable<bool?> WireTransferPortionOfFeeIndicator { get; set; }
    }
}