using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class Section32
    {
        public decimal? TreasurySecurityYield { get; set; }
        public decimal? MaximumPercentageOfLoan { get; set; }
        public decimal? MaximumPointsAndFees { get; set; }
        public bool? ProcessingPortionOfFeeIndicator { get; set; }
        public bool? ProcessingFeeToBeFinancedIndicator { get; set; }
        public bool? WireTransferPortionOfFeeIndicator { get; set; }
        public bool? WireTransferFeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1110PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1110FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1205PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1205FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1206PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1206FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1111PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1111FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1112PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1112FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1113PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1113FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1114PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1114FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1307PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1307FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1308PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1308FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1309PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1309FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined821PortionOfFeeIndicator { get; set; }
        public bool? UserDefined821FeeToBeFinancedIndicator { get; set; }
        public bool? MortgageInspectionPortionOfFeeIndicator { get; set; }
        public bool? MortgageInspectionFeeToBeFinancedIndicator { get; set; }
        public bool? AssumptionPortionOfFeeIndicator { get; set; }
        public bool? AssumptionFeeToBeFinancedIndicator { get; set; }
        public bool? AttorneyPortionOfFeeIndicator { get; set; }
        public bool? AttorneyFeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined822PortionOfFeeIndicator { get; set; }
        public bool? UserDefined822FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined823PortionOfFeeIndicator { get; set; }
        public bool? UserDefined823FeeToBeFinancedIndicator { get; set; }
        public bool? TitleSearchPortionOfFeeIndicator { get; set; }
        public bool? TitleSearchFeeToBeFinancedIndicator { get; set; }
        public bool? TitleExaminationPortionOfFeeIndicator { get; set; }
        public bool? TitleExaminationFeeToBeFinancedIndicator { get; set; }
        public bool? TitleBinderPortionOfFeeIndicator { get; set; }
        public bool? TitleBinderFeeToBeFinancedIndicator { get; set; }
        public bool? MortgageInsurancePremiumPortionOfFeeIndicator { get; set; }
        public bool? MortgageInsurancePremiumFeeToBeFinancedIndicator { get; set; }
        public bool? MortgageInsurancePortionOfFeeIndicator { get; set; }
        public bool? MortgageInsuranceFeeToBeFinancedIndicator { get; set; }
        public decimal? UserDefined1109BorPaidAmount { get; set; }
        public decimal? UserDefined1110BorPaidAmount { get; set; }
        public decimal? RateSetIndex { get; set; }
        public decimal? HoepaAPR { get; set; }
        public decimal? PrepayPenaltyPercentofAmtPrepaid { get; set; }
        public string Exceed2PercentPrepayPenalty { get; set; }
        public string PenaltyChargeMoreThan36Months { get; set; }
        public bool? MortgageBrokerPortionOfFeeIndicator { get; set; }
        public bool? UserDefined813PortionOfFeeIndicator { get; set; }
        public bool? UserDefined814PortionOfFeeIndicator { get; set; }
        public bool? UserDefined815PortionOfFeeIndicator { get; set; }
        public string ResultOfSecurityYieldTest { get; set; }
        public bool? UserDefined816PortionOfFeeIndicator { get; set; }
        public bool? UserDefined817PortionOfFeeIndicator { get; set; }
        public bool? UserDefined818PortionOfFeeIndicator { get; set; }
        public bool? UserDefined819PortionOfFeeIndicator { get; set; }
        public bool? UserDefined820PortionOfFeeIndicator { get; set; }
        public bool? AppraisalPortionOfFeeIndicator { get; set; }
        public bool? CreditReportPortionOfFeeIndicator { get; set; }
        public bool? ClosingPortionOfFeeIndicator { get; set; }
        public bool? LoanOriginationPortionOfFeeIndicator { get; set; }
        public bool? DocPrepPortionOfFeeIndicator { get; set; }
        public bool? NotaryPortionOfFeeIndicator { get; set; }
        public bool? TitleInsurancePortionOfFeeIndicator { get; set; }
        public bool? UserDefined1109PortionOfFeeIndicator { get; set; }
        public bool? RecordingPortionOfFeeIndicator { get; set; }
        public bool? CityCountyTaxStampsPortionOfFeeIndicator { get; set; }
        public bool? StateTaxStampsPortionOfFeeIndicator { get; set; }
        public bool? UserDefined1204PortionOfFeeIndicator { get; set; }
        public bool? LoanDiscountPortionOfFeeIndicator { get; set; }
        public bool? SurveyPortionOfFeeIndicator { get; set; }
        public bool? PestInspectionPortionOfFeeIndicator { get; set; }
        public bool? UserDefined1303PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1304PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1305PortionOfFeeIndicator { get; set; }
        public bool? UserDefined1306PortionOfFeeIndicator { get; set; }
        public decimal? TotalPointsAndFees { get; set; }
        public string ResultOfPointAndFees { get; set; }
        public decimal? HoepaFee { get; set; }
        public string LoanQualifyAsHighCostMortgage { get; set; }
        public bool? LoanOriginationFeeToBeFinancedIndicator { get; set; }
        public bool? LoanDiscountFeeToBeFinancedIndicator { get; set; }
        public bool? LendersInspectionFeeToBeFinancedIndicator { get; set; }
        public bool? TaxServiceFeeToBeFinancedIndicator { get; set; }
        public bool? UnderwritingFeeToBeFinancedIndicator { get; set; }
        public bool? MortgageBrokerFeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined813FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined814FeeToBeFinancedIndicator { get; set; }
        public bool? LendersInspectionPortionOfFeeIndicator { get; set; }
        public bool? UserDefined815FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined816FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined817FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined818FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined819FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined820FeeToBeFinancedIndicator { get; set; }
        public bool? AppraisalFeeToBeFinancedIndicator { get; set; }
        public bool? CreditReportFeeToBeFinancedIndicator { get; set; }
        public bool? ClosingFeeToBeFinancedIndicator { get; set; }
        public bool? DocPrepFeeToBeFinancedIndicator { get; set; }
        public bool? TaxServicePortionOfFeeIndicator { get; set; }
        public bool? NotaryFeeToBeFinancedIndicator { get; set; }
        public bool? TitleInsuranceFeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1109FeeToBeFinancedIndicator { get; set; }
        public bool? RecordingFeeToBeFinancedIndicator { get; set; }
        public bool? CityCountyTaxStampsFeeToBeFinancedIndicator { get; set; }
        public bool? StateTaxStampsFeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1204FeeToBeFinancedIndicator { get; set; }
        public bool? SurveyFeeToBeFinancedIndicator { get; set; }
        public bool? UnderwritingPortionOfFeeIndicator { get; set; }
        public bool? PestInspectionFeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1303FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1304FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1305FeeToBeFinancedIndicator { get; set; }
        public bool? UserDefined1306FeeToBeFinancedIndicator { get; set; }
        public decimal? AprExceedsTsyForFirstMortgage { get; set; }
        public decimal? AprExceedsTsyForSubordinateMortgage { get; set; }
        public bool? Section32Indicator { get; set; }
        public bool? OtherHighCostIndicator { get; set; }
        public string Jurisdications { get; set; }
        public decimal? Section35AveragePrimeRate { get; set; }
        public string Section35ResultOfSecurityYieldTest { get; set; }
        public string Section35PriorAcquisitionSource { get; set; }
        public DateTime? Section35PriorAcquisitionDate { get; set; }
        public decimal? Section35PriorAcquisitionPrice { get; set; }
        public DateTime? Section35SalesContractDate { get; set; }
        public string Section35IsSecondAppraisalRequired { get; set; }
        public string Id { get; set; }
    }
}