using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class StateDisclosure
    {
        public bool? AttorneyForTheSellerIndicator { get; set; }
        public bool? AttorneyForTheBuyerIndicator { get; set; }
        public bool? AttorneyForTheLenderIndicator { get; set; }
        public string CommitmentCondition1 { get; set; }
        public string CommitmentCondition2 { get; set; }
        public string AdvisoryCondition1 { get; set; }
        public string AdvisoryCondition2 { get; set; }
        public string AdvisoryCondition3 { get; set; }
        public string AdvisoryCondition4 { get; set; }
        public bool? LenderPayIndicator { get; set; }
        public decimal? LenderPayPercent { get; set; }
        public decimal? LenderPayAmount { get; set; }
        public decimal? LenderPayPoint { get; set; }
        public decimal? LenderPayMaxPoint { get; set; }
        public bool? BrokerPayIndicator { get; set; }
        public decimal? BrokerPayPercent { get; set; }
        public decimal? BrokerPayAmount { get; set; }
        public bool? DirectPayIndicator { get; set; }
        public decimal? DirectPayCommitment { get; set; }
        public decimal? DirectPayClosing { get; set; }
        public decimal? DirectPayPercent { get; set; }
        public decimal? DirectPayAmount { get; set; }
        public decimal? NewYorkApplicationFee { get; set; }
        public decimal? NewYorkAppraisalFee { get; set; }
        public decimal? NewYorkCreditReportFee { get; set; }
        public string RefundCondition1 { get; set; }
        public string RefundCondition2 { get; set; }
        public decimal? NewYorkProcessingFee { get; set; }
        public string QuestionContact { get; set; }
        public string QuestionContactPhone { get; set; }
        public string QuestionContactTollFree { get; set; }
        public List<NewYorkPrimaryLender> NewYorkPrimaryLenders { get; set; }
        public string ReceivedBy { get; set; }
        public decimal? FeeReceived1 { get; set; }
        public decimal? GFEFeeReceived1 { get; set; }
        public decimal? FeeReceived2 { get; set; }
        public decimal? GFEFeeReceived2 { get; set; }
        public string LenderName { get; set; }
        public string LenderStatus { get; set; }
        public DateTime? LenderDate { get; set; }
        public decimal? PaidByLender { get; set; }
        public decimal? PaidByBorrower { get; set; }
        public string PaidByOtherDescription1 { get; set; }
        public decimal? PaidByOther1 { get; set; }
        public string PaidByOtherDescription2 { get; set; }
        public decimal? PaidByOther2 { get; set; }
        public decimal? TotalFee { get; set; }
        public string RefundCondition3 { get; set; }
        public string RefundCondition4 { get; set; }
        public string RefundCondition5 { get; set; }
        public string RefundCondition6 { get; set; }
        public string IndexUsed { get; set; }
        public string InformationAboutTheIndexCanBeFound { get; set; }
        public string CheckPayableTo { get; set; }
        public string NameOfLicensee { get; set; }
        public DateTime? ApplicationDate { get; set; }
        public decimal? BrokerageFeePercent1 { get; set; }
        public decimal? BrokerageFeeAddition1 { get; set; }
        public decimal? BrokerageFeePercent2 { get; set; }
        public decimal? BrokerageFeeAddition2 { get; set; }
        public decimal? BrokerageFeePercent3 { get; set; }
        public decimal? BrokerageFeeAddition3 { get; set; }
        public decimal? FloridaApplicationFee { get; set; }
        public string RefundableType { get; set; }
        public decimal? AppraisalDeposit { get; set; }
        public decimal? CreditDeposit { get; set; }
        public string BrokerName { get; set; }
        public string BrokerLicense { get; set; }
        public bool? SubmitToLenderIndicator { get; set; }
        public bool? IndependentContractorIndicator { get; set; }
        public bool? ActingOthersIndicator { get; set; }
        public string ActingOtherDescription1 { get; set; }
        public string ActingOtherDescription2 { get; set; }
        public bool? OfferRetailPriceIndicator { get; set; }
        public bool? BasedOnWholesaleOptionsIndicator { get; set; }
        public decimal? FeesReceiving { get; set; }
        public decimal? TexasApplicationFee { get; set; }
        public decimal? TexasProcessingFee { get; set; }
        public string AppraisalContact { get; set; }
        public decimal? TexasAppraisalFee { get; set; }
        public string CreditReportContact { get; set; }
        public decimal? TexasCreditReportFee { get; set; }
        public string UnderwritingContact { get; set; }
        public decimal? UnderwritingFee { get; set; }
        public string TexasOtherFeeContact1 { get; set; }
        public decimal? TexasOtherFee1 { get; set; }
        public string TexasOtherFeeContact2 { get; set; }
        public decimal? TexasOtherFee2 { get; set; }
        public decimal? NotRefundableAmount { get; set; }
        public bool? AsRealBrokerIndicator { get; set; }
        public string BrokerForTheSeller { get; set; }
        public bool? LenderPayUnknownIndicator { get; set; }
        public decimal? BrokerPayAddition { get; set; }
        public decimal? NewMoneyAmount { get; set; }
        public decimal? PreviousMortgageAmountOne { get; set; }
        public decimal? PreviousMortgageAmountTwo { get; set; }
        public string TypeOfProperty { get; set; }
        public string InLicensedNo { get; set; }
        public string InLicensedType { get; set; }
        public string RegulatorAddress { get; set; }
        public string RegulatorCity { get; set; }
        public string RegulatorState { get; set; }
        public string RegulatorZipCode { get; set; }
        public string RegulatorPhone { get; set; }
        public string RegulatorTollFreePhone { get; set; }
        public string RegulatorMailingAddress { get; set; }
        public string RegulatorMailingCity { get; set; }
        public string RegulatorMailingState { get; set; }
        public string RegulatorMailingZipCode { get; set; }
        public string RegulatorWebAddress { get; set; }
        public bool? AsAttorneyIndicator { get; set; }
        public bool? MortgageAgreementIndicator { get; set; }
        public bool? CHARMBookletIndicator { get; set; }
        public bool? SpecificARMIndicator { get; set; }
        public bool? HUDBookletIndicator { get; set; }
        public bool? SignedByBorrowerIndicator { get; set; }
        public decimal? LenderPaid { get; set; }
        public decimal? BrokerageFeeAmount1 { get; set; }
        public decimal? BrokerageFeeAmount2 { get; set; }
        public decimal? BrokerageFeeAmount3 { get; set; }
        public int? BrokerageFeeDays { get; set; }
        public decimal? CompensationPercent { get; set; }
        public decimal? CompensationAddition { get; set; }
        public decimal? DepositReceipt { get; set; }
        public decimal? ThirdPartyFee { get; set; }
        public bool? DepositRefundableIndicator { get; set; }
        public string RefundableBy { get; set; }
        public string MtgBrokerLicense { get; set; }
        public string ProvidedBy { get; set; }
        public string DirectContact { get; set; }
        public string FeeReceivedByLender { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public bool? AcceptedByBorrowerIndicator { get; set; }
        public DateTime? AcceptedDate { get; set; }
        public bool? IsEstimateIndicator { get; set; }
        public decimal? LockInFee { get; set; }
        public decimal? CommitmentPercent { get; set; }
        public decimal? CommitmentAmount { get; set; }
        public decimal? RefinancingFee { get; set; }
        public string FloridaOtherFeeTo1 { get; set; }
        public decimal? FloridaOtherFee1 { get; set; }
        public string FloridaOtherFeeTo2 { get; set; }
        public string TermsChange { get; set; }
        public string FloridaOtherFeeTo3 { get; set; }
        public decimal? FloridaOtherFee2 { get; set; }
        public string FloridaOtherFeeTo4 { get; set; }
        public string MethodDetermine { get; set; }
        public string MethodDescription { get; set; }
        public int? DaysBeforeClosing { get; set; }
        public decimal? CommitmentFee { get; set; }
        public bool? RefundableIndicator { get; set; }
        public List<NewYorkFee> NewYorkFees { get; set; }
        public bool? SelectPrimaryLenderIndicator { get; set; }
        public bool? SelectPrivateLenderIndicator { get; set; }
        public bool? SelectDivisionFeesIndicator { get; set; }
        public string CreditIsUsedForReason { get; set; }
        public bool? BasedOnOthersIndicator { get; set; }
        public string BasedOnOthersDescription { get; set; }
        public bool? EstimatedChargeShownOnGFEIndicator { get; set; }
        public bool? PrintMDDeliveryIndicator { get; set; }
        public string ScheduleOfChargesEstimatedFinalIndicator { get; set; }
        public bool? BorrowerElectsEstablishEscrowIndicator { get; set; }
        public decimal? BorrowerElectsEstablishEscrowAmount { get; set; }
        public int? AdvFeeAgmtInEfctNumDay { get; set; }
        public string AZCmplBlankSpcsDoc1Nm { get; set; }
        public string AZCmplBlankSpcsDoc1BlankFldDesc1 { get; set; }
        public string AZCmplBlankSpcsDoc2Nm { get; set; }
        public string AZCmplBlankSpcsDoc1BlankFldDesc2 { get; set; }
        public string AZCmplBlankSpcsDoc3Nm { get; set; }
        public string AZCmplBlankSpcsDoc1BlankFldDesc3 { get; set; }
        public string BrokerAuthorizedSigningRepName { get; set; }
        public string BrokerAuthorizedSigningRepTitle { get; set; }
        public bool? OriginationFeeChargedIndicator { get; set; }
        public decimal? OriginationFeeChargedAmount { get; set; }
        public string OriginationFeePaidBy { get; set; }
        public string OriginationFeeInterestRateImpactedStatus { get; set; }
        public decimal? OriginationFeeDecreasesRate { get; set; }
        public decimal? OriginationFeeIncreasesRate { get; set; }
        public bool? YSPChargedIndicator { get; set; }
        public decimal? YSPChargedAmount { get; set; }
        public string YSPPaidBy { get; set; }
        public string YSPInterestRateImpactedStatus { get; set; }
        public decimal? YSPDecreasesRate { get; set; }
        public decimal? YSPIncreasesRate { get; set; }
        public bool? TransferFeeChargedIndicator { get; set; }
        public decimal? TransferFeeChargedAmount { get; set; }
        public string TransferFeePaidBy { get; set; }
        public bool? ServicingFeeChargedIndicator { get; set; }
        public decimal? ServicingFeeChargedAmount { get; set; }
        public string ServicingFeePaidBy { get; set; }
        public string ServicingFeePaidFrequence { get; set; }
        public string FurtherFeesEarnedByMortgageBroker { get; set; }
        public bool? RateLockHonoredIndicator { get; set; }
        public bool? LoanTermsFixedThroughDateofLoanClosingIndicator { get; set; }
        public string ScRegulatoryAgencyType { get; set; }
        public bool? KsUcccElectionIndicator { get; set; }
        public bool? TxVeteransLandBoardIndicator { get; set; }
        public bool? KyHomeSolicationLoanIndicator { get; set; }
        public string DisclosureDeliveredBy { get; set; }
        public string DisclosureDeliveredByOtherMethod { get; set; }
        public DateTime? DisclosureDeliveredDate { get; set; }
        public string Areas { get; set; }
        public bool? PrintInterestRateReductionRider { get; set; }
        public bool? PrintCertificationOfCosts { get; set; }
        public decimal? FederallySubsidizedAmountPercentage { get; set; }
        public decimal? FederallySubsidizedAmount { get; set; }
        public decimal? TaxExemptAcquisitionCostCertificationOwnersTitleInsurance { get; set; }
        public decimal? TaxExemptAcquisitionCostCertificationSurvey { get; set; }
        public decimal? TaxExemptAcquisitionCostCertificationRealEstateCommission { get; set; }
        public decimal? TaxExemptAcquisitionCostCertificationAssessments { get; set; }
        public decimal? TaxExemptAcquisitionCostCertificationRepairsImprovements { get; set; }
        public string TaxExemptAcquisitionCostCertificationOther { get; set; }
        public decimal? TaxExemptAcquisitionCostCertificationOtherAmount { get; set; }
        public decimal? TaxExemptAcquisitionCostCertificationTotalAdjustments { get; set; }
        public decimal? OriginalAcquisitionCost { get; set; }
        public decimal? AmendedAcquisitionCost { get; set; }
        public DateTime? LeaseAgreementDate { get; set; }
        public string LessorName { get; set; }
        public string Id { get; set; }
    }
}