using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class TPO
    {
        public JsonNullable<bool?> Archived { get; set; }
        public string BranchAddress { get; set; }
        public string BranchAEName { get; set; }
        public string BranchAEUserName { get; set; }
        public string BranchCity { get; set; }
        public string BranchDBAName { get; set; }
        public string BranchFax { get; set; }
        public string BranchID { get; set; }
        public string BranchLegalName { get; set; }
        public string BranchManagerEmail { get; set; }
        public string BranchManagerName { get; set; }
        public string BranchName { get; set; }
        public string BranchOrganizationID { get; set; }
        public string BranchPhone { get; set; }
        public string BranchRating { get; set; }
        public string BranchState { get; set; }
        public string BranchZip { get; set; }
        public string CFCAddress { get; set; }
        public string CFCBusinessFax { get; set; }
        public string CFCBusinessPhone { get; set; }
        public string CFCCellPhone { get; set; }
        public string CFCCity { get; set; }
        public string CFCEmail { get; set; }
        public string CFCName { get; set; }
        public string CFCNotes { get; set; }
        public string CFCRepAE { get; set; }
        public string CFCSRAEUserName { get; set; }
        public string CFCState { get; set; }
        public string CFCStatus { get; set; }
        public string CFCUserID { get; set; }
        public string CFCZip { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyAEName { get; set; }
        public string CompanyAEUserName { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyDBAName { get; set; }
        public string CompanyFax { get; set; }
        public string CompanyID { get; set; }
        public string CompanyLegalName { get; set; }
        public string CompanyManagerEmail { get; set; }
        public string CompanyManagerName { get; set; }
        public string CompanyName { get; set; }
        public string CompanyOrganizationID { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyRating { get; set; }
        public string CompanyState { get; set; }
        public string CompanyZip { get; set; }
        public JsonNullable<DateTime?> DocumentsReadyDate { get; set; }
        public string FeeReviewComments { get; set; }
        public string FeeReviewStatus { get; set; }
        public JsonNullable<DateTime?> FeeReviewStatusDate { get; set; }
        public string ImportSource { get; set; }
        public JsonNullable<DateTime?> InitialApplicationDate { get; set; }
        public JsonNullable<DateTime?> InitialSubmitDate { get; set; }
        public string LOAddress { get; set; }
        public string LOAEName { get; set; }
        public string LOAEUserName { get; set; }
        public string LOBusinessFax { get; set; }
        public string LOBusinessPhone { get; set; }
        public string LOCellPhone { get; set; }
        public string LOCity { get; set; }
        public string LOEmail { get; set; }
        public string LOID { get; set; }
        public string LOName { get; set; }
        public string LONotes { get; set; }
        public string LOState { get; set; }
        public string LOStatus { get; set; }
        public string LOZip { get; set; }
        public string LPAddress { get; set; }
        public string LPAEName { get; set; }
        public string LPAEUserName { get; set; }
        public string LPBusinessFax { get; set; }
        public string LPBusinessPhone { get; set; }
        public string LPCellPhone { get; set; }
        public string LPCity { get; set; }
        public string LPEmail { get; set; }
        public string LPID { get; set; }
        public string LPName { get; set; }
        public string LPNotes { get; set; }
        public string LPState { get; set; }
        public string LPStatus { get; set; }
        public string LPZip { get; set; }
        public JsonNullable<DateTime?> PurchaseStipsReadyDate { get; set; }
        public JsonNullable<bool?> PurchaseStipsReviewed { get; set; }
        public JsonNullable<DateTime?> ReadytoDiscloseDateUtc { get; set; }
        public JsonNullable<DateTime?> RegisterDate { get; set; }
        public string SITEID { get; set; }
        public JsonNullable<DateTime?> SubmitDate { get; set; }
        public JsonNullable<bool?> TestAccountField { get; set; }
        public JsonNullable<bool?> UnderwriterReviewed { get; set; }
        public JsonNullable<bool?> UnderwritingDelegated { get; set; }
        public JsonNullable<bool?> WatchListFlag { get; set; }
        public string WatchListReason { get; set; }
    }
}