using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class Uldd
    {
        public string ACHABARoutingAndTransitIdentifier { get; set; }
        public string ACHABARoutingAndTransitNumber { get; set; }
        public string ACHBankAccountDescription { get; set; }
        public string ACHBankAccountIdentifier { get; set; }
        public string ACHBankAccountPurposeTransitIdentifier { get; set; }
        public string ACHBankAccountPurposeType { get; set; }
        public string ACHInstitutionTelegraphicAbbreviationName { get; set; }
        public string ACHReceiverSubaccountName { get; set; }
        public JsonNullable<bool?> AdditionalPrincipalAmountIndicator { get; set; }
        public JsonNullable<decimal?> AggregateLoanCurtailmentAmount { get; set; }
        public string AppraisalIdentifier { get; set; }
        public string AttachmentType { get; set; }
        public string AVMModelNameType { get; set; }
        public JsonNullable<bool?> BalloonResetIndicator { get; set; }
        public JsonNullable<decimal?> BaseGuarantyFeePercent { get; set; }
        public string BondFinancePool { get; set; }
        public string BondFinanceProgramName { get; set; }
        public string BondFinanceProgramType { get; set; }
        public JsonNullable<bool?> BorrowerMailToAddressSameasPropertyIndicator { get; set; }
        public string BorrowerType { get; set; }
        public JsonNullable<bool?> CapitalizedLoanIndicator { get; set; }
        public string CertificateIdentifier { get; set; }
        public JsonNullable<DateTime?> CertificateMaturityDate { get; set; }
        public JsonNullable<decimal?> CertificatePrincipalBalanceAmount { get; set; }
        public string CertificateType { get; set; }
        public JsonNullable<decimal?> ClosingCost2ContributionAmount { get; set; }
        public string ClosingCost2FundsType { get; set; }
        public string ClosingCost2FundsTypeOtherDescription { get; set; }
        public string ClosingCost2SourceType { get; set; }
        public string ClosingCost2SourceTypeOtherDescription { get; set; }
        public JsonNullable<decimal?> ClosingCost3ContributionAmount { get; set; }
        public string ClosingCost3FundsType { get; set; }
        public string ClosingCost3FundsTypeOtherDescription { get; set; }
        public string ClosingCost3SourceType { get; set; }
        public string ClosingCost3SourceTypeOtherDescription { get; set; }
        public JsonNullable<decimal?> ClosingCost4ContributionAmount { get; set; }
        public string ClosingCost4FundsType { get; set; }
        public string ClosingCost4FundsTypeOtherDescription { get; set; }
        public string ClosingCost4SourceType { get; set; }
        public string ClosingCost4SourceTypeOtherDescription { get; set; }
        public JsonNullable<decimal?> ClosingCostContributionAmount { get; set; }
        public string ClosingCostFundsType { get; set; }
        public string ClosingCostFundsTypeOtherDescription { get; set; }
        public string ClosingCostSourceType { get; set; }
        public string ClosingCostSourceTypeOtherDescription { get; set; }
        public string CoBorrowerCountryCode { get; set; }
        public JsonNullable<bool?> CoBorrowerMailToAddressSameasPropertyIndicator { get; set; }
        public string CoBorrowerType { get; set; }
        public string CondominiumProjectStatusType { get; set; }
        public string ConstructionMethodType { get; set; }
        public string ConstructionMethodTypeOtherDescription { get; set; }
        public string ConstructionToPermanentClosingFeatureType { get; set; }
        public string ConstructionToPermanentClosingType { get; set; }
        public string ConvertibleStatusType { get; set; }
        public string CounselingFormatType { get; set; }
        public string CounselingFormatTypeOtherDescription { get; set; }
        public string CounselTypeOther { get; set; }
        public string CountryCode { get; set; }
        public string CreditScoreImpairmentType { get; set; }
        public JsonNullable<decimal?> CurrentAccruedInterestAmount { get; set; }
        public JsonNullable<int?> DelinquentPaymentsOverPastTwelveMonthsCount { get; set; }
        public string DocumentCustodianID { get; set; }
        public string DocumentRequiredIndicator { get; set; }
        public string DocumentSubmissionIndicator { get; set; }
        public string DownPaymentFundsType { get; set; }
        public string DownPaymentOtherTypeDescription { get; set; }
        public string DownPaymentSourceType { get; set; }
        public string DownPaymentSourceTypeOtherDescription { get; set; }
        public string FannieARMIndexType { get; set; }
        public string FannieAutoUWDec { get; set; }
        public JsonNullable<int?> FannieBLTV { get; set; }
        public string FannieBorrowerFirstName { get; set; }
        public string FannieBorrowerMiddleName { get; set; }
        public string FannieBuydownContributer { get; set; }
        public JsonNullable<int?> FannieCLTV { get; set; }
        public string FannieCoBorrowerFirstName { get; set; }
        public string FannieCoBorrowerMiddleName { get; set; }
        public string FannieCreditScoreProviderName { get; set; }
        public string FannieFloodSpecialFeatureCode { get; set; }
        public JsonNullable<int?> FannieHCLTV { get; set; }
        public JsonNullable<int?> FannieInvestorOwnershipPercent { get; set; }
        public string FannieLegalEntityType { get; set; }
        public string FannieLegalEntityTypeOther { get; set; }
        public JsonNullable<decimal?> FannieLenderPaidMIInterestRateAdjustmentPercent { get; set; }
        public string FannieLoanProgramIdentifier { get; set; }
        public JsonNullable<int?> FannieLTV { get; set; }
        public string FannieMICompanyNameTypeOther { get; set; }
        public JsonNullable<int?> FannieMICoveragePercent { get; set; }
        public JsonNullable<int?> FanniePoolOwnershipPercent { get; set; }
        public string FannieProjectClassificationType { get; set; }
        public string FanniePropertyFormType { get; set; }
        public JsonNullable<decimal?> FannieRateSpread { get; set; }
        public string FannieRefinanceType { get; set; }
        public string FannieRelatedInvestorLoanID { get; set; }
        public string FannieRelatedLoanAmortizationType { get; set; }
        public string FannieRelatedLoanLienPosition { get; set; }
        public string FannieRelatedLoanType { get; set; }
        public string FannieSectionOfAct { get; set; }
        public JsonNullable<int?> FannieTLTV { get; set; }
        public string FannieTrustName { get; set; }
        public string FannnieMortgageType { get; set; }
        public JsonNullable<int?> FinancedUnitCount { get; set; }
        public JsonNullable<DateTime?> FirstRateChangePaymentEffectiveDate { get; set; }
        public string FNMHomeImprovementProductType { get; set; }
        public string FreddieARMIndexType { get; set; }
        public string FreddieAutoUWDec { get; set; }
        public string FreddieAVMModelNameTypeExpl { get; set; }
        public string FreddieBorrowerAlienStatus { get; set; }
        public string FreddieCoBorrowerAlienStatus { get; set; }
        public string FreddieCreditScoreProviderName { get; set; }
        public string FreddieDownPaymentType { get; set; }
        public string FreddieDownPmt2SourceType { get; set; }
        public string FreddieDownPmt2SourceTypeExpl { get; set; }
        public string FreddieDownPmt2Type { get; set; }
        public string FreddieDownPmt2TypeExpl { get; set; }
        public decimal? FreddieDownPmt3Amt { get; set; }
        public string FreddieDownPmt3SourceType { get; set; }
        public string FreddieDownPmt3SourceTypeExpl { get; set; }
        public string FreddieDownPmt3Type { get; set; }
        public string FreddieDownPmt3TypeExpl { get; set; }
        public decimal? FreddieDownPmt4Amt { get; set; }
        public string FreddieDownPmt4SourceType { get; set; }
        public string FreddieDownPmt4SourceTypeExpl { get; set; }
        public string FreddieDownPmt4Type { get; set; }
        public string FreddieDownPmt4TypeExpl { get; set; }
        public string FreddieExplanationOfDownPayment { get; set; }
        public string FreddieInvestorCollateralProgramIdentifier { get; set; }
        public string FreddieInvestorFeatureIdentifier { get; set; }
        public string FreddieLegalEntityType { get; set; }
        public string FreddieLegalEntityTypeOther { get; set; }
        public string FreddieLoanProgramIdentifier { get; set; }
        public string FreddieLoanTypePublicAndIndianHousingIndicator { get; set; }
        public string FreddieMICompanyNameTypeOther { get; set; }
        public string FreddieMortgageType { get; set; }
        public string FreddieProjectClassificationType { get; set; }
        public string FreddiePropertyFormType { get; set; }
        public string FreddieRefinanceCashOutDeterminationType { get; set; }
        public string FreddieRefinanceType { get; set; }
        public JsonNullable<bool?> FreddieRelatedClosedEndSecondIndicator { get; set; }
        public string FreddieRelatedInvestorLoanID { get; set; }
        public string FreddieRelatedLoanInvestorType { get; set; }
        public string FreddieRelatedLoanLienPosition { get; set; }
        public string FreddieRelatedLoanType { get; set; }
        public string FreddieSectionOfAct { get; set; }
        public string FreddieUnderwritingTypeOther { get; set; }
        public string GinnieConstructionMethodType { get; set; }
        public JsonNullable<decimal?> GinnieGovernmentAnnualPremiumAmount { get; set; }
        public string GinnieMortgageType { get; set; }
        public string GinnieOtherConstructionMethodType { get; set; }
        public JsonNullable<decimal?> GovernmentAnnualPremiumPercent { get; set; }
        public string GovernmentRefinanceType { get; set; }
        public JsonNullable<decimal?> GovernmentUpfrontPremiumAmount { get; set; }
        public JsonNullable<decimal?> GovernmentUpfrontPremiumPercent { get; set; }
        public string GSEProjectType { get; set; }
        public JsonNullable<bool?> GuaranteeFeeAddOnIndicator { get; set; }
        public JsonNullable<decimal?> GuarantyFeeAfterAlternatePaymentMethodPercent { get; set; }
        public JsonNullable<decimal?> GuarantyFeePercent { get; set; }
        public JsonNullable<decimal?> GuarantyPercent { get; set; }
        public string Id { get; set; }
        public string IndexType { get; set; }
        public JsonNullable<int?> InitialFixedPeriodEffectiveMonthsCount { get; set; }
        public string InterestAccrualType { get; set; }
        public JsonNullable<int?> InterestAndPaymentAdjustmentIndexLeadDaysCount { get; set; }
        public string InterestCalculationBasisType { get; set; }
        public JsonNullable<int?> InterestCalculationEffectiveMonthsCount { get; set; }
        public string InterestCalculationType { get; set; }
        public string InvestorCollateralProgramIdentifier { get; set; }
        public string InvestorCommitmentIdentifier { get; set; }
        public string InvestorFeatureIdentifier { get; set; }
        public string InvestorFeatureIdPool { get; set; }
        public JsonNullable<decimal?> InvestorOwnershipPercent { get; set; }
        public string InvestorProductPlanIdentifier { get; set; }
        public JsonNullable<int?> InvestorRemittanceDay { get; set; }
        public string InvestorRemittanceType { get; set; }
        public string IssuerIdentifier { get; set; }
        public JsonNullable<DateTime?> LastPaidInstallmentDueDate { get; set; }
        public JsonNullable<DateTime?> LastPaymentReceivedDate { get; set; }
        public JsonNullable<DateTime?> LatestConversionEffectiveDate { get; set; }
        public JsonNullable<decimal?> LenderPaidMIInterestRateAdjustmentPercent { get; set; }
        public JsonNullable<DateTime?> LendersDeliveryDate { get; set; }
        public JsonNullable<decimal?> LoanAcquisitionScheduledUPBAmount { get; set; }
        public JsonNullable<int?> LoanAmortizationMaximumTermMonthsCount { get; set; }
        public JsonNullable<int?> LoanBuyupBuydownBasisPointNumber { get; set; }
        public string LoanBuyupBuydownType { get; set; }
        public string LoanDefaultLossPartyType { get; set; }
        public JsonNullable<bool?> LoanDeliveredThroughServicingReleasedProcessIndicator { get; set; }
        public string LoanIdentifierValueType { get; set; }
        public JsonNullable<DateTime?> LoanInterestAccrualStartDate { get; set; }
        public JsonNullable<bool?> LoanLevelCreditScoreSelectionMethodSellerSpecificIndicator { get; set; }
        public string LoanLevelCreditScoreSelectionMethodType { get; set; }
        public JsonNullable<int?> LoanLevelCreditScoreValue { get; set; }
        public JsonNullable<DateTime?> LoanModificationEffectiveDate { get; set; }
        public JsonNullable<DateTime?> LoanStateDate { get; set; }
        public string ManufacturedHomeWidthType { get; set; }
        public JsonNullable<bool?> MBSWeightedMarginIndicator { get; set; }
        public string MERSOriginalMortgageeOfRecordIndicator { get; set; }
        public string MICompanyNameType { get; set; }
        public string MIPremiumSourceType { get; set; }
        public JsonNullable<DateTime?> MonetaryEventAppliedDate { get; set; }
        public JsonNullable<decimal?> MonetaryEventGrossPrincipalAmount { get; set; }
        public string MonetaryEventType { get; set; }
        public JsonNullable<bool?> MortgageBackedSecurityIndicator { get; set; }
        public JsonNullable<bool?> MortgageModificationIndicator { get; set; }
        public string MortgageOriginator { get; set; }
        public string MortgageProgramType { get; set; }
        public JsonNullable<bool?> MultipleConcurrentlyClosingLienOnSubjectPropertyIndicator { get; set; }
        public JsonNullable<DateTime?> NextRateAdjustmentEffectiveDate { get; set; }
        public string NotePayToName { get; set; }
        public JsonNullable<int?> NumberOfUnitsSold { get; set; }
        public string OtherDownPaymentFundsType { get; set; }
        public JsonNullable<decimal?> OtherFundsCollectedAtClosingAmount { get; set; }
        public string OtherFundsCollectedAtClosingType { get; set; }
        public string PayeeID { get; set; }
        public JsonNullable<int?> PaymentBillingStatementLeadDaysCount { get; set; }
        public JsonNullable<decimal?> PerChangeMaximumDecreaseRatePercent { get; set; }
        public JsonNullable<decimal?> PerChangeMaximumIncreaseRatePercent { get; set; }
        public JsonNullable<decimal?> PerChangePrincipalAndInterestPaymentAdjustmentPercent { get; set; }
        public JsonNullable<DateTime?> PerChangeRateAdjustmentEffectiveDate { get; set; }
        public JsonNullable<int?> PerChangeRateAdjustmentFrequencyMonthsCount { get; set; }
        public string PoolAccrualRateStructureType { get; set; }
        public string PoolAmortizationType { get; set; }
        public JsonNullable<bool?> PoolAssumabilityIndicator { get; set; }
        public JsonNullable<bool?> PoolBalloonIndicator { get; set; }
        public JsonNullable<DateTime?> PoolCertificatePaymentDate { get; set; }
        public string PoolClassType { get; set; }
        public string PoolConcurrentTransferIndicator { get; set; }
        public JsonNullable<int?> PoolCurrentLoanCount { get; set; }
        public JsonNullable<decimal?> PoolCurrentPrincipalBalanceAmount { get; set; }
        public string PoolDocumentCustodianID { get; set; }
        public JsonNullable<decimal?> PoolFixedServicingFeePercent { get; set; }
        public string PoolIdentifier { get; set; }
        public string PoolingMethodType { get; set; }
        public JsonNullable<DateTime?> PoolInterestAdjustmentEffectiveDate { get; set; }
        public JsonNullable<int?> PoolInterestAdjustmentIndexLeadDaysCount { get; set; }
        public JsonNullable<int?> PoolInterestAndPaymentAdjustmentIndexLeadDaysCount { get; set; }
        public JsonNullable<bool?> PoolInterestOnlyIndicator { get; set; }
        public JsonNullable<decimal?> PoolInterestRateRoundingPercent { get; set; }
        public string PoolInterestRateRoundingType { get; set; }
        public string PoolInvestorProductPlanIdentifier { get; set; }
        public JsonNullable<DateTime?> PoolIssueDate { get; set; }
        public string PoolIssuerTransferee { get; set; }
        public JsonNullable<decimal?> PoolMarginRatePercent { get; set; }
        public JsonNullable<DateTime?> PoolMaturityDate { get; set; }
        public JsonNullable<int?> PoolMaturityPeriodCount { get; set; }
        public JsonNullable<decimal?> PoolMaximumAccrualRatePercent { get; set; }
        public JsonNullable<decimal?> PoolMinimumAccrualRatePercent { get; set; }
        public string PoolMortgageType { get; set; }
        public JsonNullable<int?> PoolScheduledRemittancePaymentDay { get; set; }
        public JsonNullable<decimal?> PoolSecurityIssueDateInterestRatePercent { get; set; }
        public string PoolSellerID { get; set; }
        public string PoolServicerID { get; set; }
        public string PoolStructureType { get; set; }
        public string PoolSuffixIdentifier { get; set; }
        public JsonNullable<DateTime?> PriceLockDatetime { get; set; }
        public string PrimaryMIAbsenceReasonType { get; set; }
        public string PrimaryMIAbsenceReasonTypeOtherDescription { get; set; }
        public string ProjectAttachmentType { get; set; }
        public string ProjectDesignType { get; set; }
        public JsonNullable<int?> ProjectUnitCount { get; set; }
        public JsonNullable<DateTime?> PropertyValuationEffectiveDate { get; set; }
        public string PropertyValuationMethodType { get; set; }
        public JsonNullable<decimal?> RefinanceCashOutAmount { get; set; }
        public string RefinanceCashOutDeterminationType { get; set; }
        public JsonNullable<bool?> RelatedLoanBalloonIndicator { get; set; }
        public JsonNullable<bool?> RelatedLoanHELOCIndicator { get; set; }
        public JsonNullable<bool?> RelatedLoanIndicator { get; set; }
        public string RelatedLoanInvestorType { get; set; }
        public JsonNullable<int?> RelatedLoanMaturityPeriodCount { get; set; }
        public JsonNullable<DateTime?> RelatedLoanNoteDate { get; set; }
        public JsonNullable<DateTime?> RelatedLoanScheduledFirstPaymentDate { get; set; }
        public JsonNullable<DateTime?> RelatedLoanStateDateAtClosing { get; set; }
        public JsonNullable<decimal?> RelatedLoanUnpaidPrincipalBalanceAmount { get; set; }
        public JsonNullable<bool?> RelocationLoanIndicator { get; set; }
        public string REOMarketingPartyType { get; set; }
        public JsonNullable<bool?> SecondLienIsDeliveredIndicator { get; set; }
        public JsonNullable<decimal?> SecurityOriginalSubscriptionAmount { get; set; }
        public JsonNullable<DateTime?> SecurityTradeBookEntryDate { get; set; }
        public string SellerID { get; set; }
        public string SellerLoanIdentifier { get; set; }
        public string ServicerID { get; set; }
        public string ServicerLoanIdentifier { get; set; }
        public JsonNullable<bool?> SharedEquityIndicator { get; set; }
        public JsonNullable<bool?> SiteBuiltIndicator { get; set; }
        public JsonNullable<bool?> SpecialFloodHazardAreaIndicator { get; set; }
        public JsonNullable<decimal?> SubsequentPerChangeMaximumDecreaseRatePercent { get; set; }
        public JsonNullable<decimal?> SubsequentPerChangeMaximumIncreaseRatePercent { get; set; }
        public JsonNullable<DateTime?> SubsequentPerChangeRateAdjustmentEffectiveDate { get; set; }
        public JsonNullable<int?> SubsequentPerChangeRateAdjustmentFrequencyMonthsCount { get; set; }
        public JsonNullable<bool?> TemporaryBuydownIndicator { get; set; }
        public JsonNullable<int?> TotalMortgagedPropertiesCount { get; set; }
        public JsonNullable<decimal?> Unit1SubjectPropertyGrossRentalIncome { get; set; }
        public JsonNullable<int?> Unit1TotalBedrooms { get; set; }
        public JsonNullable<decimal?> Unit2SubjectPropertyGrossRentalIncome { get; set; }
        public JsonNullable<int?> Unit2TotalBedrooms { get; set; }
        public JsonNullable<decimal?> Unit3SubjectPropertyGrossRentalIncome { get; set; }
        public JsonNullable<int?> Unit3TotalBedrooms { get; set; }
        public JsonNullable<decimal?> Unit4SubjectPropertyGrossRentalIncome { get; set; }
        public JsonNullable<int?> Unit4TotalBedrooms { get; set; }
        public JsonNullable<decimal?> UPBAmount { get; set; }
    }
}