using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class Usda
    {
        public JsonNullable<decimal?> AdditionalIncomeFromPrimaryEmployment { get; set; }
        public JsonNullable<decimal?> AdditionalMemberBaseIncome { get; set; }
        public JsonNullable<decimal?> AdjustedAnnualIncome { get; set; }
        public string AdjustedIncomeCalculationDescription1 { get; set; }
        public string AdjustedIncomeCalculationDescription2 { get; set; }
        public string AdjustedIncomeCalculationDescription3 { get; set; }
        public JsonNullable<decimal?> AdvanceAmountToDate { get; set; }
        public JsonNullable<decimal?> AmountLoanlineCredit { get; set; }
        public JsonNullable<decimal?> AnnualChildCareExpenses { get; set; }
        public JsonNullable<decimal?> AnnualIncome { get; set; }
        public string AnnualIncomeCalculationDescription1 { get; set; }
        public string AnnualIncomeCalculationDescription2 { get; set; }
        public string AnnualIncomeCalculationDescription3 { get; set; }
        public string AnnualIncomeCalculationDescription4 { get; set; }
        public string AnnualIncomeCalculationDescription5 { get; set; }
        public JsonNullable<DateTime?> AnnualReviewDate { get; set; }
        public string ApplicationNumber { get; set; }
        public string ApprovedLenderTaxId { get; set; }
        public JsonNullable<decimal?> AssetIncome { get; set; }
        public JsonNullable<decimal?> BalanceOwedOnLoan { get; set; }
        public JsonNullable<decimal?> BorrowerBaseIncome { get; set; }
        public JsonNullable<decimal?> BorrowerTotalStableIncome { get; set; }
        public string BorrowerTypeCode { get; set; }
        public JsonNullable<decimal?> BuydownInterestAssistanceRate { get; set; }
        public string CaseNumberBorrowerId { get; set; }
        public string CaseNumberCo { get; set; }
        public string CaseNumberSt { get; set; }
        public JsonNullable<DateTime?> CertificationEffectiveDate { get; set; }
        public JsonNullable<DateTime?> CertificationExpirationDate { get; set; }
        public JsonNullable<bool?> CertifiedLoanIndicator { get; set; }
        public string ChildCareProviderAddress { get; set; }
        public string ChildCareProviderCity { get; set; }
        public string ChildCareProviderPhone { get; set; }
        public string ChildCareProviderProviderName { get; set; }
        public string ChildCareProviderState { get; set; }
        public string ChildCareProviderZip { get; set; }
        public JsonNullable<decimal?> ChildCostPerMonth { get; set; }
        public JsonNullable<decimal?> ChildCostPerWeek { get; set; }
        public JsonNullable<decimal?> CoborrowerBaseIncome { get; set; }
        public JsonNullable<decimal?> CoborrowerStableBaseIncome { get; set; }
        public string CoborrowerStableBaseIncomeDesc { get; set; }
        public JsonNullable<decimal?> CoborrowerStableOtherIncome { get; set; }
        public string CoborrowerStableOtherIncomeDesc { get; set; }
        public JsonNullable<decimal?> CoBorrowerTotalStableIncome { get; set; }
        public JsonNullable<DateTime?> DateConfirmedObligationProcessed { get; set; }
        public JsonNullable<DateTime?> DateLoanNoteGuaranteeIssued { get; set; }
        public JsonNullable<DateTime?> DateLoanNoteGuaranteeRequestReceived { get; set; }
        public JsonNullable<DateTime?> DateObligationInGls { get; set; }
        public JsonNullable<DateTime?> DateVerifiedInUnifi { get; set; }
        public JsonNullable<decimal?> DependentDeduction { get; set; }
        public JsonNullable<decimal?> DisabilityDeduction { get; set; }
        public JsonNullable<decimal?> ElderlyHouseholdDeduction { get; set; }
        public JsonNullable<decimal?> FeeRate { get; set; }
        public string FinancedLoanClosingCostDescription { get; set; }
        public JsonNullable<decimal?> GuaranteeFeeCollected { get; set; }
        public JsonNullable<decimal?> GuaranteeFeeOnCommitment { get; set; }
        public string GuaranteeFeePurposeCodeType { get; set; }
        public JsonNullable<DateTime?> GuaranteePeriodBeginsDate { get; set; }
        public JsonNullable<DateTime?> GuaranteePeriodEndsDate { get; set; }
        public string GuaranteeType { get; set; }
        public JsonNullable<int?> HouseholdSize { get; set; }
        public string Id { get; set; }
        public string InterestAssistanceCodeType { get; set; }
        public JsonNullable<bool?> InterestRateBasedonFannieIndicator { get; set; }
        public string InterestRateCodeType { get; set; }
        public JsonNullable<bool?> InterestRateFloatToLoanClosingIndicator { get; set; }
        public JsonNullable<bool?> LackAdequateHeatIndicator { get; set; }
        public string LenderAuthorizedRepCompany { get; set; }
        public string LenderAuthorizedRepName { get; set; }
        public string LenderAuthorizedRepTitle { get; set; }
        public string LenderIdNo { get; set; }
        public JsonNullable<decimal?> LenderNoteRateOnGuaranteedPortion { get; set; }
        public JsonNullable<decimal?> LenderNoteRateOnNonGuaranteedPortion { get; set; }
        public string LenderStatusCodeType { get; set; }
        public string LenderTypeCode { get; set; }
        public string LoanType { get; set; }
        public JsonNullable<bool?> LockCompletePlumbingIndicator { get; set; }
        public JsonNullable<decimal?> MedicalExpenses { get; set; }
        public JsonNullable<decimal?> ModerateIncomeLimit { get; set; }
        public JsonNullable<decimal?> MonthlyRepaymentIncome { get; set; }
        public JsonNullable<int?> NumberofDependents { get; set; }
        public JsonNullable<int?> NumberofPeopleInHousehold { get; set; }
        public JsonNullable<bool?> ObligationMatchesCommitmentLenderRequestIndicator { get; set; }
        public string OfficialWhoConfirmedGlsUpdated { get; set; }
        public JsonNullable<decimal?> OtherIncome { get; set; }
        public JsonNullable<decimal?> OtherStableDependableMonthlyIncome { get; set; }
        public JsonNullable<bool?> OvercrowdedIndicator { get; set; }
        public JsonNullable<decimal?> PercentofLoanGuaranteed { get; set; }
        public string PeriodOperatingLineCreditYearsType { get; set; }
        public JsonNullable<bool?> PhysicallyDeterioratedIndicator { get; set; }
        public string PreparedByName { get; set; }
        public string PreparedByTitle { get; set; }
        public string PresentLandloardAddress { get; set; }
        public string PresentLandloardCity { get; set; }
        public string PresentLandloardName { get; set; }
        public string PresentLandloardPhone { get; set; }
        public string PresentLandloardState { get; set; }
        public string PresentLandloardZip { get; set; }
        public string PreviousLandloardAddress { get; set; }
        public string PreviousLandloardCity { get; set; }
        public string PreviousLandloardName { get; set; }
        public string PreviousLandloardPhone { get; set; }
        public string PreviousLandloardState { get; set; }
        public string PreviousLandloardZip { get; set; }
        public JsonNullable<decimal?> PurchaseOrRefinancedAmount { get; set; }
        public string PurchaseOrRefinanceDescription { get; set; }
        public string RdsfhRefinancedLoanIndicatorType { get; set; }
        public JsonNullable<bool?> RefinanceLoanIndicator { get; set; }
        public JsonNullable<decimal?> RepairOtherAmount { get; set; }
        public string RepairOtherDescription { get; set; }
        public JsonNullable<decimal?> ReservationAmountRequested { get; set; }
        public string Reserved { get; set; }
        public string ServicingOfficeName { get; set; }
        public JsonNullable<bool?> SfhglpIndicator { get; set; }
        public string SourceOfFundsType { get; set; }
        public JsonNullable<decimal?> StableDependableMonthlyIncome { get; set; }
        public string StableOtherIncomeDesc { get; set; }
        public string SubmittingLenderAddress { get; set; }
        public string SubmittingLenderCity { get; set; }
        public string SubmittingLenderContactFax { get; set; }
        public string SubmittingLenderContactName { get; set; }
        public string SubmittingLenderContactPhone { get; set; }
        public string SubmittingLenderName { get; set; }
        public string SubmittingLenderState { get; set; }
        public string SubmittingLenderTaxId { get; set; }
        public string SubmittingLenderZip { get; set; }
        public JsonNullable<int?> TermOfBuydown { get; set; }
        public string ThirdPartyOriginator { get; set; }
        public string Title { get; set; }
        public JsonNullable<decimal?> TotalBorrowerStableBaseIncome { get; set; }
        public JsonNullable<decimal?> TotalBorrowerStableOtherIncome { get; set; }
        public JsonNullable<decimal?> TotalHouseholdDeduction { get; set; }
        public JsonNullable<decimal?> TotalRequestAmount { get; set; }
        public string TpoTaxId { get; set; }
        public string UnderwritingDecisionBy { get; set; }
        public JsonNullable<DateTime?> UnderwritingDecisionDate { get; set; }
        public string UnderwritingDecisionType { get; set; }
        public JsonNullable<List<UsdaHouseholdIncome>> UsdaHouseholdIncomes { get; set; }
        public string VerificationCode { get; set; }
    }
}