using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class VaLoanData
    {
        public bool? RangeOvenIndicator { get; set; }
        public bool? RefrigeratorIndicator { get; set; }
        public bool? DishwasherIndicator { get; set; }
        public bool? ClothesWasherIndicator { get; set; }
        public bool? DryerIndicator { get; set; }
        public bool? GarbageDisposalIndicator { get; set; }
        public bool? VentFanIndicator { get; set; }
        public bool? WWCarpetIndicator { get; set; }
        public string EquipmentOtherDescription { get; set; }
        public bool? NoEnergyImprovements { get; set; }
        public bool? SolarHeatingOrCooling { get; set; }
        public bool? ReplacementOfSystem { get; set; }
        public bool? EnergyImprovementsAdditionOfFeature { get; set; }
        public bool? Insulation { get; set; }
        public bool? OtherImprovements { get; set; }
        public DateTime? DateOfAssignment { get; set; }
        public decimal? Acres { get; set; }
        public string BuildingType { get; set; }
        public string NumberOfBuildings { get; set; }
        public string AvailableForInspectionDateAndTime { get; set; }
        public string KeysAtAddress { get; set; }
        public bool? AvailableForInspectionAMIndicator { get; set; }
        public string StreetAccess { get; set; }
        public string StreetMaintenance { get; set; }
        public bool? ConstructionWarrantyIncluded { get; set; }
        public string NameOfWarrantyProgram { get; set; }
        public DateTime? WarrantyProgramExpirationDate { get; set; }
        public DateTime? ConstructionCompletedDate { get; set; }
        public string NameOfOwner { get; set; }
        public string PropertyOccupancyType { get; set; }
        public string Rent { get; set; }
        public string NameOfOccupant { get; set; }
        public string OccupantTelephone { get; set; }
        public string PropertyLegalDescription1 { get; set; }
        public string PropertyLegalDescription2 { get; set; }
        public string PropertyLegalDescription3 { get; set; }
        public string PropertyLegalDescription4 { get; set; }
        public string TitleLimitations1 { get; set; }
        public string TitleLimitations2 { get; set; }
        public string TitleLimitations3 { get; set; }
        public string LoanProcedure { get; set; }
        public string MilitaryBranchOfService { get; set; }
        public string VeteranServiceType { get; set; }
        public string PurposeOfLoan { get; set; }
        public string TypeOfOwnsership { get; set; }
        public string LoanCode { get; set; }
        public string TypeOfMortgage { get; set; }
        public decimal? AmountSpentOnEnergyImprovements { get; set; }
        public string AppraisalType { get; set; }
        public string ManufacturedHome { get; set; }
        public string TypeOfStructure { get; set; }
        public string PropertyDesignation { get; set; }
        public string MCRVNumber { get; set; }
        public bool? FundingFeeExempt { get; set; }
        public string InspectionWillBeMadeBy { get; set; }
        public string ConstructionPlan { get; set; }
        public string PlansSubmitted { get; set; }
        public string WarrantorName { get; set; }
        public string WarrantorAddress { get; set; }
        public string WarrantorPhone { get; set; }
        public string SpecialAssessmentComments1 { get; set; }
        public string SpecialAssessmentComments2 { get; set; }
        public string SpecialAssessmentComments3 { get; set; }
        public decimal? AnnualRealEstateTaxes { get; set; }
        public string MineralRightsReserved { get; set; }
        public string LeaseholdType { get; set; }
        public decimal? AnnualGroundRent { get; set; }
        public bool? ProposedSaleContractAttached { get; set; }
        public string ContractNoApprovedByVA { get; set; }
        public string LotDimensions { get; set; }
        public int? IrregularLotSizeInSquareFeet { get; set; }
        public string UtilitiesElectricDescription { get; set; }
        public string UtilitiesGasDescription { get; set; }
        public string UtilitiesWaterDescription { get; set; }
        public string UtilitiesSewerDescription { get; set; }
        public string InsuranceType { get; set; }
        public decimal? AnnualMaintenanceAssessment { get; set; }
        public bool? BuyerPurchasingLotSeparately { get; set; }
        public string WarrantorCity { get; set; }
        public string WarrantorState { get; set; }
        public string WarrantorPostalCode { get; set; }
        public string Title { get; set; }
        public List<MilitaryService> MilitaryServices { get; set; }
        public DateTime? ApplicantBirthDate { get; set; }
        public bool? VeteranDischargedIndicator { get; set; }
        public string VAClaimNumber { get; set; }
        public List<PreviousVaLoan> PreviousVaLoans { get; set; }
        public string MailingAddress { get; set; }
        public string MailingCity { get; set; }
        public string MailingState { get; set; }
        public string MailingPostalCode { get; set; }
        public string VaLoanSummaryApplicantType { get; set; }
        public string ApplicantFirstNameWithMiddleName { get; set; }
        public string ApplicantLastNameWithSuffix { get; set; }
        public string ApplicantTaxIdentificationIdentifier { get; set; }
        public string ApplicantAddressStreetLine1 { get; set; }
        public string ApplicantAddressCity { get; set; }
        public string ApplicantAddressState { get; set; }
        public string ApplicantAddressPostalCode { get; set; }
        public string ApplicantEmailAddressText { get; set; }
        public bool? PreviousVALoanIndicator { get; set; }
        public string LoanAnalysisRemarks1 { get; set; }
        public string LoanAnalysisRemarks2 { get; set; }
        public string LoanAnalysisRemarks3 { get; set; }
        public string LoanAnalysisRemarks4 { get; set; }
        public string LoanAnalysisRemarks5 { get; set; }
        public string LoanAnalysisRemarks6 { get; set; }
        public string LoanAnalysisRemarks7 { get; set; }
        public string LoanAnalysisRemarks8 { get; set; }
        public string LoanAnalysisRemarks9 { get; set; }
        public bool? PayoffIndicator1 { get; set; }
        public bool? PayoffIndicator2 { get; set; }
        public bool? PayoffIndicator3 { get; set; }
        public bool? PayoffIndicator4 { get; set; }
        public bool? PayoffIndicator5 { get; set; }
        public bool? PayoffIndicator6 { get; set; }
        public bool? PayoffIndicator7 { get; set; }
        public bool? PayoffIndicator8 { get; set; }
        public bool? PayoffIndicator9 { get; set; }
        public decimal? TotalDebtMonthlyPayment { get; set; }
        public decimal? NegativeRents { get; set; }
        public decimal? CashPaymentFromVeteran { get; set; }
        public decimal? FinalFundingFeeAmount { get; set; }
        public decimal? TotalForMaxLoanAmount { get; set; }
        public decimal? InitialTotal { get; set; }
        public decimal? PreliminaryDiscountAmount { get; set; }
        public decimal? OriginationFeeAmount { get; set; }
        public decimal? PreliminaryFundingFeeAmount { get; set; }
        public decimal? OtherClosingCosts { get; set; }
        public decimal? PreliminaryTotal { get; set; }
        public decimal? FinalDiscountAmount { get; set; }
        public decimal? DiscountPercentage { get; set; }
        public int? TotalRooms { get; set; }
        public decimal? TotalBaths { get; set; }
        public int? TotalBedrooms { get; set; }
        public bool? OriginalValueEstimateChanged { get; set; }
        public string PaidInFullVALoanNumber { get; set; }
        public decimal? OriginalLoanAmount { get; set; }
        public decimal? OriginalInterestRate { get; set; }
        public string SystemUsed { get; set; }
        public int? OriginalTerm { get; set; }
        public decimal? VAOriginalMonthlyPayment { get; set; }
        public string VAOriginalAmortizationType { get; set; }
        public decimal? VARecoupmentMonthlyDecreaseInPayment { get; set; }
        public decimal? VARecoupmentTotalClosingCosts { get; set; }
        public bool? VARecoupmentExcludePrepaids { get; set; }
        public int? VARecoupmentClosingCosts { get; set; }
        public int? VARecoupmentYears { get; set; }
        public int? VARecoupmentMonths { get; set; }
        public bool? VALatePaymentIn6Months { get; set; }
        public string EntitlementCode { get; set; }
        public string RiskClasification { get; set; }
        public int? CreditScore { get; set; }
        public string TypeOfHybridARM { get; set; }
        public string ApplicantHmdaGenderType { get; set; }
        public bool? VAIsDelinquent30Days { get; set; }
        public string LoanSummaryRemarks1 { get; set; }
        public string LoanSummaryRemarks2 { get; set; }
        public string LoanSummaryRemarks3 { get; set; }
        public bool? LoanProcessedUnderAU { get; set; }
        public string LoanSummaryRemarks4 { get; set; }
        public string LoanSummaryRemarks5 { get; set; }
        public string LoanSummaryRemarks6 { get; set; }
        public string LoanSummaryRemarks7 { get; set; }
        public string LoanSummaryRemarks8 { get; set; }
        public decimal? TotalDiscountPointCharged { get; set; }
        public decimal? BorrowerPaidDiscountPointsTotalAmount { get; set; }
        public decimal? TotalDiscountPointsCharged { get; set; }
        public decimal? DiscountPoint { get; set; }
        public bool? FirstTimeUse { get; set; }
        public string LenderSAR { get; set; }
        public int? PropertyGrossLivingArea { get; set; }
        public int? AgeOfProperty { get; set; }
        public DateTime? DateSAR { get; set; }
        public string AdministratorName { get; set; }
        public string AdministratorContact { get; set; }
        public string AdministratorAddress { get; set; }
        public string AdministratorCity { get; set; }
        public string AdministratorState { get; set; }
        public string AdministratorPostalCode { get; set; }
        public string VAClaimFolderNumber { get; set; }
        public string ServiceNumber { get; set; }
        public bool? CurrentlyOnMilitaryDuty { get; set; }
        public bool? OnMilitaryDutyFollowingSeparation { get; set; }
        public string VABenefitRelatedIndebtedness { get; set; }
        public string ClaimDisabilityBenefits { get; set; }
        public string TypeOfVeteran { get; set; }
        public string PriorLoanType { get; set; }
        public bool? AutomaticProcedure { get; set; }
        public bool? PriorApprovalProcedure { get; set; }
        public bool? FirstChattelLoanType { get; set; }
        public bool? UnsecuredLoanType { get; set; }
        public bool? OtherLoanType { get; set; }
        public string OtherDescriptionLoanType { get; set; }
        public bool? OtherEstateProperty { get; set; }
        public string OtherDescriptionEstateProperty { get; set; }
        public decimal? AnnualSpecialAssessment { get; set; }
        public decimal? TotalUnpaidSpecialAssessments { get; set; }
        public string NonrealtyDescription { get; set; }
        public string AdditionalSecurityDescription { get; set; }
        public DateTime? DateAquiredLand { get; set; }
        public decimal? LandPurchasePrice { get; set; }
        public string AmountTypeWithheld { get; set; }
        public decimal? AmountWithheld { get; set; }
        public bool? ReasonableValueCompleted { get; set; }
        public decimal? DisabilityAmountCollected { get; set; }
        public decimal? PestReportFee { get; set; }
        public string VATrackingSARName { get; set; }
        public string VATrackingSARID { get; set; }
        public bool? VATrackingIsSARLAPPCertified { get; set; }
        public DateTime? VAAppraisalSentDate { get; set; }
        public DateTime? VANOVDateReceived { get; set; }
        public DateTime? VANOVDateReviewed { get; set; }
        public DateTime? VANOVIssuedDate { get; set; }
        public DateTime? VADateNOVAppraisalMailedToBorrower { get; set; }
        public DateTime? VATrackingOrderedDate { get; set; }
        public DateTime? VATrackingCOEIssueDate { get; set; }
        public string VATrackingCOEIssueHistory { get; set; }
        public DateTime? VATrackingPaidDate { get; set; }
        public bool? VATrackingReceiptReceived { get; set; }
        public DateTime? VATrackingLoanGuaranteeCertReceipt { get; set; }
        public bool? VATrackingGSAExclusionaryListChecked { get; set; }
        public DateTime? VATrackingCertOfCommitmentIssued { get; set; }
        public DateTime? VATrackingMasterCommitmentLockExpired { get; set; }
        public DateTime? VATrackingFinalApprovalCommitmentDate { get; set; }
        public DateTime? VATrackingPurchaseContractDate { get; set; }
        public bool? VATrackingInuranceFloodPolicy { get; set; }
        public bool? VATrackingInuranceHazardPolicy { get; set; }
        public bool? VATrackingInuranceWoodDestroyingPolicy { get; set; }
        public bool? VATrackingInuranceWindOrHailPolicy { get; set; }
        public string VAQualificationCountryRegion { get; set; }
        public string VAQualification2ndTierEntitlement { get; set; }
        public decimal? VAQualificationCountyLimits { get; set; }
        public decimal? TotalMonthlyPayment { get; set; }
        public decimal? TotalProposedMonthlyPayment { get; set; }
        public bool? ExcludeTaxesInsuranceIndicator { get; set; }
        public string EmailToBeNotifiedWhenUploaded { get; set; }
        public string VABuilderIDNo { get; set; }
        public string POCName { get; set; }
        public string POCAddress { get; set; }
        public string POCCity { get; set; }
        public string POCState { get; set; }
        public string POCZipCode { get; set; }
        public string POCPhone { get; set; }
        public string VABuilderDescription { get; set; }
        public string Id { get; set; }
        public bool? IsDelinquent30Days { get; set; }
        public string ApplicantHomePhoneNumber { get; set; }
    }
}