using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed partial class VaLoanData
    {
        public JsonNullable<decimal?> Acres { get; set; }
        public string AdditionalSecurityDescription { get; set; }
        public string AdministratorAddress { get; set; }
        public string AdministratorCity { get; set; }
        public string AdministratorContact { get; set; }
        public string AdministratorName { get; set; }
        public string AdministratorPostalCode { get; set; }
        public string AdministratorState { get; set; }
        public JsonNullable<int?> AgeOfProperty { get; set; }
        public JsonNullable<decimal?> AmountSpentOnEnergyImprovements { get; set; }
        public string AmountTypeWithheld { get; set; }
        public JsonNullable<decimal?> AmountWithheld { get; set; }
        public JsonNullable<decimal?> AnnualGroundRent { get; set; }
        public JsonNullable<decimal?> AnnualMaintenanceAssessment { get; set; }
        public JsonNullable<decimal?> AnnualRealEstateTaxes { get; set; }
        public JsonNullable<decimal?> AnnualSpecialAssessment { get; set; }
        public string ApplicantAddressCity { get; set; }
        public string ApplicantAddressPostalCode { get; set; }
        public string ApplicantAddressState { get; set; }
        public string ApplicantAddressStreetLine1 { get; set; }
        public JsonNullable<DateTime?> ApplicantBirthDate { get; set; }
        public string ApplicantEmailAddressText { get; set; }
        public string ApplicantFirstNameWithMiddleName { get; set; }
        public string ApplicantHmdaGenderType { get; set; }
        public string ApplicantHomePhoneNumber { get; set; }
        public string ApplicantLastNameWithSuffix { get; set; }
        public string ApplicantTaxIdentificationIdentifier { get; set; }
        public string AppraisalType { get; set; }
        public JsonNullable<bool?> AutomaticProcedure { get; set; }
        public JsonNullable<bool?> AvailableForInspectionAMIndicator { get; set; }
        public string AvailableForInspectionDateAndTime { get; set; }
        public JsonNullable<decimal?> BorrowerPaidDiscountPointsTotalAmount { get; set; }
        public string BuildingType { get; set; }
        public JsonNullable<bool?> BuyerPurchasingLotSeparately { get; set; }
        public JsonNullable<decimal?> CashPaymentFromVeteran { get; set; }
        public string ClaimDisabilityBenefits { get; set; }
        public JsonNullable<bool?> ClothesWasherIndicator { get; set; }
        public JsonNullable<DateTime?> ConstructionCompletedDate { get; set; }
        public string ConstructionPlan { get; set; }
        public JsonNullable<bool?> ConstructionWarrantyIncluded { get; set; }
        public string ContractNoApprovedByVA { get; set; }
        public JsonNullable<int?> CreditScore { get; set; }
        public JsonNullable<bool?> CurrentlyOnMilitaryDuty { get; set; }
        public JsonNullable<DateTime?> DateAquiredLand { get; set; }
        public JsonNullable<DateTime?> DateOfAssignment { get; set; }
        public JsonNullable<DateTime?> DateSAR { get; set; }
        public JsonNullable<decimal?> DisabilityAmountCollected { get; set; }
        public JsonNullable<decimal?> DiscountPercentage { get; set; }
        public JsonNullable<decimal?> DiscountPoint { get; set; }
        public JsonNullable<bool?> DishwasherIndicator { get; set; }
        public JsonNullable<bool?> DryerIndicator { get; set; }
        public string EmailToBeNotifiedWhenUploaded { get; set; }
        public JsonNullable<bool?> EnergyImprovementsAdditionOfFeature { get; set; }
        public string EntitlementCode { get; set; }
        public string EquipmentOtherDescription { get; set; }
        public JsonNullable<bool?> ExcludeTaxesInsuranceIndicator { get; set; }
        public JsonNullable<decimal?> FinalDiscountAmount { get; set; }
        public JsonNullable<decimal?> FinalFundingFeeAmount { get; set; }
        public JsonNullable<bool?> FirstChattelLoanType { get; set; }
        public JsonNullable<bool?> FirstTimeUse { get; set; }
        public JsonNullable<bool?> FundingFeeExempt { get; set; }
        public JsonNullable<bool?> GarbageDisposalIndicator { get; set; }
        public string Id { get; set; }
        public JsonNullable<decimal?> InitialTotal { get; set; }
        public string InspectionWillBeMadeBy { get; set; }
        public JsonNullable<bool?> Insulation { get; set; }
        public string InsuranceType { get; set; }
        public JsonNullable<int?> IrregularLotSizeInSquareFeet { get; set; }
        public JsonNullable<bool?> IsDelinquent30Days { get; set; }
        public string KeysAtAddress { get; set; }
        public JsonNullable<decimal?> LandPurchasePrice { get; set; }
        public string LeaseholdType { get; set; }
        public string LenderSAR { get; set; }
        public string LoanAnalysisRemarks1 { get; set; }
        public string LoanAnalysisRemarks2 { get; set; }
        public string LoanAnalysisRemarks3 { get; set; }
        public string LoanAnalysisRemarks4 { get; set; }
        public string LoanAnalysisRemarks5 { get; set; }
        public string LoanAnalysisRemarks6 { get; set; }
        public string LoanAnalysisRemarks7 { get; set; }
        public string LoanAnalysisRemarks8 { get; set; }
        public string LoanAnalysisRemarks9 { get; set; }
        public string LoanCode { get; set; }
        public string LoanProcedure { get; set; }
        public JsonNullable<bool?> LoanProcessedUnderAU { get; set; }
        public string LoanSummaryRemarks1 { get; set; }
        public string LoanSummaryRemarks2 { get; set; }
        public string LoanSummaryRemarks3 { get; set; }
        public string LoanSummaryRemarks4 { get; set; }
        public string LoanSummaryRemarks5 { get; set; }
        public string LoanSummaryRemarks6 { get; set; }
        public string LoanSummaryRemarks7 { get; set; }
        public string LoanSummaryRemarks8 { get; set; }
        public string LotDimensions { get; set; }
        public string MailingAddress { get; set; }
        public string MailingCity { get; set; }
        public string MailingPostalCode { get; set; }
        public string MailingState { get; set; }
        public string ManufacturedHome { get; set; }
        public string MCRVNumber { get; set; }
        public string MilitaryBranchOfService { get; set; }
        public JsonNullable<List<MilitaryService>> MilitaryServices { get; set; }
        public string MineralRightsReserved { get; set; }
        public string NameOfOccupant { get; set; }
        public string NameOfOwner { get; set; }
        public string NameOfWarrantyProgram { get; set; }
        public JsonNullable<decimal?> NegativeRents { get; set; }
        public JsonNullable<bool?> NoEnergyImprovements { get; set; }
        public string NonrealtyDescription { get; set; }
        public string NumberOfBuildings { get; set; }
        public string OccupantTelephone { get; set; }
        public JsonNullable<bool?> OnMilitaryDutyFollowingSeparation { get; set; }
        public JsonNullable<decimal?> OriginalInterestRate { get; set; }
        public JsonNullable<decimal?> OriginalLoanAmount { get; set; }
        public JsonNullable<int?> OriginalTerm { get; set; }
        public JsonNullable<bool?> OriginalValueEstimateChanged { get; set; }
        public JsonNullable<decimal?> OriginationFeeAmount { get; set; }
        public JsonNullable<decimal?> OtherClosingCosts { get; set; }
        public string OtherDescriptionEstateProperty { get; set; }
        public string OtherDescriptionLoanType { get; set; }
        public JsonNullable<bool?> OtherEstateProperty { get; set; }
        public JsonNullable<bool?> OtherImprovements { get; set; }
        public JsonNullable<bool?> OtherLoanType { get; set; }
        public string PaidInFullVALoanNumber { get; set; }
        public JsonNullable<bool?> PayoffIndicator1 { get; set; }
        public JsonNullable<bool?> PayoffIndicator2 { get; set; }
        public JsonNullable<bool?> PayoffIndicator3 { get; set; }
        public JsonNullable<bool?> PayoffIndicator4 { get; set; }
        public JsonNullable<bool?> PayoffIndicator5 { get; set; }
        public JsonNullable<bool?> PayoffIndicator6 { get; set; }
        public JsonNullable<bool?> PayoffIndicator7 { get; set; }
        public JsonNullable<bool?> PayoffIndicator8 { get; set; }
        public JsonNullable<bool?> PayoffIndicator9 { get; set; }
        public JsonNullable<decimal?> PestReportFee { get; set; }
        public string PlansSubmitted { get; set; }
        public string POCAddress { get; set; }
        public string POCCity { get; set; }
        public string POCName { get; set; }
        public string POCPhone { get; set; }
        public string POCState { get; set; }
        public string POCZipCode { get; set; }
        public JsonNullable<decimal?> PreliminaryDiscountAmount { get; set; }
        public JsonNullable<decimal?> PreliminaryFundingFeeAmount { get; set; }
        public JsonNullable<decimal?> PreliminaryTotal { get; set; }
        public JsonNullable<bool?> PreviousVALoanIndicator { get; set; }
        public JsonNullable<List<PreviousVaLoan>> PreviousVaLoans { get; set; }
        public JsonNullable<bool?> PriorApprovalProcedure { get; set; }
        public string PriorLoanType { get; set; }
        public string PropertyDesignation { get; set; }
        public JsonNullable<int?> PropertyGrossLivingArea { get; set; }
        public string PropertyLegalDescription1 { get; set; }
        public string PropertyLegalDescription2 { get; set; }
        public string PropertyLegalDescription3 { get; set; }
        public string PropertyLegalDescription4 { get; set; }
        public string PropertyOccupancyType { get; set; }
        public JsonNullable<bool?> ProposedSaleContractAttached { get; set; }
        public string PurposeOfLoan { get; set; }
        public JsonNullable<bool?> RangeOvenIndicator { get; set; }
        public JsonNullable<bool?> ReasonableValueCompleted { get; set; }
        public JsonNullable<bool?> RefrigeratorIndicator { get; set; }
        public string Rent { get; set; }
        public JsonNullable<bool?> ReplacementOfSystem { get; set; }
        public string RiskClasification { get; set; }
        public string ServiceNumber { get; set; }
        public JsonNullable<bool?> SolarHeatingOrCooling { get; set; }
        public string SpecialAssessmentComments1 { get; set; }
        public string SpecialAssessmentComments2 { get; set; }
        public string SpecialAssessmentComments3 { get; set; }
        public string StreetAccess { get; set; }
        public string StreetMaintenance { get; set; }
        public string SystemUsed { get; set; }
        public string Title { get; set; }
        public string TitleLimitations1 { get; set; }
        public string TitleLimitations2 { get; set; }
        public string TitleLimitations3 { get; set; }
        public JsonNullable<decimal?> TotalBaths { get; set; }
        public JsonNullable<int?> TotalBedrooms { get; set; }
        public JsonNullable<decimal?> TotalDebtMonthlyPayment { get; set; }
        public JsonNullable<decimal?> TotalDiscountPointCharged { get; set; }
        public JsonNullable<decimal?> TotalDiscountPointsCharged { get; set; }
        public JsonNullable<decimal?> TotalForMaxLoanAmount { get; set; }
        public JsonNullable<decimal?> TotalMonthlyPayment { get; set; }
        public JsonNullable<decimal?> TotalProposedMonthlyPayment { get; set; }
        public JsonNullable<int?> TotalRooms { get; set; }
        public JsonNullable<decimal?> TotalUnpaidSpecialAssessments { get; set; }
        public string TypeOfHybridARM { get; set; }
        public string TypeOfMortgage { get; set; }
        public string TypeOfOwnsership { get; set; }
        public string TypeOfStructure { get; set; }
        public string TypeOfVeteran { get; set; }
        public JsonNullable<bool?> UnsecuredLoanType { get; set; }
        public string UtilitiesElectricDescription { get; set; }
        public string UtilitiesGasDescription { get; set; }
        public string UtilitiesSewerDescription { get; set; }
        public string UtilitiesWaterDescription { get; set; }
        public JsonNullable<DateTime?> VAAppraisalSentDate { get; set; }
        public string VABenefitRelatedIndebtedness { get; set; }
        public string VABuilderDescription { get; set; }
        public string VABuilderIDNo { get; set; }
        public string VAClaimFolderNumber { get; set; }
        public string VAClaimNumber { get; set; }
        public JsonNullable<DateTime?> VADateNOVAppraisalMailedToBorrower { get; set; }
        public JsonNullable<bool?> VAIsDelinquent30Days { get; set; }
        public JsonNullable<bool?> VALatePaymentIn6Months { get; set; }
        public string VaLoanSummaryApplicantType { get; set; }
        public JsonNullable<DateTime?> VANOVDateReceived { get; set; }
        public JsonNullable<DateTime?> VANOVDateReviewed { get; set; }
        public JsonNullable<DateTime?> VANOVIssuedDate { get; set; }
        public string VAOriginalAmortizationType { get; set; }
        public JsonNullable<decimal?> VAOriginalMonthlyPayment { get; set; }
        public string VAQualification2ndTierEntitlement { get; set; }
        public string VAQualificationCountryRegion { get; set; }
        public JsonNullable<decimal?> VAQualificationCountyLimits { get; set; }
        public JsonNullable<int?> VARecoupmentClosingCosts { get; set; }
        public JsonNullable<bool?> VARecoupmentExcludePrepaids { get; set; }
        public JsonNullable<decimal?> VARecoupmentMonthlyDecreaseInPayment { get; set; }
        public JsonNullable<int?> VARecoupmentMonths { get; set; }
        public JsonNullable<decimal?> VARecoupmentTotalClosingCosts { get; set; }
        public JsonNullable<int?> VARecoupmentYears { get; set; }
        public JsonNullable<DateTime?> VATrackingCertOfCommitmentIssued { get; set; }
        public JsonNullable<DateTime?> VATrackingCOEIssueDate { get; set; }
        public string VATrackingCOEIssueHistory { get; set; }
        public JsonNullable<DateTime?> VATrackingFinalApprovalCommitmentDate { get; set; }
        public JsonNullable<bool?> VATrackingGSAExclusionaryListChecked { get; set; }
        public JsonNullable<bool?> VATrackingInuranceFloodPolicy { get; set; }
        public JsonNullable<bool?> VATrackingInuranceHazardPolicy { get; set; }
        public JsonNullable<bool?> VATrackingInuranceWindOrHailPolicy { get; set; }
        public JsonNullable<bool?> VATrackingInuranceWoodDestroyingPolicy { get; set; }
        public JsonNullable<bool?> VATrackingIsSARLAPPCertified { get; set; }
        public JsonNullable<DateTime?> VATrackingLoanGuaranteeCertReceipt { get; set; }
        public JsonNullable<DateTime?> VATrackingMasterCommitmentLockExpired { get; set; }
        public JsonNullable<DateTime?> VATrackingOrderedDate { get; set; }
        public JsonNullable<DateTime?> VATrackingPaidDate { get; set; }
        public JsonNullable<DateTime?> VATrackingPurchaseContractDate { get; set; }
        public JsonNullable<bool?> VATrackingReceiptReceived { get; set; }
        public string VATrackingSARID { get; set; }
        public string VATrackingSARName { get; set; }
        public JsonNullable<bool?> VentFanIndicator { get; set; }
        public JsonNullable<bool?> VeteranDischargedIndicator { get; set; }
        public string VeteranServiceType { get; set; }
        public string WarrantorAddress { get; set; }
        public string WarrantorCity { get; set; }
        public string WarrantorName { get; set; }
        public string WarrantorPhone { get; set; }
        public string WarrantorPostalCode { get; set; }
        public string WarrantorState { get; set; }
        public JsonNullable<DateTime?> WarrantyProgramExpirationDate { get; set; }
        public JsonNullable<bool?> WWCarpetIndicator { get; set; }
    }
}