using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class ATRQMBorrower
    {
        public decimal? BorMonthlyEmplymentIncomeBaseIncome { get; set; }
        public decimal? BorMonthlyEmplymentIncomeOvertimeIncome { get; set; }
        public decimal? BorMonthlyEmplymentIncomeBonuseIncome { get; set; }
        public decimal? BorMonthlyEmplymentIncomeCommissionIncome { get; set; }
        public decimal? BorMonthlyEmplymentIncomeDividendInterestIncome { get; set; }
        public decimal? BorMonthlyEmplymentIncomeOtherIncome1 { get; set; }
        public decimal? BorMonthlyEmplymentIncomeOtherIncome2 { get; set; }
        public decimal? BorMonthlyEmplymentIncomeTotalEmploymentIncome { get; set; }
        public decimal? CobMonthlyEmplymentIncomeBaseIncome { get; set; }
        public decimal? CobMonthlyEmplymentIncomeOvertimeIncome { get; set; }
        public decimal? CobMonthlyEmplymentIncomeBonuseIncome { get; set; }
        public decimal? CobMonthlyEmplymentIncomeCommissionIncome { get; set; }
        public decimal? CobMonthlyEmplymentIncomeDividendInterestIncome { get; set; }
        public decimal? CobMonthlyEmplymentIncomeOtherIncome1 { get; set; }
        public decimal? CobMonthlyEmplymentIncomeOtherIncome2 { get; set; }
        public decimal? CobMonthlyEmplymentIncomeTotalEmploymentIncome { get; set; }
        public decimal? BorProjectedIncomeProjectedCostLivingAdjustment { get; set; }
        public decimal? BorProjectedIncomeProjectedPerformanceRaises { get; set; }
        public decimal? BorProjectedIncomeProjectedBonuses { get; set; }
        public decimal? BorProjectedIncomeProjectedNewJobIncome { get; set; }
        public decimal? CobProjectedIncomeProjectedCostLivingAdjustment { get; set; }
        public decimal? CobProjectedIncomeProjectedPerformanceRaises { get; set; }
        public decimal? CobProjectedIncomeProjectedBonuses { get; set; }
        public decimal? CobProjectedIncomeProjectedNewJobIncome { get; set; }
        public decimal? BorNonEmploymentIncomeMilitaryIncome { get; set; }
        public decimal? BorNonEmploymentIncomeVABenefitIncome { get; set; }
        public decimal? BorNonEmploymentIncomeGovtAssitProgramIncome { get; set; }
        public decimal? BorNonEmploymentIncomeMtgCreditCertificateIncome { get; set; }
        public decimal? BorNonEmploymentIncomeHomeownSubsidyIncome { get; set; }
        public decimal? CobNonEmploymentIncomeMilitaryIncome { get; set; }
        public decimal? CobNonEmploymentIncomeVABenefitIncome { get; set; }
        public decimal? CobNonEmploymentIncomeGovtAssitProgramIncome { get; set; }
        public decimal? CobNonEmploymentIncomeMtgCreditCertificateIncome { get; set; }
        public decimal? CobNonEmploymentIncomeHomeownSubsidyIncome { get; set; }
        public decimal? BorNonTaxableIncomeSocialSecurityIncome { get; set; }
        public decimal? BorNonTaxableIncomeFedGovtEmplRetirementIncome { get; set; }
        public decimal? BorNonTaxableIncomeRailroadRetirementBenefits { get; set; }
        public decimal? BorNonTaxableIncomeStateGovtEmplRetirementIncome { get; set; }
        public decimal? BorNonTaxableIncomeDisabilityIncome { get; set; }
        public decimal? BorNonTaxableIncomePublicAssistPayments { get; set; }
        public decimal? BorNonTaxableIncomeChildSupportIncome { get; set; }
        public decimal? BorNonTaxableIncomeMilitaryAllowances { get; set; }
        public decimal? BorNonTaxableIncomeOtherIncome { get; set; }
        public decimal? CobNonTaxableIncomeSocialSecurityIncome { get; set; }
        public decimal? CobNonTaxableIncomeFedGovtEmplRetirementIncome { get; set; }
        public decimal? CobNonTaxableIncomeRailroadRetirementBenefits { get; set; }
        public decimal? CobNonTaxableIncomeStateGovtEmplRetirementIncome { get; set; }
        public decimal? CobNonTaxableIncomeDisabilityIncome { get; set; }
        public decimal? CobNonTaxableIncomePublicAssistPayments { get; set; }
        public decimal? CobNonTaxableIncomeChildSupportIncome { get; set; }
        public decimal? CobNonTaxableIncomeMilitaryAllowances { get; set; }
        public decimal? CobNonTaxableIncomeOtherIncome { get; set; }
        public string BorContingentLiabilitiesLiabilityDescription1 { get; set; }
        public decimal? BorContingentLiabilitiesLiabilityAmount1 { get; set; }
        public string BorContingentLiabilitiesLiabilityDescription2 { get; set; }
        public decimal? BorContingentLiabilitiesLiabilityAmount2 { get; set; }
        public string BorContingentLiabilitiesLiabilityDescription3 { get; set; }
        public decimal? BorContingentLiabilitiesLiabilityAmount3 { get; set; }
        public decimal? BorContingentLiabilitiesTotalLiabilityAmount { get; set; }
        public decimal? BorCosignedObligationsCarLoanPayment { get; set; }
        public decimal? BorCosignedObligationsStudentLoanPayment { get; set; }
        public decimal? BorCosignedObligationsMortgagePayment { get; set; }
        public string BorCosignedObligationsOtherPaymentDescription { get; set; }
        public decimal? BorCosignedObligationsOtherPayment { get; set; }
        public decimal? BorCosignedObligationsTotalCoMortgagorLiabilities { get; set; }
        public int? BorOvertimeMostRecentMonths { get; set; }
        public decimal? BorOvertimeMostRecentAmount { get; set; }
        public decimal? CobOvertimeMostRecentAmount { get; set; }
        public int? BorOvertimePreviousYear1 { get; set; }
        public int? BorOvertimePreviousMonths1 { get; set; }
        public decimal? BorOvertimePreviousAmount1 { get; set; }
        public decimal? CobOvertimePreviousAmount1 { get; set; }
        public int? BorOvertimePreviousYear2 { get; set; }
        public int? BorOvertimePreviousMonths2 { get; set; }
        public decimal? BorOvertimePreviousAmount2 { get; set; }
        public decimal? CobOvertimePreviousAmount2 { get; set; }
        public decimal? BorOvertimeAverageOvertime { get; set; }
        public decimal? CobOvertimeAverageOvertime { get; set; }
        public int? BorBonusMostRecentMonths { get; set; }
        public decimal? BorBonusMostRecentAmount { get; set; }
        public decimal? CobBonusMostRecentAmount { get; set; }
        public int? BorBonusPreviousYear1 { get; set; }
        public int? BorBonusPreviousMonths1 { get; set; }
        public decimal? BorBonusPreviousAmount1 { get; set; }
        public decimal? CobBonusPreviousAmount1 { get; set; }
        public int? BorBonusPreviousYear2 { get; set; }
        public int? BorBonusPreviousMonths2 { get; set; }
        public decimal? BorBonusPreviousAmount2 { get; set; }
        public decimal? CobBonusPreviousAmount2 { get; set; }
        public decimal? BorBonusAverageOvertime { get; set; }
        public decimal? CobBonusAverageOvertime { get; set; }
        public int? BorCommissionMostRecentMonths { get; set; }
        public decimal? BorCommissionMostRecentAmount { get; set; }
        public decimal? CobCommissionMostRecentAmount { get; set; }
        public int? BorCommissionPreviousYear1 { get; set; }
        public int? BorCommissionPreviousMonths1 { get; set; }
        public decimal? BorCommissionPreviousAmount1 { get; set; }
        public decimal? CobCommissionPreviousAmount1 { get; set; }
        public decimal? BorCommissionAverageOvertime { get; set; }
        public decimal? CobCommissionAverageOvertime { get; set; }
        public int? BorDividendPreviousYear1 { get; set; }
        public int? BorDividendPreviousMonths1 { get; set; }
        public decimal? BorDividendPreviousAmount1 { get; set; }
        public decimal? CobDividendPreviousAmount1 { get; set; }
        public int? BorDividendPreviousYear2 { get; set; }
        public int? BorDividendPreviousMonths2 { get; set; }
        public decimal? BorDividendPreviousAmount2 { get; set; }
        public decimal? CobDividendPreviousAmount2 { get; set; }
        public decimal? BorDividendRequiredForCashAmount { get; set; }
        public decimal? CobDividendRequiredForCashAmount { get; set; }
        public decimal? BorDividendAverageDividend { get; set; }
        public decimal? CobDividendAverageDividend { get; set; }
        public int? BorInterestPreviousYear1 { get; set; }
        public int? BorInterestPreviousMonths1 { get; set; }
        public decimal? BorInterestPreviousAmount1 { get; set; }
        public decimal? CobInterestPreviousAmount1 { get; set; }
        public int? BorInterestPreviousYear2 { get; set; }
        public int? BorInterestPreviousMonths2 { get; set; }
        public decimal? BorInterestPreviousAmount2 { get; set; }
        public decimal? CobInterestPreviousAmount2 { get; set; }
        public decimal? BorInterestRequiredForCashAmount { get; set; }
        public decimal? CobInterestRequiredForCashAmount { get; set; }
        public decimal? BorInterestAverageDividend { get; set; }
        public decimal? CobInterestAverageDividend { get; set; }
        public decimal? BorOtherOtherIncome { get; set; }
        public decimal? BorOtherRetirementIncome { get; set; }
        public decimal? BorOtherSocialSecurityIncome { get; set; }
        public decimal? BorOtherTrustIncome { get; set; }
        public decimal? BorOtherUnemploymentIncome { get; set; }
        public decimal? BorOtherTipIncome { get; set; }
        public decimal? BorOtherParttimeIncome { get; set; }
        public decimal? BorOtherSeasonalIncome { get; set; }
        public decimal? BorOtherNotesReceivableIncome { get; set; }
        public decimal? CobOtherOtherIncome { get; set; }
        public decimal? CobOtherRetirementIncome { get; set; }
        public decimal? CobOtherSocialSecurityIncome { get; set; }
        public decimal? CobOtherTrustIncome { get; set; }
        public decimal? CobOtherUnemploymentIncome { get; set; }
        public decimal? CobOtherTipIncome { get; set; }
        public decimal? CobOtherParttimeIncome { get; set; }
        public decimal? CobOtherSeasonalIncome { get; set; }
        public decimal? CobOtherNotesReceivableIncome { get; set; }
        public decimal? BorMilitaryBasePay { get; set; }
        public decimal? BorMilitaryCombatPay { get; set; }
        public decimal? BorMilitaryFlightPay { get; set; }
        public decimal? BorMilitaryHazardPay { get; set; }
        public decimal? BorMilitaryOverseasPay { get; set; }
        public decimal? BorMilitaryPropPay { get; set; }
        public decimal? BorMilitaryTotalPay { get; set; }
        public decimal? CobMilitaryBasePay { get; set; }
        public decimal? CobMilitaryCombatPay { get; set; }
        public decimal? CobMilitaryFlightPay { get; set; }
        public decimal? CobMilitaryHazardPay { get; set; }
        public decimal? CobMilitaryOverseasPay { get; set; }
        public decimal? CobMilitaryPropPay { get; set; }
        public decimal? CobMilitaryTotalPay { get; set; }
        public decimal? BorMilitaryAllowanceClothingAllowance { get; set; }
        public decimal? BorMilitaryAllowanceRationsAllowance { get; set; }
        public decimal? BorMilitaryAllowanceVariableHousingAllowance { get; set; }
        public decimal? BorMilitaryAllowanceQuartersAllowance { get; set; }
        public decimal? BorMilitaryAllowanceOtherAllowance { get; set; }
        public decimal? BorMilitaryAllowanceTotalAllowance { get; set; }
        public decimal? CobMilitaryAllowanceClothingAllowance { get; set; }
        public decimal? CobMilitaryAllowanceRationsAllowance { get; set; }
        public decimal? CobMilitaryAllowanceVariableHousingAllowance { get; set; }
        public decimal? CobMilitaryAllowanceQuartersAllowance { get; set; }
        public decimal? CobMilitaryAllowanceOtherAllowance { get; set; }
        public decimal? CobMilitaryAllowanceTotalAllowance { get; set; }
        public string BorMilitaryAllowanceOtherAllowanceDescription { get; set; }
        public decimal? BorProjectedIncomeTotalProjectedIncome { get; set; }
        public decimal? CobProjectedIncomeTotalProjectedIncome { get; set; }
        public decimal? BorNonEmploymentIncomeTotalNonEmploymentIncome { get; set; }
        public decimal? CobNonEmploymentIncomeTotalNonEmploymentIncome { get; set; }
        public decimal? BorNonTaxableIncomeTotalNonTaxableIncome { get; set; }
        public decimal? CobNonTaxableIncomeTotalNonTaxableIncome { get; set; }
        public int? CobOvertimeMostRecentMonths { get; set; }
        public int? CobOvertimePreviousYear1 { get; set; }
        public int? CobOvertimePreviousMonths1 { get; set; }
        public int? CobOvertimePreviousYear2 { get; set; }
        public int? CobOvertimePreviousMonths2 { get; set; }
        public int? CobBonusMostRecentMonths { get; set; }
        public int? CobBonusPreviousYear1 { get; set; }
        public int? CobBonusPreviousMonths1 { get; set; }
        public int? CobBonusPreviousYear2 { get; set; }
        public int? CobBonusPreviousMonths2 { get; set; }
        public int? CobCommissionMostRecentMonths { get; set; }
        public int? CobCommissionPreviousYear1 { get; set; }
        public int? CobCommissionPreviousMonths1 { get; set; }
        public int? CobDividendPreviousYear1 { get; set; }
        public int? CobDividendPreviousMonths1 { get; set; }
        public int? CobDividendPreviousYear2 { get; set; }
        public int? CobDividendPreviousMonths2 { get; set; }
        public int? CobInterestPreviousYear1 { get; set; }
        public int? CobInterestPreviousMonths1 { get; set; }
        public int? CobInterestPreviousYear2 { get; set; }
        public int? CobInterestPreviousMonths2 { get; set; }
        public bool? BorNonEmploymentIncomeIsOffsetMtgCreditCertificateIncome { get; set; }
        public bool? BorNonEmploymentIncomeIsOffsetHomeownSubsidyIncome { get; set; }
        public int? BorOvertimeMostRecentYear { get; set; }
        public int? CobOvertimeMostRecentYear { get; set; }
        public int? BorBonusMostRecentYear { get; set; }
        public int? CobBonusMostRecentYear { get; set; }
        public int? BorCommissionMostRecentYear { get; set; }
        public int? CobCommissionMostRecentYear { get; set; }
        public int? BorCommissionPreviousYear2 { get; set; }
        public int? BorCommissionPreviousMonths2 { get; set; }
        public decimal? BorCommissionPreviousAmount2 { get; set; }
        public int? CobCommissionPreviousYear2 { get; set; }
        public int? CobCommissionPreviousMonths2 { get; set; }
        public decimal? CobCommissionPreviousAmount2 { get; set; }
        public string UnderwritingRiskAssessType { get; set; }
        public string UnderwritingRiskAssessOther { get; set; }
        public string AUSRecommendation { get; set; }
        public string DUCaseIDorLPAUSKey { get; set; }
        public string FreddieDocClass { get; set; }
        public string SubmittedBy { get; set; }
        public DateTime? SubmissionDate { get; set; }
        public string SubmissionTime { get; set; }
        public DateTime? FirstSubmissionDate { get; set; }
        public string FirstSubmissionTime { get; set; }
        public string SubmissionNumber { get; set; }
        public string AUSVersion { get; set; }
        public decimal? TotalHousingPayment { get; set; }
        public decimal? TotalMonthlyIncome { get; set; }
        public decimal? TotalMonthlyAssets { get; set; }
        public decimal? TotalMonthlyDebt { get; set; }
        public decimal? HousingRatio { get; set; }
        public decimal? TotalExpenseRatio { get; set; }
        public string Id { get; set; }
        public int? ATRQMBorrowerIndex { get; set; }
        public bool? IsEmpty { get; set; }
    }
}