using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class ClosingDocument
    {
        public string SpecialFloodHazardAreaIndictor { get; set; }
        public string TextDescription { get; set; }
        public string BorrowerUnparsedName1 { get; set; }
        public string BorrowerOrganizedUnderTheLawsOfJurisdictionName1 { get; set; }
        public string BorrowerOrganizationType1 { get; set; }
        public string BorrowerTaxIdentificationNumberIdentifier1 { get; set; }
        public string BorrowerTrustDateOrYear1 { get; set; }
        public List<ClosingEntity> ClosingEntities { get; set; }
        public string FinalVestingDescription { get; set; }
        public string DisclosurePlanCode { get; set; }
        public string PlanCode { get; set; }
        public string AlternateLender { get; set; }
        public string DisclosureAlternateLender { get; set; }
        public string DisclosureCompanyFunction { get; set; }
        public string MineralRightsDescription { get; set; }
        public bool? LegalAttached { get; set; }
        public string LastAuditDate { get; set; }
        public string LastDocumentOrdered { get; set; }
        public string DocReportGUID { get; set; }
        public DateTime? DocumentSigningDate { get; set; }
        public string AreAbleToServiceIndicator { get; set; }
        public string ExpectToAssignSellOrTransferPercent { get; set; }
        public string FirstTransferYear { get; set; }
        public decimal? FirstTransferYearValue { get; set; }
        public string SecondTransferYear { get; set; }
        public decimal? SecondTransferYearValue { get; set; }
        public string ThirdTransferYear { get; set; }
        public decimal? ThirdTransferYearValue { get; set; }
        public string AssociatedDocumentNumber { get; set; }
        public string BrokerLicenseNumberIdentifier { get; set; }
        public string RecordingJurisdictionName { get; set; }
        public string BrokerTaxIdentificationNumberIdentifier { get; set; }
        public string OfficeOfRecordationName { get; set; }
        public string DrawCounty { get; set; }
        public string ClosingState { get; set; }
        public string HoursDocumentsNeededPriorToDisbursementCount { get; set; }
        public string PayToTheOrderOfDescription { get; set; }
        public string ConditionDescription { get; set; }
        public string PerDiemCalculationMethodType { get; set; }
        public string ClosingProvider { get; set; }
        public bool? LoanIsLocked { get; set; }
        public string ComplianceJurisdictionCounty { get; set; }
        public List<AdditionalStateDisclosure> AdditionalStateDisclosures { get; set; }
        public decimal? TotalDisbursed { get; set; }
        public decimal? DisbursementsToBorrower { get; set; }
        public decimal? CashCheckFromBorrower { get; set; }
        public List<RespaHudDetail> RespaHudDetails { get; set; }
        public string TitleReportRequiredEndorsementsDescription { get; set; }
        public string PropertyTaxMessageDescription { get; set; }
        public string TitleReportItemsDescription { get; set; }
        public DateTime? PreliminaryTitleReportDate { get; set; }
        public string TermiteReportRequiredIndicator { get; set; }
        public string HUD1FileNumberIdentifier { get; set; }
        public DateTime? RescissionDate { get; set; }
        public bool? RefinanceRightOfRescissionExemptFlag { get; set; }
        public DateTime? DisbursementDate { get; set; }
        public string HUD1SettlementAgentUnparsedName { get; set; }
        public string HUD1SettlementAgentUnparsedAddress { get; set; }
        public DateTime? HUD1SettlementDate { get; set; }
        public DateTime? DocumentPreparationDate { get; set; }
        public string DrawState { get; set; }
        public string DrawCity { get; set; }
        public string MortgageType { get; set; }
        public List<StateLicense> StateLicenses { get; set; }
        public string MfgHomeMakeIdentifier { get; set; }
        public int? MfgHomeManufactureYear { get; set; }
        public int? MfgHomeLengthFeetCount { get; set; }
        public int? MfgHomeWidthFeetCount { get; set; }
        public string MfgHomeManufacturer { get; set; }
        public string MfgHomeSerialNumberIdentifier { get; set; }
        public string MfgHomeCertificateOfTitleIdentifier { get; set; }
        public string MfgHomeCertificateOfTitleType { get; set; }
        public string MfgHomeModelIdentifier { get; set; }
        public string MfgHomeNewOrUsed { get; set; }
        public string MfgHomeHUDCertificationLabelIdentifier { get; set; }
        public string MfgHomeAnchored { get; set; }
        public string MfgHomeDescription { get; set; }
        public string LienHolderName { get; set; }
        public string LienHolderAddress { get; set; }
        public string LienHolderAddressCity { get; set; }
        public string LienHolderAddressState { get; set; }
        public string LienHolderAddressPostalCode { get; set; }
        public decimal? OriginalPincipalAmountSecured { get; set; }
        public string AdditionalLienHolderName { get; set; }
        public string AdditionalLienHolderAddress { get; set; }
        public string AdditionalLienHolderAddressCity { get; set; }
        public string AdditionalLienHolderAddressState { get; set; }
        public string AdditionalLienHolderAddressPostalCode { get; set; }
        public decimal? AdditionalOriginalPincipalAmountSecured { get; set; }
        public decimal? CoopSharesOwned { get; set; }
        public string CoopCompanyName { get; set; }
        public decimal? CoopVacancyPercentNotification { get; set; }
        public string CoopCompanyExistsUnderTHeLawsOf { get; set; }
        public string CoopBuildingName { get; set; }
        public string CoopAttorneyInFact { get; set; }
        public DateTime? CoopProprietaryLeaseDate { get; set; }
        public DateTime? CoopAssignmentLeaseDate { get; set; }
        public string CoopStockCertificationNumber { get; set; }
        public string CoopApartmentNumber { get; set; }
        public bool? HousingIndicator { get; set; }
        public string HousingProgramName { get; set; }
        public DateTime? CompliancePropertyIdentifiedDate { get; set; }
        public bool? SyncInterestDateDisbursementDate { get; set; }
        public string Beneficiaries { get; set; }
        public int? NumberBrokerAgreements { get; set; }
        public int? NumberSuccessfulBrokerAgreements { get; set; }
        public int? ProcessingNumberDays { get; set; }
        public string LenderBrokerRepresents { get; set; }
        public string SuretyCompanyName { get; set; }
        public string LenderAuthorizedRepresentativeTitle { get; set; }
        public string BrokerAuthorizedRepresentativeTitle { get; set; }
        public string RateLockRefundConditions1 { get; set; }
        public string RateLockRefundConditions2 { get; set; }
        public string RateLockRefundConditions3 { get; set; }
        public string PrepaymentPenaltyDescriptions1 { get; set; }
        public string PrepaymentPenaltyDescriptions2 { get; set; }
        public string PrepaymentPenaltyDescriptions3 { get; set; }
        public string BrokerFeeRefundConditions1 { get; set; }
        public string BrokerFeeRefundConditions2 { get; set; }
        public string BrokerFeeRefundConditions3 { get; set; }
        public string LockInFeeType { get; set; }
        public bool? BorrowerConsentType1 { get; set; }
        public string BrokerWithLenders { get; set; }
        public bool? RefinanceBalloonMortgageGuarantee { get; set; }
        public string BrokerNameAsLicensed { get; set; }
        public string RMLANamePreceding10Years { get; set; }
        public string ParentAffiliatedCoName { get; set; }
        public string WeConductBusiness { get; set; }
        public bool? OnlyOneEntity { get; set; }
        public bool? PropertyIsLandTrust { get; set; }
        public string EmployeeofMortgageLender { get; set; }
        public string BrokerForPlacingLoan { get; set; }
        public bool? AffectedByInterest { get; set; }
        public string BrokerCompensationMethod { get; set; }
        public string BrokerInterestRateEffect { get; set; }
        public string BrokerLenderRelationship { get; set; }
        public bool? ConflictofInterestCheck1 { get; set; }
        public bool? ConflictofInterestCheck2 { get; set; }
        public bool? ConflictofInterestCheck3 { get; set; }
        public bool? ConflictofInterestCheck4 { get; set; }
        public bool? ConflictofInterestCheck5 { get; set; }
        public bool? ConflictofInterestCheck6 { get; set; }
        public bool? BorrowerConsentType2 { get; set; }
        public List<AntiSteeringLoanOption> AntiSteeringLoanOptions { get; set; }
        public string LoanOption { get; set; }
        public string OtherOptionDescription { get; set; }
        public string OptionSelectedReason { get; set; }
        public decimal? IncludeSafeHaborDisclosure { get; set; }
        public string RmlLenderBrokerRepresents { get; set; }
        public string RenewalExtensionDescription { get; set; }
        public DateTime? SignatureDateFor1003 { get; set; }
        public string CustomOtherRiderDescription { get; set; }
        public string MfgHomeManufacturerAddress { get; set; }
        public string MfgHomeManufacturerCity { get; set; }
        public string MfgHomeManufacturerState { get; set; }
        public string MfgHomeManufacturerPostalCode { get; set; }
        public string MfgHomeManufacturerPhoneNumber { get; set; }
        public string PlanCodeId { get; set; }
        public string ClosingDocsLoanProgramType { get; set; }
        public string ProgramCode { get; set; }
        public string ProgramSponsor { get; set; }
        public string PlanCodeDescription { get; set; }
        public string InvestorCode { get; set; }
        public string AdditionalSigVerbiageType { get; set; }
        public string AltLenderId { get; set; }
        public string BorrowerTrustAmendedDateOrYear1 { get; set; }
        public string BorrowerUnparsedName2 { get; set; }
        public string BorrowerOrganizedUnderTheLawsOfJurisdictionName2 { get; set; }
        public string BorrowerOrganizationType2 { get; set; }
        public string BorrowerTaxIdentificationNumberIdentifier2 { get; set; }
        public string BorrowerTrustDateOrYear2 { get; set; }
        public string BorrowerTrustAmendedDateOrYear2 { get; set; }
        public string Trust2Beneficiaries { get; set; }
        public string Id { get; set; }
    }
}