using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class ClosingDisclosure1
    {
        public bool? RangePaymentIndicatorC1 { get; set; }
        public bool? RangePaymentIndicatorC2 { get; set; }
        public bool? RangePaymentIndicatorC3 { get; set; }
        public bool? RangePaymentIndicatorC4 { get; set; }
        public DateTime? CDDateIssued { get; set; }
        public string SellerNames { get; set; }
        public decimal? EstimatedTaxesInsuranceAssessments { get; set; }
        public string InEscrowPropertyTaxes { get; set; }
        public string InEscrowHomeownerInsurance { get; set; }
        public string InEscrowOther { get; set; }
        public int? PPC1Year { get; set; }
        public decimal? PPC1MinimumPIPayment { get; set; }
        public string PPC1MinimumPIPaymentUI { get; set; }
        public decimal? PPC1MaximumPIPayment { get; set; }
        public string PPC1MaximumPIPaymentUI { get; set; }
        public bool? PPC1InterestOnly { get; set; }
        public decimal? PPC1MIAmount { get; set; }
        public string PPC1MIAmountUI { get; set; }
        public decimal? PPC1EstimatedEscrowAmount { get; set; }
        public string PPC1EstimatedEscrowAmountUI { get; set; }
        public decimal? PPC1MinimumMonthlyPayment { get; set; }
        public string PPC1MinimumMonthlyPaymentUI { get; set; }
        public decimal? PPC1MaximumMonthlyPayment { get; set; }
        public string PPC1MaximumMonthlyPaymentUI { get; set; }
        public int? PPC2YearFrom { get; set; }
        public int? PPC2YearTo { get; set; }
        public decimal? PPC2MinimumPIPayment { get; set; }
        public string PPC2MinimumPIPaymentUI { get; set; }
        public decimal? PPC2MaximumPIPayment { get; set; }
        public string PPC2MaximumPIPaymentUI { get; set; }
        public bool? PPC2InterestOnly { get; set; }
        public decimal? PPC2MIAmount { get; set; }
        public string PPC2MIAmountUI { get; set; }
        public decimal? PPC2EstimatedEscrowAmount { get; set; }
        public string PPC2EstimatedEscrowAmountUI { get; set; }
        public decimal? PPC2MinimumMonthlyPayment { get; set; }
        public string PPC2MinimumMonthlyPaymentUI { get; set; }
        public decimal? PPC2MaximumMonthlyPayment { get; set; }
        public string PPC2MaximumMonthlyPaymentUI { get; set; }
        public int? PPC3YearFrom { get; set; }
        public int? PPC3YearTo { get; set; }
        public decimal? PPC3MinimumPIPayment { get; set; }
        public string PPC3MinimumPIPaymentUI { get; set; }
        public decimal? PPC3MaximumPIPayment { get; set; }
        public string PPC3MaximumPIPaymentUI { get; set; }
        public bool? PPC3InterestOnly { get; set; }
        public decimal? PPC3MIAmount { get; set; }
        public string PPC3MIAmountUI { get; set; }
        public decimal? PPC3EstimatedEscrowAmount { get; set; }
        public string PPC3EstimatedEscrowAmountUI { get; set; }
        public decimal? PPC3MinimumMonthlyPayment { get; set; }
        public string PPC3MinimumMonthlyPaymentUI { get; set; }
        public decimal? PPC3MaximumMonthlyPayment { get; set; }
        public string PPC3MaximumMonthlyPaymentUI { get; set; }
        public int? PPC4YearFrom { get; set; }
        public int? PPC4YearTo { get; set; }
        public decimal? PPC4MinimumPIPayment { get; set; }
        public string PPC4MinimumPIPaymentUI { get; set; }
        public decimal? PPC4MaximumPIPayment { get; set; }
        public string PPC4MaximumPIPaymentUI { get; set; }
        public bool? PPC4InterestOnly { get; set; }
        public decimal? PPC4MIAmount { get; set; }
        public string PPC4MIAmountUI { get; set; }
        public decimal? PPC4EstimatedEscrowAmount { get; set; }
        public string PPC4EstimatedEscrowAmountUI { get; set; }
        public decimal? PPC4MinimumMonthlyPayment { get; set; }
        public string PPC4MinimumMonthlyPaymentUI { get; set; }
        public decimal? PPC4MaximumMonthlyPayment { get; set; }
        public string PPC4MaximumMonthlyPaymentUI { get; set; }
        public bool? PPCMortgageInsuranceIndicator { get; set; }
        public bool? PPCEstimatedEscrowIndicator { get; set; }
        public DateTime? DisclosureLastSentDate { get; set; }
        public string DisclosureBy { get; set; }
        public string DisclosureSentMethod { get; set; }
        public string DisclosureComments { get; set; }
        public DateTime? DisclosureReceivedDate { get; set; }
        public bool? ReasonChangeInAPR { get; set; }
        public bool? ReasonChangeInLoanProduct { get; set; }
        public bool? ReasonPrepaymentPenalty { get; set; }
        public bool? ReasonChangeSettlementCharges { get; set; }
        public bool? ReasonAdvancedReview { get; set; }
        public bool? ReasonToleranceCure { get; set; }
        public bool? ReasonClericalErrorCorrection { get; set; }
        public bool? ReasonOther { get; set; }
        public string ReasonOtherDescription { get; set; }
        public bool? ChangedCircumstanceFlag { get; set; }
        public DateTime? ChangesReceivedDate { get; set; }
        public DateTime? RevisedCDDueDate { get; set; }
        public string ChangedCircumstance { get; set; }
        public string Comments { get; set; }
        public bool? ReasonRevisionsReqConsumer { get; set; }
        public bool? ReasonInterestRatecharges { get; set; }
        public bool? ReasonChangedCircumstanceElg { get; set; }
        public decimal? TotalCashToClose { get; set; }
        public string ReasonChangedCircumstanceFlags { get; set; }
        public string MICReference { get; set; }
        public bool? NotNaturalPersonFlag { get; set; }
        public DateTime? InitialCDReceivedDate { get; set; }
        public DateTime? RevisedCDReceivedDate { get; set; }
        public string DocumentGUIDFinalExecutedCopyofStandardCD { get; set; }
        public string SignatureTypeFinalExecutedCopyofStandardCD { get; set; }
        public string DocumentGUIDFinalExecutedCopyofAlternateCD { get; set; }
        public string SignatureTypeFinalExecutedCopyofAlternateCD { get; set; }
        public string DocumentGUIDFinalExecutedCopyofSellerCD { get; set; }
        public string SignatureTypeFinalExecutedCopyofSellerCD { get; set; }
        public string Id { get; set; }
    }
}