using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class FhaVaLoan
    {
        public string PurposeOfLoan { get; set; }
        public decimal? PrepaidExpenses { get; set; }
        public string MortgageFinancialInterest { get; set; }
        public decimal? PaidAmount { get; set; }
        public decimal? GiftFundsAmount { get; set; }
        public string DulyAgentName { get; set; }
        public decimal? TotalClosingCost { get; set; }
        public int? PremiumMonths { get; set; }
        public string BorrowerCertificationAddress { get; set; }
        public string DulyAgentCity { get; set; }
        public decimal? SalesPrice { get; set; }
        public decimal? OriginalMortgageAmount { get; set; }
        public DateTime? ClosingDate { get; set; }
        public bool? OwnOrSoldOtherRealEstate { get; set; }
        public bool? ToBeSold { get; set; }
        public bool? DwellingCoveredBy { get; set; }
        public bool? OwnMoreThanFourDwellings { get; set; }
        public decimal? DiscountPoints { get; set; }
        public string SponsorID { get; set; }
        public string OtherTitleDescription { get; set; }
        public string Occupancy { get; set; }
        public bool? UtilityIncluded { get; set; }
        public string SponsorAgentName { get; set; }
        public string SponsorAgentAddress { get; set; }
        public string SponsorAgentCity { get; set; }
        public decimal? MinimumDownPayment { get; set; }
        public decimal? SellerPaidClosingCost { get; set; }
        public decimal? NonRealtyAndOtherItems { get; set; }
        public decimal? SecondMortgageAmount { get; set; }
        public decimal? FundingFeePaidInCash { get; set; }
        public decimal? SpecialAssessments { get; set; }
        public int? ProposedMaturityYears { get; set; }
        public decimal? OtherMonthlyShelterExpense { get; set; }
        public int? ProposedMaturityMonths { get; set; }
        public bool? EverHadVAHomeLoan { get; set; }
        public string Valuation { get; set; }
        public bool? HaveReceivedLeadPaintPoisoningInfo { get; set; }
        public string TitleVestedIn { get; set; }
        public string BeenInformed { get; set; }
        public decimal? OtherLiabilitiesMonthlyPayment { get; set; }
        public decimal? OtherLiabilitiesUnpaidBalance { get; set; }
        public string AddendumType { get; set; }
        public decimal? FHAMaxLoanAmount { get; set; }
        public decimal? EnergyEfficientMortgageAmount { get; set; }
        public string BorrowerCertificationCity { get; set; }
        public string BorrowerCertificationState { get; set; }
        public string BorrowerCertificationPostalCode { get; set; }
        public string SponsorAgentState { get; set; }
        public string SponsorAgentPostalCode { get; set; }
        public string LenderRepresentativeName { get; set; }
        public string LenderRepresentativeTitle { get; set; }
        public string LenderRepresentativePhone { get; set; }
        public string DulyAgentAddress { get; set; }
        public string DulyAgentFunction1 { get; set; }
        public string DulyAgentState { get; set; }
        public string DulyAgentFunction2 { get; set; }
        public string FreddieMacCounselType { get; set; }
        public List<EnergyEfficientMortgageItem> EnergyEfficientMortgageItems { get; set; }
        public EnergyEfficientMortgage Eem { get; set; }
        public decimal? ExistingDebtAmount { get; set; }
        public decimal? ExcessContributionAmount { get; set; }
        public DateTime? LastRefiDate { get; set; }
        public DateTime? PreviousPurchaseDate { get; set; }
        public string FHACaseOrderedBy { get; set; }
        public DateTime? ValidateAddressDate { get; set; }
        public string AddressValidatedBy { get; set; }
        public string FHAManagementCounselType { get; set; }
        public string AddressValidationMessage { get; set; }
        public DateTime? RefiAuthorizationDate { get; set; }
        public string RefiAuthorizationBy { get; set; }
        public string OldAgencyCaseIdentifier { get; set; }
        public DateTime? ObtainCAIVRSDate { get; set; }
        public string CAIVRSObtainedBy { get; set; }
        public DateTime? LDPGSASearchDate { get; set; }
        public string LDPGSASearchedBy { get; set; }
        public string LoanScoreID { get; set; }
        public string EligibilityAssessment { get; set; }
        public DateTime? TotalScorecardDate { get; set; }
        public string TotalScorecardBy { get; set; }
        public DateTime? CondoPudLookupDate { get; set; }
        public string CondoPudLookupBy { get; set; }
        public string CondoPudID { get; set; }
        public DateTime? AppraisalLoggedDate { get; set; }
        public string AppraisalLookupBy { get; set; }
        public DateTime? UFMIPRemittanceDueDate { get; set; }
        public DateTime? UFMIPRemittedDate { get; set; }
        public string UFMIPRemittedBy { get; set; }
        public decimal? UFMIPRemittedAmount { get; set; }
        public string UFMIPVerificationCode { get; set; }
        public DateTime? MIP1stDueDate { get; set; }
        public DateTime? MIPRemittedDate { get; set; }
        public DateTime? MIP1stToInvestor { get; set; }
        public DateTime? MIAppliedDate { get; set; }
        public string MIAppliedBy { get; set; }
        public DateTime? MIRejectedDate { get; set; }
        public DateTime? MICRetrivedDate { get; set; }
        public DateTime? CaseBinderShippedDate { get; set; }
        public string CaseBinderShippedBy { get; set; }
        public DateTime? ServingTransferedDate { get; set; }
        public bool? ForeclosedProperty { get; set; }
        public string LenderName { get; set; }
        public string LenderAddress { get; set; }
        public string LenderCity { get; set; }
        public string LenderState { get; set; }
        public string LenderPostalCode { get; set; }
        public string LenderNMLS { get; set; }
        public string LenderTaxID { get; set; }
        public bool? UseDefaultLenderInfo { get; set; }
        public string SponsorAgentNMLS { get; set; }
        public string SponsorAgentTaxID { get; set; }
        public string SponsoredOriginationsName { get; set; }
        public string SponsoredOriginationsNMLS { get; set; }
        public string SponsoredOriginationsTaxID { get; set; }
        public string HUD1003AddendumApproved { get; set; }
        public DateTime? DateMortgageApproved { get; set; }
        public DateTime? DateApprovalExpires { get; set; }
        public decimal? ModifiedLoanAmount { get; set; }
        public decimal? ModifiedInterestRate { get; set; }
        public int? ModifiedProposedMaturityYear { get; set; }
        public int? ModifiedProposedMaturityMonth { get; set; }
        public decimal? ModifiedMonthlyPayment { get; set; }
        public decimal? ModifiedUpfrontPremium { get; set; }
        public decimal? ModifiedMonthlyPremium { get; set; }
        public bool? AdditionalCondition1 { get; set; }
        public bool? AdditionalCondition2 { get; set; }
        public bool? AdditionalCondition3 { get; set; }
        public bool? AdditionalCondition4 { get; set; }
        public bool? AdditionalCondition5 { get; set; }
        public bool? AdditionalCondition6 { get; set; }
        public bool? AdditionalCondition7 { get; set; }
        public string DetailForOther { get; set; }
        public bool? AdditionalCondition8 { get; set; }
        public string MortgageeRepresentative { get; set; }
        public bool? AdditionalCondition9 { get; set; }
        public int? ModifiedTermAnnualPremium { get; set; }
        public bool? AllConditionsSatisfied { get; set; }
        public DateTime? PriorEndorsementDate { get; set; }
        public string Id { get; set; }
    }
}