using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class LoanProgram
    {
        public string MortgageType { get; set; }
        public string PropertyUsageType { get; set; }
        public string LienPriorityType { get; set; }
        public string Type { get; set; }
        public string LoanAmortizationType { get; set; }
        public decimal? RequestedInterestRatePercent { get; set; }
        public decimal? QualifyingRatePercent { get; set; }
        public int? LoanAmortizationTermMonths { get; set; }
        public int? BalloonLoanMaturityTermMonths { get; set; }
        public decimal? BuydownIncreaseRatePercent1 { get; set; }
        public int? BuydownChangeFrequencyMonths1 { get; set; }
        public decimal? BuydownIncreaseRatePercent2 { get; set; }
        public int? BuydownChangeFrequencyMonths2 { get; set; }
        public decimal? BuydownIncreaseRatePercent3 { get; set; }
        public int? BuydownChangeFrequencyMonths3 { get; set; }
        public decimal? BuydownIncreaseRatePercent4 { get; set; }
        public int? BuydownChangeFrequencyMonths4 { get; set; }
        public decimal? BuydownIncreaseRatePercent5 { get; set; }
        public int? BuydownChangeFrequencyMonths5 { get; set; }
        public decimal? BuydownIncreaseRatePercent6 { get; set; }
        public int? BuydownChangeFrequencyMonths6 { get; set; }
        public string LoanFeaturesPaymentFrequencyType { get; set; }
        public int? InterestOnlyMonths { get; set; }
        public decimal? RateAdjustmentPercent { get; set; }
        public int? RateAdjustmentSubsequentRateAdjustmentMonths { get; set; }
        public decimal? RateAdjustmentSubsequentCapPercent { get; set; }
        public int? RateAdjustmentDurationMonths { get; set; }
        public decimal? RateAdjustmentLifetimeCapPercent { get; set; }
        public decimal? IndexMarginPercent { get; set; }
        public decimal? IndexCurrentValuePercent { get; set; }
        public decimal? FloorPercent { get; set; }
        public decimal? RoundPercent { get; set; }
        public string RoundType { get; set; }
        public decimal? PaymentAdjustmentPeriodicCapPercent { get; set; }
        public int? PaymentAdjustmentDurationMonths { get; set; }
        public int? RecastPaidMonths { get; set; }
        public int? RecastStopMonths { get; set; }
        public decimal? MaximumBalance { get; set; }
        public decimal? GpmRate { get; set; }
        public int? GpmYears { get; set; }
        public decimal? GpmExtraPaymentForEarlyPayOff { get; set; }
        public string LoanProgramName { get; set; }
        public decimal? MaxLoanAmount { get; set; }
        public decimal? MaxLtv { get; set; }
        public decimal? MaxCltv { get; set; }
        public string MinCreditScore { get; set; }
        public decimal? MaxFrontRatio { get; set; }
        public decimal? MaxBackRatio { get; set; }
        public string LenderInvestorCode { get; set; }
        public decimal? PaymentFactor { get; set; }
        public int? ConstructionPeriodMonths { get; set; }
        public decimal? ConstructionRate { get; set; }
        public decimal? ConstructionInterestReserveAmount { get; set; }
        public string ConstructionDescription { get; set; }
        public decimal? MortgageInsuranceAdjustmentFactor1 { get; set; }
        public int? MortgageInsuranceMonthsOfAdjustment1 { get; set; }
        public decimal? MortgageInsuranceMonthlyPayment1 { get; set; }
        public decimal? MortgageInsuranceAdjustmentFactor2 { get; set; }
        public int? MortgageInsuranceMonthsOfAdjustment2 { get; set; }
        public decimal? MortgageInsuranceMonthlyPayment2 { get; set; }
        public decimal? MortgageInsuranceCancelPercent { get; set; }
        public string RequiredDeposit { get; set; }
        public string DemandFeature { get; set; }
        public string VariableRateFeature { get; set; }
        public string AdditionalArmInformation { get; set; }
        public string SecurityInterestInNameOf { get; set; }
        public string SecurityType { get; set; }
        public string PrepaymentPenaltyIndicator { get; set; }
        public string RefundPaymentIndicator { get; set; }
        public int? LateChargeDays { get; set; }
        public decimal? LateChargePercent { get; set; }
        public string LateChargeType { get; set; }
        public string AssumptionOnYourProperty { get; set; }
        public string Convertible { get; set; }
        public string ProgramCode { get; set; }
        public string MeansAnEstimate { get; set; }
        public string AllDateAndNumericalDisclosures { get; set; }
        public decimal? SubjectPropertyGrossRentalIncome { get; set; }
        public decimal? PercentageOfRental { get; set; }
        public string OtherMortgageTypeDescription { get; set; }
        public string ArmTypeDescription { get; set; }
        public string OtherAmortizationTypeDescription { get; set; }
        public string Description { get; set; }
        public string CreditLifeInsurance { get; set; }
        public string CreditDisability { get; set; }
        public string PropertyInsurance { get; set; }
        public string FloodInsurance { get; set; }
        public string IfYouPurchase { get; set; }
        public string IfYouPurchaseType { get; set; }
        public decimal? YearlyTerm { get; set; }
        public string OtherLoanPurposeDescription { get; set; }
        public string ClosingCostProgram { get; set; }
        public string MidpointCancellation { get; set; }
        public string CalculateBasedOnRemainingBalance { get; set; }
        public string MiCalculationType { get; set; }
        public decimal? FhaUpfrontMiPremiumPercent { get; set; }
        public string LockField { get; set; }
        public decimal? MipPaidInCash { get; set; }
        public decimal? FundingFeePaidInCash { get; set; }
        public string UseDaysInYears { get; set; }
        public string UsePitiForRatio { get; set; }
        public string LoanDocumentationType { get; set; }
        public string Mmi { get; set; }
        public string Pmi { get; set; }
        public string DisclosureType { get; set; }
        public string PerDiemCalculationMethodType { get; set; }
        public string ConstructionLoanMethod { get; set; }
        public string Acquisition { get; set; }
        public decimal? InitialAdvanceAmount { get; set; }
        public decimal? AnnualFeeNeeded { get; set; }
        public decimal? TeaserRate { get; set; }
        public decimal? ThirdPartyFeeFrom { get; set; }
        public decimal? ThirdPartyFeeTo { get; set; }
        public decimal? MinimumAdvanceAmount { get; set; }
        public decimal? MinimumAllowableApr { get; set; }
        public decimal? MinimumPaymentPercent { get; set; }
        public decimal? MinimumPaymentAmount { get; set; }
        public string Discounted { get; set; }
        public decimal? DiscountedRate { get; set; }
        public string DrawRepayPeriodTableName { get; set; }
        public decimal? TerminationFeeAmount { get; set; }
        public int? TerminationPeriodMonthsCount { get; set; }
        public string Id { get; set; }
    }
}