using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class RegulationZ
    {
        public bool? PmiIndicator { get; set; }
        public string BorrowerMiTerminationDate { get; set; }
        public string MiScheduledTerminationDate { get; set; }
        public decimal? ExtraPaymentForEarlyPayOff { get; set; }
        public string DisclosureType { get; set; }
        public bool? DemandFeatureIndicator { get; set; }
        public bool? RequiredDepositIndicator { get; set; }
        public bool? VariableRateFeatureIndicator { get; set; }
        public string AdditionalArmInformation { get; set; }
        public bool? RefundPaymentIndicator { get; set; }
        public string SecurityType { get; set; }
        public int? LateChargeDays { get; set; }
        public decimal? LateChargePercent { get; set; }
        public bool? FloodInsuranceIndicator { get; set; }
        public string AssumptionOnYourProperty { get; set; }
        public bool? AllDateAndNumericalDisclosuresIndicator { get; set; }
        public bool? MeansAnEstimateIndicator { get; set; }
        public bool? MmiIndicator { get; set; }
        public decimal? AprPercent { get; set; }
        public decimal? AmountFinanced { get; set; }
        public decimal? PrepaidFinanceCharge { get; set; }
        public int? ConstructionPeriodMonths { get; set; }
        public int? InterestOnlyMonths { get; set; }
        public int? MiMonthsOfAdjustmentLevel1 { get; set; }
        public int? MiMonthsOfAdjustmentLevel2 { get; set; }
        public decimal? MiAdjustmentFactorLevel2 { get; set; }
        public decimal? MortgageInsuranceCancelPercent { get; set; }
        public decimal? FinanceCharge { get; set; }
        public decimal? TotalOfPayments { get; set; }
        public int? MonthsOfMiPrepaid { get; set; }
        public bool? PropertyInsuranceIndicator { get; set; }
        public decimal? InterestReserveAmount { get; set; }
        public int? Years { get; set; }
        public decimal? RatePercent { get; set; }
        public string ConstructionLoanDescription { get; set; }
        public string InterestInNameOf { get; set; }
        public decimal? ConstructionRatePercent { get; set; }
        public bool? CustomizePaymentScheduleIndicator { get; set; }
        public List<RegulationZPayment> RegulationZPayments { get; set; }
        public bool? CreditLifeInsuranceIndicator { get; set; }
        public bool? CreditDisabilityIndicator { get; set; }
        public int? NumberOfPayments { get; set; }
        public string InsuranceRequiredDescription { get; set; }
        public decimal? CreditLife { get; set; }
        public decimal? CreditDisability { get; set; }
        public decimal? CreditLifeAndCreditDisability { get; set; }
        public decimal? FilingFees { get; set; }
        public bool? IfYouPurchaseIndicator { get; set; }
        public string IfYouPurchaseType { get; set; }
        public decimal? YearlyTerm { get; set; }
        public decimal? MonthlyTerm { get; set; }
        public int? RecastPaidMonths { get; set; }
        public int? RecastStopMonths { get; set; }
        public string LateChargeType { get; set; }
        public string MidpointCancellation { get; set; }
        public decimal? MiMonthlyPaymentLevel1 { get; set; }
        public decimal? MiMonthlyPaymentLevel2 { get; set; }
        public string CalculateBasedOnRemainingBalance { get; set; }
        public decimal? MarginPlusIndexPercent { get; set; }
        public bool? UsePitiForRatioIndicator { get; set; }
        public string LateChargeComments { get; set; }
        public decimal? MinimumPayment { get; set; }
        public decimal? MaximumPayment { get; set; }
        public string YearOfMaximumPayment { get; set; }
        public decimal? SamplePayments { get; set; }
        public string ArmDisclosureDescription { get; set; }
        public DateTime? FinalPaymentDate { get; set; }
        public DateTime? FirstAmortizationPaymentDate { get; set; }
        public bool? Acquisition { get; set; }
        public string NamePreparedBy { get; set; }
        public string PhonePreparedBy { get; set; }
        public string AcknowledgedDay { get; set; }
        public string AcknowledgedMonth { get; set; }
        public string AcknowledgedYear { get; set; }
        public string RegzTableType { get; set; }
        public string UseDaysInYears { get; set; }
        public string ConstructionLoanMethod { get; set; }
        public decimal? DiscountRatePercent { get; set; }
        public int? DiscountPeriod { get; set; }
        public string DiscountType { get; set; }
        public string NewConstructionIndicator { get; set; }
        public DateTime? OriginalContractDate { get; set; }
        public string InterestRateType { get; set; }
        public decimal? LendersInspectionFee { get; set; }
        public decimal? MinimumLateCharge { get; set; }
        public decimal? MaximumLateCharge { get; set; }
        public bool? MiPrepaidIndicator { get; set; }
        public bool? InterestOnlyIndicator { get; set; }
        public decimal? DisclosedAprPercent { get; set; }
        public DateTime? TilDate { get; set; }
        public bool? DisclosedByBrokerIndicator { get; set; }
        public DateTime? LastDisclosedDate { get; set; }
        public string DisclosureMethod { get; set; }
        public string LastDisclosedBy { get; set; }
        public DateTime? GfeExpirationDate { get; set; }
        public string DisclosedComments { get; set; }
        public DateTime? GfeApplicationDate { get; set; }
        public DateTime? InitialDisclosureDueDate { get; set; }
        public DateTime? InitialDisclosureProvidedDate { get; set; }
        public DateTime? EarliestFeeCollectionDate { get; set; }
        public DateTime? FeeCollectedDate { get; set; }
        public DateTime? EarliestClosingDate { get; set; }
        public DateTime? InitialGfeDisclosureProvidedDate { get; set; }
        public DateTime? InitialGfeDisclosureReceivedDate { get; set; }
        public DateTime? GfeRedisclosureProvidedDate { get; set; }
        public DateTime? GfeRedisclosureReceivedDate { get; set; }
        public DateTime? InitialTilDisclosureProvidedDate { get; set; }
        public DateTime? InitialTilDisclosureReceivedDate { get; set; }
        public DateTime? TilRedisclosureProvidedDate { get; set; }
        public DateTime? TilRedisclosureReceivedDate { get; set; }
        public DateTime? TilLastDisclosedDate { get; set; }
        public DateTime? TilLastDisclosedBorrowerReceivedDate { get; set; }
        public string TilDisclosureMethod { get; set; }
        public string TilLastDisclosedBy { get; set; }
        public string TilDisclosedComments { get; set; }
        public bool? Hud1ToleranceViolatedIndicator { get; set; }
        public DateTime? RateLockGfeDueDate { get; set; }
        public string GfeExpirationPeriod { get; set; }
        public DateTime? LastDisclosedGfeReceivedDate { get; set; }
        public bool? BorrowerIntendToContinueIndicator { get; set; }
        public DateTime? CircumstanceChangeReceivedDate { get; set; }
        public string CircumstanceChangeReason { get; set; }
        public DateTime? RevisedGfeDueDate { get; set; }
        public bool? GfeChangedCircumstanceIndicator { get; set; }
        public string GfeChangedCircumstanceItem { get; set; }
        public string GFEChangedCirsumstanceItemCode { get; set; }
        public DateTime? GfeDate { get; set; }
        public DateTime? HudToleranceResolutionDate { get; set; }
        public string HudToleranceResolutionComments { get; set; }
        public string HudToleranceResolvedBy { get; set; }
        public DateTime? BorrowerIntendToContinueDate { get; set; }
        public bool? GfeRateLockRedisclosureRequiredIndicator { get; set; }
        public bool? MiDecliningRenewalsIndicator { get; set; }
        public bool? RefundUnearnedMipIndicator { get; set; }
        public bool? ChargesAddedToPaymentsIndicator { get; set; }
        public bool? ChargesAtLoanClosingIndicator { get; set; }
        public bool? LenderPaidMortgageInsuranceIndicator { get; set; }
        public bool? MIPFactorLocked { get; set; }
        public decimal? MIPrepaidAmount { get; set; }
        public DateTime? LESentOnDate { get; set; }
        public string LEReceivedBy { get; set; }
        public string LEReceivedMethod { get; set; }
        public string LEReceivedMethodOther { get; set; }
        public string LEIntentToProceedComment { get; set; }
        public DateTime? ClosingDisclosureSentDate { get; set; }
        public DateTime? ClosingDisclosureReceivedDate { get; set; }
        public DateTime? RevisedClosingDisclosureSentDate { get; set; }
        public DateTime? RevisedClosingDisclosureReceivedDate { get; set; }
        public DateTime? PostConsummationDisclosureSentDate { get; set; }
        public DateTime? PostConsummationDisclosureReceivedDate { get; set; }
        public DateTime? ESignConsentDate { get; set; }
        public string ESignConsentBorrowerStatus1 { get; set; }
        public DateTime? ESignConsentBorrowerDateAccepted1 { get; set; }
        public string ESignConsentBorrowerIPAddress1 { get; set; }
        public string ESignConsentBorrowerSource1 { get; set; }
        public string ESignConsentCoBorrowerStatus1 { get; set; }
        public DateTime? ESignConsentCoBorrowerDateAccepted1 { get; set; }
        public string ESignConsentCoBorrowerIPAddress1 { get; set; }
        public string ESignConsentCoBorrowerSource1 { get; set; }
        public string ESignConsentBorrowerStatus2 { get; set; }
        public DateTime? ESignConsentBorrowerDateAccepted2 { get; set; }
        public string ESignConsentBorrowerIPAddress2 { get; set; }
        public string ESignConsentBorrowerSource2 { get; set; }
        public string ESignConsentCoBorrowerStatus2 { get; set; }
        public DateTime? ESignConsentCoBorrowerDateAccepted2 { get; set; }
        public string ESignConsentCoBorrowerIPAddress2 { get; set; }
        public string ESignConsentCoBorrowerSource2 { get; set; }
        public string ESignConsentBorrowerStatus3 { get; set; }
        public DateTime? ESignConsentBorrowerDateAccepted3 { get; set; }
        public string ESignConsentBorrowerIPAddress3 { get; set; }
        public string ESignConsentBorrowerSource3 { get; set; }
        public string ESignConsentCoBorrowerStatus3 { get; set; }
        public DateTime? ESignConsentCoBorrowerDateAccepted3 { get; set; }
        public string ESignConsentCoBorrowerIPAddress3 { get; set; }
        public string ESignConsentCoBorrowerSource3 { get; set; }
        public string ESignConsentBorrowerStatus4 { get; set; }
        public DateTime? ESignConsentBorrowerDateAccepted4 { get; set; }
        public string ESignConsentBorrowerIPAddress4 { get; set; }
        public string ESignConsentBorrowerSource4 { get; set; }
        public string ESignConsentCoBorrowerStatus4 { get; set; }
        public DateTime? ESignConsentCoBorrowerDateAccepted4 { get; set; }
        public string ESignConsentCoBorrowerIPAddress4 { get; set; }
        public string ESignConsentCoBorrowerSource4 { get; set; }
        public string ESignConsentBorrowerStatus5 { get; set; }
        public DateTime? ESignConsentBorrowerDateAccepted5 { get; set; }
        public string ESignConsentBorrowerIPAddress5 { get; set; }
        public string ESignConsentBorrowerSource5 { get; set; }
        public string ESignConsentCoBorrowerStatus5 { get; set; }
        public DateTime? ESignConsentCoBorrowerDateAccepted5 { get; set; }
        public string ESignConsentCoBorrowerIPAddress5 { get; set; }
        public string ESignConsentCoBorrowerSource5 { get; set; }
        public string ESignConsentBorrowerStatus6 { get; set; }
        public DateTime? ESignConsentBorrowerDateAccepted6 { get; set; }
        public string ESignConsentBorrowerIPAddress6 { get; set; }
        public string ESignConsentBorrowerSource6 { get; set; }
        public string ESignConsentCoBorrowerStatus6 { get; set; }
        public DateTime? ESignConsentCoBorrowerDateAccepted6 { get; set; }
        public string ESignConsentCoBorrowerIPAddress6 { get; set; }
        public string ESignConsentCoBorrowerSource6 { get; set; }
        public decimal? TotalOfPrincipalAndInterest { get; set; }
        public DateTime? SSPLSentDate { get; set; }
        public DateTime? SafeHarborSentDate { get; set; }
        public DateTime? OccupancyCertDate { get; set; }
        public bool? IncludeTaxesInsuranceIndicator { get; set; }
        public bool? IncludePmiIndicator { get; set; }
        public bool? IncludeMiIndicator { get; set; }
        public List<RegulationZInterestRatePeriod> RegulationZInterestRatePeriods { get; set; }
        public DateTime? DueDate { get; set; }
        public decimal? OutstandingBalance { get; set; }
        public string PaymentFrequencyType { get; set; }
        public decimal? RoundedMarginPlusIndexPercent { get; set; }
        public decimal? TotalBrokerFees { get; set; }
        public decimal? TotalLenderFees { get; set; }
        public decimal? DisclosedFinanceCharge { get; set; }
        public string DisclosedProduct { get; set; }
        public bool? DisclosedPrepayment { get; set; }
        public decimal? DisclosedDailyInterestCharge { get; set; }
        public DateTime? HighCostDisclosure { get; set; }
        public DateTime? InitialGfeAffiliatedBusinessProvidedDate { get; set; }
        public DateTime? InitialGfeCharmBookletProvidedDate { get; set; }
        public DateTime? InitialGfeHudSpecialBookletProvidedDate { get; set; }
        public DateTime? InitialGfeHelocBrochureProvidedDate { get; set; }
        public DateTime? PmiMidpointCancelationDate { get; set; }
        public decimal? FinancedAllGuaranteeFeePercent { get; set; }
        public decimal? FinancedAllGuaranteeFeeAmount { get; set; }
        public decimal? FinancedAllTotalLoanAmount { get; set; }
        public decimal? FinancedPortionGuaranteeFeePercent { get; set; }
        public decimal? FinancedPortionGuaranteeFeeAmount { get; set; }
        public decimal? FinancedPortionTotalLoanAmount { get; set; }
        public string FinancingType { get; set; }
        public DateTime? InitialGFEAppraisalProvidedDate { get; set; }
        public bool? UseCustomLenderProfile { get; set; }
        public DateTime? InitialSubsequentAppraisalProvidedDate { get; set; }
        public DateTime? InitialAVMProvidedDate { get; set; }
        public DateTime? HomeCounselingProvidedDate { get; set; }
        public decimal? LateFee { get; set; }
        public decimal? TotalLatePayment { get; set; }
        public bool? InterestOnly { get; set; }
        public decimal? PaymentIncreasePercent { get; set; }
        public bool? ConstructionRefinanceIndicator { get; set; }
        public string ConstructionFirstIntChangeAdjType { get; set; }
        public string Id { get; set; }
    }
}