using System;
using System.Collections.Generic;

namespace EncompassRest.Loans
{
    public sealed class Usda
    {
        public bool? RefinanceLoanIndicator { get; set; }
        public string RdsfhRefinancedLoanIndicatorType { get; set; }
        public int? NumberofPeopleInHousehold { get; set; }
        public decimal? AnnualIncome { get; set; }
        public decimal? AdjustedAnnualIncome { get; set; }
        public bool? InterestRateBasedonFannieIndicator { get; set; }
        public bool? InterestRateFloatToLoanClosingIndicator { get; set; }
        public string PurchaseOrRefinanceDescription { get; set; }
        public string FinancedLoanClosingCostDescription { get; set; }
        public string RepairOtherDescription { get; set; }
        public decimal? RepairOtherAmount { get; set; }
        public string ApprovedLenderTaxId { get; set; }
        public decimal? TotalRequestAmount { get; set; }
        public string ThirdPartyOriginator { get; set; }
        public string TpoTaxId { get; set; }
        public string ApplicationNumber { get; set; }
        public string LenderAuthorizedRepTitle { get; set; }
        public string LenderAuthorizedRepName { get; set; }
        public string LenderAuthorizedRepCompany { get; set; }
        public decimal? ReservationAmountRequested { get; set; }
        public string SubmittingLenderName { get; set; }
        public string SubmittingLenderTaxId { get; set; }
        public string SubmittingLenderAddress { get; set; }
        public string SubmittingLenderCity { get; set; }
        public string SubmittingLenderState { get; set; }
        public string SubmittingLenderZip { get; set; }
        public string SubmittingLenderContactName { get; set; }
        public string SubmittingLenderContactPhone { get; set; }
        public string SubmittingLenderContactFax { get; set; }
        public string LoanType { get; set; }
        public List<UsdaHouseholdIncome> UsdaHouseholdIncomes { get; set; }
        public decimal? ChildCostPerWeek { get; set; }
        public decimal? ChildCostPerMonth { get; set; }
        public string ChildCareProviderProviderName { get; set; }
        public string ChildCareProviderAddress { get; set; }
        public string ChildCareProviderCity { get; set; }
        public string ChildCareProviderState { get; set; }
        public string ChildCareProviderZip { get; set; }
        public string ChildCareProviderPhone { get; set; }
        public bool? LockCompletePlumbingIndicator { get; set; }
        public bool? LackAdequateHeatIndicator { get; set; }
        public bool? PhysicallyDeterioratedIndicator { get; set; }
        public bool? OvercrowdedIndicator { get; set; }
        public string PresentLandloardName { get; set; }
        public string PresentLandloardAddress { get; set; }
        public string PresentLandloardCity { get; set; }
        public string PresentLandloardState { get; set; }
        public string PresentLandloardZip { get; set; }
        public string PresentLandloardPhone { get; set; }
        public string PreviousLandloardName { get; set; }
        public string PreviousLandloardAddress { get; set; }
        public string PreviousLandloardCity { get; set; }
        public string PreviousLandloardState { get; set; }
        public string PreviousLandloardZip { get; set; }
        public string PreviousLandloardPhone { get; set; }
        public string CaseNumberSt { get; set; }
        public string CaseNumberCo { get; set; }
        public string CaseNumberBorrowerId { get; set; }
        public string BorrowerTypeCode { get; set; }
        public string LenderStatusCodeType { get; set; }
        public string LenderTypeCode { get; set; }
        public DateTime? CertificationEffectiveDate { get; set; }
        public DateTime? CertificationExpirationDate { get; set; }
        public string ServicingOfficeName { get; set; }
        public string InterestAssistanceCodeType { get; set; }
        public string GuaranteeFeePurposeCodeType { get; set; }
        public decimal? FeeRate { get; set; }
        public decimal? AmountLoanlineCredit { get; set; }
        public decimal? AdvanceAmountToDate { get; set; }
        public int? TermOfBuydown { get; set; }
        public decimal? LenderNoteRateOnGuaranteedPortion { get; set; }
        public decimal? LenderNoteRateOnNonGuaranteedPortion { get; set; }
        public decimal? BuydownInterestAssistanceRate { get; set; }
        public string PeriodOperatingLineCreditYearsType { get; set; }
        public string Reserved { get; set; }
        public string GuaranteeType { get; set; }
        public string InterestRateCodeType { get; set; }
        public decimal? BalanceOwedOnLoan { get; set; }
        public DateTime? GuaranteePeriodBeginsDate { get; set; }
        public DateTime? GuaranteePeriodEndsDate { get; set; }
        public DateTime? AnnualReviewDate { get; set; }
        public bool? CertifiedLoanIndicator { get; set; }
        public string Title { get; set; }
        public DateTime? UnderwritingDecisionDate { get; set; }
        public string UnderwritingDecisionBy { get; set; }
        public string UnderwritingDecisionType { get; set; }
        public DateTime? DateObligationInGls { get; set; }
        public DateTime? DateConfirmedObligationProcessed { get; set; }
        public string OfficialWhoConfirmedGlsUpdated { get; set; }
        public bool? ObligationMatchesCommitmentLenderRequestIndicator { get; set; }
        public DateTime? DateLoanNoteGuaranteeRequestReceived { get; set; }
        public DateTime? DateLoanNoteGuaranteeIssued { get; set; }
        public decimal? GuaranteeFeeCollected { get; set; }
        public decimal? GuaranteeFeeOnCommitment { get; set; }
        public DateTime? DateVerifiedInUnifi { get; set; }
        public string VerificationCode { get; set; }
        public decimal? BorrowerBaseIncome { get; set; }
        public decimal? CoborrowerBaseIncome { get; set; }
        public string SourceOfFundsType { get; set; }
        public decimal? AdditionalMemberBaseIncome { get; set; }
        public decimal? AdditionalIncomeFromPrimaryEmployment { get; set; }
        public decimal? OtherIncome { get; set; }
        public decimal? AssetIncome { get; set; }
        public decimal? DependentDeduction { get; set; }
        public decimal? AnnualChildCareExpenses { get; set; }
        public decimal? ElderlyHouseholdDeduction { get; set; }
        public decimal? DisabilityDeduction { get; set; }
        public decimal? MedicalExpenses { get; set; }
        public decimal? TotalHouseholdDeduction { get; set; }
        public int? HouseholdSize { get; set; }
        public decimal? ModerateIncomeLimit { get; set; }
        public bool? SfhglpIndicator { get; set; }
        public decimal? StableDependableMonthlyIncome { get; set; }
        public decimal? OtherStableDependableMonthlyIncome { get; set; }
        public decimal? MonthlyRepaymentIncome { get; set; }
        public int? NumberofDependents { get; set; }
        public string LenderIdNo { get; set; }
        public string PreparedByName { get; set; }
        public string PreparedByTitle { get; set; }
        public decimal? PurchaseOrRefinancedAmount { get; set; }
        public decimal? PercentofLoanGuaranteed { get; set; }
        public string StableOtherIncomeDesc { get; set; }
        public decimal? BorrowerTotalStableIncome { get; set; }
        public decimal? CoborrowerStableBaseIncome { get; set; }
        public string CoborrowerStableBaseIncomeDesc { get; set; }
        public decimal? CoborrowerStableOtherIncome { get; set; }
        public string CoborrowerStableOtherIncomeDesc { get; set; }
        public decimal? CoBorrowerTotalStableIncome { get; set; }
        public decimal? TotalBorrowerStableBaseIncome { get; set; }
        public decimal? TotalBorrowerStableOtherIncome { get; set; }
        public string AnnualIncomeCalculationDescription1 { get; set; }
        public string AnnualIncomeCalculationDescription2 { get; set; }
        public string AnnualIncomeCalculationDescription3 { get; set; }
        public string AnnualIncomeCalculationDescription4 { get; set; }
        public string AnnualIncomeCalculationDescription5 { get; set; }
        public string AdjustedIncomeCalculationDescription1 { get; set; }
        public string AdjustedIncomeCalculationDescription2 { get; set; }
        public string AdjustedIncomeCalculationDescription3 { get; set; }
        public string Id { get; set; }
    }
}