using System.Runtime.Serialization;

namespace EncompassRest.Loans.Enums
{
    public enum PrepaymentPenaltyVerbiage
    {
        [EnumMember(Value = "THIS SECTION IS SUPERSEDED BY THE ADDENDUM ATTACHED HERETO AND MADE A PART HEREOF.")]
        THISSECTIONISSUPERSEDEDBYTHEADDENDUMATTACHEDHERETOANDMADEAPARTHEREOF = 0,
        [EnumMember(Value = "THIS SECTION IS SUPERSEDED BY THE RIDER TO THE NOTE ATTACHED HERETO AND MADE A PART HEREOF.")]
        THISSECTIONISSUPERSEDEDBYTHERIDERTOTHENOTEATTACHEDHERETOANDMADEAPARTHEREOF = 1,
        [EnumMember(Value = "PLEASE REFER TO THE ATTACHED PREPAYMENT ADDENDUM WHICH AMENDS AND MODIFIES THE TERMS HEREOF AND IS HEREBY INCORPORATED BY THIS REFERENCE.")]
        PLEASEREFERTOTHEATTACHEDPREPAYMENTADDENDUMWHICHAMENDSANDMODIFIESTHETERMSHEREOFANDISHEREBYINCORPORATEDBYTHISREFERENCE = 2,
        [EnumMember(Value = "SEE ATTACHED PREPAYMENT RIDER.")]
        SEEATTACHEDPREPAYMENTRIDER = 3,
        [EnumMember(Value = "SEE PREPAYMENT ADDENDUM ATTACHED TO THIS NOTE.")]
        SEEPREPAYMENTADDENDUMATTACHEDTOTHISNOTE = 4,
        [EnumMember(Value = "THE ADDENDUM ATTACHED HERETO AND MADE A PART HEREOF AMENDS AND SUPERSEDES THIS SECTION OF THE NOTE.")]
        THEADDENDUMATTACHEDHERETOANDMADEAPARTHEREOFAMENDSANDSUPERSEDESTHISSECTIONOFTHENOTE = 5,
        [EnumMember(Value = "PREPAYMENT RIDER TO NOTE ATTACHED HERETO AND MADE A PART HEREOF.")]
        PREPAYMENTRIDERTONOTEATTACHEDHERETOANDMADEAPARTHEREOF = 6,
        [EnumMember(Value = "SEE ATTACHED PREPAYMENT ADDENDUM WHICH AMENDS AND MODIFIES THE TERMS HEREOF AND IS HEREBY INCORPORATED BY THIS REFERENCE.")]
        SEEATTACHEDPREPAYMENTADDENDUMWHICHAMENDSANDMODIFIESTHETERMSHEREOFANDISHEREBYINCORPORATEDBYTHISREFERENCE = 7,
        [EnumMember(Value = "THIS SECTION IS SUPERSEDED BY THE ADDENDUM TO THE NOTE ATTACHED HERETO AND MADE A PART HEREOF.")]
        THISSECTIONISSUPERSEDEDBYTHEADDENDUMTOTHENOTEATTACHEDHERETOANDMADEAPARTHEREOF = 8
    }
}