using System.ComponentModel;
using System.Runtime.Serialization;

namespace EncompassRest.Loans.Enums
{
    /// <summary>
    /// PrepaymentPenaltyVerbiage
    /// </summary>
    public enum PrepaymentPenaltyVerbiage
    {
        /// <summary>
        /// THIS SECTION IS SUPERSEDED BY THE ADDENDUM ATTACHED HERETO AND MADE A PART HEREOF.
        /// </summary>
        [EnumMember(Value = "THIS SECTION IS SUPERSEDED BY THE ADDENDUM ATTACHED HERETO AND MADE A PART HEREOF.")]
        THISSECTIONISSUPERSEDEDBYTHEADDENDUMATTACHEDHERETOANDMADEAPARTHEREOF = 0,
        /// <summary>
        /// THIS SECTION IS SUPERSEDED BY THE RIDER TO THE NOTE ATTACHED HERETO AND MADE A PART HEREOF.
        /// </summary>
        [EnumMember(Value = "THIS SECTION IS SUPERSEDED BY THE RIDER TO THE NOTE ATTACHED HERETO AND MADE A PART HEREOF.")]
        THISSECTIONISSUPERSEDEDBYTHERIDERTOTHENOTEATTACHEDHERETOANDMADEAPARTHEREOF = 1,
        /// <summary>
        /// PLEASE REFER TO THE ATTACHED PREPAYMENT ADDENDUM WHICH AMENDS AND MODIFIES THE TERMS HEREOF AND IS HEREBY INCORPORATED BY THIS REFERENCE.
        /// </summary>
        [EnumMember(Value = "PLEASE REFER TO THE ATTACHED PREPAYMENT ADDENDUM WHICH AMENDS AND MODIFIES THE TERMS HEREOF AND IS HEREBY INCORPORATED BY THIS REFERENCE.")]
        PLEASEREFERTOTHEATTACHEDPREPAYMENTADDENDUMWHICHAMENDSANDMODIFIESTHETERMSHEREOFANDISHEREBYINCORPORATEDBYTHISREFERENCE = 2,
        /// <summary>
        /// SEE ATTACHED PREPAYMENT RIDER.
        /// </summary>
        [EnumMember(Value = "SEE ATTACHED PREPAYMENT RIDER.")]
        SEEATTACHEDPREPAYMENTRIDER = 3,
        /// <summary>
        /// SEE PREPAYMENT ADDENDUM ATTACHED TO THIS NOTE.
        /// </summary>
        [EnumMember(Value = "SEE PREPAYMENT ADDENDUM ATTACHED TO THIS NOTE.")]
        SEEPREPAYMENTADDENDUMATTACHEDTOTHISNOTE = 4,
        /// <summary>
        /// THE ADDENDUM ATTACHED HERETO AND MADE A PART HEREOF AMENDS AND SUPERSEDES THIS SECTION OF THE NOTE.
        /// </summary>
        [EnumMember(Value = "THE ADDENDUM ATTACHED HERETO AND MADE A PART HEREOF AMENDS AND SUPERSEDES THIS SECTION OF THE NOTE.")]
        THEADDENDUMATTACHEDHERETOANDMADEAPARTHEREOFAMENDSANDSUPERSEDESTHISSECTIONOFTHENOTE = 5,
        /// <summary>
        /// PREPAYMENT RIDER TO NOTE ATTACHED HERETO AND MADE A PART HEREOF.
        /// </summary>
        [EnumMember(Value = "PREPAYMENT RIDER TO NOTE ATTACHED HERETO AND MADE A PART HEREOF.")]
        PREPAYMENTRIDERTONOTEATTACHEDHERETOANDMADEAPARTHEREOF = 6,
        /// <summary>
        /// SEE ATTACHED PREPAYMENT ADDENDUM WHICH AMENDS AND MODIFIES THE TERMS HEREOF AND IS HEREBY INCORPORATED BY THIS REFERENCE.
        /// </summary>
        [EnumMember(Value = "SEE ATTACHED PREPAYMENT ADDENDUM WHICH AMENDS AND MODIFIES THE TERMS HEREOF AND IS HEREBY INCORPORATED BY THIS REFERENCE.")]
        SEEATTACHEDPREPAYMENTADDENDUMWHICHAMENDSANDMODIFIESTHETERMSHEREOFANDISHEREBYINCORPORATEDBYTHISREFERENCE = 7,
        /// <summary>
        /// THIS SECTION IS SUPERSEDED BY THE ADDENDUM TO THE NOTE ATTACHED HERETO AND MADE A PART HEREOF.
        /// </summary>
        [EnumMember(Value = "THIS SECTION IS SUPERSEDED BY THE ADDENDUM TO THE NOTE ATTACHED HERETO AND MADE A PART HEREOF.")]
        THISSECTIONISSUPERSEDEDBYTHEADDENDUMTOTHENOTEATTACHEDHERETOANDMADEAPARTHEREOF = 8
    }
}