name: Build
on:
  push:
    branches:
      - master
      - feature/*

jobs:
  determine_version:
    name: Determine Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: Calculate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        useConfigFile: true

  display_semver:
    name: Display Semantic Version
    runs-on: ubuntu-latest
    needs: determine_version
    env:
      SEMVER: ${{ needs.determine_version.outputs.semVer }}
    steps:
    - name: Display Version
      run: |
        echo "SemVer: $SEMVER"

  build:
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Restore NuGet Packages
      run: dotnet restore src/EncompassApi/EncompassApi.csproj

    - name: Build Solution
      run: dotnet build -c $env:CONFIGURATION src/EncompassApi/EncompassApi.csproj
