name: Publish
on:
  workflow_run:
    workflows: ["Build"]
    branches:
      - master
    types:
      - completed

jobs:
  publish:
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: Calculate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        targetPath: src/EncompassApi
        useConfigFile: true
        updateAssemblyInfo: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    - name: Restore NuGet Packages
      run: dotnet restore src/EncompassApi/EncompassApi.csproj

    - name: Build Solution
      run: dotnet build -c $env:CONFIGURATION -p:Version=${{ steps.gitversion.outputs.MajorMinorPatch }} --version-suffix ${{ steps.gitversion.outputs.PreReleaseTag }} src/EncompassApi/EncompassApi.csproj

    - name: Push NuGet Package
      run: dotnet nuget push --no-symbols --skip-duplicates --api-key ${{ secrets.NUGET_API_KEY }} "src/EncompassApi/bin/Release/**/*.nupkg"
